-- READ ONLY
-- Source One final null-only mapping batch profile
-- Date: 2026-09-25
-- Purpose: confirm the 13 remaining non-Profile DEFERRED fields are still
-- absent/JSON-null in today's Authorization Package snapshot before we
-- preserve them as null-valued OSCAL extension properties.
-- No values or record IDs are returned.

WITH fields(FIELD_NAME) AS (
  SELECT COLUMN1 FROM VALUES
    ('ARCHER_CONTENT_AUTHORIZATION_PACKAGE_CONFIRMED_IN_ARCHER'),
    ('CONTROL_OWNER_CO'),
    ('ADD_ADDITIONAL_CONTROLS'),
    ('INHERITED_CONTROL_SELECTION'),
    ('CONTROL_STANDARDS'),
    ('MASTER_CONTROLS'),
    ('ALTERNATE_SECURITY_CONTROL_ASSESSOR_SCA_TEXT'),
    ('EXPORT_CONTROLLED_DATA_ITARAR_IF_APPLICABLE'),
    ('ALLOCATED_CONTROLS_AUTHORIZATION_PACKAGE'),
    ('CONTROL_SET_TO_ASSESS'),
    ('CHANGE_CONTROL'),
    ('CURRENT_CONTROL_RISK_THRESHOLD'),
    ('OF_SATISFIED_CONTROLS')
),
src AS (
  SELECT CURATED_JSON
  FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
),
profile AS (
  SELECT
    f.FIELD_NAME,
    GET(s.CURATED_JSON, f.FIELD_NAME) AS V
  FROM src s
  CROSS JOIN fields f
)
SELECT
  FIELD_NAME,
  COUNT(*) AS SOURCE_ROWS,
  COUNT_IF(V IS NULL) AS SQL_NULL_OR_MISSING,
  COUNT_IF(IS_NULL_VALUE(V)) AS JSON_NULL_ROWS,
  COUNT_IF(V IS NOT NULL AND NOT IS_NULL_VALUE(V)) AS POPULATED_ROWS,
  COUNT_IF(TYPEOF(V)='ARRAY') AS ARRAY_ROWS,
  COUNT_IF(TYPEOF(V)='OBJECT') AS OBJECT_ROWS,
  COUNT_IF(TYPEOF(V)='VARCHAR') AS TEXT_ROWS,
  COUNT_IF(TYPEOF(V) IN ('INTEGER','DECIMAL','DOUBLE','NUMBER')) AS NUMBER_ROWS,
  COUNT_IF(TYPEOF(V)='BOOLEAN') AS BOOLEAN_ROWS
FROM profile
GROUP BY FIELD_NAME
ORDER BY FIELD_NAME;
