-- READ ONLY
-- Remaining 21 SSP Control Implementation fields: source-location + shape profile
-- Date: 2026-09-24
--
-- Purpose:
-- One pass to determine where the remaining Excel Control Implementation fields
-- actually live and what Archer shape they use. This avoids guessing one field at
-- a time and does not expose actual field values.
--
-- Sources compared:
--   1) Authorization Package (Source One)
--   2) Matched Level-355 Allocated Controls Control rows
--
-- NO DML.

WITH fields(FIELD_NAME) AS (
    SELECT COLUMN1 FROM VALUES
      ('CONTROL_OWNER_CO'),
      ('SECURITY_CONTROL_ASSESSOR_SCA'),
      ('ADD_ADDITIONAL_CONTROLS'),
      ('ALLOCATED_CONTROLS'),
      ('ARCHIVED_CONTROLS'),
      ('INHERITED_CONTROL_SELECTION'),
      ('INHERITABLE_CONTROLS'),
      ('GS_LAB_CONTROL_ENTITY'),
      ('CONTROL_STANDARDS'),
      ('MASTER_CONTROLS'),
      ('ALLOCATED_CONTROLS_PARTIAL_CONTROL_PROVIDERS'),
      ('ALTERNATE_SECURITY_CONTROL_ASSESSOR_SCA_TEXT'),
      ('EXPORT_CONTROL_ASSESSOR_ECA_TEXT'),
      ('SECURITY_CONTROL_ASSESSOR_SCA_TEXT'),
      ('EXPORT_CONTROLLED_DATA_ITARAR_IF_APPLICABLE'),
      ('ALTERNATE_SECURITY_CONTROL_ASSESSOR_SCA'),
      ('ALLOCATED_CONTROLS_AUTHORIZATION_PACKAGE'),
      ('CONTROL_SET_TO_ASSESS'),
      ('CHANGE_CONTROL'),
      ('CURRENT_CONTROL_RISK_THRESHOLD'),
      ('OF_SATISFIED_CONTROLS')
),
authorization_package AS (
    SELECT CURATED_JSON
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
),
level355 AS (
    SELECT s.CURATED_JSON
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_ALLOCATED_CONTROLS_CONTROL_RAW s
    JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW p
      ON TRIM(p.CONTENT_ID::STRING) = TRIM(s.CONTENT_ID::STRING)
),
profile_rows AS (
    SELECT
        'AUTHORIZATION_PACKAGE' AS SOURCE_DATASET,
        f.FIELD_NAME,
        GET(a.CURATED_JSON, f.FIELD_NAME) AS V
    FROM authorization_package a
    CROSS JOIN fields f

    UNION ALL

    SELECT
        'LEVEL355_ALLOCATED_CONTROL' AS SOURCE_DATASET,
        f.FIELD_NAME,
        GET(l.CURATED_JSON, f.FIELD_NAME) AS V
    FROM level355 l
    CROSS JOIN fields f
)
SELECT
    SOURCE_DATASET,
    FIELD_NAME,
    COUNT(*) AS SOURCE_ROWS,
    COUNT_IF(V IS NOT NULL AND NOT IS_NULL_VALUE(V)) AS PRESENT_NON_JSON_NULL,
    COUNT_IF(V IS NULL) AS SQL_NULL_OR_MISSING,
    COUNT_IF(IS_NULL_VALUE(V)) AS JSON_NULL_ROWS,
    COUNT_IF(TYPEOF(V) = 'ARRAY') AS ARRAY_ROWS,
    COUNT_IF(TYPEOF(V) = 'OBJECT') AS OBJECT_ROWS,
    COUNT_IF(TYPEOF(V) = 'VARCHAR') AS TEXT_ROWS,
    COUNT_IF(TYPEOF(V) IN ('INTEGER','DECIMAL','DOUBLE','NUMBER')) AS NUMBER_ROWS,
    COUNT_IF(TYPEOF(V) = 'BOOLEAN') AS BOOLEAN_ROWS,
    COUNT_IF(TYPEOF(V) = 'ARRAY' AND ARRAY_SIZE(V) > 0) AS NONEMPTY_ARRAY_ROWS,
    COUNT(DISTINCT IFF(TYPEOF(V) = 'VARCHAR', V::STRING, NULL)) AS DISTINCT_TEXT_VALUES,
    COUNT_IF(TO_JSON(V) ILIKE '%"UserList"%') AS HAS_USERLIST_SHAPE,
    COUNT_IF(TO_JSON(V) ILIKE '%"GroupList"%') AS HAS_GROUPLIST_SHAPE,
    COUNT_IF(
        TO_JSON(V) ILIKE '%"ValuesListIds"%'
        OR TO_JSON(V) ILIKE '%"ValueListIds"%'
    ) AS HAS_VALUE_LIST_SHAPE,
    COUNT_IF(TO_JSON(V) ILIKE '%"ContentId"%') AS HAS_CONTENT_ID_SHAPE
FROM profile_rows
GROUP BY SOURCE_DATASET, FIELD_NAME
HAVING PRESENT_NON_JSON_NULL > 0
ORDER BY FIELD_NAME, SOURCE_DATASET;
