-- Level-355 AUTHORIZATION_PACKAGE array join diagnostic
-- Date: 2026-09-29
-- READ ONLY. No DML / DDL.
--
-- Current evidence:
--   * 160,000 allocated-control rows
--   * stored CONTENT_ID = RequestedObject.Id on all 160,000 rows
--   * AUTHORIZATION_PACKAGE is ARRAY on 127,496 rows and JSON null on 32,504 rows
--   * failed SSP PREVIEW found 127,495 obsolete implemented-requirement rows
--     across 1,895 Authorization Package source records
--
-- Purpose:
--   Prove whether CURATED_JSON:AUTHORIZATION_PACKAGE now contains the package-grain
--   reference that should replace the old overloaded top-level CONTENT_ID join.
--
-- Result set 1: array/member shape.
-- Result set 2: package-match coverage and required CONTROL_NUMBER coverage.
-- No source payload values are returned.

WITH controls AS (
    SELECT
        s.CONTENT_ID::VARCHAR AS CONTROL_RECORD_ID,
        s.CURATED_JSON:"AUTHORIZATION_PACKAGE" AS AUTHORIZATION_PACKAGE_VALUE,
        s.CURATED_JSON:"CONTROL_NUMBER" AS CONTROL_NUMBER
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_ALLOCATED_CONTROLS_CONTROL_RAW s
),
array_rows AS (
    SELECT *
    FROM controls
    WHERE COALESCE(IS_ARRAY(AUTHORIZATION_PACKAGE_VALUE), FALSE)
),
members AS (
    SELECT
        a.CONTROL_RECORD_ID,
        a.CONTROL_NUMBER,
        f.INDEX AS MEMBER_INDEX,
        f.VALUE AS MEMBER_VALUE,
        TYPEOF(f.VALUE) AS MEMBER_TYPE,
        CASE
            WHEN TYPEOF(f.VALUE) IN ('INTEGER', 'DECIMAL', 'VARCHAR')
                THEN f.VALUE::VARCHAR
            WHEN TYPEOF(f.VALUE) = 'OBJECT'
                THEN COALESCE(
                    f.VALUE:"ContentId"::VARCHAR,
                    f.VALUE:"CONTENT_ID"::VARCHAR,
                    f.VALUE:"Id"::VARCHAR,
                    f.VALUE:"ID"::VARCHAR,
                    f.VALUE:"Value"::VARCHAR,
                    f.VALUE:"value"::VARCHAR
                )
        END AS PACKAGE_REF_ID
    FROM array_rows a,
         LATERAL FLATTEN(INPUT => AS_ARRAY(a.AUTHORIZATION_PACKAGE_VALUE)) f
)
SELECT
    COUNT(*) AS ARRAY_MEMBER_OCCURRENCES,
    COUNT(DISTINCT CONTROL_RECORD_ID) AS CONTROL_ROWS_WITH_ARRAY_MEMBERS,
    COUNT_IF(MEMBER_VALUE IS NULL OR COALESCE(IS_NULL_VALUE(MEMBER_VALUE), FALSE))
        AS NULL_MEMBER_OCCURRENCES,
    COUNT_IF(PACKAGE_REF_ID IS NULL) AS MEMBERS_WITHOUT_EXTRACTABLE_PACKAGE_ID,
    COUNT(DISTINCT PACKAGE_REF_ID) AS DISTINCT_EXTRACTED_PACKAGE_IDS,
    MIN(MEMBER_INDEX) AS MIN_MEMBER_INDEX,
    MAX(MEMBER_INDEX) AS MAX_MEMBER_INDEX
FROM members;

WITH controls AS (
    SELECT
        s.CONTENT_ID::VARCHAR AS CONTROL_RECORD_ID,
        s.CURATED_JSON:"AUTHORIZATION_PACKAGE" AS AUTHORIZATION_PACKAGE_VALUE,
        s.CURATED_JSON:"CONTROL_NUMBER" AS CONTROL_NUMBER
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_ALLOCATED_CONTROLS_CONTROL_RAW s
),
members AS (
    SELECT
        c.CONTROL_RECORD_ID,
        c.CONTROL_NUMBER,
        f.INDEX AS MEMBER_INDEX,
        f.VALUE AS MEMBER_VALUE,
        TYPEOF(f.VALUE) AS MEMBER_TYPE,
        CASE
            WHEN TYPEOF(f.VALUE) IN ('INTEGER', 'DECIMAL', 'VARCHAR')
                THEN f.VALUE::VARCHAR
            WHEN TYPEOF(f.VALUE) = 'OBJECT'
                THEN COALESCE(
                    f.VALUE:"ContentId"::VARCHAR,
                    f.VALUE:"CONTENT_ID"::VARCHAR,
                    f.VALUE:"Id"::VARCHAR,
                    f.VALUE:"ID"::VARCHAR,
                    f.VALUE:"Value"::VARCHAR,
                    f.VALUE:"value"::VARCHAR
                )
        END AS PACKAGE_REF_ID
    FROM controls c,
         LATERAL FLATTEN(INPUT => AS_ARRAY(c.AUTHORIZATION_PACKAGE_VALUE)) f
    WHERE COALESCE(IS_ARRAY(c.AUTHORIZATION_PACKAGE_VALUE), FALSE)
),
packages AS (
    SELECT DISTINCT CONTENT_ID::VARCHAR AS PACKAGE_CONTENT_ID
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    WHERE CONTENT_ID IS NOT NULL
),
matched AS (
    SELECT
        m.CONTROL_RECORD_ID,
        m.CONTROL_NUMBER,
        m.MEMBER_INDEX,
        m.MEMBER_TYPE,
        m.PACKAGE_REF_ID,
        p.PACKAGE_CONTENT_ID
    FROM members m
    LEFT JOIN packages p
      ON p.PACKAGE_CONTENT_ID = m.PACKAGE_REF_ID
),
per_control AS (
    SELECT
        CONTROL_RECORD_ID,
        COUNT(*) AS MEMBER_COUNT,
        COUNT_IF(PACKAGE_REF_ID IS NOT NULL) AS EXTRACTABLE_MEMBER_COUNT,
        COUNT_IF(PACKAGE_CONTENT_ID IS NOT NULL) AS PACKAGE_MATCH_COUNT,
        COUNT(DISTINCT PACKAGE_CONTENT_ID) AS DISTINCT_PACKAGE_MATCH_COUNT,
        MAX(PACKAGE_CONTENT_ID) AS MATCHED_PACKAGE_CONTENT_ID,
        MAX(CONTROL_NUMBER) AS CONTROL_NUMBER
    FROM matched
    GROUP BY CONTROL_RECORD_ID
)
SELECT
    COUNT(*) AS CONTROL_ROWS_WITH_AUTH_PACKAGE_ARRAY,
    COUNT_IF(MEMBER_COUNT = 1) AS CONTROL_ROWS_WITH_ONE_ARRAY_MEMBER,
    COUNT_IF(MEMBER_COUNT > 1) AS CONTROL_ROWS_WITH_MULTIPLE_ARRAY_MEMBERS,
    COUNT_IF(EXTRACTABLE_MEMBER_COUNT = 1) AS CONTROL_ROWS_WITH_ONE_EXTRACTABLE_PACKAGE_ID,
    COUNT_IF(PACKAGE_MATCH_COUNT = 1 AND DISTINCT_PACKAGE_MATCH_COUNT = 1)
        AS CONTROL_ROWS_WITH_EXACTLY_ONE_PACKAGE_MATCH,
    COUNT_IF(PACKAGE_MATCH_COUNT = 0) AS CONTROL_ROWS_WITH_NO_PACKAGE_MATCH,
    COUNT_IF(PACKAGE_MATCH_COUNT > 1 OR DISTINCT_PACKAGE_MATCH_COUNT > 1)
        AS CONTROL_ROWS_WITH_AMBIGUOUS_PACKAGE_MATCH,
    COUNT(DISTINCT MATCHED_PACKAGE_CONTENT_ID) AS DISTINCT_MATCHED_PACKAGES,

    COUNT_IF(
        PACKAGE_MATCH_COUNT = 1
        AND DISTINCT_PACKAGE_MATCH_COUNT = 1
        AND CONTROL_NUMBER IS NOT NULL
        AND NOT COALESCE(IS_NULL_VALUE(CONTROL_NUMBER), FALSE)
        AND NULLIF(TRIM(CONTROL_NUMBER::VARCHAR), '') IS NOT NULL
    ) AS MATCHED_ROWS_WITH_USABLE_CONTROL_NUMBER,

    COUNT_IF(
        PACKAGE_MATCH_COUNT = 1
        AND DISTINCT_PACKAGE_MATCH_COUNT = 1
        AND (
            CONTROL_NUMBER IS NULL
            OR COALESCE(IS_NULL_VALUE(CONTROL_NUMBER), FALSE)
            OR NULLIF(TRIM(CONTROL_NUMBER::VARCHAR), '') IS NULL
        )
    ) AS MATCHED_ROWS_WITHOUT_USABLE_CONTROL_NUMBER
FROM per_control;

-- Member datatype profile only; no values.
WITH controls AS (
    SELECT CURATED_JSON:"AUTHORIZATION_PACKAGE" AS AUTHORIZATION_PACKAGE_VALUE
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_ALLOCATED_CONTROLS_CONTROL_RAW
    WHERE COALESCE(IS_ARRAY(CURATED_JSON:"AUTHORIZATION_PACKAGE"), FALSE)
),
members AS (
    SELECT TYPEOF(f.VALUE) AS MEMBER_TYPE
    FROM controls c,
         LATERAL FLATTEN(INPUT => AS_ARRAY(c.AUTHORIZATION_PACKAGE_VALUE)) f
)
SELECT
    MEMBER_TYPE,
    COUNT(*) AS MEMBER_OCCURRENCES
FROM members
GROUP BY MEMBER_TYPE
ORDER BY MEMBER_OCCURRENCES DESC, MEMBER_TYPE;
