-- ONE-TIME GUARDED CLEANUP — current-valid-set difference
-- Date: 2026-09-24
--
-- Purpose:
-- Remove the one historical Level-355 implemented-requirement that is no longer
-- valid because its current source row has no defensible CONTROL_NUMBER.
--
-- This version does NOT try to guess the bad row's historical node key.
-- Instead it:
--   1) identifies the one bad source row and its package;
--   2) computes BOTH possible historical node keys for EVERY VALID sibling control
--      in that same package;
--   3) finds the target implemented-requirement row in that package that is NOT
--      represented by the current valid source set;
--   4) requires exactly one stale DIM row, one incoming FACT edge, zero outgoing;
--   5) deletes only that row/edge and verifies the cleanup.
--
-- No broad delete is allowed.

EXECUTE IMMEDIATE $$
DECLARE
  bad_source_rows NUMBER;
  package_source_rows NUMBER;
  valid_source_rows NUMBER;
  target_package_ir_rows NUMBER;
  stale_target_rows NUMBER;
  incoming_fact_count NUMBER;
  outgoing_fact_count NUMBER;
  remaining_dim NUMBER;
  remaining_fact NUMBER;
  started BOOLEAN DEFAULT FALSE;

  bad_source_shape EXCEPTION (-20941, 'LEVEL355_BAD_SOURCE_SHAPE_CHANGED: expected exactly one matched source row without CONTROL_NUMBER.');
  stale_shape EXCEPTION (-20942, 'LEVEL355_STALE_TARGET_SHAPE_CHANGED: expected exactly one target implemented-requirement outside the current valid source set.');
  edge_shape EXCEPTION (-20943, 'LEVEL355_STALE_EDGE_SHAPE_CHANGED: expected one incoming and zero outgoing edges.');
  verify_failed EXCEPTION (-20944, 'LEVEL355_STALE_ROW_CLEANUP_VERIFY_FAILED.');
BEGIN

  CREATE OR REPLACE TEMP TABLE TMP_LEVEL355_BAD_SOURCE AS
  SELECT
      TRIM(s.CONTENT_ID::STRING) AS PACKAGE_CONTENT_ID,
      s.CURATED_JSON:ALLOCATED_CONTROL_ID::STRING AS ALLOCATED_CONTROL_ID
  FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_ALLOCATED_CONTROLS_CONTROL_RAW s
  JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW p
    ON TRIM(p.CONTENT_ID::STRING) = TRIM(s.CONTENT_ID::STRING)
  WHERE (
        s.CURATED_JSON:CONTROL_NUMBER IS NULL
        OR IS_NULL_VALUE(s.CURATED_JSON:CONTROL_NUMBER)
        OR NULLIF(TRIM(s.CURATED_JSON:CONTROL_NUMBER::STRING), '') IS NULL
  );

  SELECT COUNT(*) INTO :bad_source_rows
  FROM TMP_LEVEL355_BAD_SOURCE;

  IF (bad_source_rows <> 1) THEN
    RAISE bad_source_shape;
  END IF;

  CREATE OR REPLACE TEMP TABLE TMP_LEVEL355_PACKAGE_SOURCE AS
  SELECT
      TRIM(s.CONTENT_ID::STRING) AS PACKAGE_CONTENT_ID,
      s.CURATED_JSON:ALLOCATED_CONTROL_ID::STRING AS ALLOCATED_CONTROL_ID_DECODED,
      TO_JSON(s.CURATED_JSON:ALLOCATED_CONTROL_ID) AS ALLOCATED_CONTROL_ID_SERIALIZED,
      s.CURATED_JSON:CONTROL_NUMBER AS CONTROL_NUMBER
  FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_ALLOCATED_CONTROLS_CONTROL_RAW s
  JOIN TMP_LEVEL355_BAD_SOURCE b
    ON TRIM(s.CONTENT_ID::STRING) = b.PACKAGE_CONTENT_ID;

  SELECT COUNT(*) INTO :package_source_rows
  FROM TMP_LEVEL355_PACKAGE_SOURCE;

  SELECT COUNT(*) INTO :valid_source_rows
  FROM TMP_LEVEL355_PACKAGE_SOURCE
  WHERE CONTROL_NUMBER IS NOT NULL
    AND NOT IS_NULL_VALUE(CONTROL_NUMBER)
    AND NULLIF(TRIM(CONTROL_NUMBER::STRING), '') IS NOT NULL;

  CREATE OR REPLACE TEMP TABLE TMP_LEVEL355_VALID_KEYS AS
  SELECT
      TO_BINARY(
        MD5(
          'v1_registry_path_instance|ARCHER|ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW|'
          || PACKAGE_CONTENT_ID
          || '|SSP|system-security-plan.control-implementation.implemented-requirements[]|'
          || ALLOCATED_CONTROL_ID_DECODED
        ),
        'HEX'
      ) AS PK_OSCAL_SSP_ELEMENT_HASH
  FROM TMP_LEVEL355_PACKAGE_SOURCE
  WHERE CONTROL_NUMBER IS NOT NULL
    AND NOT IS_NULL_VALUE(CONTROL_NUMBER)
    AND NULLIF(TRIM(CONTROL_NUMBER::STRING), '') IS NOT NULL

  UNION

  SELECT
      TO_BINARY(
        MD5(
          'v1_registry_path_instance|ARCHER|ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW|'
          || PACKAGE_CONTENT_ID
          || '|SSP|system-security-plan.control-implementation.implemented-requirements[]|'
          || ALLOCATED_CONTROL_ID_SERIALIZED
        ),
        'HEX'
      ) AS PK_OSCAL_SSP_ELEMENT_HASH
  FROM TMP_LEVEL355_PACKAGE_SOURCE
  WHERE CONTROL_NUMBER IS NOT NULL
    AND NOT IS_NULL_VALUE(CONTROL_NUMBER)
    AND NULLIF(TRIM(CONTROL_NUMBER::STRING), '') IS NOT NULL;

  SELECT COUNT(*) INTO :target_package_ir_rows
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT d
  JOIN TMP_LEVEL355_BAD_SOURCE b
    ON d.SOURCE_RECORD_ID = b.PACKAGE_CONTENT_ID
  WHERE d.SOURCE_SYSTEM_NAME = 'ARCHER'
    AND d.SOURCE_TABLE_NAME = 'ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND d.ELEMENT_TYPE = 'implemented-requirements';

  CREATE OR REPLACE TEMP TABLE TMP_LEVEL355_STALE_IR AS
  SELECT d.PK_OSCAL_SSP_ELEMENT_HASH
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT d
  JOIN TMP_LEVEL355_BAD_SOURCE b
    ON d.SOURCE_RECORD_ID = b.PACKAGE_CONTENT_ID
  WHERE d.SOURCE_SYSTEM_NAME = 'ARCHER'
    AND d.SOURCE_TABLE_NAME = 'ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND d.ELEMENT_TYPE = 'implemented-requirements'
    AND NOT EXISTS (
        SELECT 1
        FROM TMP_LEVEL355_VALID_KEYS v
        WHERE v.PK_OSCAL_SSP_ELEMENT_HASH = d.PK_OSCAL_SSP_ELEMENT_HASH
    );

  SELECT COUNT(*) INTO :stale_target_rows
  FROM TMP_LEVEL355_STALE_IR;

  IF (stale_target_rows <> 1) THEN
    RAISE stale_shape;
  END IF;

  SELECT COUNT(*) INTO :incoming_fact_count
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY f
  JOIN TMP_LEVEL355_STALE_IR b
    ON f.FK_TARGET_ELEMENT_HASH = b.PK_OSCAL_SSP_ELEMENT_HASH;

  SELECT COUNT(*) INTO :outgoing_fact_count
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY f
  JOIN TMP_LEVEL355_STALE_IR b
    ON f.FK_SOURCE_ELEMENT_HASH = b.PK_OSCAL_SSP_ELEMENT_HASH;

  IF (incoming_fact_count <> 1 OR outgoing_fact_count <> 0) THEN
    RAISE edge_shape;
  END IF;

  BEGIN TRANSACTION;
  started := TRUE;

  DELETE FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY f
  USING TMP_LEVEL355_STALE_IR b
  WHERE f.FK_TARGET_ELEMENT_HASH = b.PK_OSCAL_SSP_ELEMENT_HASH;

  DELETE FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT d
  USING TMP_LEVEL355_STALE_IR b
  WHERE d.PK_OSCAL_SSP_ELEMENT_HASH = b.PK_OSCAL_SSP_ELEMENT_HASH;

  COMMIT;
  started := FALSE;

  SELECT COUNT(*) INTO :remaining_dim
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT d
  JOIN TMP_LEVEL355_STALE_IR b
    ON d.PK_OSCAL_SSP_ELEMENT_HASH = b.PK_OSCAL_SSP_ELEMENT_HASH;

  SELECT COUNT(*) INTO :remaining_fact
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY f
  JOIN TMP_LEVEL355_STALE_IR b
    ON f.FK_TARGET_ELEMENT_HASH = b.PK_OSCAL_SSP_ELEMENT_HASH
    OR f.FK_SOURCE_ELEMENT_HASH = b.PK_OSCAL_SSP_ELEMENT_HASH;

  IF (remaining_dim <> 0 OR remaining_fact <> 0) THEN
    RAISE verify_failed;
  END IF;

  RETURN OBJECT_CONSTRUCT(
      'STATUS', 'LEVEL355_SINGLE_BAD_IMPLEMENTED_REQUIREMENT_REMOVED',
      'SOURCE_BAD_ROWS', bad_source_rows,
      'PACKAGE_SOURCE_ROWS', package_source_rows,
      'VALID_SOURCE_ROWS', valid_source_rows,
      'TARGET_PACKAGE_IR_ROWS_BEFORE', target_package_ir_rows,
      'STALE_TARGET_ROWS_REMOVED', stale_target_rows,
      'FACT_ROWS_REMOVED', incoming_fact_count,
      'READBACK_BAD_DIM', remaining_dim,
      'READBACK_BAD_FACT', remaining_fact,
      'COMMITTED', TRUE
  );

EXCEPTION
  WHEN OTHER THEN
    IF (started) THEN
      ROLLBACK;
    END IF;
    RAISE;
END;
$$;
