-- READ ONLY
-- Level-355 Allocated Controls Control sample joined to Authorization Package by CONTENT_ID
-- Date: 2026-09-24
--
-- Purpose:
-- Inspect whether the 1,895 matching CONTENT_ID values expose the control identity
-- and implementation fields needed for SSP control-implementation /
-- implemented-requirements[] mapping.

SELECT
    s.CONTENT_ID,
    s.CURATED_JSON:CONTROL_NUMBER         AS CONTROL_NUMBER,
    s.CURATED_JSON:CONTROL_NAME           AS CONTROL_NAME,
    s.CURATED_JSON:IMPLEMENTATION_DETAILS AS IMPLEMENTATION_DETAILS,
    s.CURATED_JSON:IMPLEMENTATION_STATUS  AS IMPLEMENTATION_STATUS,
    s.CURATED_JSON:ALLOCATED_CONTROL_ID   AS ALLOCATED_CONTROL_ID,
    s.CURATED_JSON:AUTHORIZATION_PACKAGE  AS AUTHORIZATION_PACKAGE
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_ALLOCATED_CONTROLS_CONTROL_RAW s
JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW p
  ON p.CONTENT_ID = s.CONTENT_ID
LIMIT 20;
