-- READ ONLY
-- Source One closeout: inspect the only two populated deferred Control Implementation arrays
-- Date: 2026-09-25
--
-- No values, record IDs, names, or payload text are returned.
-- We only need element type and common reference-key shapes.

WITH source AS (
    SELECT CURATED_JSON
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
),
items AS (
    SELECT
        'INHERITABLE_CONTROLS' AS FIELD_NAME,
        f.VALUE AS ITEM
    FROM source s,
         LATERAL FLATTEN(INPUT => s.CURATED_JSON:INHERITABLE_CONTROLS) f

    UNION ALL

    SELECT
        'ALLOCATED_CONTROLS_PARTIAL_CONTROL_PROVIDERS' AS FIELD_NAME,
        f.VALUE AS ITEM
    FROM source s,
         LATERAL FLATTEN(INPUT => s.CURATED_JSON:ALLOCATED_CONTROLS_PARTIAL_CONTROL_PROVIDERS) f
)
SELECT
    FIELD_NAME,
    TYPEOF(ITEM) AS ITEM_TYPE,
    COUNT(*) AS ITEM_COUNT,
    COUNT_IF(ITEM:ContentId IS NOT NULL) AS HAS_CONTENT_ID,
    COUNT_IF(ITEM:ContentIds IS NOT NULL) AS HAS_CONTENT_IDS,
    COUNT_IF(ITEM:Id IS NOT NULL) AS HAS_ID,
    COUNT_IF(ITEM:UserList IS NOT NULL) AS HAS_USER_LIST,
    COUNT_IF(ITEM:GroupList IS NOT NULL) AS HAS_GROUP_LIST,
    COUNT_IF(
        ITEM:ValuesListIds IS NOT NULL
        OR ITEM:ValueListIds IS NOT NULL
    ) AS HAS_VALUE_LIST_IDS,
    COUNT_IF(ITEM:Value IS NOT NULL) AS HAS_VALUE_MEMBER,
    COUNT_IF(ITEM:LevelId IS NOT NULL) AS HAS_LEVEL_ID,
    COUNT_IF(TYPEOF(ITEM) = 'VARCHAR') AS SCALAR_TEXT_ITEMS,
    COUNT_IF(TYPEOF(ITEM) IN ('INTEGER','DECIMAL','DOUBLE','NUMBER')) AS SCALAR_NUMBER_ITEMS
FROM items
GROUP BY FIELD_NAME, TYPEOF(ITEM)
ORDER BY FIELD_NAME, ITEM_TYPE;
