-- READ ONLY
-- Level-355 matched-control identity and implementation-field profile
-- Date: 2026-09-24
--
-- Purpose:
-- Validate the working relationship:
--   ARCHER_CONTENT_ALLOCATED_CONTROLS_CONTROL_RAW.CONTENT_ID
--     = ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW.CONTENT_ID
--
-- and determine the row-level identity + populated fields needed for
-- SSP control-implementation / implemented-requirements[].
--
-- No DML.

-- =====================================================================
-- 1. Matched grain / candidate identity
-- =====================================================================
WITH matched AS (
    SELECT
        TRIM(s.CONTENT_ID::STRING) AS PACKAGE_CONTENT_ID,
        s.CURATED_JSON
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_ALLOCATED_CONTROLS_CONTROL_RAW s
    JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW p
      ON TRIM(p.CONTENT_ID::STRING) = TRIM(s.CONTENT_ID::STRING)
)
SELECT
    COUNT(*) AS MATCHED_CONTROL_ROWS,
    COUNT(DISTINCT PACKAGE_CONTENT_ID) AS MATCHED_AUTHORIZATION_PACKAGES,
    COUNT_IF(CURATED_JSON:ALLOCATED_CONTROL_ID IS NULL) AS NULL_ALLOCATED_CONTROL_ID_ROWS,
    COUNT(DISTINCT CURATED_JSON:ALLOCATED_CONTROL_ID::STRING) AS DISTINCT_ALLOCATED_CONTROL_IDS,
    COUNT(DISTINCT PACKAGE_CONTENT_ID || '|' || COALESCE(CURATED_JSON:ALLOCATED_CONTROL_ID::STRING, '<NULL>'))
        AS DISTINCT_PACKAGE_ALLOCATED_CONTROL_PAIRS,
    COUNT(DISTINCT PACKAGE_CONTENT_ID || '|' || COALESCE(CURATED_JSON:CONTROL_NUMBER::STRING, '<NULL>'))
        AS DISTINCT_PACKAGE_CONTROL_NUMBER_PAIRS
FROM matched;


-- =====================================================================
-- 2. Check whether ALLOCATED_CONTROL_ID is a stable row identity
-- Expected for a clean identity candidate: no duplicate groups.
-- =====================================================================
WITH matched AS (
    SELECT
        TRIM(s.CONTENT_ID::STRING) AS PACKAGE_CONTENT_ID,
        s.CURATED_JSON:ALLOCATED_CONTROL_ID::STRING AS ALLOCATED_CONTROL_ID
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_ALLOCATED_CONTROLS_CONTROL_RAW s
    JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW p
      ON TRIM(p.CONTENT_ID::STRING) = TRIM(s.CONTENT_ID::STRING)
)
SELECT
    PACKAGE_CONTENT_ID,
    ALLOCATED_CONTROL_ID,
    COUNT(*) AS ROWS_PER_IDENTITY
FROM matched
GROUP BY PACKAGE_CONTENT_ID, ALLOCATED_CONTROL_ID
HAVING COUNT(*) > 1
ORDER BY ROWS_PER_IDENTITY DESC, PACKAGE_CONTENT_ID, ALLOCATED_CONTROL_ID
LIMIT 50;


-- =====================================================================
-- 3. Population profile for the first implemented-requirement mapping batch
-- =====================================================================
WITH matched AS (
    SELECT s.CURATED_JSON
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_ALLOCATED_CONTROLS_CONTROL_RAW s
    JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW p
      ON TRIM(p.CONTENT_ID::STRING) = TRIM(s.CONTENT_ID::STRING)
)
SELECT
    COUNT(*) AS MATCHED_ROWS,

    COUNT_IF(CURATED_JSON:CONTROL_NUMBER IS NOT NULL) AS CONTROL_NUMBER_POPULATED,
    COUNT_IF(CURATED_JSON:CONTROL_NAME IS NOT NULL) AS CONTROL_NAME_POPULATED,
    COUNT_IF(CURATED_JSON:ALLOCATED_CONTROL_ID IS NOT NULL) AS ALLOCATED_CONTROL_ID_POPULATED,
    COUNT_IF(CURATED_JSON:AUTHORIZATION_PACKAGE IS NOT NULL) AS AUTHORIZATION_PACKAGE_POPULATED,

    COUNT_IF(CURATED_JSON:IMPLEMENTATION_DETAILS IS NOT NULL) AS IMPLEMENTATION_DETAILS_POPULATED,
    COUNT_IF(CURATED_JSON:OVERALL_IMPLEMENTATION_DETAILS IS NOT NULL) AS OVERALL_IMPLEMENTATION_DETAILS_POPULATED,
    COUNT_IF(CURATED_JSON:IMPLEMENTATION_STATUS IS NOT NULL) AS IMPLEMENTATION_STATUS_POPULATED,

    COUNT_IF(CURATED_JSON:CONTROL_ORIGINATION IS NOT NULL) AS CONTROL_ORIGINATION_POPULATED,
    COUNT_IF(CURATED_JSON:RESPONSIBLE_ROLE IS NOT NULL) AS RESPONSIBLE_ROLE_POPULATED,
    COUNT_IF(CURATED_JSON:CONTROL_PARAMETERS IS NOT NULL) AS CONTROL_PARAMETERS_POPULATED,
    COUNT_IF(CURATED_JSON:CONTROL_ENTITY IS NOT NULL) AS CONTROL_ENTITY_POPULATED,
    COUNT_IF(CURATED_JSON:CONTROL_SET IS NOT NULL) AS CONTROL_SET_POPULATED,

    COUNT_IF(CURATED_JSON:INHERITED_IMPLEMENTATION_DETAILS IS NOT NULL) AS INHERITED_IMPLEMENTATION_DETAILS_POPULATED,
    COUNT_IF(CURATED_JSON:PARTIAL_INHERITED_IMPLEMENTATION_DETAILS IS NOT NULL) AS PARTIAL_INHERITED_IMPLEMENTATION_DETAILS_POPULATED,
    COUNT_IF(CURATED_JSON:ASSESSMENT_STATUS IS NOT NULL) AS ASSESSMENT_STATUS_POPULATED,
    COUNT_IF(CURATED_JSON:OVERALL_ASSESSMENT_STATUS IS NOT NULL) AS OVERALL_ASSESSMENT_STATUS_POPULATED
FROM matched;


-- =====================================================================
-- 4. Confirm that the Level-355 AUTHORIZATION_PACKAGE field points back to
--    the same package CONTENT_ID used by the physical join.
-- =====================================================================
WITH matched AS (
    SELECT
        TRIM(s.CONTENT_ID::STRING) AS PACKAGE_CONTENT_ID,
        s.CURATED_JSON
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_ALLOCATED_CONTROLS_CONTROL_RAW s
    JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW p
      ON TRIM(p.CONTENT_ID::STRING) = TRIM(s.CONTENT_ID::STRING)
),
auth_refs AS (
    SELECT DISTINCT
        m.PACKAGE_CONTENT_ID,
        TRIM(f.VALUE::STRING) AS AUTHORIZATION_PACKAGE_REF
    FROM matched m,
         LATERAL FLATTEN(INPUT => m.CURATED_JSON:AUTHORIZATION_PACKAGE) f
)
SELECT
    COUNT(*) AS DISTINCT_PACKAGE_REFERENCE_PAIRS,
    COUNT_IF(PACKAGE_CONTENT_ID = AUTHORIZATION_PACKAGE_REF) AS SAME_ID_PAIRS,
    COUNT_IF(PACKAGE_CONTENT_ID <> AUTHORIZATION_PACKAGE_REF) AS DIFFERENT_ID_PAIRS
FROM auth_refs;


-- =====================================================================
-- 5. Show only rows that actually contain implementation detail/status data.
--    This tells us which source field should feed OSCAL descriptions/status.
-- =====================================================================
SELECT
    s.CONTENT_ID,
    s.CURATED_JSON:ALLOCATED_CONTROL_ID AS ALLOCATED_CONTROL_ID,
    s.CURATED_JSON:CONTROL_NUMBER AS CONTROL_NUMBER,
    s.CURATED_JSON:CONTROL_NAME AS CONTROL_NAME,
    s.CURATED_JSON:IMPLEMENTATION_DETAILS AS IMPLEMENTATION_DETAILS,
    s.CURATED_JSON:OVERALL_IMPLEMENTATION_DETAILS AS OVERALL_IMPLEMENTATION_DETAILS,
    s.CURATED_JSON:IMPLEMENTATION_STATUS AS IMPLEMENTATION_STATUS,
    s.CURATED_JSON:CONTROL_ORIGINATION AS CONTROL_ORIGINATION,
    s.CURATED_JSON:RESPONSIBLE_ROLE AS RESPONSIBLE_ROLE,
    s.CURATED_JSON:CONTROL_PARAMETERS AS CONTROL_PARAMETERS
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_ALLOCATED_CONTROLS_CONTROL_RAW s
JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW p
  ON TRIM(p.CONTENT_ID::STRING) = TRIM(s.CONTENT_ID::STRING)
WHERE s.CURATED_JSON:IMPLEMENTATION_DETAILS IS NOT NULL
   OR s.CURATED_JSON:OVERALL_IMPLEMENTATION_DETAILS IS NOT NULL
   OR s.CURATED_JSON:IMPLEMENTATION_STATUS IS NOT NULL
   OR s.CURATED_JSON:CONTROL_ORIGINATION IS NOT NULL
   OR s.CURATED_JSON:RESPONSIBLE_ROLE IS NOT NULL
   OR s.CURATED_JSON:CONTROL_PARAMETERS IS NOT NULL
LIMIT 50;
