-- READ ONLY
-- Source One Assessment Results final two-field closeout
-- Date: 2026-09-25
-- No DML and no source values are returned.

-- 1) FINDINGS: classify whether today's source contains any real finding payload.
WITH src AS (
    SELECT CURATED_JSON:FINDINGS AS V
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
)
SELECT
    'FINDINGS' AS FIELD_NAME,
    COUNT(*) AS SOURCE_ROWS,
    COUNT_IF(V IS NULL) AS SQL_NULL_OR_MISSING,
    COUNT_IF(IS_NULL_VALUE(V)) AS JSON_NULL_ROWS,
    COUNT_IF(TYPEOF(V)='ARRAY' AND ARRAY_SIZE(V)=0) AS EMPTY_ARRAY_ROWS,
    COUNT_IF(TYPEOF(V)='OBJECT' AND OBJECT_SIZE(V)=0) AS EMPTY_OBJECT_ROWS,
    COUNT_IF(
      TYPEOF(V)='VARCHAR'
      AND LOWER(TRIM(V::STRING)) IN ('', '[]', '{}', 'null', '""')
    ) AS EMPTY_TEXT_SENTINEL_ROWS,
    COUNT_IF(
      V IS NOT NULL
      AND NOT IS_NULL_VALUE(V)
      AND NOT (TYPEOF(V)='ARRAY' AND ARRAY_SIZE(V)=0)
      AND NOT (TYPEOF(V)='OBJECT' AND OBJECT_SIZE(V)=0)
      AND NOT (
        TYPEOF(V)='VARCHAR'
        AND LOWER(TRIM(V::STRING)) IN ('', '[]', '{}', 'null', '""')
      )
    ) AS EFFECTIVE_NONEMPTY_ROWS
FROM src;

-- 2) RISK_ASSESSMENT_REPORT: prove current array/member shape without exposing IDs.
WITH src AS (
    SELECT CURATED_JSON:RISK_ASSESSMENT_REPORT AS V
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
),
items AS (
    SELECT f.VALUE AS ITEM
    FROM src s,
         LATERAL FLATTEN(INPUT => s.V) f
)
SELECT
    'RISK_ASSESSMENT_REPORT' AS FIELD_NAME,
    (SELECT COUNT(*) FROM src) AS SOURCE_ROWS,
    (SELECT COUNT_IF(V IS NOT NULL AND NOT IS_NULL_VALUE(V)) FROM src) AS POPULATED_ROOT_ROWS,
    (SELECT COUNT_IF(TYPEOF(V)='ARRAY') FROM src) AS ARRAY_ROOT_ROWS,
    COUNT(*) AS ITEM_COUNT,
    COUNT_IF(TYPEOF(ITEM)='INTEGER') AS INTEGER_ITEMS,
    COUNT_IF(TYPEOF(ITEM) IN ('DECIMAL','DOUBLE','NUMBER')) AS OTHER_NUMBER_ITEMS,
    COUNT_IF(TYPEOF(ITEM)='VARCHAR') AS TEXT_ITEMS,
    COUNT_IF(TYPEOF(ITEM)='OBJECT') AS OBJECT_ITEMS,
    COUNT_IF(TYPEOF(ITEM)='ARRAY') AS NESTED_ARRAY_ITEMS
FROM items;
