-- Level-355 post-refresh join-key diagnostic
-- Date: 2026-09-29
-- READ ONLY. No DML / DDL.
--
-- Why:
--   The failed SSP PREVIEW reported 127,495 obsolete implemented-requirement rows
--   across 1,895 source records. Historically, exactly 1,895 distinct Authorization
--   Package CONTENT_ID values matched ARCHER_CONTENT_ALLOCATED_CONTROLS_CONTROL_RAW
--   on p.CONTENT_ID = s.CONTENT_ID.
--
-- This query checks whether the recent generic raw->curated change caused the
-- allocated-controls table CONTENT_ID to become RequestedObject.Id (row identity),
-- which would break the package-grain join used by the SSP joined-record mapper.

WITH controls AS (
    SELECT
        s.CONTENT_ID::VARCHAR AS STORED_CONTENT_ID,
        IFF(
            TYPEOF(s.RAW_DATA) = 'ARRAY',
            s.RAW_DATA[0],
            s.RAW_DATA
        ) AS OBJ,
        s.CURATED_JSON
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_ALLOCATED_CONTROLS_CONTROL_RAW s
),
controls_norm AS (
    SELECT
        STORED_CONTENT_ID,
        OBJ:"RequestedObject":"Id"::VARCHAR AS REQUESTED_OBJECT_ID,
        CURATED_JSON:"AUTHORIZATION_PACKAGE" AS AUTHORIZATION_PACKAGE_VALUE,
        TYPEOF(CURATED_JSON:"AUTHORIZATION_PACKAGE") AS AUTHORIZATION_PACKAGE_TYPE,
        CASE
            WHEN TYPEOF(CURATED_JSON:"AUTHORIZATION_PACKAGE") IN ('INTEGER','DECIMAL','VARCHAR')
                THEN CURATED_JSON:"AUTHORIZATION_PACKAGE"::VARCHAR
            WHEN TYPEOF(CURATED_JSON:"AUTHORIZATION_PACKAGE") = 'OBJECT'
                THEN COALESCE(
                    CURATED_JSON:"AUTHORIZATION_PACKAGE":"ContentId"::VARCHAR,
                    CURATED_JSON:"AUTHORIZATION_PACKAGE":"CONTENT_ID"::VARCHAR,
                    CURATED_JSON:"AUTHORIZATION_PACKAGE":"Id"::VARCHAR,
                    CURATED_JSON:"AUTHORIZATION_PACKAGE":"ID"::VARCHAR,
                    CURATED_JSON:"AUTHORIZATION_PACKAGE":"Value"::VARCHAR
                )
        END AS AUTHORIZATION_PACKAGE_REF_ID
    FROM controls
),
packages AS (
    SELECT CONTENT_ID::VARCHAR AS PACKAGE_CONTENT_ID
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    WHERE CONTENT_ID IS NOT NULL
)
SELECT
    (SELECT COUNT(*) FROM controls_norm) AS CONTROL_ROWS,
    (SELECT COUNT(DISTINCT STORED_CONTENT_ID) FROM controls_norm
      WHERE STORED_CONTENT_ID IS NOT NULL) AS DISTINCT_CONTROL_STORED_CONTENT_IDS,
    (SELECT COUNT(DISTINCT REQUESTED_OBJECT_ID) FROM controls_norm
      WHERE REQUESTED_OBJECT_ID IS NOT NULL) AS DISTINCT_CONTROL_REQUESTED_OBJECT_IDS,

    (SELECT COUNT(*) FROM controls_norm
      WHERE STORED_CONTENT_ID IS NOT NULL
        AND REQUESTED_OBJECT_ID IS NOT NULL
        AND STORED_CONTENT_ID = REQUESTED_OBJECT_ID)
        AS CONTROL_ROWS_CONTENT_ID_EQUALS_REQUESTED_OBJECT_ID,

    (SELECT COUNT(*) FROM controls_norm c
      JOIN packages p ON p.PACKAGE_CONTENT_ID = c.STORED_CONTENT_ID)
        AS CONTROL_ROWS_MATCHING_PACKAGE_BY_STORED_CONTENT_ID,

    (SELECT COUNT(DISTINCT c.STORED_CONTENT_ID) FROM controls_norm c
      JOIN packages p ON p.PACKAGE_CONTENT_ID = c.STORED_CONTENT_ID)
        AS DISTINCT_PACKAGES_MATCHING_BY_STORED_CONTENT_ID,

    (SELECT COUNT(*) FROM controls_norm c
      JOIN packages p ON p.PACKAGE_CONTENT_ID = c.REQUESTED_OBJECT_ID)
        AS CONTROL_ROWS_MATCHING_PACKAGE_BY_REQUESTED_OBJECT_ID,

    (SELECT COUNT(DISTINCT c.REQUESTED_OBJECT_ID) FROM controls_norm c
      JOIN packages p ON p.PACKAGE_CONTENT_ID = c.REQUESTED_OBJECT_ID)
        AS DISTINCT_PACKAGES_MATCHING_BY_REQUESTED_OBJECT_ID,

    (SELECT COUNT(*) FROM controls_norm
      WHERE AUTHORIZATION_PACKAGE_REF_ID IS NOT NULL)
        AS CONTROL_ROWS_WITH_SCALAR_AUTH_PACKAGE_REF,

    (SELECT COUNT(*) FROM controls_norm c
      JOIN packages p ON p.PACKAGE_CONTENT_ID = c.AUTHORIZATION_PACKAGE_REF_ID)
        AS CONTROL_ROWS_MATCHING_PACKAGE_BY_AUTH_PACKAGE_FIELD,

    (SELECT COUNT(DISTINCT c.AUTHORIZATION_PACKAGE_REF_ID) FROM controls_norm c
      JOIN packages p ON p.PACKAGE_CONTENT_ID = c.AUTHORIZATION_PACKAGE_REF_ID)
        AS DISTINCT_PACKAGES_MATCHING_BY_AUTH_PACKAGE_FIELD;

-- Shape of AUTHORIZATION_PACKAGE in the current allocated-controls CURATED_JSON.
WITH controls AS (
    SELECT CURATED_JSON:"AUTHORIZATION_PACKAGE" AS AUTHORIZATION_PACKAGE_VALUE
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_ALLOCATED_CONTROLS_CONTROL_RAW
)
SELECT
    TYPEOF(AUTHORIZATION_PACKAGE_VALUE) AS AUTHORIZATION_PACKAGE_TYPE,
    COUNT(*) AS ROWS
FROM controls
GROUP BY TYPEOF(AUTHORIZATION_PACKAGE_VALUE)
ORDER BY ROWS DESC, AUTHORIZATION_PACKAGE_TYPE;
