-- SSP component hydration gap diagnostic
-- Date: 2026-10-01
-- READ ONLY. No DML / DDL.
--
-- Context:
-- Cell 7 failed before commit with:
--   Component hydration lookup record is missing
--
-- Historical accepted SSP component hydration intentionally fails closed when
-- an approved component reference cannot be found in its configured lookup source.
--
-- Current hydrated fields:
--   SOFTWARE
--     -> RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_SOFTWARE_RAW
--   INTERCONNECTIONS
--   INTERCONNECTIONS_CONNECTING_INFORMATION_SYSTEM
--     -> RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_INTERCONNECTIONS_RAW
--
-- This file answers three questions:
--   1) which field/type has missing lookup coverage,
--   2) which reference IDs are missing and from which SSP record,
--   3) whether the lookup tables themselves have identity/null/duplicate problems.


-- 1. Coverage summary by hydrated source field.
WITH SOURCE_REFS AS (
    SELECT
        A.CONTENT_ID::VARCHAR AS SSP_CONTENT_ID,
        'SOFTWARE' AS ARCHER_FIELD_NAME,
        'software' AS REFERENCE_TYPE,
        'RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_SOFTWARE_RAW' AS LOOKUP_TABLE,
        TRIM(
            COALESCE(
                F.VALUE:"ContentId"::VARCHAR,
                IFF(TYPEOF(F.VALUE) IN ('VARCHAR','INTEGER','DECIMAL'), F.VALUE::VARCHAR, NULL)
            )
        ) AS REFERENCED_CONTENT_ID
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW A,
         LATERAL FLATTEN(INPUT => GET(A.CURATED_JSON, 'SOFTWARE')) F
    WHERE A.CONTENT_ID IS NOT NULL
      AND TYPEOF(A.CURATED_JSON) = 'OBJECT'

    UNION ALL

    SELECT
        A.CONTENT_ID::VARCHAR,
        'INTERCONNECTIONS',
        'interconnection',
        'RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_INTERCONNECTIONS_RAW',
        TRIM(
            COALESCE(
                F.VALUE:"ContentId"::VARCHAR,
                IFF(TYPEOF(F.VALUE) IN ('VARCHAR','INTEGER','DECIMAL'), F.VALUE::VARCHAR, NULL)
            )
        )
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW A,
         LATERAL FLATTEN(INPUT => GET(A.CURATED_JSON, 'INTERCONNECTIONS')) F
    WHERE A.CONTENT_ID IS NOT NULL
      AND TYPEOF(A.CURATED_JSON) = 'OBJECT'

    UNION ALL

    SELECT
        A.CONTENT_ID::VARCHAR,
        'INTERCONNECTIONS_CONNECTING_INFORMATION_SYSTEM',
        'interconnection',
        'RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_INTERCONNECTIONS_RAW',
        TRIM(
            COALESCE(
                F.VALUE:"ContentId"::VARCHAR,
                IFF(TYPEOF(F.VALUE) IN ('VARCHAR','INTEGER','DECIMAL'), F.VALUE::VARCHAR, NULL)
            )
        )
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW A,
         LATERAL FLATTEN(INPUT => GET(A.CURATED_JSON, 'INTERCONNECTIONS_CONNECTING_INFORMATION_SYSTEM')) F
    WHERE A.CONTENT_ID IS NOT NULL
      AND TYPEOF(A.CURATED_JSON) = 'OBJECT'
),
SOFTWARE_LOOKUP AS (
    SELECT DISTINCT TRIM(CONTENT_ID::VARCHAR) AS CONTENT_ID
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_SOFTWARE_RAW
    WHERE CONTENT_ID IS NOT NULL
),
INTERCONNECTION_LOOKUP AS (
    SELECT DISTINCT TRIM(CONTENT_ID::VARCHAR) AS CONTENT_ID
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_INTERCONNECTIONS_RAW
    WHERE CONTENT_ID IS NOT NULL
),
CHECKED AS (
    SELECT
        S.*,
        CASE
            WHEN S.REFERENCE_TYPE = 'software' AND SW.CONTENT_ID IS NOT NULL THEN 'MATCHED'
            WHEN S.REFERENCE_TYPE = 'interconnection' AND IC.CONTENT_ID IS NOT NULL THEN 'MATCHED'
            ELSE 'MISSING'
        END AS LOOKUP_STATUS
    FROM SOURCE_REFS S
    LEFT JOIN SOFTWARE_LOOKUP SW
      ON S.REFERENCE_TYPE = 'software'
     AND SW.CONTENT_ID = S.REFERENCED_CONTENT_ID
    LEFT JOIN INTERCONNECTION_LOOKUP IC
      ON S.REFERENCE_TYPE = 'interconnection'
     AND IC.CONTENT_ID = S.REFERENCED_CONTENT_ID
    WHERE S.REFERENCED_CONTENT_ID IS NOT NULL
      AND LENGTH(S.REFERENCED_CONTENT_ID) > 0
)
SELECT
    ARCHER_FIELD_NAME,
    REFERENCE_TYPE,
    LOOKUP_TABLE,
    COUNT(*) AS REFERENCE_OCCURRENCES,
    COUNT(DISTINCT REFERENCED_CONTENT_ID) AS DISTINCT_REFERENCED_IDS,
    COUNT_IF(LOOKUP_STATUS = 'MATCHED') AS MATCHED_OCCURRENCES,
    COUNT_IF(LOOKUP_STATUS = 'MISSING') AS MISSING_OCCURRENCES,
    COUNT(DISTINCT IFF(LOOKUP_STATUS = 'MISSING', REFERENCED_CONTENT_ID, NULL))
        AS DISTINCT_MISSING_IDS
FROM CHECKED
GROUP BY 1,2,3
ORDER BY ARCHER_FIELD_NAME;


-- 2. Exact missing references, including the parent SSP record.
WITH SOURCE_REFS AS (
    SELECT
        A.CONTENT_ID::VARCHAR AS SSP_CONTENT_ID,
        'SOFTWARE' AS ARCHER_FIELD_NAME,
        'software' AS REFERENCE_TYPE,
        TRIM(COALESCE(F.VALUE:"ContentId"::VARCHAR,
             IFF(TYPEOF(F.VALUE) IN ('VARCHAR','INTEGER','DECIMAL'), F.VALUE::VARCHAR, NULL)))
            AS REFERENCED_CONTENT_ID
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW A,
         LATERAL FLATTEN(INPUT => GET(A.CURATED_JSON, 'SOFTWARE')) F
    WHERE A.CONTENT_ID IS NOT NULL AND TYPEOF(A.CURATED_JSON) = 'OBJECT'

    UNION ALL

    SELECT
        A.CONTENT_ID::VARCHAR,
        'INTERCONNECTIONS',
        'interconnection',
        TRIM(COALESCE(F.VALUE:"ContentId"::VARCHAR,
             IFF(TYPEOF(F.VALUE) IN ('VARCHAR','INTEGER','DECIMAL'), F.VALUE::VARCHAR, NULL)))
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW A,
         LATERAL FLATTEN(INPUT => GET(A.CURATED_JSON, 'INTERCONNECTIONS')) F
    WHERE A.CONTENT_ID IS NOT NULL AND TYPEOF(A.CURATED_JSON) = 'OBJECT'

    UNION ALL

    SELECT
        A.CONTENT_ID::VARCHAR,
        'INTERCONNECTIONS_CONNECTING_INFORMATION_SYSTEM',
        'interconnection',
        TRIM(COALESCE(F.VALUE:"ContentId"::VARCHAR,
             IFF(TYPEOF(F.VALUE) IN ('VARCHAR','INTEGER','DECIMAL'), F.VALUE::VARCHAR, NULL)))
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW A,
         LATERAL FLATTEN(INPUT => GET(A.CURATED_JSON, 'INTERCONNECTIONS_CONNECTING_INFORMATION_SYSTEM')) F
    WHERE A.CONTENT_ID IS NOT NULL AND TYPEOF(A.CURATED_JSON) = 'OBJECT'
)
SELECT
    S.SSP_CONTENT_ID,
    S.ARCHER_FIELD_NAME,
    S.REFERENCE_TYPE,
    S.REFERENCED_CONTENT_ID,
    CASE
        WHEN S.REFERENCE_TYPE = 'software' THEN
            'RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_SOFTWARE_RAW'
        ELSE
            'RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_INTERCONNECTIONS_RAW'
    END AS EXPECTED_LOOKUP_TABLE
FROM SOURCE_REFS S
LEFT JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_SOFTWARE_RAW SW
  ON S.REFERENCE_TYPE = 'software'
 AND TRIM(SW.CONTENT_ID::VARCHAR) = S.REFERENCED_CONTENT_ID
LEFT JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_INTERCONNECTIONS_RAW IC
  ON S.REFERENCE_TYPE = 'interconnection'
 AND TRIM(IC.CONTENT_ID::VARCHAR) = S.REFERENCED_CONTENT_ID
WHERE S.REFERENCED_CONTENT_ID IS NOT NULL
  AND LENGTH(S.REFERENCED_CONTENT_ID) > 0
  AND (
      (S.REFERENCE_TYPE = 'software' AND SW.CONTENT_ID IS NULL)
      OR
      (S.REFERENCE_TYPE = 'interconnection' AND IC.CONTENT_ID IS NULL)
  )
ORDER BY S.ARCHER_FIELD_NAME, S.SSP_CONTENT_ID, S.REFERENCED_CONTENT_ID;


-- 3. Lookup-table identity / curated-payload health.
SELECT
    'software' AS REFERENCE_TYPE,
    COUNT(*) AS LOOKUP_ROWS,
    COUNT_IF(CONTENT_ID IS NULL OR LENGTH(TRIM(CONTENT_ID::VARCHAR)) = 0)
        AS MISSING_CONTENT_ID_ROWS,
    COUNT_IF(CURATED_JSON IS NULL) AS CURATED_JSON_NULL_ROWS,
    COUNT(*) - COUNT(DISTINCT TRIM(CONTENT_ID::VARCHAR)) AS DUPLICATE_CONTENT_ID_ROWS
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_SOFTWARE_RAW

UNION ALL

SELECT
    'interconnection',
    COUNT(*),
    COUNT_IF(CONTENT_ID IS NULL OR LENGTH(TRIM(CONTENT_ID::VARCHAR)) = 0),
    COUNT_IF(CURATED_JSON IS NULL),
    COUNT(*) - COUNT(DISTINCT TRIM(CONTENT_ID::VARCHAR))
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_INTERCONNECTIONS_RAW;
