-- READ ONLY: inspect the evidence left by the failed cleanup; do NOT rerun cleanup.
-- Date: 2026-09-24
-- Basis: simplify-metadata-boundary @ 9cf0cd05ec4090f3fd19895595ae7d61a926a992
-- Run in the SAME SQL session, database and schema as the STALE_SHAPE failure.
-- Uses the existing TMP tables from that attempt. Does not recreate or drop them.
-- If the TMP tables are unavailable, stop; do not run the DELETE script to recreate them.
-- Output: aggregate counts and stored metadata labels only, no record IDs/payloads.
-- This query does not infer a safe deletion from the observed counts.

WITH affected_packages AS (
    SELECT DISTINCT PACKAGE_CONTENT_ID
    FROM TMP_LEVEL355_BAD_SOURCE
),
package_target AS (
    SELECT d.PK_OSCAL_SSP_ELEMENT_HASH,
           d.SOURCE_SYSTEM_NAME, d.SOURCE_TABLE_NAME, d.ELEMENT_TYPE
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT d
    WHERE EXISTS (
        SELECT 1 FROM affected_packages p
        WHERE p.PACKAGE_CONTENT_ID = d.SOURCE_RECORD_ID
    )
),
scoped_ir AS (
    SELECT * FROM package_target
    WHERE SOURCE_SYSTEM_NAME = 'ARCHER'
      AND SOURCE_TABLE_NAME = 'ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
      AND ELEMENT_TYPE = 'implemented-requirements'
),
checks AS (
    SELECT 10 AS SORT_ORDER, 'BAD_SOURCE_ROWS' AS CHECK_NAME,
           CAST(COUNT(*) AS VARCHAR) AS OBSERVED_VALUE
    FROM TMP_LEVEL355_BAD_SOURCE
    UNION ALL
    SELECT 20, 'PACKAGE_SOURCE_ROWS', CAST(COUNT(*) AS VARCHAR)
    FROM TMP_LEVEL355_PACKAGE_SOURCE
    UNION ALL
    SELECT 30, 'GENERATED_VALID_KEY_ROWS', CAST(COUNT(*) AS VARCHAR)
    FROM TMP_LEVEL355_VALID_KEYS
    UNION ALL
    SELECT 40, 'DISTINCT_NONNULL_VALID_KEYS',
           CAST(COUNT(DISTINCT PK_OSCAL_SSP_ELEMENT_HASH) AS VARCHAR)
    FROM TMP_LEVEL355_VALID_KEYS
    UNION ALL
    SELECT 50, 'TARGET_ROWS_FOR_PACKAGE_BEFORE_METADATA_FILTERS', CAST(COUNT(*) AS VARCHAR)
    FROM package_target
    UNION ALL
    SELECT 60, 'TARGET_IR_ROWS_AFTER_EXACT_METADATA_FILTERS', CAST(COUNT(*) AS VARCHAR)
    FROM scoped_ir
    UNION ALL
    SELECT 70, 'TARGET_IR_ROWS_MATCHING_VALID_KEYS', CAST(COUNT(*) AS VARCHAR)
    FROM scoped_ir t
    WHERE EXISTS (
        SELECT 1 FROM TMP_LEVEL355_VALID_KEYS v
        WHERE v.PK_OSCAL_SSP_ELEMENT_HASH = t.PK_OSCAL_SSP_ELEMENT_HASH
    )
    UNION ALL
    SELECT 80, 'STALE_ROWS_CAPTURED_BY_FAILED_CLEANUP', CAST(COUNT(*) AS VARCHAR)
    FROM TMP_LEVEL355_STALE_IR
    UNION ALL
    SELECT 90, 'DISTINCT_STALE_KEYS',
           CAST(COUNT(DISTINCT PK_OSCAL_SSP_ELEMENT_HASH) AS VARCHAR)
    FROM TMP_LEVEL355_STALE_IR
    UNION ALL
    SELECT 100, 'PACKAGE_KEY_MATCHES_WITHOUT_METADATA_FILTERS', CAST(COUNT(*) AS VARCHAR)
    FROM package_target t
    WHERE EXISTS (
        SELECT 1 FROM TMP_LEVEL355_VALID_KEYS v
        WHERE v.PK_OSCAL_SSP_ELEMENT_HASH = t.PK_OSCAL_SSP_ELEMENT_HASH
    )
    UNION ALL
    SELECT 110, 'ALL_TARGET_ROWS_IN_CONFIGURED_TABLE', CAST(COUNT(*) AS VARCHAR)
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
    UNION ALL
    SELECT 200,
           'STORED_METADATA | ' || COALESCE(SOURCE_SYSTEM_NAME, '<SQL_NULL>')
           || ' | ' || COALESCE(SOURCE_TABLE_NAME, '<SQL_NULL>')
           || ' | ' || COALESCE(ELEMENT_TYPE, '<SQL_NULL>'),
           CAST(COUNT(*) AS VARCHAR)
    FROM package_target
    GROUP BY SOURCE_SYSTEM_NAME, SOURCE_TABLE_NAME, ELEMENT_TYPE
)
SELECT CHECK_NAME, OBSERVED_VALUE
FROM checks
ORDER BY SORT_ORDER, CHECK_NAME;
