-- READ ONLY: resolve the actual Archer value-list IDs used by the 11 SSP CIA/FIPS candidate fields.
-- No guessed Legacy LOE -> FIPS crosswalk is applied.
WITH CIA_SOURCE AS (
    SELECT CONTENT_ID::STRING AS CONTENT_ID, 'RECOMMENDED_CONFIDENTIALITY_CONTROL_CATEGORY' AS ARCHER_FIELD_NAME,
           GET(CURATED_JSON,'RECOMMENDED_CONFIDENTIALITY_CONTROL_CATEGORY') AS RAW_VALUE
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    UNION ALL
    SELECT CONTENT_ID::STRING,'CONFIDENTIALITY_CONTROL_CATEGORY_OVERRIDE',
           GET(CURATED_JSON,'CONFIDENTIALITY_CONTROL_CATEGORY_OVERRIDE')
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    UNION ALL
    SELECT CONTENT_ID::STRING,'RECOMMENDED_INTEGRITY_CONTROL_CATEGORY',
           GET(CURATED_JSON,'RECOMMENDED_INTEGRITY_CONTROL_CATEGORY')
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    UNION ALL
    SELECT CONTENT_ID::STRING,'INTEGRITY_CONTROL_CATEGORY_OVERRIDE',
           GET(CURATED_JSON,'INTEGRITY_CONTROL_CATEGORY_OVERRIDE')
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    UNION ALL
    SELECT CONTENT_ID::STRING,'PROGRAMSITE_INTEGRITY_CONTROL_CATEGORY',
           GET(CURATED_JSON,'PROGRAMSITE_INTEGRITY_CONTROL_CATEGORY')
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    UNION ALL
    SELECT CONTENT_ID::STRING,'RECOMMENDED_AVAILABILITY_CONTROL_CATEGORY',
           GET(CURATED_JSON,'RECOMMENDED_AVAILABILITY_CONTROL_CATEGORY')
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    UNION ALL
    SELECT CONTENT_ID::STRING,'AVAILABILITY_CONTROL_CATEGORY_OVERRIDE',
           GET(CURATED_JSON,'AVAILABILITY_CONTROL_CATEGORY_OVERRIDE')
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    UNION ALL
    SELECT CONTENT_ID::STRING,'PROGRAMSITE_AVAILABILITY_CONTROL_CATEGORY',
           GET(CURATED_JSON,'PROGRAMSITE_AVAILABILITY_CONTROL_CATEGORY')
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    UNION ALL
    SELECT CONTENT_ID::STRING,'CNSS_CONFIDENTIALITY_RATING',
           GET(CURATED_JSON,'CNSS_CONFIDENTIALITY_RATING')
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    UNION ALL
    SELECT CONTENT_ID::STRING,'CNSS_INTEGRITY_RATING',
           GET(CURATED_JSON,'CNSS_INTEGRITY_RATING')
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    UNION ALL
    SELECT CONTENT_ID::STRING,'CNSS_AVAILABILITY_RATING',
           GET(CURATED_JSON,'CNSS_AVAILABILITY_RATING')
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
),
IDS AS (
    SELECT
        S.CONTENT_ID,
        S.ARCHER_FIELD_NAME,
        V.VALUE::STRING AS SELECT_VALUE_ID
    FROM CIA_SOURCE S,
         LATERAL FLATTEN(INPUT => GET(S.RAW_VALUE,'ValuesListIds')) V
)
SELECT
    I.ARCHER_FIELD_NAME,
    TRIM(I.SELECT_VALUE_ID) AS SELECT_VALUE_ID,
    TRIM(M.SELECT_VALUE_NAME::STRING) AS ARCHER_RESOLVED_LABEL,
    CASE
      WHEN LOWER(TRIM(M.SELECT_VALUE_NAME::STRING)) IN ('low','moderate','high')
        THEN LOWER(TRIM(M.SELECT_VALUE_NAME::STRING))
      ELSE NULL
    END AS CANONICAL_FIPS_VALUE_IF_DIRECT,
    COUNT(*) AS OCCURRENCES,
    COUNT(DISTINCT I.CONTENT_ID) AS DISTINCT_CONTENT_IDS,
    MIN(I.CONTENT_ID) AS SAMPLE_CONTENT_ID
FROM IDS I
LEFT JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_META_VALUE M
  ON TRIM(M.SELECT_VALUE_ID::STRING)=TRIM(I.SELECT_VALUE_ID)
GROUP BY 1,2,3,4
ORDER BY 1,3,2;
