-- OLD PUBLISHED VIEW vs NEW OSCAL PUBLISHED VIEW
-- Date: 2026-09-25
-- READ ONLY.
--
-- Legacy consumer view shown by owner:
-- RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_PUBLISHED.C2S_AUTHORIZATION_PACKAGE_ALL
--
-- New OSCAL-backed POC view:
-- RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_PUBLISHED.C2S_OSCAL_AUTHORIZATION_PACKAGE_ALL
--
-- Purpose:
-- 1) prove one-row-per-package parity,
-- 2) compare supported common business columns,
-- 3) identify old columns that are not yet representable from OSCAL-only data,
-- 4) prevent an unsafe replacement of the existing consumer view.


-- =====================================================================
-- 01. KEY / ROW-COUNT PARITY
-- =====================================================================
WITH oldv AS (
  SELECT ARCHER_AUTHORIZATION_PACKAGE_DATA_CONTENT_ID::STRING CONTENT_ID
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_PUBLISHED.C2S_AUTHORIZATION_PACKAGE_ALL
),
newv AS (
  SELECT ARCHER_AUTHORIZATION_PACKAGE_DATA_CONTENT_ID::STRING CONTENT_ID
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_PUBLISHED.C2S_OSCAL_AUTHORIZATION_PACKAGE_ALL
)
SELECT
  (SELECT COUNT(*) FROM oldv) OLD_ROWS,
  (SELECT COUNT(DISTINCT CONTENT_ID) FROM oldv) OLD_DISTINCT_CONTENT_IDS,
  (SELECT COUNT(*) FROM newv) NEW_ROWS,
  (SELECT COUNT(DISTINCT CONTENT_ID) FROM newv) NEW_DISTINCT_CONTENT_IDS,
  (SELECT COUNT(*) FROM oldv o LEFT JOIN newv n USING(CONTENT_ID) WHERE n.CONTENT_ID IS NULL) OLD_ONLY_IDS,
  (SELECT COUNT(*) FROM newv n LEFT JOIN oldv o USING(CONTENT_ID) WHERE o.CONTENT_ID IS NULL) NEW_ONLY_IDS;


-- =====================================================================
-- 02. DIRECT COMMON-COLUMN VALUE PARITY
-- Only compare fields whose semantics are already supported in OSCAL.
-- =====================================================================
WITH oldv AS (
  SELECT
    ARCHER_AUTHORIZATION_PACKAGE_DATA_CONTENT_ID::STRING CONTENT_ID,
    AUTHORIZATION_PACKAGE_NAME,
    OPERATIONAL_STATUS,
    ATOIATO_DATE,
    AUTHORIZATION_DECISION,
    ACRONYM
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_PUBLISHED.C2S_AUTHORIZATION_PACKAGE_ALL
),
newv AS (
  SELECT
    ARCHER_AUTHORIZATION_PACKAGE_DATA_CONTENT_ID::STRING CONTENT_ID,
    AUTHORIZATION_PACKAGE_NAME,
    OPERATIONAL_STATUS,
    ATOIATO_DATE,
    AUTHORIZATION_DECISION,
    ACRONYM
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_PUBLISHED.C2S_OSCAL_AUTHORIZATION_PACKAGE_ALL
),
cmp AS (
  SELECT
    o.CONTENT_ID,
    NOT EQUAL_NULL(o.AUTHORIZATION_PACKAGE_NAME,n.AUTHORIZATION_PACKAGE_NAME) BAD_NAME,
    NOT EQUAL_NULL(o.OPERATIONAL_STATUS,n.OPERATIONAL_STATUS) BAD_OPERATIONAL_STATUS,
    NOT EQUAL_NULL(o.ATOIATO_DATE,n.ATOIATO_DATE) BAD_ATOIATO_DATE,
    NOT EQUAL_NULL(o.AUTHORIZATION_DECISION,n.AUTHORIZATION_DECISION) BAD_AUTHORIZATION_DECISION,
    NOT EQUAL_NULL(o.ACRONYM,n.ACRONYM) BAD_ACRONYM
  FROM oldv o
  JOIN newv n USING(CONTENT_ID)
)
SELECT 'AUTHORIZATION_PACKAGE_NAME' COLUMN_NAME,COUNT_IF(BAD_NAME) MISMATCH_ROWS FROM cmp
UNION ALL
SELECT 'OPERATIONAL_STATUS',COUNT_IF(BAD_OPERATIONAL_STATUS) FROM cmp
UNION ALL
SELECT 'ATOIATO_DATE',COUNT_IF(BAD_ATOIATO_DATE) FROM cmp
UNION ALL
SELECT 'AUTHORIZATION_DECISION',COUNT_IF(BAD_AUTHORIZATION_DECISION) FROM cmp
UNION ALL
SELECT 'ACRONYM',COUNT_IF(BAD_ACRONYM) FROM cmp
ORDER BY COLUMN_NAME;


-- =====================================================================
-- 03. DETAIL FOR COMMON-COLUMN MISMATCHES
-- Expected zero rows when old/new represent the same current business value.
-- =====================================================================
SELECT
  o.ARCHER_AUTHORIZATION_PACKAGE_DATA_CONTENT_ID AS CONTENT_ID,
  o.AUTHORIZATION_PACKAGE_NAME OLD_AUTHORIZATION_PACKAGE_NAME,
  n.AUTHORIZATION_PACKAGE_NAME NEW_AUTHORIZATION_PACKAGE_NAME,
  o.OPERATIONAL_STATUS OLD_OPERATIONAL_STATUS,
  n.OPERATIONAL_STATUS NEW_OPERATIONAL_STATUS,
  o.ATOIATO_DATE OLD_ATOIATO_DATE,
  n.ATOIATO_DATE NEW_ATOIATO_DATE,
  o.AUTHORIZATION_DECISION OLD_AUTHORIZATION_DECISION,
  n.AUTHORIZATION_DECISION NEW_AUTHORIZATION_DECISION,
  o.ACRONYM OLD_ACRONYM,
  n.ACRONYM NEW_ACRONYM
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_PUBLISHED.C2S_AUTHORIZATION_PACKAGE_ALL o
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_PUBLISHED.C2S_OSCAL_AUTHORIZATION_PACKAGE_ALL n
  ON n.ARCHER_AUTHORIZATION_PACKAGE_DATA_CONTENT_ID::STRING
   = o.ARCHER_AUTHORIZATION_PACKAGE_DATA_CONTENT_ID::STRING
WHERE NOT EQUAL_NULL(o.AUTHORIZATION_PACKAGE_NAME,n.AUTHORIZATION_PACKAGE_NAME)
   OR NOT EQUAL_NULL(o.OPERATIONAL_STATUS,n.OPERATIONAL_STATUS)
   OR NOT EQUAL_NULL(o.ATOIATO_DATE,n.ATOIATO_DATE)
   OR NOT EQUAL_NULL(o.AUTHORIZATION_DECISION,n.AUTHORIZATION_DECISION)
   OR NOT EQUAL_NULL(o.ACRONYM,n.ACRONYM)
ORDER BY CONTENT_ID
LIMIT 200;


-- =====================================================================
-- 04. OLD CONTRACT COLUMNS THAT NEED EXPLICIT CUTOVER DECISIONS
--
-- These are visible in the owner-provided existing-view screenshots but are
-- not currently equivalent OSCAL output columns with the same semantics.
--
-- DO NOT silently alias them.
--
-- LEGACY_SAP_ID
-- BUSINESS
-- BUSINESS_NAME
-- POAM_ID
-- POAM_NAME
-- POAM_ID_NAME
-- AUTHORIZATION_PACKAGE_SUBMIT_DATE
-- ATOIATO_EXPIRATION_DATE
-- SYSTEM_ADMINISTRATOR_SA
-- SYSTEM_ADMINISTRATOR_SA_ID_ONLY
-- SYSTEM_ADMINISTRATOR_SA_NAME_ONLY
-- SYSTEM_ADMINISTRATOR_SA_ID_NAME
-- ALTERNATE_SYSTEM_ADMINISTRATOR_SA
-- ALTERNATE_SYSTEM_ADMINISTRATOR_SA_ID_ONLY
-- ALTERNATE_SYSTEM_ADMINISTRATOR_SA_NAME_ONLY
-- ALTERNATE_SYSTEM_ADMINISTRATOR_SA_ID_NAME
-- INFORMATION_OWNER_IO name/id display variants
-- AUTHORIZING_OFFICIAL_AO name/id display variants
-- ENTITY
-- ENTITY_NAME
--
-- Current OSCAL equivalents/near-equivalents that ARE available:
-- SAP_ID (do not assume equals LEGACY_SAP_ID without proof)
-- POAM_ITEMS / POAM_ITEM_COUNT
-- responsible-party UUIDs / RESPONSIBLE_PARTIES
-- PARTIES (currently UUID/type payload, not LDAP employee-name hydration)
-- ASSESSMENT_RESULT_PROPERTIES
-- SYSTEM_CHARACTERISTICS property object
-- COMPONENTS
-- IMPLEMENTED_REQUIREMENTS
-- ASSESSMENT_OBSERVATIONS
-- ASSESSMENT_TASKS
-- relationship-integrity columns
-- =====================================================================


-- =====================================================================
-- 05. NEW INFORMATION AVAILABLE ONLY IN OSCAL POC
-- This is the value-add beyond the old view.
-- =====================================================================
SELECT
  ARCHER_AUTHORIZATION_PACKAGE_DATA_CONTENT_ID,
  SSP_UUID,
  SSP_NODE_COUNT,
  SSP_EDGE_COUNT,
  SSP_RELATIONSHIP_INTEGRITY,

  COMPONENT_COUNT,
  COMPONENTS,

  IMPLEMENTED_REQUIREMENT_COUNT,
  IMPLEMENTED_REQUIREMENTS,

  ASSESSMENT_RESULTS_UUID,
  AR_NODE_COUNT,
  AR_EDGE_COUNT,
  AR_OBSERVATION_COUNT,
  ASSESSMENT_OBSERVATIONS,
  ASSESSMENT_RESULT_PROPERTIES,
  ASSESSMENT_RESULTS_RELATIONSHIP_INTEGRITY,

  POAM_UUID,
  POAM_ITEM_COUNT,
  POAM_ITEMS,
  POAM_RELATIONSHIP_INTEGRITY,

  ASSESSMENT_PLAN_UUID,
  SAP_TASK_COUNT,
  ASSESSMENT_TASKS,
  ASSESSMENT_PLAN_PROPERTIES,
  ASSESSMENT_PLAN_RELATIONSHIP_INTEGRITY,

  CROSS_MODEL_COVERAGE,
  OVERALL_RELATIONSHIP_INTEGRITY
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_PUBLISHED.C2S_OSCAL_AUTHORIZATION_PACKAGE_ALL
ORDER BY ARCHER_AUTHORIZATION_PACKAGE_DATA_CONTENT_ID
LIMIT 100;
