-- POAM POST-REBUILD WHOLE-TABLE QA - 2026-09-28
-- READ ONLY: one SELECT, no substitutions. Returns 17 aggregate rows.
-- Reviewed repository: theenduser009/Oscal-mapping-strategy
-- Branch: simplify-metadata-boundary @ 2b9ec6d652d78c9341d30fa94a766600b570c3a1
-- Bindings/rules reviewed in sql/qa/SOURCE_ONE_PRODUCTION_QA_2026-09-25.sql.
-- Baseline: owner-posted September 28 rebuild COMMITTED_AND_VERIFIED report:
-- 2,813 source records, 2,821 DIM rows, 8 FACT rows. Not permanent business constants.
-- Whole POAM DIM/FACT tables: NO Content ID or source filter can hide orphans.
-- Other model tables, source data, mappings and registry are not changed/read.
-- PASS: these stored counts and structural checks agree with the rebuild.
-- DRIFT: baseline counts differ, even if the structural checks pass.
-- FAIL: at least one structural check fails. Do not sum overlapping defect counts.
-- Duplicate DIM keys can multiply joined defect counts; the key check fails too.
-- Not source-field parity, full OSCAL document conformance, or a loader code fix.
-- This script is a separate post-load gate, not added to the daily pipeline.

WITH
d AS (
    SELECT PK_DIM_OSCAL_POAM_ELEMENT_HASH AS NODE_KEY, ELEMENT_TYPE, OSCAL_UUID,
           SOURCE_SYSTEM_NAME, SOURCE_TABLE_NAME, SOURCE_RECORD_ID
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT
),
f AS (
    SELECT PK_FACT_OSCAL_POAM_DEPENDENCY_HASH AS FACT_KEY,
           FK_SOURCE_ELEMENT_HASH, FK_TARGET_ELEMENT_HASH, DEPENDENCY_TYPE,
           SOURCE_OSCAL_UUID, TARGET_OSCAL_UUID
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_POAM_DEPENDENCY
),
key_defects AS (
    SELECT 'DIM_PK' AS KEY_KIND FROM d
    GROUP BY NODE_KEY HAVING NODE_KEY IS NULL OR COUNT(*)>1
    UNION ALL
    SELECT 'FACT_PK' FROM f
    GROUP BY FACT_KEY HAVING FACT_KEY IS NULL OR COUNT(*)>1
    UNION ALL
    SELECT 'DIM_UUID' FROM d
    GROUP BY OSCAL_UUID
    HAVING OSCAL_UUID IS NULL OR TRIM(OSCAL_UUID)='' OR COUNT(*)>1
),
joined_edges AS (
    SELECT f.*,
           s.ELEMENT_TYPE AS SOURCE_TYPE, t.ELEMENT_TYPE AS TARGET_TYPE,
           s.OSCAL_UUID AS PARENT_UUID, t.OSCAL_UUID AS CHILD_UUID,
           s.SOURCE_SYSTEM_NAME AS PARENT_SYSTEM, t.SOURCE_SYSTEM_NAME AS CHILD_SYSTEM,
           s.SOURCE_TABLE_NAME AS PARENT_TABLE, t.SOURCE_TABLE_NAME AS CHILD_TABLE,
           s.SOURCE_RECORD_ID AS PARENT_RECORD, t.SOURCE_RECORD_ID AS CHILD_RECORD
    FROM f
    JOIN d s ON s.NODE_KEY=f.FK_SOURCE_ELEMENT_HASH
    JOIN d t ON t.NODE_KEY=f.FK_TARGET_ELEMENT_HASH
),
root_counts AS (
    SELECT SOURCE_SYSTEM_NAME, SOURCE_TABLE_NAME, SOURCE_RECORD_ID,
           SUM(CASE WHEN ELEMENT_TYPE='plan-of-action-and-milestones' THEN 1 ELSE 0 END) AS ROOTS
    FROM d GROUP BY SOURCE_SYSTEM_NAME, SOURCE_TABLE_NAME, SOURCE_RECORD_ID
),
parent_counts AS (
    SELECT d.NODE_KEY, d.ELEMENT_TYPE, COUNT(f.FK_TARGET_ELEMENT_HASH) AS PARENTS
    FROM d LEFT JOIN f ON f.FK_TARGET_ELEMENT_HASH=d.NODE_KEY
    GROUP BY d.NODE_KEY, d.ELEMENT_TYPE
),
checks AS (
    SELECT 1 AS CHECK_ORDER, 'DIM_ROWS' AS QA_CHECK, COUNT(*) AS OBSERVED_COUNT,
           2821 AS EXPECTED_COUNT, 'BASELINE' AS CHECK_KIND FROM d
    UNION ALL SELECT 2, 'FACT_ROWS', COUNT(*), 8, 'BASELINE' FROM f
    UNION ALL SELECT 3, 'ROOT_ROWS', COUNT(*), 2813, 'BASELINE'
        FROM d WHERE ELEMENT_TYPE='plan-of-action-and-milestones'
    UNION ALL SELECT 4, 'POAM_ITEM_ROWS', COUNT(*), 8, 'BASELINE'
        FROM d WHERE ELEMENT_TYPE='poam-items'
    UNION ALL SELECT 5, 'NULL_OR_DUPLICATE_KEY_GROUPS', COUNT(*), 0, 'DEFECT' FROM key_defects
    UNION ALL SELECT 6, 'INVALID_SOURCE_OWNERSHIP_ROWS', COUNT(*), 0, 'DEFECT'
        FROM d WHERE SOURCE_SYSTEM_NAME IS DISTINCT FROM 'ARCHER'
            OR SOURCE_TABLE_NAME IS DISTINCT FROM 'ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
            OR SOURCE_RECORD_ID IS NULL OR TRIM(SOURCE_RECORD_ID)=''
    UNION ALL SELECT 7, 'UNEXPECTED_ELEMENT_TYPES', COUNT(*), 0, 'DEFECT'
        FROM d WHERE ELEMENT_TYPE IS NULL
            OR ELEMENT_TYPE NOT IN ('plan-of-action-and-milestones','poam-items')
    UNION ALL SELECT 8, 'RECORDS_WITHOUT_EXACTLY_ONE_ROOT', COUNT(*), 0, 'DEFECT'
        FROM root_counts WHERE ROOTS<>1
    UNION ALL SELECT 9, 'NULL_OR_BLANK_FACT_REFERENCES', COUNT(*), 0, 'DEFECT'
        FROM f WHERE FK_SOURCE_ELEMENT_HASH IS NULL OR FK_TARGET_ELEMENT_HASH IS NULL
            OR SOURCE_OSCAL_UUID IS NULL OR TRIM(SOURCE_OSCAL_UUID)=''
            OR TARGET_OSCAL_UUID IS NULL OR TRIM(TARGET_OSCAL_UUID)=''
    UNION ALL SELECT 10, 'ORPHAN_SOURCE_FK', COUNT(*), 0, 'DEFECT'
        FROM f WHERE NOT EXISTS (SELECT 1 FROM d WHERE d.NODE_KEY=f.FK_SOURCE_ELEMENT_HASH)
    UNION ALL SELECT 11, 'ORPHAN_TARGET_FK', COUNT(*), 0, 'DEFECT'
        FROM f WHERE NOT EXISTS (SELECT 1 FROM d WHERE d.NODE_KEY=f.FK_TARGET_ELEMENT_HASH)
    UNION ALL SELECT 12, 'UUID_MISMATCH', COUNT(*), 0, 'DEFECT'
        FROM joined_edges WHERE SOURCE_OSCAL_UUID IS DISTINCT FROM PARENT_UUID
            OR TARGET_OSCAL_UUID IS DISTINCT FROM CHILD_UUID
    UNION ALL SELECT 13, 'CROSS_RECORD_OR_NAMESPACE_EDGES', COUNT(*), 0, 'DEFECT'
        FROM joined_edges WHERE PARENT_SYSTEM IS DISTINCT FROM CHILD_SYSTEM
            OR PARENT_TABLE IS DISTINCT FROM CHILD_TABLE
            OR PARENT_RECORD IS DISTINCT FROM CHILD_RECORD
    UNION ALL SELECT 14, 'INVALID_CONTAINS_OR_ROOT_ITEM_EDGES', COUNT(*), 0, 'DEFECT'
        FROM joined_edges WHERE DEPENDENCY_TYPE IS DISTINCT FROM 'CONTAINS'
            OR SOURCE_TYPE IS DISTINCT FROM 'plan-of-action-and-milestones'
            OR TARGET_TYPE IS DISTINCT FROM 'poam-items'
            OR FK_SOURCE_ELEMENT_HASH=FK_TARGET_ELEMENT_HASH
    UNION ALL SELECT 15, 'WRONG_PARENT_COUNT', COUNT(*), 0, 'DEFECT'
        FROM parent_counts
        WHERE PARENTS<>CASE WHEN ELEMENT_TYPE='plan-of-action-and-milestones' THEN 0 ELSE 1 END
    UNION ALL SELECT 16, 'EDGE_MINUS_NONROOT_COUNT',
        (SELECT COUNT(*) FROM f) -
        ((SELECT COUNT(*) FROM d) -
         (SELECT COUNT(*) FROM d WHERE ELEMENT_TYPE='plan-of-action-and-milestones')),
        0, 'DEFECT'
),
results AS (
    SELECT CHECK_ORDER, QA_CHECK, OBSERVED_COUNT, EXPECTED_COUNT,
           CASE WHEN OBSERVED_COUNT=EXPECTED_COUNT THEN 'PASS'
                WHEN CHECK_KIND='BASELINE' THEN 'DRIFT'
                ELSE 'FAIL' END AS STATUS
    FROM checks
),
report AS (
    SELECT 0 AS CHECK_ORDER, 'OVERALL_POAM_REBUILD_QA' AS QA_CHECK,
           SUM(CASE WHEN STATUS<>'PASS' THEN 1 ELSE 0 END) AS OBSERVED_COUNT,
           0 AS EXPECTED_COUNT,
           CASE WHEN SUM(CASE WHEN STATUS='FAIL' THEN 1 ELSE 0 END)>0 THEN 'FAIL'
                WHEN SUM(CASE WHEN STATUS='DRIFT' THEN 1 ELSE 0 END)>0 THEN 'DRIFT'
                ELSE 'PASS' END AS STATUS
    FROM results
    UNION ALL
    SELECT CHECK_ORDER, QA_CHECK, OBSERVED_COUNT, EXPECTED_COUNT, STATUS FROM results
)
SELECT CURRENT_TIMESTAMP() AS QA_EXECUTED_AT,
       CHECK_ORDER, QA_CHECK, OBSERVED_COUNT, EXPECTED_COUNT, STATUS
FROM report
ORDER BY CHECK_ORDER;
