-- SOURCE ONE PRODUCTION QA / RELEASE SIGN-OFF
-- Date: 2026-09-25
-- READ ONLY: no source, registry, DIM or FACT DML.
--
-- Purpose:
--   Validate the actual committed Source One DIM/FACT warehouse state after mapping.
--   This pack tests source coverage, graph cardinality, duplicate keys, UUIDs,
--   orphan facts, parent/child lineage, cross-model CONTENT_ID coverage,
--   selected field-value parity, Level-355 implemented-requirement parity,
--   and current-release baseline counts.
--
-- Source One RAW:
--   RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
--
-- Source One target models:
--   SSP
--   ASSESSMENT_RESULTS
--   POAM
--   SECURITY_ASSESSMENT_PLAN
--
-- IMPORTANT:
-- DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT / FACT_OSCAL_ASSESSMENT_RESULTS_DEPENDENCY
-- are shared with Source Two. Source One tests therefore scope by:
--   SOURCE_SYSTEM_NAME='ARCHER'
--   SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
--
-- PASS RULE:
-- Any DEFECT_COUNT > 0 in defect sections requires review.
-- Current-release baseline counts are release evidence, not permanent business constants.


-- =====================================================================
-- 00. SOURCE ONE RAW UNIQUENESS
-- Expected now: 2813 rows, 2813 distinct CONTENT_ID, 0 null/blank IDs.
-- =====================================================================
SELECT
  COUNT(*) AS SOURCE_ROWS,
  COUNT(DISTINCT TRIM(CONTENT_ID::STRING)) AS DISTINCT_CONTENT_IDS,
  COUNT_IF(CONTENT_ID IS NULL OR NULLIF(TRIM(CONTENT_ID::STRING),'') IS NULL) AS NULL_OR_BLANK_CONTENT_IDS,
  IFF(
    COUNT(*) = COUNT(DISTINCT TRIM(CONTENT_ID::STRING))
    AND COUNT_IF(CONTENT_ID IS NULL OR NULLIF(TRIM(CONTENT_ID::STRING),'') IS NULL)=0,
    'PASS','FAIL'
  ) AS STATUS
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW;


-- =====================================================================
-- 01. CURRENT RELEASE MODEL COUNTS + GRAPH CARDINALITY
-- In this graph design every non-root node has exactly one incoming edge,
-- therefore SOURCE-ONE edge count must equal node count minus root count.
--
-- Current accepted release baseline:
-- SSP:                   546799 nodes / 543986 edges
-- ASSESSMENT_RESULTS:    109630 nodes / 106817 edges
-- POAM:                    2821 nodes /      8 edges
-- SECURITY_ASSESSMENT_PLAN:11252 nodes /   8439 edges
-- =====================================================================
WITH
ssp_d AS (
  SELECT *
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER'
    AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
),
ssp_f AS (
  SELECT f.*
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY f
  JOIN ssp_d s ON s.PK_OSCAL_SSP_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
  JOIN ssp_d t ON t.PK_OSCAL_SSP_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
),
ar_d AS (
  SELECT *
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER'
    AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
),
ar_f AS (
  SELECT f.*
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_RESULTS_DEPENDENCY f
  JOIN ar_d s ON s.PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
  JOIN ar_d t ON t.PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
),
poam_d AS (
  SELECT *
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER'
    AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
),
poam_f AS (
  SELECT f.*
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_POAM_DEPENDENCY f
  JOIN poam_d s ON s.PK_DIM_OSCAL_POAM_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
  JOIN poam_d t ON t.PK_DIM_OSCAL_POAM_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
),
sap_d AS (
  SELECT *
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER'
    AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
),
sap_f AS (
  SELECT f.*
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_PLAN_DEPENDENCY f
  JOIN sap_d s ON s.PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
  JOIN sap_d t ON t.PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
),
counts AS (
  SELECT 'SSP' MODEL, (SELECT COUNT(*) FROM ssp_d) NODES,
         (SELECT COUNT_IF(ELEMENT_TYPE='system-security-plan') FROM ssp_d) ROOTS,
         (SELECT COUNT(*) FROM ssp_f) EDGES,
         546799 BASELINE_NODES, 543986 BASELINE_EDGES
  UNION ALL
  SELECT 'ASSESSMENT_RESULTS', (SELECT COUNT(*) FROM ar_d),
         (SELECT COUNT_IF(ELEMENT_TYPE='assessment-results') FROM ar_d),
         (SELECT COUNT(*) FROM ar_f), 109630, 106817
  UNION ALL
  SELECT 'POAM', (SELECT COUNT(*) FROM poam_d),
         (SELECT COUNT_IF(ELEMENT_TYPE='plan-of-action-and-milestones') FROM poam_d),
         (SELECT COUNT(*) FROM poam_f), 2821, 8
  UNION ALL
  SELECT 'SECURITY_ASSESSMENT_PLAN', (SELECT COUNT(*) FROM sap_d),
         (SELECT COUNT_IF(ELEMENT_TYPE='assessment-plan') FROM sap_d),
         (SELECT COUNT(*) FROM sap_f), 11252, 8439
)
SELECT
  MODEL, NODES, ROOTS, EDGES,
  NODES-ROOTS AS EXPECTED_EDGES_FROM_TREE_GRAIN,
  IFF(EDGES=NODES-ROOTS,'PASS','FAIL') AS GRAPH_CARDINALITY_STATUS,
  BASELINE_NODES, BASELINE_EDGES,
  IFF(NODES=BASELINE_NODES AND EDGES=BASELINE_EDGES,'PASS','DRIFT') AS CURRENT_RELEASE_BASELINE_STATUS
FROM counts
ORDER BY MODEL;


-- =====================================================================
-- 02. ROOT COVERAGE BY CONTENT_ID
-- Every Source One CONTENT_ID must have exactly one root in every executable model.
-- Expected: MISSING_ROOTS=0, DUPLICATE_ROOT_IDS=0, EXTRA_ROOT_IDS=0 for every model.
-- =====================================================================
WITH
src AS (
  SELECT DISTINCT TRIM(CONTENT_ID::STRING) CONTENT_ID
  FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
),
ssp_r AS (
  SELECT TRIM(SOURCE_RECORD_ID::STRING) CONTENT_ID, COUNT(*) N
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER'
    AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='system-security-plan'
  GROUP BY 1
),
ar_r AS (
  SELECT TRIM(SOURCE_RECORD_ID::STRING) CONTENT_ID, COUNT(*) N
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER'
    AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='assessment-results'
  GROUP BY 1
),
poam_r AS (
  SELECT TRIM(SOURCE_RECORD_ID::STRING) CONTENT_ID, COUNT(*) N
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER'
    AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='plan-of-action-and-milestones'
  GROUP BY 1
),
sap_r AS (
  SELECT TRIM(SOURCE_RECORD_ID::STRING) CONTENT_ID, COUNT(*) N
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER'
    AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='assessment-plan'
  GROUP BY 1
),
summary AS (
  SELECT 'SSP' MODEL,
         COUNT_IF(r.CONTENT_ID IS NULL) MISSING_ROOTS,
         COUNT_IF(COALESCE(r.N,0)>1) DUPLICATE_ROOT_IDS,
         (SELECT COUNT(*) FROM ssp_r r2 LEFT JOIN src s2 USING(CONTENT_ID) WHERE s2.CONTENT_ID IS NULL) EXTRA_ROOT_IDS
  FROM src s LEFT JOIN ssp_r r USING(CONTENT_ID)
  UNION ALL
  SELECT 'ASSESSMENT_RESULTS',
         COUNT_IF(r.CONTENT_ID IS NULL), COUNT_IF(COALESCE(r.N,0)>1),
         (SELECT COUNT(*) FROM ar_r r2 LEFT JOIN src s2 USING(CONTENT_ID) WHERE s2.CONTENT_ID IS NULL)
  FROM src s LEFT JOIN ar_r r USING(CONTENT_ID)
  UNION ALL
  SELECT 'POAM',
         COUNT_IF(r.CONTENT_ID IS NULL), COUNT_IF(COALESCE(r.N,0)>1),
         (SELECT COUNT(*) FROM poam_r r2 LEFT JOIN src s2 USING(CONTENT_ID) WHERE s2.CONTENT_ID IS NULL)
  FROM src s LEFT JOIN poam_r r USING(CONTENT_ID)
  UNION ALL
  SELECT 'SECURITY_ASSESSMENT_PLAN',
         COUNT_IF(r.CONTENT_ID IS NULL), COUNT_IF(COALESCE(r.N,0)>1),
         (SELECT COUNT(*) FROM sap_r r2 LEFT JOIN src s2 USING(CONTENT_ID) WHERE s2.CONTENT_ID IS NULL)
  FROM src s LEFT JOIN sap_r r USING(CONTENT_ID)
)
SELECT *,
       IFF(MISSING_ROOTS=0 AND DUPLICATE_ROOT_IDS=0 AND EXTRA_ROOT_IDS=0,'PASS','FAIL') STATUS
FROM summary
ORDER BY MODEL;


-- 02B. DETAIL ONLY IF ROOT COVERAGE FAILED. Expected: zero rows.
WITH
src AS (
  SELECT DISTINCT TRIM(CONTENT_ID::STRING) CONTENT_ID
  FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
),
roots AS (
  SELECT 'SSP' MODEL, TRIM(SOURCE_RECORD_ID::STRING) CONTENT_ID, COUNT(*) N
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='system-security-plan' GROUP BY 1,2
  UNION ALL
  SELECT 'ASSESSMENT_RESULTS', TRIM(SOURCE_RECORD_ID::STRING), COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='assessment-results' GROUP BY 1,2
  UNION ALL
  SELECT 'POAM', TRIM(SOURCE_RECORD_ID::STRING), COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='plan-of-action-and-milestones' GROUP BY 1,2
  UNION ALL
  SELECT 'SECURITY_ASSESSMENT_PLAN', TRIM(SOURCE_RECORD_ID::STRING), COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='assessment-plan' GROUP BY 1,2
),
models AS (
  SELECT COLUMN1 MODEL FROM VALUES ('SSP'),('ASSESSMENT_RESULTS'),('POAM'),('SECURITY_ASSESSMENT_PLAN')
)
SELECT m.MODEL, s.CONTENT_ID,
       CASE WHEN r.CONTENT_ID IS NULL THEN 'MISSING_ROOT'
            WHEN r.N<>1 THEN 'DUPLICATE_ROOT'
       END DEFECT,
       COALESCE(r.N,0) ROOT_COUNT
FROM src s CROSS JOIN models m
LEFT JOIN roots r ON r.MODEL=m.MODEL AND r.CONTENT_ID=s.CONTENT_ID
WHERE r.CONTENT_ID IS NULL OR r.N<>1
UNION ALL
SELECT r.MODEL, r.CONTENT_ID, 'EXTRA_ROOT', r.N
FROM roots r LEFT JOIN src s USING(CONTENT_ID)
WHERE s.CONTENT_ID IS NULL
ORDER BY MODEL, CONTENT_ID
LIMIT 500;


-- =====================================================================
-- 03. DIM INTEGRITY
-- Expected every DEFECT_COUNT = 0.
-- Checks: duplicate physical PK, duplicate OSCAL UUID, blank lineage,
-- invalid UUID width, null audit metadata.
-- =====================================================================
WITH checks AS (
  SELECT 'SSP' MODEL, 'DUPLICATE_DIM_PK' DEFECT,
         COUNT(*) DEFECT_COUNT FROM (
    SELECT PK_OSCAL_SSP_ELEMENT_HASH
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
    GROUP BY 1 HAVING COUNT(*)>1
  )
  UNION ALL
  SELECT 'SSP','DUPLICATE_OSCAL_UUID',COUNT(*) FROM (
    SELECT OSCAL_UUID
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
    WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    GROUP BY 1 HAVING COUNT(*)>1
  )
  UNION ALL
  SELECT 'SSP','NULL_OR_BAD_LINEAGE',
    COUNT_IF(SOURCE_RECORD_ID IS NULL OR NULLIF(TRIM(SOURCE_RECORD_ID),'') IS NULL
             OR SOURCE_SYSTEM_NAME<>'ARCHER'
             OR SOURCE_TABLE_NAME<>'ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW')
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
  WHERE SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW' OR SOURCE_SYSTEM_NAME='ARCHER'
  UNION ALL
  SELECT 'SSP','INVALID_UUID_LENGTH',
    COUNT_IF(OSCAL_UUID IS NULL OR LENGTH(OSCAL_UUID)<>32)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  UNION ALL
  SELECT 'SSP','NULL_AUDIT',
    COUNT_IF(DW_PIPELINE_RUN_ID IS NULL OR DW_LOAD_TIMESTAMP IS NULL OR DW_LOAD_TIMESTAMP_TZ IS NULL)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'

  UNION ALL
  SELECT 'ASSESSMENT_RESULTS','DUPLICATE_DIM_PK',COUNT(*) FROM (
    SELECT PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT
    GROUP BY 1 HAVING COUNT(*)>1
  )
  UNION ALL
  SELECT 'ASSESSMENT_RESULTS','DUPLICATE_OSCAL_UUID',COUNT(*) FROM (
    SELECT OSCAL_UUID
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT
    WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    GROUP BY 1 HAVING COUNT(*)>1
  )
  UNION ALL
  SELECT 'ASSESSMENT_RESULTS','NULL_OR_BAD_LINEAGE',
    COUNT_IF(SOURCE_RECORD_ID IS NULL OR NULLIF(TRIM(SOURCE_RECORD_ID),'') IS NULL)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  UNION ALL
  SELECT 'ASSESSMENT_RESULTS','INVALID_UUID_LENGTH',
    COUNT_IF(OSCAL_UUID IS NULL OR LENGTH(OSCAL_UUID)<>32)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  UNION ALL
  SELECT 'ASSESSMENT_RESULTS','NULL_AUDIT',
    COUNT_IF(DW_PIPELINE_RUN_ID IS NULL OR DW_LOAD_TIMESTAMP IS NULL OR DW_LOAD_TIMESTAMP_TZ IS NULL)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'

  UNION ALL
  SELECT 'POAM','DUPLICATE_DIM_PK',COUNT(*) FROM (
    SELECT PK_DIM_OSCAL_POAM_ELEMENT_HASH
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT
    GROUP BY 1 HAVING COUNT(*)>1
  )
  UNION ALL
  SELECT 'POAM','DUPLICATE_OSCAL_UUID',COUNT(*) FROM (
    SELECT OSCAL_UUID
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT
    WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    GROUP BY 1 HAVING COUNT(*)>1
  )
  UNION ALL
  SELECT 'POAM','NULL_OR_BAD_LINEAGE',
    COUNT_IF(SOURCE_RECORD_ID IS NULL OR NULLIF(TRIM(SOURCE_RECORD_ID),'') IS NULL)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  UNION ALL
  SELECT 'POAM','INVALID_UUID_LENGTH',
    COUNT_IF(OSCAL_UUID IS NULL OR LENGTH(OSCAL_UUID)<>32)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  UNION ALL
  SELECT 'POAM','NULL_AUDIT',
    COUNT_IF(DW_PIPELINE_RUN_ID IS NULL OR DW_LOAD_TIMESTAMP IS NULL OR DW_LOAD_TIMESTAMP_TZ IS NULL)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'

  UNION ALL
  SELECT 'SECURITY_ASSESSMENT_PLAN','DUPLICATE_DIM_PK',COUNT(*) FROM (
    SELECT PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT
    GROUP BY 1 HAVING COUNT(*)>1
  )
  UNION ALL
  SELECT 'SECURITY_ASSESSMENT_PLAN','DUPLICATE_OSCAL_UUID',COUNT(*) FROM (
    SELECT OSCAL_UUID
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT
    WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    GROUP BY 1 HAVING COUNT(*)>1
  )
  UNION ALL
  SELECT 'SECURITY_ASSESSMENT_PLAN','NULL_OR_BAD_LINEAGE',
    COUNT_IF(SOURCE_RECORD_ID IS NULL OR NULLIF(TRIM(SOURCE_RECORD_ID),'') IS NULL)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  UNION ALL
  SELECT 'SECURITY_ASSESSMENT_PLAN','INVALID_UUID_LENGTH',
    COUNT_IF(OSCAL_UUID IS NULL OR LENGTH(OSCAL_UUID)<>32)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  UNION ALL
  SELECT 'SECURITY_ASSESSMENT_PLAN','NULL_AUDIT',
    COUNT_IF(DW_PIPELINE_RUN_ID IS NULL OR DW_LOAD_TIMESTAMP IS NULL OR DW_LOAD_TIMESTAMP_TZ IS NULL)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
)
SELECT MODEL, DEFECT, DEFECT_COUNT, IFF(DEFECT_COUNT=0,'PASS','FAIL') STATUS
FROM checks
ORDER BY MODEL, DEFECT;


-- =====================================================================
-- 04. FACT / RELATIONSHIP INTEGRITY
-- Expected every DEFECT_COUNT = 0.
-- Includes:
--   duplicate fact PK
--   null FK
--   orphan source/target FK
--   self edge
--   fact UUID mismatch against DIM UUID
--   cross-record edge inside Source One
--   cross-source-namespace edge (especially important for shared AR tables)
-- =====================================================================
WITH checks AS (
  -- SSP
  SELECT 'SSP' MODEL,'DUPLICATE_FACT_PK' DEFECT,COUNT(*) DEFECT_COUNT FROM (
    SELECT PK_FACT_OSCAL_DEPENDENCY_HASH
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY
    GROUP BY 1 HAVING COUNT(*)>1
  )
  UNION ALL
  SELECT 'SSP','NULL_FK',
    COUNT_IF(FK_SOURCE_ELEMENT_HASH IS NULL OR FK_TARGET_ELEMENT_HASH IS NULL)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY
  UNION ALL
  SELECT 'SSP','ORPHAN_SOURCE_FK',COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY f
  LEFT JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT d
    ON d.PK_OSCAL_SSP_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
  WHERE d.PK_OSCAL_SSP_ELEMENT_HASH IS NULL
  UNION ALL
  SELECT 'SSP','ORPHAN_TARGET_FK',COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY f
  LEFT JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT d
    ON d.PK_OSCAL_SSP_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
  WHERE d.PK_OSCAL_SSP_ELEMENT_HASH IS NULL
  UNION ALL
  SELECT 'SSP','SELF_EDGE',COUNT_IF(FK_SOURCE_ELEMENT_HASH=FK_TARGET_ELEMENT_HASH)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY
  UNION ALL
  SELECT 'SSP','UUID_MISMATCH',COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY f
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT s
    ON s.PK_OSCAL_SSP_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT t
    ON t.PK_OSCAL_SSP_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
  WHERE f.SOURCE_OSCAL_UUID<>s.OSCAL_UUID OR f.TARGET_OSCAL_UUID<>t.OSCAL_UUID
  UNION ALL
  SELECT 'SSP','CROSS_RECORD_EDGE',COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY f
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT s
    ON s.PK_OSCAL_SSP_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT t
    ON t.PK_OSCAL_SSP_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
  WHERE s.SOURCE_SYSTEM_NAME='ARCHER' AND s.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND t.SOURCE_SYSTEM_NAME='ARCHER' AND t.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND s.SOURCE_RECORD_ID<>t.SOURCE_RECORD_ID
  UNION ALL
  SELECT 'SSP','CROSS_NAMESPACE_EDGE',COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY f
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT s
    ON s.PK_OSCAL_SSP_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT t
    ON t.PK_OSCAL_SSP_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
  WHERE COALESCE(s.SOURCE_SYSTEM_NAME,'')<>COALESCE(t.SOURCE_SYSTEM_NAME,'')
     OR COALESCE(s.SOURCE_TABLE_NAME,'')<>COALESCE(t.SOURCE_TABLE_NAME,'')

  -- ASSESSMENT RESULTS
  UNION ALL
  SELECT 'ASSESSMENT_RESULTS','DUPLICATE_FACT_PK',COUNT(*) FROM (
    SELECT PK_FACT_OSCAL_ASSESSMENT_RESULTS_DEPENDENCY_HASH
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_RESULTS_DEPENDENCY
    GROUP BY 1 HAVING COUNT(*)>1
  )
  UNION ALL
  SELECT 'ASSESSMENT_RESULTS','NULL_FK',
    COUNT_IF(FK_SOURCE_ELEMENT_HASH IS NULL OR FK_TARGET_ELEMENT_HASH IS NULL)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_RESULTS_DEPENDENCY
  UNION ALL
  SELECT 'ASSESSMENT_RESULTS','ORPHAN_SOURCE_FK',COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_RESULTS_DEPENDENCY f
  LEFT JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT d
    ON d.PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
  WHERE d.PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH IS NULL
  UNION ALL
  SELECT 'ASSESSMENT_RESULTS','ORPHAN_TARGET_FK',COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_RESULTS_DEPENDENCY f
  LEFT JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT d
    ON d.PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
  WHERE d.PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH IS NULL
  UNION ALL
  SELECT 'ASSESSMENT_RESULTS','SELF_EDGE',
    COUNT_IF(FK_SOURCE_ELEMENT_HASH=FK_TARGET_ELEMENT_HASH)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_RESULTS_DEPENDENCY
  UNION ALL
  SELECT 'ASSESSMENT_RESULTS','UUID_MISMATCH',COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_RESULTS_DEPENDENCY f
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT s
    ON s.PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT t
    ON t.PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
  WHERE f.SOURCE_OSCAL_UUID<>s.OSCAL_UUID OR f.TARGET_OSCAL_UUID<>t.OSCAL_UUID
  UNION ALL
  SELECT 'ASSESSMENT_RESULTS','CROSS_RECORD_EDGE',COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_RESULTS_DEPENDENCY f
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT s
    ON s.PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT t
    ON t.PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
  WHERE s.SOURCE_SYSTEM_NAME='ARCHER' AND s.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND t.SOURCE_SYSTEM_NAME='ARCHER' AND t.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND s.SOURCE_RECORD_ID<>t.SOURCE_RECORD_ID
  UNION ALL
  SELECT 'ASSESSMENT_RESULTS','CROSS_NAMESPACE_EDGE',COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_RESULTS_DEPENDENCY f
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT s
    ON s.PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT t
    ON t.PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
  WHERE COALESCE(s.SOURCE_SYSTEM_NAME,'')<>COALESCE(t.SOURCE_SYSTEM_NAME,'')
     OR COALESCE(s.SOURCE_TABLE_NAME,'')<>COALESCE(t.SOURCE_TABLE_NAME,'')

  -- POAM
  UNION ALL
  SELECT 'POAM','DUPLICATE_FACT_PK',COUNT(*) FROM (
    SELECT PK_FACT_OSCAL_POAM_DEPENDENCY_HASH
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_POAM_DEPENDENCY
    GROUP BY 1 HAVING COUNT(*)>1
  )
  UNION ALL
  SELECT 'POAM','NULL_FK',
    COUNT_IF(FK_SOURCE_ELEMENT_HASH IS NULL OR FK_TARGET_ELEMENT_HASH IS NULL)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_POAM_DEPENDENCY
  UNION ALL
  SELECT 'POAM','ORPHAN_SOURCE_FK',COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_POAM_DEPENDENCY f
  LEFT JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT d
    ON d.PK_DIM_OSCAL_POAM_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
  WHERE d.PK_DIM_OSCAL_POAM_ELEMENT_HASH IS NULL
  UNION ALL
  SELECT 'POAM','ORPHAN_TARGET_FK',COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_POAM_DEPENDENCY f
  LEFT JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT d
    ON d.PK_DIM_OSCAL_POAM_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
  WHERE d.PK_DIM_OSCAL_POAM_ELEMENT_HASH IS NULL
  UNION ALL
  SELECT 'POAM','SELF_EDGE',COUNT_IF(FK_SOURCE_ELEMENT_HASH=FK_TARGET_ELEMENT_HASH)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_POAM_DEPENDENCY
  UNION ALL
  SELECT 'POAM','UUID_MISMATCH',COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_POAM_DEPENDENCY f
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT s
    ON s.PK_DIM_OSCAL_POAM_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT t
    ON t.PK_DIM_OSCAL_POAM_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
  WHERE f.SOURCE_OSCAL_UUID<>s.OSCAL_UUID OR f.TARGET_OSCAL_UUID<>t.OSCAL_UUID
  UNION ALL
  SELECT 'POAM','CROSS_RECORD_EDGE',COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_POAM_DEPENDENCY f
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT s
    ON s.PK_DIM_OSCAL_POAM_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT t
    ON t.PK_DIM_OSCAL_POAM_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
  WHERE s.SOURCE_SYSTEM_NAME='ARCHER' AND s.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND t.SOURCE_SYSTEM_NAME='ARCHER' AND t.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND s.SOURCE_RECORD_ID<>t.SOURCE_RECORD_ID
  UNION ALL
  SELECT 'POAM','CROSS_NAMESPACE_EDGE',COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_POAM_DEPENDENCY f
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT s
    ON s.PK_DIM_OSCAL_POAM_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT t
    ON t.PK_DIM_OSCAL_POAM_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
  WHERE COALESCE(s.SOURCE_SYSTEM_NAME,'')<>COALESCE(t.SOURCE_SYSTEM_NAME,'')
     OR COALESCE(s.SOURCE_TABLE_NAME,'')<>COALESCE(t.SOURCE_TABLE_NAME,'')

  -- SECURITY ASSESSMENT PLAN
  UNION ALL
  SELECT 'SECURITY_ASSESSMENT_PLAN','DUPLICATE_FACT_PK',COUNT(*) FROM (
    SELECT PK_FACT_OSCAL_ASSESSMENT_PLAN_DEPENDENCY_HASH
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_PLAN_DEPENDENCY
    GROUP BY 1 HAVING COUNT(*)>1
  )
  UNION ALL
  SELECT 'SECURITY_ASSESSMENT_PLAN','NULL_FK',
    COUNT_IF(FK_SOURCE_ELEMENT_HASH IS NULL OR FK_TARGET_ELEMENT_HASH IS NULL)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_PLAN_DEPENDENCY
  UNION ALL
  SELECT 'SECURITY_ASSESSMENT_PLAN','ORPHAN_SOURCE_FK',COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_PLAN_DEPENDENCY f
  LEFT JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT d
    ON d.PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
  WHERE d.PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH IS NULL
  UNION ALL
  SELECT 'SECURITY_ASSESSMENT_PLAN','ORPHAN_TARGET_FK',COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_PLAN_DEPENDENCY f
  LEFT JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT d
    ON d.PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
  WHERE d.PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH IS NULL
  UNION ALL
  SELECT 'SECURITY_ASSESSMENT_PLAN','SELF_EDGE',
    COUNT_IF(FK_SOURCE_ELEMENT_HASH=FK_TARGET_ELEMENT_HASH)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_PLAN_DEPENDENCY
  UNION ALL
  SELECT 'SECURITY_ASSESSMENT_PLAN','UUID_MISMATCH',COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_PLAN_DEPENDENCY f
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT s
    ON s.PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT t
    ON t.PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
  WHERE f.SOURCE_OSCAL_UUID<>s.OSCAL_UUID OR f.TARGET_OSCAL_UUID<>t.OSCAL_UUID
  UNION ALL
  SELECT 'SECURITY_ASSESSMENT_PLAN','CROSS_RECORD_EDGE',COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_PLAN_DEPENDENCY f
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT s
    ON s.PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT t
    ON t.PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
  WHERE s.SOURCE_SYSTEM_NAME='ARCHER' AND s.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND t.SOURCE_SYSTEM_NAME='ARCHER' AND t.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND s.SOURCE_RECORD_ID<>t.SOURCE_RECORD_ID
  UNION ALL
  SELECT 'SECURITY_ASSESSMENT_PLAN','CROSS_NAMESPACE_EDGE',COUNT(*)
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_PLAN_DEPENDENCY f
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT s
    ON s.PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT t
    ON t.PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
  WHERE COALESCE(s.SOURCE_SYSTEM_NAME,'')<>COALESCE(t.SOURCE_SYSTEM_NAME,'')
     OR COALESCE(s.SOURCE_TABLE_NAME,'')<>COALESCE(t.SOURCE_TABLE_NAME,'')
)
SELECT MODEL, DEFECT, DEFECT_COUNT, IFF(DEFECT_COUNT=0,'PASS','FAIL') STATUS
FROM checks
ORDER BY MODEL, DEFECT;


-- =====================================================================
-- 05. INCOMING-PARENT INVARIANT
-- Every root: 0 incoming edges.
-- Every non-root Source One node: exactly 1 incoming edge.
-- Expected all defect counts = 0.
-- =====================================================================
WITH
ssp_d AS (
  SELECT * FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
),
ssp_i AS (
  SELECT FK_TARGET_ELEMENT_HASH K, COUNT(*) N
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY
  GROUP BY 1
),
ar_d AS (
  SELECT * FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
),
ar_i AS (
  SELECT FK_TARGET_ELEMENT_HASH K, COUNT(*) N
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_RESULTS_DEPENDENCY
  GROUP BY 1
),
poam_d AS (
  SELECT * FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
),
poam_i AS (
  SELECT FK_TARGET_ELEMENT_HASH K, COUNT(*) N
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_POAM_DEPENDENCY
  GROUP BY 1
),
sap_d AS (
  SELECT * FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
),
sap_i AS (
  SELECT FK_TARGET_ELEMENT_HASH K, COUNT(*) N
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_PLAN_DEPENDENCY
  GROUP BY 1
)
SELECT 'SSP' MODEL,
       COUNT_IF(ELEMENT_TYPE='system-security-plan' AND COALESCE(i.N,0)<>0) ROOT_PARENT_DEFECTS,
       COUNT_IF(ELEMENT_TYPE<>'system-security-plan' AND COALESCE(i.N,0)<>1) NONROOT_PARENT_DEFECTS
FROM ssp_d d LEFT JOIN ssp_i i ON i.K=d.PK_OSCAL_SSP_ELEMENT_HASH
UNION ALL
SELECT 'ASSESSMENT_RESULTS',
       COUNT_IF(ELEMENT_TYPE='assessment-results' AND COALESCE(i.N,0)<>0),
       COUNT_IF(ELEMENT_TYPE<>'assessment-results' AND COALESCE(i.N,0)<>1)
FROM ar_d d LEFT JOIN ar_i i ON i.K=d.PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH
UNION ALL
SELECT 'POAM',
       COUNT_IF(ELEMENT_TYPE='plan-of-action-and-milestones' AND COALESCE(i.N,0)<>0),
       COUNT_IF(ELEMENT_TYPE<>'plan-of-action-and-milestones' AND COALESCE(i.N,0)<>1)
FROM poam_d d LEFT JOIN poam_i i ON i.K=d.PK_DIM_OSCAL_POAM_ELEMENT_HASH
UNION ALL
SELECT 'SECURITY_ASSESSMENT_PLAN',
       COUNT_IF(ELEMENT_TYPE='assessment-plan' AND COALESCE(i.N,0)<>0),
       COUNT_IF(ELEMENT_TYPE<>'assessment-plan' AND COALESCE(i.N,0)<>1)
FROM sap_d d LEFT JOIN sap_i i ON i.K=d.PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH
ORDER BY MODEL;


-- =====================================================================
-- 06. CROSS-MODEL CONTENT_ID COVERAGE
-- Every current Source One CONTENT_ID should be represented by all four roots.
-- Expected: all missing counts = 0.
-- =====================================================================
WITH
src AS (
  SELECT DISTINCT TRIM(CONTENT_ID::STRING) CONTENT_ID
  FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
),
ssp AS (
  SELECT DISTINCT TRIM(SOURCE_RECORD_ID::STRING) CONTENT_ID
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='system-security-plan'
),
ar AS (
  SELECT DISTINCT TRIM(SOURCE_RECORD_ID::STRING) CONTENT_ID
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='assessment-results'
),
poam AS (
  SELECT DISTINCT TRIM(SOURCE_RECORD_ID::STRING) CONTENT_ID
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='plan-of-action-and-milestones'
),
sap AS (
  SELECT DISTINCT TRIM(SOURCE_RECORD_ID::STRING) CONTENT_ID
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='assessment-plan'
),
matrix AS (
  SELECT s.CONTENT_ID,
         IFF(ssp.CONTENT_ID IS NOT NULL,1,0) HAS_SSP,
         IFF(ar.CONTENT_ID IS NOT NULL,1,0) HAS_AR,
         IFF(poam.CONTENT_ID IS NOT NULL,1,0) HAS_POAM,
         IFF(sap.CONTENT_ID IS NOT NULL,1,0) HAS_SAP
  FROM src s
  LEFT JOIN ssp USING(CONTENT_ID)
  LEFT JOIN ar USING(CONTENT_ID)
  LEFT JOIN poam USING(CONTENT_ID)
  LEFT JOIN sap USING(CONTENT_ID)
)
SELECT
  COUNT(*) SOURCE_CONTENT_IDS,
  COUNT_IF(HAS_SSP=0) MISSING_SSP,
  COUNT_IF(HAS_AR=0) MISSING_ASSESSMENT_RESULTS,
  COUNT_IF(HAS_POAM=0) MISSING_POAM,
  COUNT_IF(HAS_SAP=0) MISSING_ASSESSMENT_PLAN,
  IFF(COUNT_IF(HAS_SSP=0 OR HAS_AR=0 OR HAS_POAM=0 OR HAS_SAP=0)=0,'PASS','FAIL') STATUS
FROM matrix;


-- 06B. DETAIL ONLY IF 06 FAILED. Expected zero rows.
WITH
src AS (
  SELECT DISTINCT TRIM(CONTENT_ID::STRING) CONTENT_ID
  FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
),
ssp AS (
  SELECT DISTINCT TRIM(SOURCE_RECORD_ID::STRING) CONTENT_ID
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='system-security-plan'
),
ar AS (
  SELECT DISTINCT TRIM(SOURCE_RECORD_ID::STRING) CONTENT_ID
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='assessment-results'
),
poam AS (
  SELECT DISTINCT TRIM(SOURCE_RECORD_ID::STRING) CONTENT_ID
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='plan-of-action-and-milestones'
),
sap AS (
  SELECT DISTINCT TRIM(SOURCE_RECORD_ID::STRING) CONTENT_ID
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='assessment-plan'
)
SELECT s.CONTENT_ID,
       IFF(ssp.CONTENT_ID IS NULL,'MISSING','OK') SSP,
       IFF(ar.CONTENT_ID IS NULL,'MISSING','OK') ASSESSMENT_RESULTS,
       IFF(poam.CONTENT_ID IS NULL,'MISSING','OK') POAM,
       IFF(sap.CONTENT_ID IS NULL,'MISSING','OK') SECURITY_ASSESSMENT_PLAN
FROM src s
LEFT JOIN ssp USING(CONTENT_ID)
LEFT JOIN ar USING(CONTENT_ID)
LEFT JOIN poam USING(CONTENT_ID)
LEFT JOIN sap USING(CONTENT_ID)
WHERE ssp.CONTENT_ID IS NULL OR ar.CONTENT_ID IS NULL OR poam.CONTENT_ID IS NULL OR sap.CONTENT_ID IS NULL
ORDER BY s.CONTENT_ID
LIMIT 500;


-- =====================================================================
-- 07. SSP LEVEL-355 CONTROL IMPLEMENTATION SOURCE/TARGET PARITY
-- Compare valid Level-355 CONTROL_NUMBER multiplicities by package to the
-- implemented-requirements[].control-id values stored in SSP DIM.
-- Expected: zero mismatch rows.
-- =====================================================================
WITH source_controls AS (
  SELECT
    TRIM(s.CONTENT_ID::STRING) CONTENT_ID,
    s.CURATED_JSON:CONTROL_NUMBER::STRING CONTROL_ID,
    COUNT(*) N
  FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_ALLOCATED_CONTROLS_CONTROL_RAW s
  JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW p
    ON TRIM(p.CONTENT_ID::STRING)=TRIM(s.CONTENT_ID::STRING)
  WHERE s.CURATED_JSON:CONTROL_NUMBER IS NOT NULL
    AND NOT IS_NULL_VALUE(s.CURATED_JSON:CONTROL_NUMBER)
    AND NULLIF(TRIM(s.CURATED_JSON:CONTROL_NUMBER::STRING),'') IS NOT NULL
  GROUP BY 1,2
),
target_controls AS (
  SELECT
    TRIM(SOURCE_RECORD_ID::STRING) CONTENT_ID,
    METADATA_JSON:"control-id"::STRING CONTROL_ID,
    COUNT(*) N
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER'
    AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='implemented-requirements'
  GROUP BY 1,2
)
SELECT
  COALESCE(s.CONTENT_ID,t.CONTENT_ID) CONTENT_ID,
  COALESCE(s.CONTROL_ID,t.CONTROL_ID) CONTROL_ID,
  COALESCE(s.N,0) SOURCE_COUNT,
  COALESCE(t.N,0) TARGET_COUNT,
  CASE WHEN s.CONTENT_ID IS NULL THEN 'EXTRA_TARGET'
       WHEN t.CONTENT_ID IS NULL THEN 'MISSING_TARGET'
       WHEN s.N<>t.N THEN 'COUNT_MISMATCH'
  END DEFECT
FROM source_controls s
FULL OUTER JOIN target_controls t
  ON s.CONTENT_ID=t.CONTENT_ID
 AND s.CONTROL_ID=t.CONTROL_ID
WHERE s.CONTENT_ID IS NULL OR t.CONTENT_ID IS NULL OR s.N<>t.N
ORDER BY CONTENT_ID, CONTROL_ID
LIMIT 500;


-- 07B. Aggregate Level-355 parity summary.
WITH source_controls AS (
  SELECT TRIM(s.CONTENT_ID::STRING) CONTENT_ID,
         s.CURATED_JSON:CONTROL_NUMBER::STRING CONTROL_ID
  FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_ALLOCATED_CONTROLS_CONTROL_RAW s
  JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW p
    ON TRIM(p.CONTENT_ID::STRING)=TRIM(s.CONTENT_ID::STRING)
  WHERE s.CURATED_JSON:CONTROL_NUMBER IS NOT NULL
    AND NOT IS_NULL_VALUE(s.CURATED_JSON:CONTROL_NUMBER)
    AND NULLIF(TRIM(s.CURATED_JSON:CONTROL_NUMBER::STRING),'') IS NOT NULL
),
target_controls AS (
  SELECT TRIM(SOURCE_RECORD_ID::STRING) CONTENT_ID,
         METADATA_JSON:"control-id"::STRING CONTROL_ID
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER'
    AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='implemented-requirements'
)
SELECT
  (SELECT COUNT(*) FROM source_controls) SOURCE_VALID_CONTROL_ROWS,
  (SELECT COUNT(*) FROM target_controls) TARGET_IMPLEMENTED_REQUIREMENTS,
  IFF(
    (SELECT COUNT(*) FROM source_controls)=(SELECT COUNT(*) FROM target_controls),
    'PASS','FAIL'
  ) ROW_COUNT_STATUS;


-- =====================================================================
-- 08. POAM SOURCE/TARGET ITEM COUNT PARITY BY CONTENT_ID
-- Expected: zero mismatch rows.
-- =====================================================================
WITH source_counts AS (
  SELECT
    TRIM(s.CONTENT_ID::STRING) CONTENT_ID,
    COUNT(f.VALUE) N
  FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW s,
       LATERAL FLATTEN(INPUT => s.CURATED_JSON:POAMS, OUTER => TRUE) f
  WHERE f.VALUE IS NOT NULL
  GROUP BY 1
),
target_counts AS (
  SELECT TRIM(SOURCE_RECORD_ID::STRING) CONTENT_ID, COUNT(*) N
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER'
    AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='poam-items'
  GROUP BY 1
)
SELECT
  COALESCE(s.CONTENT_ID,t.CONTENT_ID) CONTENT_ID,
  COALESCE(s.N,0) SOURCE_POAM_ITEMS,
  COALESCE(t.N,0) TARGET_POAM_ITEMS
FROM source_counts s
FULL OUTER JOIN target_counts t USING(CONTENT_ID)
WHERE COALESCE(s.N,0)<>COALESCE(t.N,0)
ORDER BY CONTENT_ID
LIMIT 500;


-- =====================================================================
-- 09. DIRECT FIELD VALUE PARITY ACROSS ALL SOURCE RECORDS
-- These are intentionally simple direct/native mappings where exact equality
-- is expected after the approved transform.
-- Expected MISMATCH_COUNT = 0 for every row.
-- =====================================================================
WITH
src AS (
  SELECT TRIM(CONTENT_ID::STRING) CONTENT_ID, CURATED_JSON
  FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
),
meta AS (
  SELECT TRIM(SOURCE_RECORD_ID::STRING) CONTENT_ID, METADATA_JSON
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='metadata'
),
sc AS (
  SELECT TRIM(SOURCE_RECORD_ID::STRING) CONTENT_ID, METADATA_JSON
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='system-characteristics'
),
boundary AS (
  SELECT TRIM(SOURCE_RECORD_ID::STRING) CONTENT_ID, METADATA_JSON
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
    AND ELEMENT_TYPE='authorization-boundary'
),
checks AS (
  SELECT 'AUTHORIZATION_PACKAGE_NAME -> metadata.title' CHECK_NAME,
         COUNT_IF(NOT EQUAL_NULL(s.CURATED_JSON:AUTHORIZATION_PACKAGE_NAME::STRING,
                                 m.METADATA_JSON:title::STRING)) MISMATCH_COUNT
  FROM src s JOIN meta m USING(CONTENT_ID)
  UNION ALL
  SELECT 'AUTHORIZATION_PACKAGE_NAME -> system-name',
         COUNT_IF(NOT EQUAL_NULL(s.CURATED_JSON:AUTHORIZATION_PACKAGE_NAME::STRING,
                                 c.METADATA_JSON:"system-name"::STRING))
  FROM src s JOIN sc c USING(CONTENT_ID)
  UNION ALL
  SELECT 'ACRONYM -> system-name-short',
         COUNT_IF(NOT EQUAL_NULL(s.CURATED_JSON:ACRONYM::STRING,
                                 c.METADATA_JSON:"system-name-short"::STRING))
  FROM src s JOIN sc c USING(CONTENT_ID)
  UNION ALL
  SELECT 'MISSION_PURPOSE -> description',
         COUNT_IF(NOT EQUAL_NULL(s.CURATED_JSON:MISSION_PURPOSE::STRING,
                                 c.METADATA_JSON:description::STRING))
  FROM src s JOIN sc c USING(CONTENT_ID)
  UNION ALL
  SELECT 'AUTHORIZATION_BOUNDARY_DESCRIPTION -> authorization-boundary.description',
         COUNT_IF(NOT EQUAL_NULL(s.CURATED_JSON:AUTHORIZATION_BOUNDARY_DESCRIPTION::STRING,
                                 b.METADATA_JSON:description::STRING))
  FROM src s JOIN boundary b USING(CONTENT_ID)
)
SELECT CHECK_NAME, MISMATCH_COUNT, IFF(MISMATCH_COUNT=0,'PASS','FAIL') STATUS
FROM checks
ORDER BY CHECK_NAME;


-- =====================================================================
-- 10. ONE CONTENT_ID DRILL-DOWN ACROSS ALL FOUR MODELS
-- First run 10A to choose a content ID, then set QA_CONTENT_ID and run 10B.
-- =====================================================================

-- 10A. Candidate content IDs with broad Source One data.
SELECT
  TRIM(CONTENT_ID::STRING) CONTENT_ID,
  IFF(CURATED_JSON:POAMS IS NOT NULL AND NOT IS_NULL_VALUE(CURATED_JSON:POAMS),1,0) HAS_POAM,
  IFF(CURATED_JSON:VULNERABILITY_SCORE IS NOT NULL AND NOT IS_NULL_VALUE(CURATED_JSON:VULNERABILITY_SCORE),1,0) HAS_AR_SCORE,
  IFF(CURATED_JSON:REQUEST_TO_BEGIN_ASSESSMENT IS NOT NULL AND NOT IS_NULL_VALUE(CURATED_JSON:REQUEST_TO_BEGIN_ASSESSMENT),1,0) HAS_SAP,
  IFF(CURATED_JSON:AUTHORIZATION_PACKAGE_NAME IS NOT NULL AND NOT IS_NULL_VALUE(CURATED_JSON:AUTHORIZATION_PACKAGE_NAME),1,0) HAS_SSP
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
ORDER BY HAS_POAM DESC, HAS_AR_SCORE DESC, HAS_SAP DESC, HAS_SSP DESC, CONTENT_ID
LIMIT 20;

-- Replace this value after choosing from 10A.
SET QA_CONTENT_ID = 'REPLACE_WITH_CONTENT_ID';

-- 10B. Node inventory for that same CONTENT_ID across all four models.
SELECT 'SSP' MODEL, ELEMENT_TYPE, COUNT(*) N
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  AND TRIM(SOURCE_RECORD_ID::STRING)=$QA_CONTENT_ID
GROUP BY 1,2
UNION ALL
SELECT 'ASSESSMENT_RESULTS', ELEMENT_TYPE, COUNT(*)
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT
WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  AND TRIM(SOURCE_RECORD_ID::STRING)=$QA_CONTENT_ID
GROUP BY 1,2
UNION ALL
SELECT 'POAM', ELEMENT_TYPE, COUNT(*)
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT
WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  AND TRIM(SOURCE_RECORD_ID::STRING)=$QA_CONTENT_ID
GROUP BY 1,2
UNION ALL
SELECT 'SECURITY_ASSESSMENT_PLAN', ELEMENT_TYPE, COUNT(*)
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT
WHERE SOURCE_SYSTEM_NAME='ARCHER' AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  AND TRIM(SOURCE_RECORD_ID::STRING)=$QA_CONTENT_ID
GROUP BY 1,2
ORDER BY MODEL, ELEMENT_TYPE;


-- =====================================================================
-- 11. IDEMPOTENCY / REPLAY SIGN-OFF
-- SQL can prove the committed warehouse is internally consistent, but true
-- idempotency requires regenerating the intended graph from the same inputs.
--
-- Production sign-off step:
--   Run the universal mapper once more in PREVIEW, same Source One snapshot:
--     SELECTED_MODELS=("SSP","ASSESSMENT_RESULTS","POAM","SECURITY_ASSESSMENT_PLAN")
--     OSCAL_LOAD_MODE="PREVIEW"
--
-- PASS only when every route reports:
--   DIM INSERTS=0, UPDATES=0
--   FACT INSERTS=0, UPDATES=0
--
-- Then rerun section 01 of this SQL pack and confirm current-release counts
-- remain unchanged. This is the read-only idempotency proof.
-- =====================================================================


-- =====================================================================
-- 12. LEGACY / HISTORICAL TABLE COMPARISON
--
-- Do NOT guess the legacy object or column names.
-- To build the exact field-by-field historical comparison, provide:
--   1) fully qualified legacy table name
--   2) its CONTENT_ID/key column name
--   3) DESCRIBE TABLE output (or the exact legacy column list)
--
-- Once supplied, compare:
--   a) legacy CONTENT_ID set vs Source One RAW CONTENT_ID set
--   b) legacy CONTENT_ID set vs one root per OSCAL model
--   c) selected legacy scalar columns vs native OSCAL payload fields
--   d) legacy child/reference counts vs DIM child counts
--   e) legacy relationship columns vs FACT source/target edges
--
-- The exact comparison belongs in a separate versioned SQL file because
-- historical column names are not authoritative in the current repository.
-- =====================================================================
