-- SOURCE ONE OTHER MODELS: ROOT -> BRANCH -> LEAF GRAPH WALK
-- Date: 2026-09-25
-- READ ONLY. No DML.
--
-- Use the SAME Authorization Package SOURCE_RECORD_ID / CONTENT_ID for:
--   1) Assessment Results
--   2) POA&M
--   3) Security Assessment Plan
--
-- Change only this value.
SET QA_CONTENT_ID = '565189';


-- =====================================================================
-- 01. ASSESSMENT RESULTS ROOT -> LEAF
--
-- Expected current structure is approximately:
-- assessment-results
--   -> results
--       -> observations
--       -> props
--       -> findings (only when native finding data exists)
--           -> props
--
-- Current Source One FINDINGS is preserved as a result-level property, so
-- native findings[] may be absent in today's graph.
-- =====================================================================
WITH RECURSIVE
NODES AS
(
    SELECT
        PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH AS NODE_KEY,
        TRIM(SOURCE_RECORD_ID::STRING) AS SOURCE_RECORD_ID,
        ELEMENT_TYPE,
        OSCAL_UUID,
        METADATA_JSON
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT
    WHERE SOURCE_SYSTEM_NAME = 'ARCHER'
      AND SOURCE_TABLE_NAME = 'ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
      AND TRIM(SOURCE_RECORD_ID::STRING) = $QA_CONTENT_ID
),
EDGES AS
(
    SELECT
        FK_SOURCE_ELEMENT_HASH AS PARENT_NODE_KEY,
        FK_TARGET_ELEMENT_HASH AS CHILD_NODE_KEY,
        DEPENDENCY_TYPE
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_RESULTS_DEPENDENCY
),
OUT_DEGREE AS
(
    SELECT PARENT_NODE_KEY, COUNT(*) AS CHILD_COUNT
    FROM EDGES
    GROUP BY PARENT_NODE_KEY
),
TREE
(
    DEPTH, SOURCE_RECORD_ID, NODE_KEY, PARENT_NODE_KEY,
    ELEMENT_TYPE, OSCAL_UUID, PARENT_ELEMENT_TYPE, PARENT_OSCAL_UUID,
    DEPENDENCY_TYPE, STRUCTURAL_PATH, METADATA_JSON
) AS
(
    SELECT
        0,
        N.SOURCE_RECORD_ID,
        N.NODE_KEY,
        CAST(NULL AS BINARY(16)),
        N.ELEMENT_TYPE,
        N.OSCAL_UUID,
        CAST(NULL AS VARCHAR),
        CAST(NULL AS VARCHAR),
        CAST(NULL AS VARCHAR),
        CAST(N.ELEMENT_TYPE AS VARCHAR(5000)),
        N.METADATA_JSON
    FROM NODES N
    WHERE N.ELEMENT_TYPE = 'assessment-results'

    UNION ALL

    SELECT
        T.DEPTH + 1,
        C.SOURCE_RECORD_ID,
        C.NODE_KEY,
        E.PARENT_NODE_KEY,
        C.ELEMENT_TYPE,
        C.OSCAL_UUID,
        P.ELEMENT_TYPE,
        P.OSCAL_UUID,
        E.DEPENDENCY_TYPE,
        CAST(T.STRUCTURAL_PATH || ' > ' || C.ELEMENT_TYPE AS VARCHAR(5000)),
        C.METADATA_JSON
    FROM TREE T
    JOIN EDGES E
      ON E.PARENT_NODE_KEY = T.NODE_KEY
    JOIN NODES C
      ON C.NODE_KEY = E.CHILD_NODE_KEY
    JOIN NODES P
      ON P.NODE_KEY = E.PARENT_NODE_KEY
    WHERE T.DEPTH < 50
)
SELECT
    'ASSESSMENT_RESULTS' AS MODEL,
    T.DEPTH,
    CASE
        WHEN T.DEPTH = 0 THEN 'ROOT'
        WHEN COALESCE(O.CHILD_COUNT,0) = 0 THEN 'LEAF'
        ELSE 'BRANCH'
    END AS NODE_POSITION,
    T.SOURCE_RECORD_ID,
    T.PARENT_ELEMENT_TYPE,
    T.PARENT_OSCAL_UUID,
    T.DEPENDENCY_TYPE,
    T.ELEMENT_TYPE AS CHILD_ELEMENT_TYPE,
    T.OSCAL_UUID AS CHILD_OSCAL_UUID,
    COALESCE(O.CHILD_COUNT,0) AS CHILD_COUNT,
    T.STRUCTURAL_PATH,
    T.METADATA_JSON
FROM TREE T
LEFT JOIN OUT_DEGREE O
  ON O.PARENT_NODE_KEY = T.NODE_KEY
ORDER BY T.DEPTH, T.STRUCTURAL_PATH, T.OSCAL_UUID;


-- =====================================================================
-- 02. POA&M ROOT -> LEAF
--
-- Current Source One graph is intentionally shallow:
-- plan-of-action-and-milestones
--   -> poam-items
-- =====================================================================
WITH RECURSIVE
NODES AS
(
    SELECT
        PK_DIM_OSCAL_POAM_ELEMENT_HASH AS NODE_KEY,
        TRIM(SOURCE_RECORD_ID::STRING) AS SOURCE_RECORD_ID,
        ELEMENT_TYPE,
        OSCAL_UUID,
        METADATA_JSON
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT
    WHERE SOURCE_SYSTEM_NAME = 'ARCHER'
      AND SOURCE_TABLE_NAME = 'ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
      AND TRIM(SOURCE_RECORD_ID::STRING) = $QA_CONTENT_ID
),
EDGES AS
(
    SELECT
        FK_SOURCE_ELEMENT_HASH AS PARENT_NODE_KEY,
        FK_TARGET_ELEMENT_HASH AS CHILD_NODE_KEY,
        DEPENDENCY_TYPE
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_POAM_DEPENDENCY
),
OUT_DEGREE AS
(
    SELECT PARENT_NODE_KEY, COUNT(*) AS CHILD_COUNT
    FROM EDGES
    GROUP BY PARENT_NODE_KEY
),
TREE
(
    DEPTH, SOURCE_RECORD_ID, NODE_KEY, PARENT_NODE_KEY,
    ELEMENT_TYPE, OSCAL_UUID, PARENT_ELEMENT_TYPE, PARENT_OSCAL_UUID,
    DEPENDENCY_TYPE, STRUCTURAL_PATH, METADATA_JSON
) AS
(
    SELECT
        0,
        N.SOURCE_RECORD_ID,
        N.NODE_KEY,
        CAST(NULL AS BINARY(16)),
        N.ELEMENT_TYPE,
        N.OSCAL_UUID,
        CAST(NULL AS VARCHAR),
        CAST(NULL AS VARCHAR),
        CAST(NULL AS VARCHAR),
        CAST(N.ELEMENT_TYPE AS VARCHAR(5000)),
        N.METADATA_JSON
    FROM NODES N
    WHERE N.ELEMENT_TYPE = 'plan-of-action-and-milestones'

    UNION ALL

    SELECT
        T.DEPTH + 1,
        C.SOURCE_RECORD_ID,
        C.NODE_KEY,
        E.PARENT_NODE_KEY,
        C.ELEMENT_TYPE,
        C.OSCAL_UUID,
        P.ELEMENT_TYPE,
        P.OSCAL_UUID,
        E.DEPENDENCY_TYPE,
        CAST(T.STRUCTURAL_PATH || ' > ' || C.ELEMENT_TYPE AS VARCHAR(5000)),
        C.METADATA_JSON
    FROM TREE T
    JOIN EDGES E
      ON E.PARENT_NODE_KEY = T.NODE_KEY
    JOIN NODES C
      ON C.NODE_KEY = E.CHILD_NODE_KEY
    JOIN NODES P
      ON P.NODE_KEY = E.PARENT_NODE_KEY
    WHERE T.DEPTH < 50
)
SELECT
    'POAM' AS MODEL,
    T.DEPTH,
    CASE
        WHEN T.DEPTH = 0 THEN 'ROOT'
        WHEN COALESCE(O.CHILD_COUNT,0) = 0 THEN 'LEAF'
        ELSE 'BRANCH'
    END AS NODE_POSITION,
    T.SOURCE_RECORD_ID,
    T.PARENT_ELEMENT_TYPE,
    T.PARENT_OSCAL_UUID,
    T.DEPENDENCY_TYPE,
    T.ELEMENT_TYPE AS CHILD_ELEMENT_TYPE,
    T.OSCAL_UUID AS CHILD_OSCAL_UUID,
    COALESCE(O.CHILD_COUNT,0) AS CHILD_COUNT,
    T.STRUCTURAL_PATH,
    T.METADATA_JSON
FROM TREE T
LEFT JOIN OUT_DEGREE O
  ON O.PARENT_NODE_KEY = T.NODE_KEY
ORDER BY T.DEPTH, T.STRUCTURAL_PATH, T.OSCAL_UUID;


-- =====================================================================
-- 03. SECURITY ASSESSMENT PLAN ROOT -> LEAF
--
-- Current Source One structure:
-- assessment-plan
--   -> tasks
--       -> props
--
-- task title/type/remarks are payload members, not separate graph nodes.
-- =====================================================================
WITH RECURSIVE
NODES AS
(
    SELECT
        PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH AS NODE_KEY,
        TRIM(SOURCE_RECORD_ID::STRING) AS SOURCE_RECORD_ID,
        ELEMENT_TYPE,
        OSCAL_UUID,
        METADATA_JSON
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT
    WHERE SOURCE_SYSTEM_NAME = 'ARCHER'
      AND SOURCE_TABLE_NAME = 'ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
      AND TRIM(SOURCE_RECORD_ID::STRING) = $QA_CONTENT_ID
),
EDGES AS
(
    SELECT
        FK_SOURCE_ELEMENT_HASH AS PARENT_NODE_KEY,
        FK_TARGET_ELEMENT_HASH AS CHILD_NODE_KEY,
        DEPENDENCY_TYPE
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_PLAN_DEPENDENCY
),
OUT_DEGREE AS
(
    SELECT PARENT_NODE_KEY, COUNT(*) AS CHILD_COUNT
    FROM EDGES
    GROUP BY PARENT_NODE_KEY
),
TREE
(
    DEPTH, SOURCE_RECORD_ID, NODE_KEY, PARENT_NODE_KEY,
    ELEMENT_TYPE, OSCAL_UUID, PARENT_ELEMENT_TYPE, PARENT_OSCAL_UUID,
    DEPENDENCY_TYPE, STRUCTURAL_PATH, METADATA_JSON
) AS
(
    SELECT
        0,
        N.SOURCE_RECORD_ID,
        N.NODE_KEY,
        CAST(NULL AS BINARY(16)),
        N.ELEMENT_TYPE,
        N.OSCAL_UUID,
        CAST(NULL AS VARCHAR),
        CAST(NULL AS VARCHAR),
        CAST(NULL AS VARCHAR),
        CAST(N.ELEMENT_TYPE AS VARCHAR(5000)),
        N.METADATA_JSON
    FROM NODES N
    WHERE N.ELEMENT_TYPE = 'assessment-plan'

    UNION ALL

    SELECT
        T.DEPTH + 1,
        C.SOURCE_RECORD_ID,
        C.NODE_KEY,
        E.PARENT_NODE_KEY,
        C.ELEMENT_TYPE,
        C.OSCAL_UUID,
        P.ELEMENT_TYPE,
        P.OSCAL_UUID,
        E.DEPENDENCY_TYPE,
        CAST(T.STRUCTURAL_PATH || ' > ' || C.ELEMENT_TYPE AS VARCHAR(5000)),
        C.METADATA_JSON
    FROM TREE T
    JOIN EDGES E
      ON E.PARENT_NODE_KEY = T.NODE_KEY
    JOIN NODES C
      ON C.NODE_KEY = E.CHILD_NODE_KEY
    JOIN NODES P
      ON P.NODE_KEY = E.PARENT_NODE_KEY
    WHERE T.DEPTH < 50
)
SELECT
    'SECURITY_ASSESSMENT_PLAN' AS MODEL,
    T.DEPTH,
    CASE
        WHEN T.DEPTH = 0 THEN 'ROOT'
        WHEN COALESCE(O.CHILD_COUNT,0) = 0 THEN 'LEAF'
        ELSE 'BRANCH'
    END AS NODE_POSITION,
    T.SOURCE_RECORD_ID,
    T.PARENT_ELEMENT_TYPE,
    T.PARENT_OSCAL_UUID,
    T.DEPENDENCY_TYPE,
    T.ELEMENT_TYPE AS CHILD_ELEMENT_TYPE,
    T.OSCAL_UUID AS CHILD_OSCAL_UUID,
    COALESCE(O.CHILD_COUNT,0) AS CHILD_COUNT,
    T.STRUCTURAL_PATH,
    T.METADATA_JSON
FROM TREE T
LEFT JOIN OUT_DEGREE O
  ON O.PARENT_NODE_KEY = T.NODE_KEY
ORDER BY T.DEPTH, T.STRUCTURAL_PATH, T.OSCAL_UUID;
