-- SOURCE TWO CATALOG: POST-COMMIT STRUCTURE + TRACKING-ID QA
-- Date: 2026-09-28. SELECT ONLY. Run the entire file as-is.
-- Repository basis: simplify-metadata-boundary @ 44e444f656d77009872d344b5e9cc42de753be8f.
-- Owner COMMIT baseline: 148 source records, 1697 DIM rows, 1549 FACT rows.
-- Those counts describe this increment, not permanent business requirements.
-- Whole Catalog DIM/FACT scans: no source/record filter can hide orphan FACT rows.
-- Field parity reads the CURRENT Source Two Source RAW.CURATED_JSON, not the
-- notebook's retained snapshot. Source changes after COMMIT require review.
-- Duplicate/noncanonical source IDs or unreviewed tracking shapes BLOCK acceptance;
-- no arbitrary latest-row winner is selected by this independent QA query.
-- Tracking-id parity supports populated INTEGER or nonblank VARCHAR source values,
-- using exact SOURCE_TRACKING_ID and trim-to-string, with no numeric coercion of
-- target values. Other source types/null/absence require review, not fabricated data.
-- Catalog stage checked: catalog -> metadata -> props, as implemented for this
-- Source-level metadata increment. Later groups/controls need a revised QA contract.
-- This is not all-field parity, full OSCAL conformance, a source workbook audit,
-- Topic/Section/Sub-Section or Policy/Control Standard relationship acceptance,
-- or an implementation of the still-open daily-loader whole-table orphan safeguard.
-- PASS / DRIFT / FAIL / BLOCKED are explained in the accompanying checkpoint.
-- Defect counts can overlap; duplicate DIM keys may multiply joined counts.
-- No private identifiers, source values, or payloads are returned; aggregates only.

WITH
source_payloads AS (
    SELECT CAST(CONTENT_ID AS VARCHAR) AS SOURCE_RECORD_ID,
           CASE WHEN TYPEOF(CURATED_JSON)='VARCHAR'
                THEN TRY_PARSE_JSON(AS_VARCHAR(CURATED_JSON))
                ELSE CURATED_JSON END AS PAYLOAD
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW
),
source_rows AS (
    SELECT SOURCE_RECORD_ID, PAYLOAD, GET(PAYLOAD,'SOURCE_TRACKING_ID') AS RAW_TRACKING,
           COUNT(*) OVER (PARTITION BY SOURCE_RECORD_ID) AS ROWS_PER_ID
    FROM source_payloads
),
source_valid AS (
    SELECT SOURCE_RECORD_ID, TRIM(TO_VARCHAR(RAW_TRACKING)) AS EXPECTED_VALUE
    FROM source_rows
    WHERE ROWS_PER_ID=1 AND SOURCE_RECORD_ID IS NOT NULL
      AND TRIM(SOURCE_RECORD_ID)<>'' AND SOURCE_RECORD_ID=TRIM(SOURCE_RECORD_ID)
      AND COALESCE(IS_OBJECT(PAYLOAD),FALSE)
      AND TYPEOF(RAW_TRACKING) IN ('INTEGER','VARCHAR')
      AND TRIM(TO_VARCHAR(RAW_TRACKING))<>''
),
d AS (
    SELECT PK_DIM_OSCAL_CATALOG_ELEMENT_HASH AS NODE_KEY, ELEMENT_TYPE, OSCAL_UUID,
           SOURCE_SYSTEM_NAME, SOURCE_TABLE_NAME, SOURCE_RECORD_ID, METADATA_JSON
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_CATALOG_ELEMENT
),
f AS (
    SELECT PK_FACT_OSCAL_CATALOG_DEPENDENCY_HASH AS FACT_KEY,
           FK_SOURCE_ELEMENT_HASH, FK_TARGET_ELEMENT_HASH, DEPENDENCY_TYPE,
           SOURCE_OSCAL_UUID, TARGET_OSCAL_UUID
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_CATALOG_DEPENDENCY
),
key_defects AS (
    SELECT 'DIM_PK' AS KEY_KIND FROM d GROUP BY NODE_KEY
    HAVING NODE_KEY IS NULL OR COUNT(*)>1
    UNION ALL SELECT 'FACT_PK' FROM f GROUP BY FACT_KEY
    HAVING FACT_KEY IS NULL OR COUNT(*)>1
    UNION ALL SELECT 'DIM_UUID' FROM d GROUP BY OSCAL_UUID
    HAVING OSCAL_UUID IS NULL OR TRIM(OSCAL_UUID)='' OR COUNT(*)>1
),
record_nodes AS (
    SELECT SOURCE_RECORD_ID,
           SUM(CASE WHEN ELEMENT_TYPE='catalog' THEN 1 ELSE 0 END) AS ROOTS,
           SUM(CASE WHEN ELEMENT_TYPE='metadata' THEN 1 ELSE 0 END) AS METADATA_ROWS
    FROM d GROUP BY SOURCE_RECORD_ID
),
parent_counts AS (
    SELECT d.NODE_KEY, d.ELEMENT_TYPE, COUNT(f.FK_TARGET_ELEMENT_HASH) AS PARENTS
    FROM d LEFT JOIN f ON f.FK_TARGET_ELEMENT_HASH=d.NODE_KEY
    GROUP BY d.NODE_KEY, d.ELEMENT_TYPE
),
joined_edges AS (
    SELECT f.*, s.ELEMENT_TYPE AS SOURCE_TYPE, t.ELEMENT_TYPE AS TARGET_TYPE,
           s.OSCAL_UUID AS PARENT_UUID, t.OSCAL_UUID AS CHILD_UUID,
           s.SOURCE_SYSTEM_NAME AS PARENT_SYSTEM, t.SOURCE_SYSTEM_NAME AS CHILD_SYSTEM,
           s.SOURCE_TABLE_NAME AS PARENT_TABLE, t.SOURCE_TABLE_NAME AS CHILD_TABLE,
           s.SOURCE_RECORD_ID AS PARENT_RECORD, t.SOURCE_RECORD_ID AS CHILD_RECORD
    FROM f JOIN d s ON s.NODE_KEY=f.FK_SOURCE_ELEMENT_HASH
           JOIN d t ON t.NODE_KEY=f.FK_TARGET_ELEMENT_HASH
),
tracking AS (
    SELECT d.*, GET(METADATA_JSON,'value') AS PROPERTY_VALUE
    FROM d WHERE ELEMENT_TYPE='props'
      AND AS_VARCHAR(GET(METADATA_JSON,'name'))='tracking-id'
),
tracking_counts AS (
    SELECT SOURCE_RECORD_ID, COUNT(*) AS PROPERTY_ROWS
    FROM tracking GROUP BY SOURCE_RECORD_ID
),
tracking_comparison AS (
    SELECT s.SOURCE_RECORD_ID, s.EXPECTED_VALUE, t.PROPERTY_VALUE
    FROM source_valid s JOIN tracking_counts c ON c.SOURCE_RECORD_ID=s.SOURCE_RECORD_ID
    JOIN tracking t ON t.SOURCE_RECORD_ID=s.SOURCE_RECORD_ID
    WHERE c.PROPERTY_ROWS=1
),
checks AS (
    SELECT 1 AS CHECK_ORDER, 'SOURCE_ROWS' AS QA_CHECK,
           (SELECT COUNT(*) FROM source_rows) AS OBSERVED_COUNT, 148 AS EXPECTED_COUNT, 'BASELINE' AS CHECK_KIND
    UNION ALL
    SELECT 2, 'CATALOG_DIM_ROWS',
           (SELECT COUNT(*) FROM d), 1697, 'BASELINE'
    UNION ALL
    SELECT 3, 'CATALOG_FACT_ROWS',
           (SELECT COUNT(*) FROM f), 1549, 'BASELINE'
    UNION ALL
    SELECT 4, 'CATALOG_ROOT_ROWS',
           (SELECT COUNT(*) FROM d WHERE ELEMENT_TYPE='catalog'), 148, 'BASELINE'
    UNION ALL
    SELECT 5, 'TRACKING_ID_PROPERTY_ROWS',
           (SELECT COUNT(*) FROM tracking), 148, 'BASELINE'
    UNION ALL
    SELECT 6, 'MATCHED_TRACKING_IDS',
           (SELECT COUNT(*) FROM tracking_comparison WHERE AS_VARCHAR(PROPERTY_VALUE)=EXPECTED_VALUE), 148, 'BASELINE'
    UNION ALL
    SELECT 7, 'INVALID_OR_DUPLICATE_SOURCE_ID_GROUPS',
           (SELECT COUNT(*) FROM (SELECT SOURCE_RECORD_ID FROM source_rows GROUP BY SOURCE_RECORD_ID HAVING SOURCE_RECORD_ID IS NULL OR TRIM(SOURCE_RECORD_ID)='' OR SOURCE_RECORD_ID<>TRIM(SOURCE_RECORD_ID) OR COUNT(*)<>1) q), 0, 'INPUT'
    UNION ALL
    SELECT 8, 'SOURCE_TRACKING_INPUTS_NEEDING_REVIEW',
           (SELECT COUNT(*) FROM source_rows WHERE NOT COALESCE(IS_OBJECT(PAYLOAD),FALSE) OR NOT COALESCE(TYPEOF(RAW_TRACKING) IN ('INTEGER','VARCHAR'),FALSE) OR COALESCE(TRIM(TO_VARCHAR(RAW_TRACKING)),'')=''), 0, 'INPUT'
    UNION ALL
    SELECT 9, 'NULL_OR_DUPLICATE_TARGET_KEY_GROUPS',
           (SELECT COUNT(*) FROM key_defects), 0, 'DEFECT'
    UNION ALL
    SELECT 10, 'INVALID_TARGET_OWNERSHIP_OR_PAYLOAD_ROWS',
           (SELECT COUNT(*) FROM d WHERE SOURCE_SYSTEM_NAME IS DISTINCT FROM 'ARCHER' OR SOURCE_TABLE_NAME IS DISTINCT FROM 'ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW' OR SOURCE_RECORD_ID IS NULL OR TRIM(SOURCE_RECORD_ID)='' OR SOURCE_RECORD_ID<>TRIM(SOURCE_RECORD_ID) OR NOT COALESCE(IS_OBJECT(METADATA_JSON),FALSE) OR NOT EXISTS (SELECT 1 FROM source_rows s WHERE s.SOURCE_RECORD_ID=d.SOURCE_RECORD_ID)), 0, 'DEFECT'
    UNION ALL
    SELECT 11, 'SOURCE_ROOT_OR_METADATA_COVERAGE_ERRORS',
           (SELECT COUNT(*) FROM source_rows s LEFT JOIN record_nodes r ON r.SOURCE_RECORD_ID=s.SOURCE_RECORD_ID WHERE COALESCE(r.ROOTS,0)<>1 OR COALESCE(r.METADATA_ROWS,0)<>1), 0, 'DEFECT'
    UNION ALL
    SELECT 12, 'UNEXPECTED_ELEMENT_TYPES',
           (SELECT COUNT(*) FROM d WHERE ELEMENT_TYPE IS NULL OR ELEMENT_TYPE NOT IN ('catalog','metadata','props')), 0, 'DEFECT'
    UNION ALL
    SELECT 13, 'NULL_OR_BLANK_FACT_REFERENCES',
           (SELECT COUNT(*) FROM f WHERE FK_SOURCE_ELEMENT_HASH IS NULL OR FK_TARGET_ELEMENT_HASH IS NULL OR SOURCE_OSCAL_UUID IS NULL OR TRIM(SOURCE_OSCAL_UUID)='' OR TARGET_OSCAL_UUID IS NULL OR TRIM(TARGET_OSCAL_UUID)=''), 0, 'DEFECT'
    UNION ALL
    SELECT 14, 'ORPHAN_SOURCE_FK',
           (SELECT COUNT(*) FROM f WHERE NOT EXISTS (SELECT 1 FROM d WHERE d.NODE_KEY=f.FK_SOURCE_ELEMENT_HASH)), 0, 'DEFECT'
    UNION ALL
    SELECT 15, 'ORPHAN_TARGET_FK',
           (SELECT COUNT(*) FROM f WHERE NOT EXISTS (SELECT 1 FROM d WHERE d.NODE_KEY=f.FK_TARGET_ELEMENT_HASH)), 0, 'DEFECT'
    UNION ALL
    SELECT 16, 'UUID_MISMATCH',
           (SELECT COUNT(*) FROM joined_edges WHERE SOURCE_OSCAL_UUID IS DISTINCT FROM PARENT_UUID OR TARGET_OSCAL_UUID IS DISTINCT FROM CHILD_UUID), 0, 'DEFECT'
    UNION ALL
    SELECT 17, 'CROSS_RECORD_OR_NAMESPACE_EDGES',
           (SELECT COUNT(*) FROM joined_edges WHERE PARENT_SYSTEM IS DISTINCT FROM CHILD_SYSTEM OR PARENT_TABLE IS DISTINCT FROM CHILD_TABLE OR PARENT_RECORD IS DISTINCT FROM CHILD_RECORD), 0, 'DEFECT'
    UNION ALL
    SELECT 18, 'INVALID_CONTAINS_OR_HIERARCHY_EDGES',
           (SELECT COUNT(*) FROM joined_edges WHERE DEPENDENCY_TYPE IS DISTINCT FROM 'CONTAINS' OR NOT COALESCE((SOURCE_TYPE='catalog' AND TARGET_TYPE='metadata') OR (SOURCE_TYPE='metadata' AND TARGET_TYPE='props'),FALSE) OR FK_SOURCE_ELEMENT_HASH=FK_TARGET_ELEMENT_HASH), 0, 'DEFECT'
    UNION ALL
    SELECT 19, 'WRONG_PARENT_COUNT',
           (SELECT COUNT(*) FROM parent_counts WHERE PARENTS<>CASE WHEN ELEMENT_TYPE='catalog' THEN 0 ELSE 1 END), 0, 'DEFECT'
    UNION ALL
    SELECT 20, 'MISSING_OR_DUPLICATE_TRACKING_PER_SOURCE',
           (SELECT COUNT(*) FROM source_valid s LEFT JOIN tracking_counts t ON t.SOURCE_RECORD_ID=s.SOURCE_RECORD_ID WHERE COALESCE(t.PROPERTY_ROWS,0)<>1), 0, 'DEFECT'
    UNION ALL
    SELECT 21, 'TRACKING_VALUE_OR_TYPE_MISMATCH',
           (SELECT COUNT(*) FROM tracking_comparison WHERE AS_VARCHAR(PROPERTY_VALUE) IS DISTINCT FROM EXPECTED_VALUE), 0, 'DEFECT'
),
results AS (
    SELECT CHECK_ORDER, QA_CHECK, OBSERVED_COUNT, EXPECTED_COUNT,
           CASE WHEN OBSERVED_COUNT=EXPECTED_COUNT THEN 'PASS'
                WHEN CHECK_KIND='INPUT' THEN 'BLOCKED'
                WHEN CHECK_KIND='BASELINE' THEN 'DRIFT'
                ELSE 'FAIL' END AS STATUS
    FROM checks
),
report AS (
    SELECT 0 AS CHECK_ORDER, 'OVERALL_CATALOG_POST_COMMIT_QA' AS QA_CHECK,
           SUM(CASE WHEN STATUS<>'PASS' THEN 1 ELSE 0 END) AS OBSERVED_COUNT,
           0 AS EXPECTED_COUNT,
           CASE WHEN SUM(CASE WHEN STATUS='BLOCKED' THEN 1 ELSE 0 END)>0 THEN 'BLOCKED'
                WHEN SUM(CASE WHEN STATUS='FAIL' THEN 1 ELSE 0 END)>0 THEN 'FAIL'
                WHEN SUM(CASE WHEN STATUS='DRIFT' THEN 1 ELSE 0 END)>0 THEN 'DRIFT'
                ELSE 'PASS' END AS STATUS
    FROM results
    UNION ALL SELECT CHECK_ORDER, QA_CHECK, OBSERVED_COUNT, EXPECTED_COUNT, STATUS FROM results
)
SELECT CURRENT_TIMESTAMP() AS QA_EXECUTED_AT,
       CHECK_ORDER, QA_CHECK, OBSERVED_COUNT, EXPECTED_COUNT, STATUS
FROM report
ORDER BY CHECK_ORDER;
