-- SOURCE ONE OSCAL-ONLY INTEGRATED RELATIONSHIP QA
-- Date: 2026-09-25
-- READ ONLY. No RAW / historical / registry tables.
--
-- Goal:
--   Validate the four committed Source One OSCAL models using only OSCAL DIM/FACT.
--   Produce one integrated row per SOURCE_RECORD_ID (Authorization Package CONTENT_ID)
--   across SSP, Assessment Results, POA&M, and Security Assessment Plan.
--
-- IMPORTANT:
--   Cross-model linkage is by SOURCE_RECORD_ID, not by cross-model FACT foreign key.
--   FACT tables validate hierarchy only inside each OSCAL model.
--
-- This query intentionally avoids SELECT * fan-out across all child nodes.
-- Each model is aggregated to one row per SOURCE_RECORD_ID first, then joined.
--
-- Current project policy does not use curated views, so this is delivered as a
-- SELECT-only QA query. If a view is later approved, wrap the final SELECT in
-- CREATE OR REPLACE VIEW ... AS.


-- =====================================================================
-- 01. ONE ROW PER SOURCE_RECORD_ID ACROSS ALL FOUR OSCAL MODELS
-- Expected:
--   HAS_* = 1 for all four models
--   ROOT_COUNT = 1 for every model
--   EDGE_COUNT = NODE_COUNT - 1 for every model
--   CROSS_RECORD_EDGES = 0 for every model
-- =====================================================================
WITH
ssp_d AS (
  SELECT
    PK_OSCAL_SSP_ELEMENT_HASH AS NODE_KEY,
    TRIM(SOURCE_RECORD_ID::STRING) AS SOURCE_RECORD_ID,
    ELEMENT_TYPE,
    OSCAL_UUID,
    METADATA_JSON
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER'
    AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
),
ssp_e AS (
  SELECT
    s.SOURCE_RECORD_ID,
    COUNT(*) AS EDGE_COUNT,
    COUNT_IF(s.SOURCE_RECORD_ID<>t.SOURCE_RECORD_ID) AS CROSS_RECORD_EDGES
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY f
  JOIN ssp_d s ON s.NODE_KEY=f.FK_SOURCE_ELEMENT_HASH
  JOIN ssp_d t ON t.NODE_KEY=f.FK_TARGET_ELEMENT_HASH
  GROUP BY 1
),
ssp AS (
  SELECT
    d.SOURCE_RECORD_ID,
    COUNT(*) AS NODE_COUNT,
    COUNT_IF(d.ELEMENT_TYPE='system-security-plan') AS ROOT_COUNT,
    MAX(IFF(d.ELEMENT_TYPE='system-security-plan',d.OSCAL_UUID,NULL)) AS ROOT_UUID,
    COUNT_IF(d.ELEMENT_TYPE='metadata') AS METADATA_NODES,
    COUNT_IF(d.ELEMENT_TYPE='system-characteristics') AS SYSTEM_CHARACTERISTICS_NODES,
    COUNT_IF(d.ELEMENT_TYPE='components') AS COMPONENT_NODES,
    COUNT_IF(d.ELEMENT_TYPE='implemented-requirements') AS IMPLEMENTED_REQUIREMENT_NODES,
    COUNT_IF(d.ELEMENT_TYPE='props') AS PROP_NODES,
    COALESCE(MAX(e.EDGE_COUNT),0) AS EDGE_COUNT,
    COALESCE(MAX(e.CROSS_RECORD_EDGES),0) AS CROSS_RECORD_EDGES
  FROM ssp_d d
  LEFT JOIN ssp_e e USING(SOURCE_RECORD_ID)
  GROUP BY 1
),

ar_d AS (
  SELECT
    PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH AS NODE_KEY,
    TRIM(SOURCE_RECORD_ID::STRING) AS SOURCE_RECORD_ID,
    ELEMENT_TYPE,
    OSCAL_UUID,
    METADATA_JSON
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER'
    AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
),
ar_e AS (
  SELECT
    s.SOURCE_RECORD_ID,
    COUNT(*) AS EDGE_COUNT,
    COUNT_IF(s.SOURCE_RECORD_ID<>t.SOURCE_RECORD_ID) AS CROSS_RECORD_EDGES
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_RESULTS_DEPENDENCY f
  JOIN ar_d s ON s.NODE_KEY=f.FK_SOURCE_ELEMENT_HASH
  JOIN ar_d t ON t.NODE_KEY=f.FK_TARGET_ELEMENT_HASH
  GROUP BY 1
),
ar AS (
  SELECT
    d.SOURCE_RECORD_ID,
    COUNT(*) AS NODE_COUNT,
    COUNT_IF(d.ELEMENT_TYPE='assessment-results') AS ROOT_COUNT,
    MAX(IFF(d.ELEMENT_TYPE='assessment-results',d.OSCAL_UUID,NULL)) AS ROOT_UUID,
    COUNT_IF(d.ELEMENT_TYPE='result') AS RESULT_NODES,
    COUNT_IF(d.ELEMENT_TYPE='observations') AS OBSERVATION_NODES,
    COUNT_IF(d.ELEMENT_TYPE='findings') AS FINDING_NODES,
    COUNT_IF(d.ELEMENT_TYPE='props') AS PROP_NODES,
    COALESCE(MAX(e.EDGE_COUNT),0) AS EDGE_COUNT,
    COALESCE(MAX(e.CROSS_RECORD_EDGES),0) AS CROSS_RECORD_EDGES
  FROM ar_d d
  LEFT JOIN ar_e e USING(SOURCE_RECORD_ID)
  GROUP BY 1
),

poam_d AS (
  SELECT
    PK_DIM_OSCAL_POAM_ELEMENT_HASH AS NODE_KEY,
    TRIM(SOURCE_RECORD_ID::STRING) AS SOURCE_RECORD_ID,
    ELEMENT_TYPE,
    OSCAL_UUID,
    METADATA_JSON
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER'
    AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
),
poam_e AS (
  SELECT
    s.SOURCE_RECORD_ID,
    COUNT(*) AS EDGE_COUNT,
    COUNT_IF(s.SOURCE_RECORD_ID<>t.SOURCE_RECORD_ID) AS CROSS_RECORD_EDGES
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_POAM_DEPENDENCY f
  JOIN poam_d s ON s.NODE_KEY=f.FK_SOURCE_ELEMENT_HASH
  JOIN poam_d t ON t.NODE_KEY=f.FK_TARGET_ELEMENT_HASH
  GROUP BY 1
),
poam AS (
  SELECT
    d.SOURCE_RECORD_ID,
    COUNT(*) AS NODE_COUNT,
    COUNT_IF(d.ELEMENT_TYPE='plan-of-action-and-milestones') AS ROOT_COUNT,
    MAX(IFF(d.ELEMENT_TYPE='plan-of-action-and-milestones',d.OSCAL_UUID,NULL)) AS ROOT_UUID,
    COUNT_IF(d.ELEMENT_TYPE='poam-items') AS POAM_ITEM_NODES,
    COUNT_IF(d.ELEMENT_TYPE='props') AS PROP_NODES,
    COALESCE(MAX(e.EDGE_COUNT),0) AS EDGE_COUNT,
    COALESCE(MAX(e.CROSS_RECORD_EDGES),0) AS CROSS_RECORD_EDGES
  FROM poam_d d
  LEFT JOIN poam_e e USING(SOURCE_RECORD_ID)
  GROUP BY 1
),

sap_d AS (
  SELECT
    PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH AS NODE_KEY,
    TRIM(SOURCE_RECORD_ID::STRING) AS SOURCE_RECORD_ID,
    ELEMENT_TYPE,
    OSCAL_UUID,
    METADATA_JSON
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER'
    AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
),
sap_e AS (
  SELECT
    s.SOURCE_RECORD_ID,
    COUNT(*) AS EDGE_COUNT,
    COUNT_IF(s.SOURCE_RECORD_ID<>t.SOURCE_RECORD_ID) AS CROSS_RECORD_EDGES
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_PLAN_DEPENDENCY f
  JOIN sap_d s ON s.NODE_KEY=f.FK_SOURCE_ELEMENT_HASH
  JOIN sap_d t ON t.NODE_KEY=f.FK_TARGET_ELEMENT_HASH
  GROUP BY 1
),
sap AS (
  SELECT
    d.SOURCE_RECORD_ID,
    COUNT(*) AS NODE_COUNT,
    COUNT_IF(d.ELEMENT_TYPE='assessment-plan') AS ROOT_COUNT,
    MAX(IFF(d.ELEMENT_TYPE='assessment-plan',d.OSCAL_UUID,NULL)) AS ROOT_UUID,
    COUNT_IF(d.ELEMENT_TYPE='tasks') AS TASK_NODES,
    COUNT_IF(d.ELEMENT_TYPE='props') AS PROP_NODES,
    COALESCE(MAX(e.EDGE_COUNT),0) AS EDGE_COUNT,
    COALESCE(MAX(e.CROSS_RECORD_EDGES),0) AS CROSS_RECORD_EDGES
  FROM sap_d d
  LEFT JOIN sap_e e USING(SOURCE_RECORD_ID)
  GROUP BY 1
),

ids AS (
  SELECT SOURCE_RECORD_ID FROM ssp
  UNION
  SELECT SOURCE_RECORD_ID FROM ar
  UNION
  SELECT SOURCE_RECORD_ID FROM poam
  UNION
  SELECT SOURCE_RECORD_ID FROM sap
)

SELECT
  ids.SOURCE_RECORD_ID,

  IFF(ssp.SOURCE_RECORD_ID IS NOT NULL,1,0) AS HAS_SSP,
  ssp.ROOT_UUID AS SSP_ROOT_UUID,
  ssp.NODE_COUNT AS SSP_NODE_COUNT,
  ssp.EDGE_COUNT AS SSP_EDGE_COUNT,
  ssp.METADATA_NODES AS SSP_METADATA_NODES,
  ssp.SYSTEM_CHARACTERISTICS_NODES AS SSP_SYSTEM_CHARACTERISTICS_NODES,
  ssp.COMPONENT_NODES AS SSP_COMPONENT_NODES,
  ssp.IMPLEMENTED_REQUIREMENT_NODES AS SSP_IMPLEMENTED_REQUIREMENT_NODES,
  ssp.PROP_NODES AS SSP_PROP_NODES,
  IFF(ssp.ROOT_COUNT=1
      AND ssp.EDGE_COUNT=ssp.NODE_COUNT-1
      AND ssp.CROSS_RECORD_EDGES=0,'PASS','FAIL') AS SSP_INTEGRITY,

  IFF(ar.SOURCE_RECORD_ID IS NOT NULL,1,0) AS HAS_ASSESSMENT_RESULTS,
  ar.ROOT_UUID AS AR_ROOT_UUID,
  ar.NODE_COUNT AS AR_NODE_COUNT,
  ar.EDGE_COUNT AS AR_EDGE_COUNT,
  ar.RESULT_NODES AS AR_RESULT_NODES,
  ar.OBSERVATION_NODES AS AR_OBSERVATION_NODES,
  ar.FINDING_NODES AS AR_FINDING_NODES,
  ar.PROP_NODES AS AR_PROP_NODES,
  IFF(ar.ROOT_COUNT=1
      AND ar.EDGE_COUNT=ar.NODE_COUNT-1
      AND ar.CROSS_RECORD_EDGES=0,'PASS','FAIL') AS AR_INTEGRITY,

  IFF(poam.SOURCE_RECORD_ID IS NOT NULL,1,0) AS HAS_POAM,
  poam.ROOT_UUID AS POAM_ROOT_UUID,
  poam.NODE_COUNT AS POAM_NODE_COUNT,
  poam.EDGE_COUNT AS POAM_EDGE_COUNT,
  poam.POAM_ITEM_NODES AS POAM_ITEM_NODES,
  poam.PROP_NODES AS POAM_PROP_NODES,
  IFF(poam.ROOT_COUNT=1
      AND poam.EDGE_COUNT=poam.NODE_COUNT-1
      AND poam.CROSS_RECORD_EDGES=0,'PASS','FAIL') AS POAM_INTEGRITY,

  IFF(sap.SOURCE_RECORD_ID IS NOT NULL,1,0) AS HAS_ASSESSMENT_PLAN,
  sap.ROOT_UUID AS SAP_ROOT_UUID,
  sap.NODE_COUNT AS SAP_NODE_COUNT,
  sap.EDGE_COUNT AS SAP_EDGE_COUNT,
  sap.TASK_NODES AS SAP_TASK_NODES,
  sap.PROP_NODES AS SAP_PROP_NODES,
  IFF(sap.ROOT_COUNT=1
      AND sap.EDGE_COUNT=sap.NODE_COUNT-1
      AND sap.CROSS_RECORD_EDGES=0,'PASS','FAIL') AS SAP_INTEGRITY,

  IFF(
    ssp.SOURCE_RECORD_ID IS NOT NULL
    AND ar.SOURCE_RECORD_ID IS NOT NULL
    AND poam.SOURCE_RECORD_ID IS NOT NULL
    AND sap.SOURCE_RECORD_ID IS NOT NULL,
    'PASS','FAIL'
  ) AS CROSS_MODEL_COVERAGE,

  IFF(
    ssp.ROOT_COUNT=1 AND ssp.EDGE_COUNT=ssp.NODE_COUNT-1 AND ssp.CROSS_RECORD_EDGES=0
    AND ar.ROOT_COUNT=1 AND ar.EDGE_COUNT=ar.NODE_COUNT-1 AND ar.CROSS_RECORD_EDGES=0
    AND poam.ROOT_COUNT=1 AND poam.EDGE_COUNT=poam.NODE_COUNT-1 AND poam.CROSS_RECORD_EDGES=0
    AND sap.ROOT_COUNT=1 AND sap.EDGE_COUNT=sap.NODE_COUNT-1 AND sap.CROSS_RECORD_EDGES=0,
    'PASS','FAIL'
  ) AS OVERALL_RELATIONSHIP_INTEGRITY

FROM ids
LEFT JOIN ssp USING(SOURCE_RECORD_ID)
LEFT JOIN ar USING(SOURCE_RECORD_ID)
LEFT JOIN poam USING(SOURCE_RECORD_ID)
LEFT JOIN sap USING(SOURCE_RECORD_ID)
ORDER BY ids.SOURCE_RECORD_ID;


-- =====================================================================
-- 02. INTEGRATED OSCAL-ONLY SUMMARY
-- Expected:
--   2813 integrated Source One IDs
--   0 missing models
--   0 integrity failures
-- =====================================================================
WITH
ssp AS (
  SELECT TRIM(SOURCE_RECORD_ID::STRING) SOURCE_RECORD_ID,
         COUNT(*) NODE_COUNT,
         COUNT_IF(ELEMENT_TYPE='system-security-plan') ROOT_COUNT
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER'
    AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  GROUP BY 1
),
ssp_e AS (
  SELECT TRIM(s.SOURCE_RECORD_ID::STRING) SOURCE_RECORD_ID,COUNT(*) EDGE_COUNT,
         COUNT_IF(s.SOURCE_RECORD_ID<>t.SOURCE_RECORD_ID) CROSS_RECORD_EDGES
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY f
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT s
    ON s.PK_OSCAL_SSP_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
   AND s.SOURCE_SYSTEM_NAME='ARCHER'
   AND s.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT t
    ON t.PK_OSCAL_SSP_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
   AND t.SOURCE_SYSTEM_NAME='ARCHER'
   AND t.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  GROUP BY 1
),
ar AS (
  SELECT TRIM(SOURCE_RECORD_ID::STRING) SOURCE_RECORD_ID,
         COUNT(*) NODE_COUNT,
         COUNT_IF(ELEMENT_TYPE='assessment-results') ROOT_COUNT
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER'
    AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  GROUP BY 1
),
ar_e AS (
  SELECT TRIM(s.SOURCE_RECORD_ID::STRING) SOURCE_RECORD_ID,COUNT(*) EDGE_COUNT,
         COUNT_IF(s.SOURCE_RECORD_ID<>t.SOURCE_RECORD_ID) CROSS_RECORD_EDGES
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_RESULTS_DEPENDENCY f
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT s
    ON s.PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
   AND s.SOURCE_SYSTEM_NAME='ARCHER'
   AND s.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT t
    ON t.PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
   AND t.SOURCE_SYSTEM_NAME='ARCHER'
   AND t.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  GROUP BY 1
),
poam AS (
  SELECT TRIM(SOURCE_RECORD_ID::STRING) SOURCE_RECORD_ID,
         COUNT(*) NODE_COUNT,
         COUNT_IF(ELEMENT_TYPE='plan-of-action-and-milestones') ROOT_COUNT
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER'
    AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  GROUP BY 1
),
poam_e AS (
  SELECT TRIM(s.SOURCE_RECORD_ID::STRING) SOURCE_RECORD_ID,COUNT(*) EDGE_COUNT,
         COUNT_IF(s.SOURCE_RECORD_ID<>t.SOURCE_RECORD_ID) CROSS_RECORD_EDGES
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_POAM_DEPENDENCY f
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT s
    ON s.PK_DIM_OSCAL_POAM_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
   AND s.SOURCE_SYSTEM_NAME='ARCHER'
   AND s.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT t
    ON t.PK_DIM_OSCAL_POAM_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
   AND t.SOURCE_SYSTEM_NAME='ARCHER'
   AND t.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  GROUP BY 1
),
sap AS (
  SELECT TRIM(SOURCE_RECORD_ID::STRING) SOURCE_RECORD_ID,
         COUNT(*) NODE_COUNT,
         COUNT_IF(ELEMENT_TYPE='assessment-plan') ROOT_COUNT
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT
  WHERE SOURCE_SYSTEM_NAME='ARCHER'
    AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  GROUP BY 1
),
sap_e AS (
  SELECT TRIM(s.SOURCE_RECORD_ID::STRING) SOURCE_RECORD_ID,COUNT(*) EDGE_COUNT,
         COUNT_IF(s.SOURCE_RECORD_ID<>t.SOURCE_RECORD_ID) CROSS_RECORD_EDGES
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_PLAN_DEPENDENCY f
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT s
    ON s.PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
   AND s.SOURCE_SYSTEM_NAME='ARCHER'
   AND s.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT t
    ON t.PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
   AND t.SOURCE_SYSTEM_NAME='ARCHER'
   AND t.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  GROUP BY 1
),
ids AS (
  SELECT SOURCE_RECORD_ID FROM ssp
  UNION SELECT SOURCE_RECORD_ID FROM ar
  UNION SELECT SOURCE_RECORD_ID FROM poam
  UNION SELECT SOURCE_RECORD_ID FROM sap
),
m AS (
  SELECT
    ids.SOURCE_RECORD_ID,
    IFF(ssp.SOURCE_RECORD_ID IS NULL,1,0) MISS_SSP,
    IFF(ar.SOURCE_RECORD_ID IS NULL,1,0) MISS_AR,
    IFF(poam.SOURCE_RECORD_ID IS NULL,1,0) MISS_POAM,
    IFF(sap.SOURCE_RECORD_ID IS NULL,1,0) MISS_SAP,
    IFF(ssp.ROOT_COUNT<>1 OR COALESCE(ssp_e.EDGE_COUNT,0)<>ssp.NODE_COUNT-1
        OR COALESCE(ssp_e.CROSS_RECORD_EDGES,0)<>0,1,0) SSP_BAD,
    IFF(ar.ROOT_COUNT<>1 OR COALESCE(ar_e.EDGE_COUNT,0)<>ar.NODE_COUNT-1
        OR COALESCE(ar_e.CROSS_RECORD_EDGES,0)<>0,1,0) AR_BAD,
    IFF(poam.ROOT_COUNT<>1 OR COALESCE(poam_e.EDGE_COUNT,0)<>poam.NODE_COUNT-1
        OR COALESCE(poam_e.CROSS_RECORD_EDGES,0)<>0,1,0) POAM_BAD,
    IFF(sap.ROOT_COUNT<>1 OR COALESCE(sap_e.EDGE_COUNT,0)<>sap.NODE_COUNT-1
        OR COALESCE(sap_e.CROSS_RECORD_EDGES,0)<>0,1,0) SAP_BAD
  FROM ids
  LEFT JOIN ssp USING(SOURCE_RECORD_ID)
  LEFT JOIN ssp_e USING(SOURCE_RECORD_ID)
  LEFT JOIN ar USING(SOURCE_RECORD_ID)
  LEFT JOIN ar_e USING(SOURCE_RECORD_ID)
  LEFT JOIN poam USING(SOURCE_RECORD_ID)
  LEFT JOIN poam_e USING(SOURCE_RECORD_ID)
  LEFT JOIN sap USING(SOURCE_RECORD_ID)
  LEFT JOIN sap_e USING(SOURCE_RECORD_ID)
)
SELECT
  COUNT(*) AS INTEGRATED_SOURCE_RECORD_IDS,
  COUNT_IF(MISS_SSP=1) AS MISSING_SSP,
  COUNT_IF(MISS_AR=1) AS MISSING_ASSESSMENT_RESULTS,
  COUNT_IF(MISS_POAM=1) AS MISSING_POAM,
  COUNT_IF(MISS_SAP=1) AS MISSING_ASSESSMENT_PLAN,
  COUNT_IF(SSP_BAD=1) AS SSP_INTEGRITY_FAILURES,
  COUNT_IF(AR_BAD=1) AS AR_INTEGRITY_FAILURES,
  COUNT_IF(POAM_BAD=1) AS POAM_INTEGRITY_FAILURES,
  COUNT_IF(SAP_BAD=1) AS SAP_INTEGRITY_FAILURES,
  IFF(
    COUNT_IF(MISS_SSP+MISS_AR+MISS_POAM+MISS_SAP+SSP_BAD+AR_BAD+POAM_BAD+SAP_BAD>0)=0,
    'PASS','FAIL'
  ) AS OVERALL_STATUS
FROM m;


-- =====================================================================
-- 03. ONE CONTENT_ID: SHOW ALL OSCAL NODES ACROSS THE FOUR DIM TABLES
-- Change QA_CONTENT_ID to any SOURCE_RECORD_ID returned by section 01.
-- =====================================================================
SET QA_CONTENT_ID = 'REPLACE_WITH_SOURCE_RECORD_ID';

SELECT 'SSP' MODEL,SOURCE_RECORD_ID,ELEMENT_TYPE,OSCAL_UUID,METADATA_JSON
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
WHERE SOURCE_SYSTEM_NAME='ARCHER'
  AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  AND TRIM(SOURCE_RECORD_ID::STRING)=$QA_CONTENT_ID
UNION ALL
SELECT 'ASSESSMENT_RESULTS',SOURCE_RECORD_ID,ELEMENT_TYPE,OSCAL_UUID,METADATA_JSON
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT
WHERE SOURCE_SYSTEM_NAME='ARCHER'
  AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  AND TRIM(SOURCE_RECORD_ID::STRING)=$QA_CONTENT_ID
UNION ALL
SELECT 'POAM',SOURCE_RECORD_ID,ELEMENT_TYPE,OSCAL_UUID,METADATA_JSON
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT
WHERE SOURCE_SYSTEM_NAME='ARCHER'
  AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  AND TRIM(SOURCE_RECORD_ID::STRING)=$QA_CONTENT_ID
UNION ALL
SELECT 'SECURITY_ASSESSMENT_PLAN',SOURCE_RECORD_ID,ELEMENT_TYPE,OSCAL_UUID,METADATA_JSON
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT
WHERE SOURCE_SYSTEM_NAME='ARCHER'
  AND SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  AND TRIM(SOURCE_RECORD_ID::STRING)=$QA_CONTENT_ID
ORDER BY MODEL,ELEMENT_TYPE,OSCAL_UUID;


-- =====================================================================
-- 04. ONE CONTENT_ID: SHOW ALL WITHIN-MODEL PARENT -> CHILD RELATIONSHIPS
-- Uses only OSCAL DIM/FACT.
-- =====================================================================
SELECT
  'SSP' MODEL,
  s.SOURCE_RECORD_ID,
  s.ELEMENT_TYPE PARENT_TYPE,
  s.OSCAL_UUID PARENT_UUID,
  f.DEPENDENCY_TYPE,
  t.ELEMENT_TYPE CHILD_TYPE,
  t.OSCAL_UUID CHILD_UUID
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY f
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT s
  ON s.PK_OSCAL_SSP_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT t
  ON t.PK_OSCAL_SSP_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
WHERE s.SOURCE_SYSTEM_NAME='ARCHER'
  AND s.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  AND t.SOURCE_SYSTEM_NAME='ARCHER'
  AND t.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  AND TRIM(s.SOURCE_RECORD_ID::STRING)=$QA_CONTENT_ID

UNION ALL

SELECT
  'ASSESSMENT_RESULTS',
  s.SOURCE_RECORD_ID,
  s.ELEMENT_TYPE,
  s.OSCAL_UUID,
  f.DEPENDENCY_TYPE,
  t.ELEMENT_TYPE,
  t.OSCAL_UUID
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_RESULTS_DEPENDENCY f
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT s
  ON s.PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT t
  ON t.PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
WHERE s.SOURCE_SYSTEM_NAME='ARCHER'
  AND s.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  AND t.SOURCE_SYSTEM_NAME='ARCHER'
  AND t.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  AND TRIM(s.SOURCE_RECORD_ID::STRING)=$QA_CONTENT_ID

UNION ALL

SELECT
  'POAM',
  s.SOURCE_RECORD_ID,
  s.ELEMENT_TYPE,
  s.OSCAL_UUID,
  f.DEPENDENCY_TYPE,
  t.ELEMENT_TYPE,
  t.OSCAL_UUID
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_POAM_DEPENDENCY f
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT s
  ON s.PK_DIM_OSCAL_POAM_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT t
  ON t.PK_DIM_OSCAL_POAM_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
WHERE s.SOURCE_SYSTEM_NAME='ARCHER'
  AND s.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  AND t.SOURCE_SYSTEM_NAME='ARCHER'
  AND t.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  AND TRIM(s.SOURCE_RECORD_ID::STRING)=$QA_CONTENT_ID

UNION ALL

SELECT
  'SECURITY_ASSESSMENT_PLAN',
  s.SOURCE_RECORD_ID,
  s.ELEMENT_TYPE,
  s.OSCAL_UUID,
  f.DEPENDENCY_TYPE,
  t.ELEMENT_TYPE,
  t.OSCAL_UUID
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_PLAN_DEPENDENCY f
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT s
  ON s.PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH=f.FK_SOURCE_ELEMENT_HASH
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT t
  ON t.PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH=f.FK_TARGET_ELEMENT_HASH
WHERE s.SOURCE_SYSTEM_NAME='ARCHER'
  AND s.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  AND t.SOURCE_SYSTEM_NAME='ARCHER'
  AND t.SOURCE_TABLE_NAME='ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
  AND TRIM(s.SOURCE_RECORD_ID::STRING)=$QA_CONTENT_ID
ORDER BY MODEL,PARENT_TYPE,CHILD_TYPE,PARENT_UUID,CHILD_UUID;


-- =====================================================================
-- INTERPRETATION
--
-- Within a model:
--   DIM node PK <-> FACT FK proves graph relationship integrity.
--
-- Across models:
--   SOURCE_RECORD_ID is the shared Source One business key.
--   There is intentionally no SSP-FK-to-AR or SSP-FK-to-POAM cross-model edge.
--
-- For a production-grade integrated query:
--   aggregate each model to one row per SOURCE_RECORD_ID first,
--   then join those aggregates. Do NOT directly join child DIM tables across
--   models, because one-to-many child collections would multiply rows.
-- =====================================================================
