-- SOURCE ONE UPSTREAM PAYLOAD DISCOVERY
-- Date: 2026-09-28
-- READ ONLY.
--
-- Purpose:
-- Identify the actual physical columns in ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
-- before building the raw-payload -> CURATED_JSON reconciliation.
--
-- Do not assume the pre-CURATED Archer payload column name.

SELECT
    COLUMN_NAME,
    DATA_TYPE,
    ORDINAL_POSITION,
    IS_NULLABLE
FROM RTX_RAW_DEV.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ES_ESC_GRC'
  AND TABLE_NAME = 'ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
ORDER BY ORDINAL_POSITION;

-- Optional one-row shape check for the columns already known to the OSCAL mapper.
SELECT
    CONTENT_ID,
    TYPEOF(CURATED_JSON) AS CURATED_JSON_TYPE,
    ARRAY_SIZE(OBJECT_KEYS(CURATED_JSON)) AS CURATED_JSON_KEY_COUNT
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
LIMIT 1;
