-- READ ONLY: compare both Archer timestamp candidates to SSP metadata.
SELECT
    r.CONTENT_ID,
    r.CURATED_JSON:ARCHER_CONTENT_AUTHORIZATION_PACKAGE_FIRST_PUBLISHED AS ARCHER_PACKAGE_FIRST_PUBLISHED,
    r.CURATED_JSON:FIRST_PUBLISHED AS FIRST_PUBLISHED,
    m.METADATA_JSON:published AS OSCAL_PUBLISHED,
    r.CURATED_JSON:ARCHER_CONTENT_AUTHORIZATION_PACKAGE_LAST_UPDATED AS ARCHER_PACKAGE_LAST_UPDATED,
    r.CURATED_JSON:LAST_UPDATED AS LAST_UPDATED,
    m.METADATA_JSON:"last-modified" AS OSCAL_LAST_MODIFIED
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT m
  ON m.SOURCE_RECORD_ID = r.CONTENT_ID::STRING
WHERE m.ELEMENT_TYPE = 'metadata'
ORDER BY r.CONTENT_ID
LIMIT 25;
