-- READ ONLY: check whether authorization-boundary is stored as its own DIM node.
SELECT r.CONTENT_ID,
       r.CURATED_JSON:AUTHORIZATION_BOUNDARY_DESCRIPTION::STRING AS ARCHER_BOUNDARY,
       b.ELEMENT_TYPE,
       b.METADATA_JSON:description::STRING AS OSCAL_BOUNDARY
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT b
  ON b.SOURCE_RECORD_ID = r.CONTENT_ID::STRING
WHERE b.ELEMENT_TYPE = 'authorization-boundary'
ORDER BY r.CONTENT_ID
LIMIT 25;
