-- READ ONLY: prove one populated System Characteristics prop end-to-end.
SELECT
  COUNT_IF(TYPEOF(CURATED_JSON:MISSION_CRITICAL) <> 'NULL_VALUE') AS SOURCE_REAL_VALUES
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW;

SELECT COUNT(*) AS TARGET_PROP_ROWS
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
WHERE ELEMENT_TYPE = 'props'
  AND METADATA_JSON:name::STRING = 'mission-critical';
