-- READ ONLY: verify all SSP metadata responsible-party roles at once.
WITH rp AS (
  SELECT d.SOURCE_RECORD_ID,
         d.METADATA_JSON:"role-id"::STRING AS ROLE_ID,
         f.VALUE::STRING AS PARTY_UUID
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT d,
       LATERAL FLATTEN(INPUT => d.METADATA_JSON:"party-uuids") f
  WHERE d.ELEMENT_TYPE = 'responsible-parties'
)
SELECT rp.ROLE_ID,
       COUNT(*) AS PARTY_LINKS,
       COUNT_IF(p.METADATA_JSON:name::STRING IS NOT NULL) AS NAMED_PARTIES
FROM rp
LEFT JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT p
  ON p.METADATA_JSON:uuid::STRING = rp.PARTY_UUID
 AND p.ELEMENT_TYPE = 'parties'
GROUP BY rp.ROLE_ID
ORDER BY rp.ROLE_ID;
