-- READ ONLY: identify the correct Archer metadata row for SSP System Characteristics.
SELECT SQL_FIELD_NAME, FIELD_NAME, FIELD_ID, FIELD_TYPE_ID, LEVEL_ID, MODULE_ID
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_META_FIELD
WHERE SQL_FIELD_NAME IN (
  'INFORMATION_SYSTEM_TYPE','FISMA_REPORTABLE','FINANCIAL_SYSTEM','MISSION_CRITICAL',
  'CRITICAL_INFRASTRUCTURE','PACKAGE_TYPE','AUTHORIZATION_DECISION','PIA_REQUIRED'
)
ORDER BY SQL_FIELD_NAME, LEVEL_ID, FIELD_ID;
