-- READ ONLY: verify information-owner party UUID resolves to the party node.
WITH info_owner AS (
  SELECT d.SOURCE_RECORD_ID,
         f.VALUE::STRING AS PARTY_UUID
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT d,
       LATERAL FLATTEN(INPUT => d.METADATA_JSON:"party-uuids") f
  WHERE d.ELEMENT_TYPE = 'responsible-parties'
    AND d.METADATA_JSON:"role-id"::STRING = 'information-owner'
)
SELECT i.SOURCE_RECORD_ID,
       i.PARTY_UUID,
       p.METADATA_JSON:name::STRING AS PARTY_NAME
FROM info_owner i
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT p
  ON p.METADATA_JSON:uuid::STRING = i.PARTY_UUID
WHERE p.ELEMENT_TYPE = 'parties'
ORDER BY i.SOURCE_RECORD_ID
LIMIT 25;
