-- READ ONLY: quick FISMA mapping diagnostic

-- 1) Does Archer actually have FISMA_REPORTABLE data?
SELECT COUNT(*) AS TOTAL_ROWS,
       COUNT_IF(CURATED_JSON:FISMA_REPORTABLE IS NOT NULL) AS POPULATED_ROWS
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW;

-- 2) Which SSP props actually exist in the target?
SELECT METADATA_JSON:name::STRING AS PROP_NAME, COUNT(*) AS ROW_COUNT
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
WHERE ELEMENT_TYPE = 'props'
GROUP BY 1
ORDER BY 1;
