-- READ ONLY
SELECT s.SOURCE_RECORD_ID, p.METADATA_JSON:name::STRING AS PROP_NAME, p.METADATA_JSON:value AS PROP_VALUE
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT s
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY f ON f.FK_SOURCE_ELEMENT_HASH = s.PK_OSCAL_SSP_ELEMENT_HASH
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT p ON p.PK_OSCAL_SSP_ELEMENT_HASH = f.FK_TARGET_ELEMENT_HASH
WHERE s.ELEMENT_TYPE = 'system-characteristics' AND p.ELEMENT_TYPE = 'props'
AND p.METADATA_JSON:name::STRING IN ('information-system-type','fisma-reportable','financial-system','mission-critical','critical-infrastructure','package-type','authorization-decision','pia-required')
ORDER BY s.SOURCE_RECORD_ID, PROP_NAME;
