-- SSP responsible-party UUID: end-to-end tester walkthrough
-- Date: 2026-09-30
-- READ ONLY.
--
-- Change only this Content ID. Use a record that has INFORMATION_OWNER_IO populated.
SET QA_CONTENT_ID = '2883408';

-- STEP 1: Start with the Archer user reference.
-- The stable source identity is UserList[].Id.
SELECT
    r.CONTENT_ID,
    u.VALUE:"Id"::NUMBER AS ARCHER_USER_ID,
    u.VALUE:"ResolvedUser":"LookupStatus"::STRING AS LOOKUP_STATUS,
    u.VALUE:"ResolvedUser":"FIRST_NAME"::STRING AS FIRST_NAME,
    u.VALUE:"ResolvedUser":"MIDDLE_NAME"::STRING AS MIDDLE_NAME,
    u.VALUE:"ResolvedUser":"LAST_NAME"::STRING AS LAST_NAME
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r,
     LATERAL FLATTEN(INPUT => r.CURATED_JSON:INFORMATION_OWNER_IO:"UserList") u
WHERE r.CONTENT_ID::STRING = $QA_CONTENT_ID;

-- STEP 2: Prove UserList[].Id resolves to ARCHER_META_USER.
SELECT
    r.CONTENT_ID,
    u.VALUE:"Id"::NUMBER AS ARCHER_USER_ID,
    mu.ARCHER_USER_ID AS META_USER_ID,
    mu.EEID,
    mu.FIRST_NAME,
    mu.MIDDLE_NAME,
    mu.LAST_NAME
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r,
     LATERAL FLATTEN(INPUT => r.CURATED_JSON:INFORMATION_OWNER_IO:"UserList") u
LEFT JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_META_USER mu
  ON mu.ARCHER_USER_ID = u.VALUE:"Id"::NUMBER
WHERE r.CONTENT_ID::STRING = $QA_CONTENT_ID;

-- STEP 3: Re-create the exact OSCAL party UUID.
-- Python mapper logic:
-- uuid.uuid5(uuid.NAMESPACE_URL, 'ARCHER|<CONTENT_ID>|party|<ARCHER_USER_ID>')
-- uuid.NAMESPACE_URL = 6ba7b811-9dad-11d1-80b4-00c04fd430c8
SELECT
    r.CONTENT_ID,
    u.VALUE:"Id"::NUMBER AS ARCHER_USER_ID,
    'ARCHER|' || r.CONTENT_ID::STRING || '|party|' || u.VALUE:"Id"::STRING AS UUID_SEED,
    UUID_STRING(
      '6ba7b811-9dad-11d1-80b4-00c04fd430c8',
      'ARCHER|' || r.CONTENT_ID::STRING || '|party|' || u.VALUE:"Id"::STRING
    ) AS EXPECTED_PARTY_UUID
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r,
     LATERAL FLATTEN(INPUT => r.CURATED_JSON:INFORMATION_OWNER_IO:"UserList") u
WHERE r.CONTENT_ID::STRING = $QA_CONTENT_ID;

-- STEP 4: See the UUID stored on OSCAL responsible-parties[].
SELECT
    rp.SOURCE_RECORD_ID,
    rp.METADATA_JSON:"role-id"::STRING AS ROLE_ID,
    f.VALUE::STRING AS ACTUAL_PARTY_UUID
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT rp,
     LATERAL FLATTEN(INPUT => rp.METADATA_JSON:"party-uuids") f
WHERE rp.SOURCE_RECORD_ID = $QA_CONTENT_ID
  AND rp.ELEMENT_TYPE = 'responsible-parties'
  AND rp.METADATA_JSON:"role-id"::STRING = 'information-owner';

-- STEP 5: Prove generated UUID = responsible-party UUID.
WITH source_user AS (
  SELECT
      r.CONTENT_ID::STRING AS SOURCE_RECORD_ID,
      u.VALUE:"Id"::NUMBER AS ARCHER_USER_ID,
      UUID_STRING(
        '6ba7b811-9dad-11d1-80b4-00c04fd430c8',
        'ARCHER|' || r.CONTENT_ID::STRING || '|party|' || u.VALUE:"Id"::STRING
      ) AS EXPECTED_PARTY_UUID
  FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r,
       LATERAL FLATTEN(INPUT => r.CURATED_JSON:INFORMATION_OWNER_IO:"UserList") u
  WHERE r.CONTENT_ID::STRING = $QA_CONTENT_ID
),
assignment AS (
  SELECT
      rp.SOURCE_RECORD_ID,
      f.VALUE::STRING AS ACTUAL_PARTY_UUID
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT rp,
       LATERAL FLATTEN(INPUT => rp.METADATA_JSON:"party-uuids") f
  WHERE rp.SOURCE_RECORD_ID = $QA_CONTENT_ID
    AND rp.ELEMENT_TYPE = 'responsible-parties'
    AND rp.METADATA_JSON:"role-id"::STRING = 'information-owner'
)
SELECT
    s.ARCHER_USER_ID,
    s.EXPECTED_PARTY_UUID,
    a.ACTUAL_PARTY_UUID,
    IFF(s.EXPECTED_PARTY_UUID = a.ACTUAL_PARTY_UUID, 'MATCH', 'MISMATCH') AS UUID_STATUS
FROM source_user s
LEFT JOIN assignment a
  ON a.SOURCE_RECORD_ID = s.SOURCE_RECORD_ID
 AND a.ACTUAL_PARTY_UUID = s.EXPECTED_PARTY_UUID;

-- STEP 6: Resolve responsible-party UUID to the OSCAL party/name.
WITH assignment AS (
  SELECT
      rp.SOURCE_RECORD_ID,
      rp.METADATA_JSON:"role-id"::STRING AS ROLE_ID,
      f.VALUE::STRING AS PARTY_UUID
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT rp,
       LATERAL FLATTEN(INPUT => rp.METADATA_JSON:"party-uuids") f
  WHERE rp.SOURCE_RECORD_ID = $QA_CONTENT_ID
    AND rp.ELEMENT_TYPE = 'responsible-parties'
    AND rp.METADATA_JSON:"role-id"::STRING = 'information-owner'
)
SELECT
    a.SOURCE_RECORD_ID,
    a.ROLE_ID,
    a.PARTY_UUID,
    p.OSCAL_UUID AS PARTY_NODE_OSCAL_UUID,
    p.METADATA_JSON:name::STRING AS PARTY_NAME
FROM assignment a
LEFT JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT p
  ON p.SOURCE_RECORD_ID = a.SOURCE_RECORD_ID
 AND p.ELEMENT_TYPE = 'parties'
 AND p.METADATA_JSON:uuid::STRING = a.PARTY_UUID;

-- STEP 7: Show the separate warehouse containment relationship.
-- FACT says metadata CONTAINS the party node.
-- It does NOT replace the OSCAL responsible-party.party-uuids -> parties.uuid reference.
SELECT
    m.SOURCE_RECORD_ID,
    m.PK_OSCAL_SSP_ELEMENT_HASH AS METADATA_DIM_KEY,
    f.DEPENDENCY_TYPE,
    p.PK_OSCAL_SSP_ELEMENT_HASH AS PARTY_DIM_KEY,
    p.OSCAL_UUID AS PARTY_OSCAL_UUID,
    p.METADATA_JSON:name::STRING AS PARTY_NAME
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT m
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY f
  ON f.FK_SOURCE_ELEMENT_HASH = m.PK_OSCAL_SSP_ELEMENT_HASH
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT p
  ON p.PK_OSCAL_SSP_ELEMENT_HASH = f.FK_TARGET_ELEMENT_HASH
WHERE m.SOURCE_RECORD_ID = $QA_CONTENT_ID
  AND m.ELEMENT_TYPE = 'metadata'
  AND p.ELEMENT_TYPE = 'parties';
