-- READ ONLY: inspect all Archer candidates for SSP integrity objective.
SELECT r.CONTENT_ID,
       r.CURATED_JSON:RECOMMENDED_INTEGRITY_CONTROL_CATEGORY AS ARCHER_INTEGRITY_RECOMMENDED,
       r.CURATED_JSON:INTEGRITY_CONTROL_CATEGORY_OVERRIDE AS ARCHER_INTEGRITY_OVERRIDE,
       r.CURATED_JSON:PROGRAMSITE_INTEGRITY_CONTROL_CATEGORY AS ARCHER_INTEGRITY_PROGRAMSITE,
       r.CURATED_JSON:CNSS_INTEGRITY_RATING AS ARCHER_INTEGRITY_CNSS,
       sil.METADATA_JSON:"security-objective-integrity"::STRING AS OSCAL_INTEGRITY
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT sil
  ON sil.SOURCE_RECORD_ID = r.CONTENT_ID::STRING
WHERE sil.ELEMENT_TYPE = 'security-impact-level'
ORDER BY r.CONTENT_ID
LIMIT 25;
