-- READ ONLY: quick check for system-characteristics props that are absent in target
SELECT
  COUNT_IF(CURATED_JSON:FISMA_REPORTABLE IS NOT NULL) AS FISMA_REPORTABLE_ROWS,
  COUNT_IF(CURATED_JSON:FINANCIAL_SYSTEM IS NOT NULL) AS FINANCIAL_SYSTEM_ROWS,
  COUNT_IF(CURATED_JSON:PIA_REQUIRED IS NOT NULL) AS PIA_REQUIRED_ROWS
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW;
