-- READ ONLY: distinguish retained JSON nulls from real values.
SELECT
  COUNT_IF(TYPEOF(CURATED_JSON:FISMA_REPORTABLE) = 'NULL_VALUE') AS FISMA_JSON_NULLS,
  COUNT_IF(TYPEOF(CURATED_JSON:FISMA_REPORTABLE) <> 'NULL_VALUE') AS FISMA_REAL_VALUES,
  COUNT_IF(TYPEOF(CURATED_JSON:FINANCIAL_SYSTEM) = 'NULL_VALUE') AS FINANCIAL_JSON_NULLS,
  COUNT_IF(TYPEOF(CURATED_JSON:FINANCIAL_SYSTEM) <> 'NULL_VALUE') AS FINANCIAL_REAL_VALUES,
  COUNT_IF(TYPEOF(CURATED_JSON:PIA_REQUIRED) = 'NULL_VALUE') AS PIA_JSON_NULLS,
  COUNT_IF(TYPEOF(CURATED_JSON:PIA_REQUIRED) <> 'NULL_VALUE') AS PIA_REAL_VALUES
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW;

-- Show the actual populated values, if any.
SELECT CONTENT_ID,
       CURATED_JSON:FISMA_REPORTABLE AS FISMA_REPORTABLE,
       CURATED_JSON:FINANCIAL_SYSTEM AS FINANCIAL_SYSTEM,
       CURATED_JSON:PIA_REQUIRED AS PIA_REQUIRED
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
WHERE TYPEOF(CURATED_JSON:FISMA_REPORTABLE) <> 'NULL_VALUE'
   OR TYPEOF(CURATED_JSON:FINANCIAL_SYSTEM) <> 'NULL_VALUE'
   OR TYPEOF(CURATED_JSON:PIA_REQUIRED) <> 'NULL_VALUE'
LIMIT 25;
