-- Simple SSP metadata props[] collection query
SELECT m.SOURCE_RECORD_ID, c.OSCAL_UUID, c.METADATA_JSON
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT m
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY f
  ON f.FK_SOURCE_ELEMENT_HASH = m.PK_OSCAL_SSP_ELEMENT_HASH
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT c
  ON c.PK_OSCAL_SSP_ELEMENT_HASH = f.FK_TARGET_ELEMENT_HASH
WHERE m.ELEMENT_TYPE = 'metadata'
  AND c.ELEMENT_TYPE = 'props';
