-- SSP metadata branch -> deepest descendant
-- Date: 2026-09-30
-- READ ONLY.
--
-- Purpose:
--   Start at the SSP metadata node and follow DIM -> FACT -> DIM recursively
--   through every child until the last/leaf level.
--
-- Change only this Content ID / SOURCE_RECORD_ID.
SET QA_CONTENT_ID = '565189';

WITH RECURSIVE METADATA_TREE
(
    DEPTH,
    SOURCE_RECORD_ID,
    NODE_KEY,
    PARENT_NODE_KEY,
    ELEMENT_TYPE,
    OSCAL_UUID,
    PARENT_ELEMENT_TYPE,
    DEPENDENCY_TYPE,
    STRUCTURAL_PATH,
    METADATA_JSON
) AS
(
    -- Start directly at metadata.
    SELECT
        0 AS DEPTH,
        D.SOURCE_RECORD_ID,
        D.PK_OSCAL_SSP_ELEMENT_HASH AS NODE_KEY,
        CAST(NULL AS BINARY(16)) AS PARENT_NODE_KEY,
        D.ELEMENT_TYPE,
        D.OSCAL_UUID,
        CAST(NULL AS VARCHAR) AS PARENT_ELEMENT_TYPE,
        CAST(NULL AS VARCHAR) AS DEPENDENCY_TYPE,
        CAST(D.ELEMENT_TYPE AS VARCHAR(5000)) AS STRUCTURAL_PATH,
        D.METADATA_JSON
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT D
    WHERE D.SOURCE_SYSTEM_NAME = 'ARCHER'
      AND D.SOURCE_TABLE_NAME = 'ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
      AND TRIM(D.SOURCE_RECORD_ID::STRING) = $QA_CONTENT_ID
      AND D.ELEMENT_TYPE = 'metadata'

    UNION ALL

    -- Parent DIM -> FACT -> child DIM.
    SELECT
        T.DEPTH + 1,
        C.SOURCE_RECORD_ID,
        C.PK_OSCAL_SSP_ELEMENT_HASH AS NODE_KEY,
        T.NODE_KEY AS PARENT_NODE_KEY,
        C.ELEMENT_TYPE,
        C.OSCAL_UUID,
        T.ELEMENT_TYPE AS PARENT_ELEMENT_TYPE,
        F.DEPENDENCY_TYPE,
        CAST(T.STRUCTURAL_PATH || ' > ' || C.ELEMENT_TYPE AS VARCHAR(5000)),
        C.METADATA_JSON
    FROM METADATA_TREE T
    JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY F
      ON F.FK_SOURCE_ELEMENT_HASH = T.NODE_KEY
    JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT C
      ON C.PK_OSCAL_SSP_ELEMENT_HASH = F.FK_TARGET_ELEMENT_HASH
    WHERE C.SOURCE_RECORD_ID = T.SOURCE_RECORD_ID
      AND T.DEPTH < 50
),

CHILD_COUNTS AS
(
    SELECT
        F.FK_SOURCE_ELEMENT_HASH AS NODE_KEY,
        COUNT(*) AS CHILD_COUNT
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY F
    GROUP BY F.FK_SOURCE_ELEMENT_HASH
)

SELECT
    T.DEPTH,
    CASE
        WHEN T.DEPTH = 0 THEN 'METADATA_ROOT'
        WHEN COALESCE(CC.CHILD_COUNT, 0) = 0 THEN 'LEAF'
        ELSE 'BRANCH'
    END AS NODE_POSITION,

    T.SOURCE_RECORD_ID,

    T.PARENT_ELEMENT_TYPE,
    T.DEPENDENCY_TYPE,

    T.ELEMENT_TYPE,
    T.OSCAL_UUID,

    COALESCE(CC.CHILD_COUNT, 0) AS CHILD_COUNT,

    T.STRUCTURAL_PATH,
    T.METADATA_JSON

FROM METADATA_TREE T
LEFT JOIN CHILD_COUNTS CC
  ON CC.NODE_KEY = T.NODE_KEY

ORDER BY
    T.DEPTH,
    T.STRUCTURAL_PATH,
    T.OSCAL_UUID;
