-- SSP System Characteristics security-impact / FIPS-199 end-to-end validation
-- Date: 2026-09-30
-- READ ONLY.
--
-- Query 1 validates the 11 ACTIVE Archer candidate fields that target the
-- three OSCAL security-impact-level security objectives.

WITH source_values AS (
    SELECT CONTENT_ID::STRING AS SOURCE_RECORD_ID,
           'RECOMMENDED_CONFIDENTIALITY_CONTROL_CATEGORY' AS SOURCE_FIELD,
           'confidentiality' AS OBJECTIVE,
           CURATED_JSON:RECOMMENDED_CONFIDENTIALITY_CONTROL_CATEGORY AS RAW_VALUE
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    UNION ALL
    SELECT CONTENT_ID::STRING, 'CONFIDENTIALITY_CONTROL_CATEGORY_OVERRIDE', 'confidentiality',
           CURATED_JSON:CONFIDENTIALITY_CONTROL_CATEGORY_OVERRIDE
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    UNION ALL
    SELECT CONTENT_ID::STRING, 'CNSS_CONFIDENTIALITY_RATING', 'confidentiality',
           CURATED_JSON:CNSS_CONFIDENTIALITY_RATING
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    UNION ALL
    SELECT CONTENT_ID::STRING, 'RECOMMENDED_INTEGRITY_CONTROL_CATEGORY', 'integrity',
           CURATED_JSON:RECOMMENDED_INTEGRITY_CONTROL_CATEGORY
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    UNION ALL
    SELECT CONTENT_ID::STRING, 'INTEGRITY_CONTROL_CATEGORY_OVERRIDE', 'integrity',
           CURATED_JSON:INTEGRITY_CONTROL_CATEGORY_OVERRIDE
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    UNION ALL
    SELECT CONTENT_ID::STRING, 'PROGRAMSITE_INTEGRITY_CONTROL_CATEGORY', 'integrity',
           CURATED_JSON:PROGRAMSITE_INTEGRITY_CONTROL_CATEGORY
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    UNION ALL
    SELECT CONTENT_ID::STRING, 'CNSS_INTEGRITY_RATING', 'integrity',
           CURATED_JSON:CNSS_INTEGRITY_RATING
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    UNION ALL
    SELECT CONTENT_ID::STRING, 'AVAILABILITY_CONTROL_CATEGORY_OVERRIDE', 'availability',
           CURATED_JSON:AVAILABILITY_CONTROL_CATEGORY_OVERRIDE
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    UNION ALL
    SELECT CONTENT_ID::STRING, 'RECOMMENDED_AVAILABILITY_CONTROL_CATEGORY', 'availability',
           CURATED_JSON:RECOMMENDED_AVAILABILITY_CONTROL_CATEGORY
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    UNION ALL
    SELECT CONTENT_ID::STRING, 'PROGRAMSITE_AVAILABILITY_CONTROL_CATEGORY', 'availability',
           CURATED_JSON:PROGRAMSITE_AVAILABILITY_CONTROL_CATEGORY
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
    UNION ALL
    SELECT CONTENT_ID::STRING, 'CNSS_AVAILABILITY_RATING', 'availability',
           CURATED_JSON:CNSS_AVAILABILITY_RATING
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
),
resolved AS (
    SELECT s.*,
           COALESCE(
             TRY_TO_NUMBER(s.RAW_VALUE:"ValuesListIds"[0]::STRING),
             TRY_TO_NUMBER(s.RAW_VALUE:"ValueListIds"[0]::STRING)
           ) AS ARCHER_SELECT_ID,
           COALESCE(
             mv.SELECT_VALUE_NAME,
             IFF(TYPEOF(s.RAW_VALUE) = 'VARCHAR', s.RAW_VALUE::STRING, NULL)
           ) AS ARCHER_RESOLVED_LABEL
    FROM source_values s
    LEFT JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_META_VALUE mv
      ON mv.SELECT_VALUE_ID = COALESCE(
           TRY_TO_NUMBER(s.RAW_VALUE:"ValuesListIds"[0]::STRING),
           TRY_TO_NUMBER(s.RAW_VALUE:"ValueListIds"[0]::STRING)
         )
    WHERE s.RAW_VALUE IS NOT NULL
      AND NOT IS_NULL_VALUE(s.RAW_VALUE)
),
transformed AS (
    SELECT r.*,
           CASE
             WHEN LOWER(TRIM(ARCHER_RESOLVED_LABEL)) IN ('low','moderate','high')
               THEN LOWER(TRIM(ARCHER_RESOLVED_LABEL))
             WHEN ARCHER_RESOLVED_LABEL IN (
               'Legacy LOE A','Legacy LOE A + DFARS',
               'Legacy LOE B','Legacy LOE B + DFARS',
               'Legacy LOE C','Legacy LOE C + DFARS',
               'Legacy LOE D','Legacy LOE D + DFARS'
             )
               THEN ARCHER_RESOLVED_LABEL
           END AS EXPECTED_OSCAL_VALUE
    FROM resolved r
),
compared AS (
    SELECT t.*,
           CASE t.OBJECTIVE
             WHEN 'confidentiality' THEN sil.METADATA_JSON:"security-objective-confidentiality"::STRING
             WHEN 'integrity' THEN sil.METADATA_JSON:"security-objective-integrity"::STRING
             WHEN 'availability' THEN sil.METADATA_JSON:"security-objective-availability"::STRING
           END AS ACTUAL_OSCAL_VALUE,
           COUNT(DISTINCT t.EXPECTED_OSCAL_VALUE)
             OVER (PARTITION BY t.SOURCE_RECORD_ID, t.OBJECTIVE) AS DISTINCT_CANDIDATE_VALUES
    FROM transformed t
    LEFT JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT sil
      ON sil.SOURCE_RECORD_ID = t.SOURCE_RECORD_ID
     AND sil.ELEMENT_TYPE = 'security-impact-level'
)
SELECT SOURCE_RECORD_ID,
       SOURCE_FIELD,
       OBJECTIVE,
       ARCHER_SELECT_ID,
       ARCHER_RESOLVED_LABEL,
       EXPECTED_OSCAL_VALUE,
       ACTUAL_OSCAL_VALUE,
       DISTINCT_CANDIDATE_VALUES,
       CASE
         WHEN EXPECTED_OSCAL_VALUE IS NULL THEN 'UNRESOLVED_OR_UNAPPROVED_SOURCE_LABEL'
         WHEN DISTINCT_CANDIDATE_VALUES > 1 THEN 'CONFLICTING_SOURCE_CANDIDATES'
         WHEN ACTUAL_OSCAL_VALUE IS NULL THEN 'MISSING_TARGET'
         WHEN EXPECTED_OSCAL_VALUE = ACTUAL_OSCAL_VALUE THEN 'MATCH'
         ELSE 'MISMATCH'
       END AS VALIDATION_STATUS
FROM compared
ORDER BY SOURCE_RECORD_ID, OBJECTIVE, SOURCE_FIELD;

-- Query 2: SECURITY_CATEGORY is one of the 13 historical rows, but it is NOT
-- a confidentiality/integrity/availability objective. It maps directly to
-- system-characteristics.security-sensitivity-level.
SELECT r.CONTENT_ID,
       r.CURATED_JSON:SECURITY_CATEGORY::STRING AS ARCHER_SECURITY_CATEGORY,
       sc.METADATA_JSON:"security-sensitivity-level"::STRING AS OSCAL_SECURITY_SENSITIVITY_LEVEL
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT sc
  ON sc.SOURCE_RECORD_ID = r.CONTENT_ID::STRING
 AND sc.ELEMENT_TYPE = 'system-characteristics'
WHERE r.CURATED_JSON:SECURITY_CATEGORY IS NOT NULL
ORDER BY r.CONTENT_ID
LIMIT 25;

-- Query 3: FULL_CONTROL_ASSESSMENT_HELPER is the other historical row.
-- It is EXCLUDED from executable OSCAL security-impact mapping.
-- This only profiles the source values; no OSCAL target is expected.
SELECT r.CURATED_JSON:FULL_CONTROL_ASSESSMENT_HELPER::STRING AS SOURCE_VALUE,
       COUNT(*) AS ROWS
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r
WHERE r.CURATED_JSON:FULL_CONTROL_ASSESSMENT_HELPER IS NOT NULL
GROUP BY 1
ORDER BY 2 DESC;
