-- READ ONLY: verify TRACKING_ID -> metadata.document-ids[].identifier.
SELECT r.CONTENT_ID,
       r.CURATED_JSON:TRACKING_ID::STRING AS ARCHER_TRACKING_ID,
       d.METADATA_JSON:identifier::STRING AS OSCAL_DOCUMENT_ID
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT d
  ON d.SOURCE_RECORD_ID = r.CONTENT_ID::STRING
WHERE d.ELEMENT_TYPE = 'document-ids'
ORDER BY r.CONTENT_ID
LIMIT 25;
