-- READ ONLY: show System Characteristics props and their Archer-style field names.
SELECT s.SOURCE_RECORD_ID,
       UPPER(REPLACE(p.METADATA_JSON:name::STRING,'-','_')) AS ARCHER_FIELD_NAME,
       p.METADATA_JSON:name::STRING AS OSCAL_PROP_NAME,
       p.METADATA_JSON:value AS OSCAL_PROP_VALUE
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT s
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY f
  ON f.FK_SOURCE_ELEMENT_HASH = s.PK_OSCAL_SSP_ELEMENT_HASH
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT p
  ON p.PK_OSCAL_SSP_ELEMENT_HASH = f.FK_TARGET_ELEMENT_HASH
WHERE s.ELEMENT_TYPE = 'system-characteristics'
  AND p.ELEMENT_TYPE = 'props'
ORDER BY s.SOURCE_RECORD_ID, OSCAL_PROP_NAME;
