-- READ ONLY: verify INFORMATION_OWNER_IO -> metadata responsible-parties.
SELECT r.CONTENT_ID,
       r.CURATED_JSON:INFORMATION_OWNER_IO AS ARCHER_INFORMATION_OWNER,
       rp.METADATA_JSON:"role-id"::STRING AS OSCAL_ROLE_ID,
       rp.METADATA_JSON:"party-uuids" AS OSCAL_PARTY_UUIDS
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT rp
  ON rp.SOURCE_RECORD_ID = r.CONTENT_ID::STRING
WHERE rp.ELEMENT_TYPE = 'responsible-parties'
  AND rp.METADATA_JSON:"role-id"::STRING = 'information-owner'
ORDER BY r.CONTENT_ID
LIMIT 25;
