-- READ ONLY: inspect the System Characteristics security-impact-level node.
SELECT r.CONTENT_ID,
       r.CURATED_JSON:RECOMMENDED_CONFIDENTIALITY_CONTROL_CATEGORY AS ARCHER_CONF_RECOMMENDED,
       r.CURATED_JSON:CONFIDENTIALITY_CONTROL_CATEGORY_OVERRIDE AS ARCHER_CONF_OVERRIDE,
       r.CURATED_JSON:CNSS_CONFIDENTIALITY_RATING AS ARCHER_CONF_CNSS,
       sil.METADATA_JSON:"security-objective-confidentiality"::STRING AS OSCAL_CONFIDENTIALITY
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT sil
  ON sil.SOURCE_RECORD_ID = r.CONTENT_ID::STRING
WHERE sil.ELEMENT_TYPE = 'security-impact-level'
ORDER BY r.CONTENT_ID
LIMIT 25;
