-- READ ONLY: pause here and see how Archer UserList[].Id becomes the OSCAL party UUID.
-- Change only this Content ID. Use a record where AUTHORIZING_OFFICIAL_AO has a UserList member.
SET QA_CONTENT_ID = '2883408';

WITH src AS (
  SELECT r.CONTENT_ID::STRING AS SOURCE_RECORD_ID,
         u.VALUE:"Id"::STRING AS ARCHER_USER_ID,
         UUID_STRING(
           '6ba7b811-9dad-11d1-80b4-00c04fd430c8',
           'ARCHER|' || r.CONTENT_ID::STRING || '|party|' || u.VALUE:"Id"::STRING
         ) AS EXPECTED_PARTY_UUID
  FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r,
       LATERAL FLATTEN(INPUT => r.CURATED_JSON:AUTHORIZING_OFFICIAL_AO:"UserList") u
  WHERE r.CONTENT_ID::STRING = $QA_CONTENT_ID
)
SELECT s.SOURCE_RECORD_ID,
       s.ARCHER_USER_ID,
       s.EXPECTED_PARTY_UUID,
       p.OSCAL_UUID AS ACTUAL_PARTY_UUID,
       p.METADATA_JSON:name::STRING AS PARTY_NAME
FROM src s
LEFT JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT p
  ON p.SOURCE_RECORD_ID = s.SOURCE_RECORD_ID
 AND p.ELEMENT_TYPE = 'parties'
 AND p.OSCAL_UUID = s.EXPECTED_PARTY_UUID;
