-- OSCAL resolution playground
-- Date: 2026-09-30
-- READ ONLY.

-- A. Archer select ID -> ARCHER_META_VALUE label.
SELECT r.CONTENT_ID,
       r.CURATED_JSON:INTEGRITY_CONTROL_CATEGORY_OVERRIDE:"ValuesListIds"[0]::NUMBER AS SELECT_ID,
       mv.SELECT_VALUE_NAME AS RESOLVED_LABEL
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r
LEFT JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_META_VALUE mv
  ON mv.SELECT_VALUE_ID = r.CURATED_JSON:INTEGRITY_CONTROL_CATEGORY_OVERRIDE:"ValuesListIds"[0]::NUMBER
WHERE r.CURATED_JSON:INTEGRITY_CONTROL_CATEGORY_OVERRIDE IS NOT NULL
LIMIT 25;

-- B. Archer UserList Id -> Meta User -> ResolvedUser.
SELECT r.CONTENT_ID,
       u.VALUE:"Id"::NUMBER AS ARCHER_USER_ID,
       mu.ARCHER_USER_ID AS META_USER_ID,
       u.VALUE:"ResolvedUser":"LookupStatus"::STRING AS LOOKUP_STATUS,
       u.VALUE:"ResolvedUser":"FIRST_NAME"::STRING AS RESOLVED_FIRST_NAME,
       u.VALUE:"ResolvedUser":"LAST_NAME"::STRING AS RESOLVED_LAST_NAME
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r,
     LATERAL FLATTEN(INPUT => r.CURATED_JSON:INFORMATION_OWNER_IO:"UserList") u
LEFT JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_META_USER mu
  ON mu.ARCHER_USER_ID = u.VALUE:"Id"::NUMBER
LIMIT 25;

-- C. OSCAL responsible-party UUID -> party UUID -> party name.
WITH rp AS (
  SELECT d.SOURCE_RECORD_ID,
         d.METADATA_JSON:"role-id"::STRING AS ROLE_ID,
         f.VALUE::STRING AS PARTY_UUID
  FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT d,
       LATERAL FLATTEN(INPUT => d.METADATA_JSON:"party-uuids") f
  WHERE d.ELEMENT_TYPE = 'responsible-parties'
)
SELECT rp.SOURCE_RECORD_ID,
       rp.ROLE_ID,
       rp.PARTY_UUID,
       p.METADATA_JSON:name::STRING AS PARTY_NAME
FROM rp
LEFT JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT p
  ON p.METADATA_JSON:uuid::STRING = rp.PARTY_UUID
 AND p.ELEMENT_TYPE = 'parties'
ORDER BY rp.SOURCE_RECORD_ID, rp.ROLE_ID
LIMIT 25;
