-- READ ONLY: verify SAP_ID -> system-characteristics.system-ids[].id.
SELECT r.CONTENT_ID,
       r.CURATED_JSON:SAP_ID::STRING AS ARCHER_SAP_ID,
       sid.METADATA_JSON:id::STRING AS OSCAL_SYSTEM_ID
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT sid
  ON sid.SOURCE_RECORD_ID = r.CONTENT_ID::STRING
WHERE sid.ELEMENT_TYPE = 'system-ids'
ORDER BY r.CONTENT_ID
LIMIT 25;
