-- READ ONLY: resolve Archer confidentiality override select ID and compare to OSCAL.
SELECT
    r.CONTENT_ID,
    r.CURATED_JSON:CONFIDENTIALITY_CONTROL_CATEGORY_OVERRIDE:"ValuesListIds"[0]::NUMBER AS ARCHER_SELECT_ID,
    mv.SELECT_VALUE_NAME AS ARCHER_RESOLVED_VALUE,
    sil.METADATA_JSON:"security-objective-confidentiality"::STRING AS OSCAL_CONFIDENTIALITY
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT sil
  ON sil.SOURCE_RECORD_ID = r.CONTENT_ID::STRING
LEFT JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_META_VALUE mv
  ON mv.SELECT_VALUE_ID = r.CURATED_JSON:CONFIDENTIALITY_CONTROL_CATEGORY_OVERRIDE:"ValuesListIds"[0]::NUMBER
WHERE sil.ELEMENT_TYPE = 'security-impact-level'
  AND r.CURATED_JSON:CONFIDENTIALITY_CONTROL_CATEGORY_OVERRIDE IS NOT NULL
ORDER BY r.CONTENT_ID
LIMIT 25;
