-- READ ONLY: verify information-owner responsible-party UUID resolves to a party node.
SELECT rp.SOURCE_RECORD_ID,
       rp.METADATA_JSON:"role-id"::STRING AS ROLE_ID,
       pu.VALUE::STRING AS PARTY_UUID,
       p.METADATA_JSON:name::STRING AS PARTY_NAME
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT rp,
     LATERAL FLATTEN(INPUT => rp.METADATA_JSON:"party-uuids") pu,
     RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT p
WHERE rp.ELEMENT_TYPE = 'responsible-parties'
  AND rp.METADATA_JSON:"role-id"::STRING = 'information-owner'
  AND p.SOURCE_RECORD_ID = rp.SOURCE_RECORD_ID
  AND p.ELEMENT_TYPE = 'parties'
  AND p.METADATA_JSON:uuid::STRING = pu.VALUE::STRING
ORDER BY rp.SOURCE_RECORD_ID
LIMIT 25;
