-- READ ONLY: first System Characteristics source-to-target check.
SELECT
    r.CONTENT_ID,
    r.CURATED_JSON:AUTHORIZATION_PACKAGE_NAME::STRING AS ARCHER_SYSTEM_NAME,
    s.METADATA_JSON:"system-name"::STRING AS OSCAL_SYSTEM_NAME,
    r.CURATED_JSON:ACRONYM::STRING AS ARCHER_ACRONYM,
    s.METADATA_JSON:"system-name-short"::STRING AS OSCAL_ACRONYM,
    r.CURATED_JSON:MISSION_PURPOSE::STRING AS ARCHER_MISSION_PURPOSE,
    s.METADATA_JSON:description::STRING AS OSCAL_DESCRIPTION,
    r.CURATED_JSON:AUTHORIZATION_BOUNDARY_DESCRIPTION::STRING AS ARCHER_BOUNDARY,
    s.METADATA_JSON:"authorization-boundary":"description"::STRING AS OSCAL_BOUNDARY,
    r.CURATED_JSON:ATOIATO_DATE AS ARCHER_ATO_DATE,
    s.METADATA_JSON:"date-authorized" AS OSCAL_ATO_DATE,
    r.CURATED_JSON:SECURITY_CATEGORY AS ARCHER_SECURITY_CATEGORY,
    s.METADATA_JSON:"security-sensitivity-level" AS OSCAL_SECURITY_CATEGORY
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT s
  ON s.SOURCE_RECORD_ID = r.CONTENT_ID::STRING
WHERE s.ELEMENT_TYPE = 'system-characteristics'
ORDER BY r.CONTENT_ID
LIMIT 25;
