-- READ ONLY: compare Archer FISMA_REPORTABLE to the OSCAL system-characteristics prop.
SELECT r.CONTENT_ID,
       r.CURATED_JSON:FISMA_REPORTABLE AS ARCHER_FISMA_REPORTABLE,
       p.METADATA_JSON:name::STRING AS OSCAL_PROP_NAME,
       p.METADATA_JSON:value AS OSCAL_PROP_VALUE
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT p
  ON p.SOURCE_RECORD_ID = r.CONTENT_ID::STRING
WHERE p.ELEMENT_TYPE = 'props'
  AND p.METADATA_JSON:name::STRING = 'fisma-reportable';
