-- SSP ROOT -> BRANCH -> LEAF GRAPH WALK
-- Date: 2026-09-25
-- READ ONLY. No DML.
--
-- Give this query one Authorization Package CONTENT_ID / SOURCE_RECORD_ID.
-- It walks the committed SSP graph from the system-security-plan root down
-- through every FACT parent->child edge and shows the complete tree.
--
-- DIM = node
-- FACT.FK_SOURCE_ELEMENT_HASH = parent DIM PK
-- FACT.FK_TARGET_ELEMENT_HASH = child DIM PK
--
-- Change only this value.
SET QA_CONTENT_ID = '565189';

WITH RECURSIVE

NODES AS
(
    SELECT
        PK_OSCAL_SSP_ELEMENT_HASH AS NODE_KEY,
        TRIM(SOURCE_RECORD_ID::STRING) AS SOURCE_RECORD_ID,
        ELEMENT_TYPE,
        OSCAL_UUID,
        METADATA_JSON
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
    WHERE SOURCE_SYSTEM_NAME = 'ARCHER'
      AND SOURCE_TABLE_NAME = 'ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
      AND TRIM(SOURCE_RECORD_ID::STRING) = $QA_CONTENT_ID
),

EDGES AS
(
    SELECT
        FK_SOURCE_ELEMENT_HASH AS PARENT_NODE_KEY,
        FK_TARGET_ELEMENT_HASH AS CHILD_NODE_KEY,
        DEPENDENCY_TYPE
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY
),

OUT_DEGREE AS
(
    SELECT
        PARENT_NODE_KEY,
        COUNT(*) AS CHILD_COUNT
    FROM EDGES
    GROUP BY PARENT_NODE_KEY
),

TREE
(
    DEPTH,
    SOURCE_RECORD_ID,
    NODE_KEY,
    PARENT_NODE_KEY,
    ELEMENT_TYPE,
    OSCAL_UUID,
    PARENT_ELEMENT_TYPE,
    PARENT_OSCAL_UUID,
    DEPENDENCY_TYPE,
    STRUCTURAL_PATH,
    METADATA_JSON
) AS
(
    -- Anchor row: exactly one SSP root for this CONTENT_ID.
    SELECT
        0 AS DEPTH,
        N.SOURCE_RECORD_ID,
        N.NODE_KEY,
        CAST(NULL AS BINARY(16)) AS PARENT_NODE_KEY,
        N.ELEMENT_TYPE,
        N.OSCAL_UUID,
        CAST(NULL AS VARCHAR) AS PARENT_ELEMENT_TYPE,
        CAST(NULL AS VARCHAR) AS PARENT_OSCAL_UUID,
        CAST(NULL AS VARCHAR) AS DEPENDENCY_TYPE,
        CAST(N.ELEMENT_TYPE AS VARCHAR(5000)) AS STRUCTURAL_PATH,
        N.METADATA_JSON
    FROM NODES N
    WHERE N.ELEMENT_TYPE = 'system-security-plan'

    UNION ALL

    -- Recursive step:
    -- current TREE node = parent
    -- FACT finds its outgoing child edge
    -- DIM resolves the child node
    SELECT
        T.DEPTH + 1,
        C.SOURCE_RECORD_ID,
        C.NODE_KEY,
        E.PARENT_NODE_KEY,
        C.ELEMENT_TYPE,
        C.OSCAL_UUID,
        P.ELEMENT_TYPE AS PARENT_ELEMENT_TYPE,
        P.OSCAL_UUID AS PARENT_OSCAL_UUID,
        E.DEPENDENCY_TYPE,
        CAST(T.STRUCTURAL_PATH || ' > ' || C.ELEMENT_TYPE AS VARCHAR(5000)),
        C.METADATA_JSON
    FROM TREE T
    JOIN EDGES E
      ON E.PARENT_NODE_KEY = T.NODE_KEY
    JOIN NODES C
      ON C.NODE_KEY = E.CHILD_NODE_KEY
    JOIN NODES P
      ON P.NODE_KEY = E.PARENT_NODE_KEY
    WHERE T.DEPTH < 50
)

SELECT
    T.DEPTH,
    CASE
        WHEN T.DEPTH = 0 THEN 'ROOT'
        WHEN COALESCE(O.CHILD_COUNT,0) = 0 THEN 'LEAF'
        ELSE 'BRANCH'
    END AS NODE_POSITION,

    T.SOURCE_RECORD_ID,

    T.PARENT_ELEMENT_TYPE,
    T.PARENT_OSCAL_UUID,

    T.DEPENDENCY_TYPE,

    T.ELEMENT_TYPE AS CHILD_ELEMENT_TYPE,
    T.OSCAL_UUID AS CHILD_OSCAL_UUID,

    COALESCE(O.CHILD_COUNT,0) AS CHILD_COUNT,

    T.STRUCTURAL_PATH,

    T.METADATA_JSON

FROM TREE T
LEFT JOIN OUT_DEGREE O
  ON O.PARENT_NODE_KEY = T.NODE_KEY

ORDER BY
    T.DEPTH,
    T.STRUCTURAL_PATH,
    T.OSCAL_UUID;
