-- READ ONLY
SELECT r.CONTENT_ID,
       r.CURATED_JSON:OPERATIONAL_STATUS AS ARCHER_OPERATIONAL_STATUS,
       s.METADATA_JSON:status:state::STRING AS OSCAL_STATUS_STATE,
       r.CURATED_JSON:AUTHORIZATION_COMMENTS::STRING AS ARCHER_AUTHORIZATION_COMMENTS,
       s.METADATA_JSON:status:remarks::STRING AS OSCAL_STATUS_REMARKS
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT s
  ON s.SOURCE_RECORD_ID = r.CONTENT_ID::STRING
WHERE s.ELEMENT_TYPE = 'system-characteristics'
ORDER BY r.CONTENT_ID
LIMIT 25;
