-- READ ONLY: System Characteristics status is stored as its own DIM node.
SELECT r.CONTENT_ID,
       r.CURATED_JSON:OPERATIONAL_STATUS AS ARCHER_OPERATIONAL_STATUS,
       st.METADATA_JSON:state::STRING AS OSCAL_STATUS_STATE,
       r.CURATED_JSON:AUTHORIZATION_COMMENTS::STRING AS ARCHER_AUTHORIZATION_COMMENTS,
       st.METADATA_JSON:remarks::STRING AS OSCAL_STATUS_REMARKS
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT st
  ON st.SOURCE_RECORD_ID = r.CONTENT_ID::STRING
WHERE st.ELEMENT_TYPE = 'status'
ORDER BY r.CONTENT_ID
LIMIT 25;
