-- READ ONLY: verify the source value that supplies SSP metadata.title.
SELECT r.CONTENT_ID,
       r.CURATED_JSON:AUTHORIZATION_PACKAGE_NAME::STRING AS ARCHER_AUTHORIZATION_PACKAGE_NAME,
       m.METADATA_JSON:title::STRING AS OSCAL_METADATA_TITLE,
       m.METADATA_JSON:published AS OSCAL_PUBLISHED,
       m.METADATA_JSON:"last-modified" AS OSCAL_LAST_MODIFIED,
       m.METADATA_JSON:version::STRING AS OSCAL_DOCUMENT_VERSION,
       m.METADATA_JSON:"oscal-version"::STRING AS OSCAL_VERSION
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW r
JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT m
  ON m.SOURCE_RECORD_ID = r.CONTENT_ID::STRING
WHERE m.ELEMENT_TYPE = 'metadata'
ORDER BY r.CONTENT_ID
LIMIT 25;
