"""Business-output acceptance through fresh Cell 1/3/4/5/6 definitions.

Expected SSP fingerprint and AR oracle predate the lean rebuild. Their source
fixtures are unchanged; no expected output is generated by the new mapper.
"""
import copy
import hashlib
import json
import runpy
import unittest

from lean_support import Frame, build, business, namespace
import test_multi_model_graph as frozen
from test_registry_release import mapping_rows, release_registry, SUPPORT
from test_flat_mapping_release import SSP_GRAPH_DIGEST


class LeanAcceptanceTests(unittest.TestCase):
    def setUp(self):
        self.ns = namespace()

    def compile(self, rows=None, registry=None, models=("SSP",), config=None):
        profile = copy.deepcopy(self.ns["SOURCE_PROFILES"][0])
        profile["MODEL_KEYS"] = models
        profile["BASE_CONFIG"].update(config or {})
        contexts = self.ns["compile_mapping_contexts"](
            {profile["SOURCE_KEY"]: mapping_rows() if rows is None else rows},
            release_registry() if registry is None else registry,
            [profile], self.ns["MODEL_CONTRACTS"], self.ns["ROUTING_METADATA"])
        for context in contexts:
            self.assertEqual("READY", context["routing_report"]["STATUS"], context["routing_report"])
        return contexts

    def ssp(self, registry_edit=None):
        old, records, registry, lookups = frozen.ssp_fixture(frozen.namespace(legacy=True))
        fields = {row["SOURCE_FIELD_NAME"] for row in old["mapping_rows"]}
        rows = [row for row in mapping_rows() if row["EXECUTION_STATUS"] == "APPROVED"
                and (row["SOURCE_FIELD_NAME"] in fields or row["RULE_ID"] in SUPPORT)]
        registry = release_registry(registry.rows)
        if registry_edit:
            registry_edit(registry)
        context = self.compile(rows, registry, config=old["config"])[0]
        context["lookups"] = copy.deepcopy(old["lookups"])
        # Hydration transport is tested separately; freeze its accepted payload here.
        self.ns["_build_component_hydration_lookups"] = lambda *args: lookups
        return context, records

    def test_ssp_exact_pre_rebuild_business_fingerprint(self):
        context, records = self.ssp()
        original = copy.deepcopy(records)
        nodes, edges = build(self.ns, context, records)
        self.assertEqual((20, 19), (len(nodes.rows), len(edges.rows)))
        serialized = json.dumps([business(nodes), business(edges)], sort_keys=True)
        self.assertEqual(SSP_GRAPH_DIGEST, hashlib.sha256(serialized.encode()).hexdigest())
        self.assertEqual(original, records)
        expected_parents = {row["NODE_PATH"]: row["PARENT_NODE_PATH"] for row in context["registry_rows"]}
        for node in nodes.rows:
            self.assertEqual(expected_parents[node["ELEMENT_PATH"]], node["PARENT_NODE_PATH"])
        self.ns["_load_graph"](nodes, edges, context["config"])

    def test_ar17_matches_existing_standalone_oracle_including_decimal_and_zero(self):
        old_ns = frozen.namespace(legacy=True)
        old = frozen.ar_context(old_ns)
        fields = tuple(row["SOURCE_FIELD_NAME"] for row in old["mapping_rows"])
        records = [
            {"SOURCE_RECORD_ID": "100", "CURATED_JSON": json.dumps({field: n + 1 for n, field in enumerate(fields)})},
            {"SOURCE_RECORD_ID": "101", "CURATED_JSON": '{"VULNERABILITY_SCORE":1.000000000000000001,"PATCH_SCORE":0,"RISK_SCORE_GRADE":"A"}'},
        ]
        registry = release_registry()
        context = self.compile(models=("ASSESSMENT_RESULTS",), registry=registry, config=old["config"])[0]
        context["lookups"] = copy.deepcopy(old["lookups"])
        oracle = runpy.run_path(str(frozen.AR), run_name="lean_ar_acceptance_oracle")
        scope = oracle["build_ar_score_batch"].__globals__
        scope["AR_SCORE_FIELDS"], scope["AR_ALTERNATIVE_SCORE_FIELDS"] = scope["AR_ACCEPTED_SCORE_FIELDS"], ()
        helpers = {name: old_ns[name] for name in oracle["AR_HELPERS"]}
        helpers["resolve_archer_select_value"] = lambda value: old_ns["resolve_archer_select_value"](value, old)
        expected = oracle["build_ar_score_batch"](
            records, old["mapping_rows"], [row for row in registry if row["OSCAL_MODEL_KEY"] == "ASSESSMENT_RESULTS"],
            old["config"], helpers)
        nodes, edges = build(self.ns, context, records)
        self.assertEqual(frozen.business(expected["nodes"]), business(nodes))
        self.assertEqual(frozen.business(expected["edges"]), business(edges))
        self.ns["_load_graph"](nodes, edges, dict(context["config"], EXPECTED_SOURCE_RECORDS=2))
        result = self.ns["validate_and_load_oscal"](nodes, edges, context["config"])
        self.assertEqual("MAPPED_GRAPH_VALIDATED_TARGET_CONTRACT_PENDING", result["status"])
        self.assertFalse(result["writes_executed"])

    def test_identity_and_links_survive_record_order_and_run_id_changes(self):
        context, records = self.ssp()
        records.append(dict(copy.deepcopy(records[0]), SOURCE_RECORD_ID="101"))
        first = build(self.ns, context, records)
        context["config"]["RUN_ID"] = "another-run"
        second = build(self.ns, context, list(reversed(records)))
        self.assertEqual([business(frame) for frame in first], [business(frame) for frame in second])
        self.ns["_load_graph"](*second, dict(context["config"], EXPECTED_SOURCE_RECORDS=2))

    def test_process_order_cannot_build_children_before_parents(self):
        context, records = self.ssp(lambda registry: [row.update(PROCESS_ORDER=100-row["PROCESS_ORDER"]) for row in registry])
        nodes, edges = build(self.ns, context, records)
        self.assertEqual(SSP_GRAPH_DIGEST, hashlib.sha256(json.dumps([business(nodes), business(edges)], sort_keys=True).encode()).hexdigest())

    def test_registry_specific_child_element_type_survives_graph_and_validation(self):
        path = "system-security-plan.metadata.document-ids[]"
        context, records = self.ssp(lambda registry: [row.update(ELEMENT_TYPE="document-id") for row in registry if row["NODE_PATH"] == path])
        nodes, edges = build(self.ns, context, records)
        self.assertEqual(["document-id"], [node["ELEMENT_TYPE"] for node in nodes.rows if node["ELEMENT_PATH"] == path])
        self.ns["_load_graph"](nodes, edges, context["config"])

    def test_missing_required_title_fails_before_any_graph_is_returned(self):
        context, records = self.ssp()
        records[0]["CURATED_JSON"].pop("AUTHORIZATION_PACKAGE_NAME")
        with self.assertRaises(ValueError):
            build(self.ns, context, records)

    def test_incomplete_security_impact_assembly_is_not_partially_emitted(self):
        context, records = self.ssp()
        records[0]["CURATED_JSON"].pop("RECOMMENDED_INTEGRITY_CONTROL_CATEGORY")
        nodes, edges = build(self.ns, context, records)
        self.assertFalse(any(node["ELEMENT_PATH"].endswith(".security-impact-level") for node in nodes.rows))
        self.ns["_load_graph"](nodes, edges, context["config"])

    def test_duplicate_and_invalid_record_identities_fail(self):
        for identity in ("100", "", " 100 ", None, 100):
            with self.subTest(identity=identity):
                context, records = self.ssp()
                records.append(dict(copy.deepcopy(records[0]), SOURCE_RECORD_ID=identity))
                with self.assertRaises(ValueError):
                    build(self.ns, context, records)

    def test_root_shape_errors_and_empty_source_fail(self):
        for payload in ("[]", "1", "invalid-json"):
            context, records = self.ssp()
            records[0]["CURATED_JSON"] = payload
            with self.subTest(payload=payload), self.assertRaises(ValueError):
                build(self.ns, context, records)
        with self.assertRaises(ValueError):
            build(self.ns, context, [])

    def test_stale_compiler_release_fails_before_source_read(self):
        context, _ = self.ssp()
        context["compiled_plan"]["release"] = "old"
        class Unreadable(Frame):
            def to_local_iterator(self):
                raise AssertionError("Source should not be read")
        config = context["config"]
        with self.assertRaisesRegex(ValueError, "matching lean Cell 3"):
            self.ns["build_oscal_graph"](Unreadable([]), None, None, config["OSCAL_MODEL"],
                                        config["SOURCE_SYSTEM_NAME"], config["SOURCE_TABLE_NAME"], context)


if __name__ == "__main__":
    unittest.main()
