"""NB_ARCHER_OSCAL_MAPPER_V1

Metadata-driven seven-cell mapper: one selector, reviewed mapping metadata,
registry hierarchy, reusable transformations, and guarded persistence.
Field rules: ARCHER_OSCAL_MAPPINGS.csv. Structure: versioned registry columns.
Upload the CSV to notebook Files; no JSON catalog is read.
Default PREVIEW: no target DML. AR destination contract remains pending.
Generated by tools/sync_notebook_cells.py from notebooks/cells/; edit that source.
See docs/REGISTRY_METADATA_SETUP.md for one-time setup and preview instructions.
"""


# %% Cell 1 - Configuration
import copy
import csv
import datetime
import hashlib
import json
import re
import uuid
from decimal import Decimal
from snowflake.snowpark.context import get_active_session
from snowflake.snowpark.functions import col, lit, dense_rank
from snowflake.snowpark.window import Window
from snowflake.snowpark.types import StringType, StructField, StructType, TimestampType, TimestampTimeZone

session = get_active_session()
SELECTED_MODELS = ("SSP",)
CONFIG = {
    "RUN_ID": str(uuid.uuid4()), "OSCAL_VERSION": "1.2.3", "SSP_DOCUMENT_VERSION": "1.0",
    "EXECUTE_WRITES": False, "IDENTITY_VERSION": "v1_registry_path_instance",
    "ELEMENT_REGISTRY_TABLE": "RTX_RAW_DEV.ES_ESC_GRC.OSCAL_ELEMENT_REGISTRY",
    "ARCHER_META_VALUE_TABLE": "RTX_RAW_DEV.ES_ESC_GRC.ARCHER_META_VALUE",
}
SOURCE_FILES = [{
    "SOURCE_KEY": "source-one", "SOURCE_SYSTEM_NAME": "ARCHER",
    "SOURCE_TABLE_NAME": "ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW",
    "RAW_TABLE": "RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW",
    "CONTENT_ID_COLUMN": "CONTENT_ID", "CURATED_JSON_COLUMN": "CURATED_JSON",
    "MAPPING_FILE": "ARCHER_OSCAL_MAPPINGS.csv", "MAPPING_ENCODING": "utf-8-sig",
    "MAPPING_SOURCE_COLUMN": "SOURCE_KEY", "MAPPING_SOURCE_VALUE": "source-one",
    "MODEL_BINDINGS": ("SSP", "ASSESSMENT_RESULTS"),
    "SOURCE_ORDER_CANDIDATES": (
        "DW_LOAD_TIMESTAMP_TZ", "DW_LOAD_TIMESTAMP", "UPDATED_DATE",
        "LAST_UPDATED_DATE", "MODIFIED_DATE", "CREATE_DATE",
    ),
    "LOOKUP_CONTRACTS": {
        "software": {
            "source_table": "RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_SOFTWARE_RAW",
            "title_field": "SOFTWARE_NAME", "description_field": "DESCRIPTION",
        },
        "interconnection": {
            "source_table": "RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_INTERCONNECTIONS_RAW",
            "title_field": "INTERCONNECTION_NAME", "description_field": "DESCRIPTION",
        },
    },
}]
MODEL_CONTRACTS = {
    "SSP": {
        "MODEL_KEY": "SSP", "POLICY": "metadata-v1", "UNREVIEWED_ROWS": "DEFER",
        "MODEL_ALIASES": ("System Security Plan", "SSP - Metadata", "SSP - System Characteristics",
                          "SSP - System Implementation", "SSP - Control Implementation"),
        "LOOKUP_GROUPS": ("components",),
        "RUNTIME_OPTIONS": {"parse_decimal": False, "null_source_as_empty": True},
        "STORAGE_CONTRACT": {
            "VERIFIED": True, "PHYSICAL_PROFILE": "BINARY16_UUID32", "MODEL_KEY": "SSP",
            "ROOT_PATH": "system-security-plan", "ROOT_ELEMENT_TYPE": "system-security-plan",
            "SOURCE_SYSTEM_NAME": "ARCHER", "SOURCE_TABLE_NAME": "ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW",
            "RAW_TABLE": "RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW",
            "TARGET_DIM": "RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT",
            "TARGET_FACT": "RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY",
            "DIM_PK_COLUMN": "PK_OSCAL_SSP_ELEMENT_HASH", "FACT_PK_COLUMN": "PK_FACT_OSCAL_DEPENDENCY_HASH",
            "IDENTITY_VERSION": "v1_registry_path_instance",
        },
    },
    "ASSESSMENT_RESULTS": {
        "MODEL_KEY": "ASSESSMENT_RESULTS", "POLICY": "metadata-v1", "UNREVIEWED_ROWS": "DEFER",
        "MODEL_ALIASES": ("Assessment Results", "AR"), "LOOKUP_GROUPS": (),
        "RUNTIME_OPTIONS": {"parse_decimal": True, "null_source_as_empty": False},
        "STORAGE_CONTRACT": None,
    },
}
ROUTING_METADATA = {
    "DEFERRED_MODEL_LABELS": ("TBD", "N/A - Calculated", "Multiple - See Notes"),
    "DEFERRED_TARGET_PATHS": ("TBD", "All Nulls", "Multiple - See Notes"),
}

if (not SELECTED_MODELS or len(set(SELECTED_MODELS)) != len(SELECTED_MODELS)
        or set(SELECTED_MODELS) - MODEL_CONTRACTS.keys()):
    raise ValueError("Choose distinct configured models in SELECTED_MODELS")
SOURCE_PROFILES = []
if (len({source["RAW_TABLE"].upper() for source in SOURCE_FILES}) != len(SOURCE_FILES)
        or len({(source["SOURCE_SYSTEM_NAME"].upper(), source["SOURCE_TABLE_NAME"].upper())
                for source in SOURCE_FILES}) != len(SOURCE_FILES)):
    raise ValueError("Each physical source and source namespace must have one binding")
for source in SOURCE_FILES:
    routes = tuple(model for model in SELECTED_MODELS if model in source["MODEL_BINDINGS"])
    if routes:
        SOURCE_PROFILES.append({**source, "MODEL_KEYS": routes, "BASE_CONFIG": dict(CONFIG)})
if any(not any(model in source["MODEL_KEYS"] for source in SOURCE_PROFILES) for model in SELECTED_MODELS):
    raise ValueError("Selected model has no configured source")
print("OSCAL mapping:", SELECTED_MODELS, "Run:", CONFIG["RUN_ID"])


# %% Cell 2 - Read source and metadata once

def _normalized_columns(columns):
    result = {}
    for name in columns:
        # Snowpark includes quotes around case-sensitive/otherwise quoted names.
        key = name[1:-1].replace('""', '"') if name.startswith('"') and name.endswith('"') else name.strip().upper()
        if key in result:
            raise ValueError("Duplicate normalized source column")
        result[key] = name
    return result


def _input_column(columns, configured):
    if configured.startswith('"') and configured.endswith('"'):
        return columns.get(configured[1:-1].replace('""', '"'))
    return columns.get(configured, columns.get(configured.upper()))


def _input_no_transaction(active_session):
    # Temporary-table DDL must never commit somebody else's open transaction.
    try:
        current = active_session.sql("SELECT CURRENT_TRANSACTION() AS TX").collect()[0]["TX"]
    except Exception:
        raise ValueError("Cannot verify transaction state before input snapshot") from None
    if current is not None:
        raise ValueError("Finish the existing transaction before input snapshot")


def load_source_input(active_session, profile):
    _input_no_transaction(active_session)
    raw = active_session.table(profile["RAW_TABLE"])
    columns = _normalized_columns(raw.columns)
    id_name = _input_column(columns, profile.get("CONTENT_ID_COLUMN", "CONTENT_ID"))
    json_name = _input_column(columns, profile.get("CURATED_JSON_COLUMN", "CURATED_JSON"))
    if id_name is None or json_name is None:
        raise ValueError("Source requires its configured identity and curated JSON columns")
    selected = [col(id_name).cast("string").alias("SOURCE_RECORD_ID"),
                col(json_name).alias("CURATED_JSON")]
    order_columns = []
    for candidate in profile.get("SOURCE_ORDER_CANDIDATES", ()):
        name = _input_column(columns, candidate)
        if name is not None:
            alias = "_SOURCE_ORDER_" + str(len(order_columns))
            selected.append(col(name).alias(alias))
            order_columns.append(alias)
    # Freeze once in a session-local temporary table, before validation and
    # model fan-out. Keep the returned cache handle alive in SOURCE_INPUTS.
    candidates = raw.select(*selected).cache_result()
    if candidates.filter("SOURCE_RECORD_ID IS NULL OR LENGTH(TRIM(SOURCE_RECORD_ID)) = 0").count():
        raise ValueError("Source contains missing record identities")
    count = candidates.count()
    distinct = candidates.select("SOURCE_RECORD_ID").distinct().count()
    if count != distinct:
        if not order_columns:
            raise ValueError("Duplicate source identities require approved technical ordering")
        order = [col(name).desc_nulls_last() for name in order_columns]
        latest = candidates.with_column(
            "_SOURCE_RANK", dense_rank().over(
                Window.partition_by("SOURCE_RECORD_ID").order_by(*order)
            )
        ).filter(col("_SOURCE_RANK") == lit(1))
        # Equal latest payloads are interchangeable; conflicting ones need a
        # source tie-break column. JSON text/object key order is not an identity.
        result = latest.select("SOURCE_RECORD_ID", "CURATED_JSON").distinct()
        if result.count() != distinct:
            raise ValueError("Conflicting source payloads share the latest approved technical ordering")
    else:
        result = candidates.select("SOURCE_RECORD_ID", "CURATED_JSON")
    # The frozen snapshot yields one selected row per distinct source identity.
    return result, {"RAW_ROWS": count, "SELECTED_ROWS": distinct,
                    "DUPLICATE_SOURCE_ROWS_RESOLVED": count - distinct}, candidates


def load_mapping_rows(profile):
    with open(profile["MAPPING_FILE"], encoding=profile.get("MAPPING_ENCODING", "utf-8-sig"), newline="") as handle:
        reader = csv.reader(handle, strict=True)
        header = next((row for row in reader if row and any(v.strip() for v in row)), None)
        if header is None:
            raise ValueError("Mapping CSV header is missing")
        header = [name.strip().upper() for name in header]
        if not all(header) or len(header) != len(set(header)):
            raise ValueError("Mapping CSV columns must be nonblank and unique")
        binding = profile.get("MAPPING_SOURCE_COLUMN", "").upper()
        if binding and binding not in header:
            raise ValueError("Mapping source binding column is missing")
        rows = []
        for values in reader:
            if not values or not any(value.strip() for value in values):
                continue
            if len(values) > len(header):
                raise ValueError("Mapping CSV row has more values than header columns")
            row = dict.fromkeys(header)
            row.update((key, value or None) for key, value in zip(header, values))
            if not binding or str(row[binding] or "").strip() == profile.get("MAPPING_SOURCE_VALUE", profile["SOURCE_TABLE_NAME"]):
                rows.append(row)
    return rows


def load_source_lookups(active_session, profile, model_contracts, shared_config):
    _input_no_transaction(active_session)
    values = active_session.table(shared_config["ARCHER_META_VALUE_TABLE"]).select(
        col("SELECT_VALUE_ID"), col("SELECT_VALUE_NAME")
    ).filter(col("SELECT_VALUE_NAME").is_not_null())
    archer = {}
    for row in values.collect():
        if row["SELECT_VALUE_ID"] is not None:
            key = str(row["SELECT_VALUE_ID"]).strip()
            value = str(row["SELECT_VALUE_NAME"]).strip()
            if key in archer and archer[key] != value:
                raise ValueError("Archer lookup identity has conflicting labels")
            archer[key] = value
    components = {}
    required = {group for key in profile["MODEL_KEYS"]
                for group in model_contracts[key].get("LOOKUP_GROUPS", ())}
    # Lookup requirements are data in the source profile, not table names in
    # the shared input loader. Only profiles that need them read them.
    for kind, contract in profile.get("LOOKUP_CONTRACTS", {}).items():
        if "components" not in required:
            continue
        table = active_session.table(contract["source_table"])
        names = _normalized_columns(table.columns)
        if not {"CONTENT_ID", "CURATED_JSON"}.issubset(names):
            raise ValueError("Configured component lookup columns are missing")
        components[kind] = table.select(
            col(names["CONTENT_ID"]).alias("CONTENT_ID"),
            col(names["CURATED_JSON"]).alias("CURATED_JSON")
        ).cache_result()
    return {"archer_values": archer,
            "fips_values": {key: value for key, value in archer.items()
                            if value.lower() in {"low", "moderate", "high"}},
            "component_sources": components,
            "component_contract": profile.get("LOOKUP_CONTRACTS", {})}


SOURCE_INPUTS, MAPPING_INPUTS = {}, {}
for profile in SOURCE_PROFILES:
    key = profile["SOURCE_KEY"]
    if key in SOURCE_INPUTS:
        raise ValueError("Duplicate source binding")
    frame, counts, snapshot = load_source_input(session, profile)
    MAPPING_INPUTS[key] = load_mapping_rows(profile)
    SOURCE_INPUTS[key] = {
        "source_df": frame, "snapshot": snapshot, "selection": counts,
        "lookups": load_source_lookups(session, profile, MODEL_CONTRACTS, CONFIG),
    }
REGISTRY_INPUT_ROWS = [row.as_dict(recursive=True) for row in
                       session.table(CONFIG["ELEMENT_REGISTRY_TABLE"]).collect()]
print("Sources:", {key: value["selection"] for key, value in SOURCE_INPUTS.items()})


# %% Cell 3 - Compile the mapping CSV against the element registry

import copy
import math
import re
from collections import Counter

LEAN_MAPPER_RELEASE = "lean-csv-registry-v1"
METADATA_TRANSFORM_IDS = {
    "direct", "text", "timestamp", "date", "identifier", "archer-select",
    "scalar-score", "security-objective", "status-crosswalk", "reject-populated",
    "skip", "canonical-text",
}
METADATA_INSTANCE_RULES = {
    "record": "SOURCE_RECORD_ID", "observations": "SOURCE_FIELD_NAME",
    "properties": "SOURCE_FIELD_NAME+VALUE", "values": "VALUE", "references": "CONTENT_ID",
    "roles": "SOURCE_FIELD_NAME", "parties": "ID", "assignments": "SOURCE_FIELD_NAME+ID",
}
METADATA_ITEM_PATHS = {operator: (None if operator in {"record", "observations"} else
                                "UserList[]" if operator in {"parties", "assignments"} else "$")
                       for operator in METADATA_INSTANCE_RULES}


def _meta_row(row):
    row = row.as_dict(recursive=True) if hasattr(row, "as_dict") else row
    result = {}
    for key, value in row.items():
        key = str(key).strip().upper()
        key = {"ARCHER_FIELD_NAME": "SOURCE_FIELD_NAME", "MAPPING_STATUS": "STATUS"}.get(key, key)
        if key in result:
            raise ValueError("Ambiguous metadata column: " + key)
        result[key] = (None if value is None or isinstance(value, float) and math.isnan(value)
                       else value.strip() if isinstance(value, str) else value)
    return result


def _metadata_column_text(row, key, required=False):
    value = row.get(key)
    if value in (None, "") and not required:
        return None
    if not isinstance(value, str) or not value.strip():
        raise ValueError(key + " must contain nonblank text")
    return value.strip()


def _metadata_items(row, key):
    value = _metadata_column_text(row, key)
    items = [item.strip() for item in value.split("|")] if value else []
    if any(not item for item in items) or len(set(items)) != len(items):
        raise ValueError(key + " contains empty or duplicate entries")
    return items


def _registry_meta_bool(row, key):
    value = row.get(key)
    if type(value) is bool:
        return value
    if isinstance(value, str) and value.lower() in {"true", "false"}:
        return value.lower() == "true"
    raise ValueError(key + " must be true or false")


def _registry_path(row):
    return row.get("NODE_PATH") or ""


def _registry_model(row):
    return str(row.get("OSCAL_MODEL_KEY") or "").upper()


def _model_token(value):
    return re.sub(r"[^a-z0-9]+", "", str(value or "").lower())


def _metadata_params(row):
    return row.get("REPRESENTATION_PARAMS") or {}


def _metadata_target(row):
    return _metadata_params(row).get("target") or row.get("FIELD_RELATIVE_PATH") or row.get("OSCAL_FIELD_NAME")


def _owner_for_path(path, paths):
    return max((p for p in paths if path == p or path.startswith(p + ".")), key=len, default=None)


def _registry_operator(row):
    operator = _metadata_column_text(row, "OPERATOR")
    if operator:
        if operator not in {"object", *METADATA_INSTANCE_RULES}:
            raise ValueError("Unknown registry OPERATOR")
        return operator
    if not _registry_meta_bool(row, "IS_COLLECTION"):
        return "object"
    identity = (row.get("INSTANCE_KEY_RULE"), row.get("ITEM_PATH"))
    for candidate in METADATA_INSTANCE_RULES:
        if identity == (METADATA_INSTANCE_RULES[candidate], METADATA_ITEM_PATHS[candidate]):
            return candidate
    raise ValueError("Collection requires a supported registry OPERATOR and identity")


def _registry_elements(rows, selected, profile, model):
    """Validate hierarchy once, retaining mapped/explicit paths and their ancestors."""
    by_path = {_registry_path(row): row for row in rows}
    if not by_path or "" in by_path or len(by_path) != len(rows):
        raise ValueError("Enabled model requires unique active registry paths")
    parents = {path: row.get("PARENT_NODE_PATH") or None for path, row in by_path.items()}
    roots = [path for path, parent in parents.items() if parent is None]
    if len(roots) != 1 or "." in roots[0]:
        raise ValueError("Enabled model requires one registry root")
    root = roots[0]
    for path, row in by_path.items():
        order = row.get("PROCESS_ORDER")
        order = 0 if order in (None, "") else order
        if isinstance(order, bool) or int(order) != float(order):
            raise ValueError("Registry PROCESS_ORDER must be an integer")
        row["PROCESS_ORDER"] = int(order)
        if _registry_meta_bool(row, "IS_COLLECTION") != path.endswith("[]"):
            raise ValueError("Registry collection flag conflicts with its path")
        if path != root and (parents[path] not in by_path or not path.startswith(parents[path] + ".")):
            raise ValueError("Registry child requires its active path ancestor")
    included = {root} | {row["OWNER_ELEMENT_PATH"] for row in selected}
    included.update(path for path, row in by_path.items() if row.get("OPERATOR"))
    groups, linked = [], set()
    for path in sorted(included):
        if _registry_operator(by_path[path]) != "assignments":
            continue
        siblings = {"roles": [], "parties": []}
        for other, row in by_path.items():
            if parents[other] != parents[path]:
                continue
            try:
                operator = _registry_operator(row)
            except ValueError:
                if row.get("OPERATOR"):
                    raise
                continue
            if operator in siblings:
                siblings[operator].append(other)
        if any(len(paths) != 1 for paths in siblings.values()):
            raise ValueError("Assignment requires one role and one party registry sibling")
        role, party = siblings["roles"][0], siblings["parties"][0]
        if {path, role, party} & linked:
            raise ValueError("Reference families require distinct registry paths")
        linked.update((path, role, party))
        groups.append({"roles_path": role, "parties_path": party, "assignments_path": path,
                       "party_type": "person", "source_namespace": {
                           "SOURCE_SYSTEM_NAME": profile["SOURCE_SYSTEM_NAME"],
                           "SOURCE_TABLE_NAME": profile["SOURCE_TABLE_NAME"], "MODEL_KEY": model}})
    included.update(linked)
    for path in tuple(included):
        parent = parents[path]
        while parent is not None and parent not in included:
            included.add(parent)
            parent = parents[parent]
    elements = {}
    for path in sorted(included):
        row, parent = by_path[path], parents[path]
        operator, collection = _registry_operator(row), _registry_meta_bool(row, "IS_COLLECTION")
        if operator != "object" and not collection:
            raise ValueError("Collection operator requires IS_COLLECTION=true")
        parameters = {"registry_contract": {"parent_path": parent, "is_collection": collection}}
        if collection:
            identity = (row.get("INSTANCE_KEY_RULE"), row.get("ITEM_PATH"))
            expected = ("VALUE", "$") if operator == "object" else (METADATA_INSTANCE_RULES[operator], METADATA_ITEM_PATHS[operator])
            if identity != expected:
                raise ValueError("Registry identity conflicts with OPERATOR")
            parameters["registry_contract"].update(instance_key_rule=identity[0], item_path=identity[1])
        if parent and _registry_meta_bool(by_path[parent], "IS_COLLECTION"):
            if _registry_operator(by_path[parent]) != "record":
                raise ValueError("Nested collection requires a record parent identity")
            parameters["parent_instance_rule"] = "source-record"
        elif operator == "record":
            parameters["parent_instance_rule"] = "singleton"
        policy = _metadata_column_text(row, "UUID_POLICY", required=bool(row.get("OPERATOR"))) or "omit"
        if policy not in {"omit", "node", "instance"} or (policy == "instance") != (operator == "parties"):
            raise ValueError("Invalid registry UUID policy")
        if policy != "omit":
            parameters["include_uuid"] = True
        if policy == "instance":
            parameters["uuid_from_instance"] = True
        members = _metadata_items(row, "REQUIRED_MEMBERS")
        if members:
            if operator != "object" or any(not re.fullmatch(r"[\w-]+(?:\.[\w-]+)*", member) for member in members):
                raise ValueError("REQUIRED_MEMBERS requires scalar object member paths")
            parameters.update(required_members=members, optional_assembly=True)
        elif operator == "object" and not collection:
            parameters["materialize_empty"] = True
        if operator in {"properties", "observations"}:
            parameters["property_name_rule"] = "source-field-slug"
        if operator in {"roles", "parties"} and path not in linked:
            raise ValueError("Linked identity operator lacks an assignment family")
        elements[path] = {"operator": operator, "parameters": parameters}
    if elements[root]["operator"] != "object":
        raise ValueError("Registry root requires an object operator")
    return root, [row for row in rows if _registry_path(row) in included], elements, groups


def _compile_mapping(row, elements):
    """Translate explicit CSV columns to the parameters used by Cell Four."""
    transform = _metadata_column_text(row, "TRANSFORM_ID", True)
    rule = _metadata_column_text(row, "RULE_ID", True)
    if transform not in METADATA_TRANSFORM_IDS:
        raise ValueError("Unknown reusable TRANSFORM_ID")
    if row["EXECUTION_STATUS"] == "BLOCKED_IF_POPULATED" and transform != "reject-populated":
        raise ValueError("Populated-only guard requires reject-populated")
    operator = elements[row["OWNER_ELEMENT_PATH"]]["operator"]
    target = row["FIELD_RELATIVE_PATH"]
    params, representation = {}, {}
    if target:
        if operator not in {"object", "record", "values"} or not re.fullmatch(r"[\w-]+(?:\.[\w-]+)*", target):
            raise ValueError("Member target conflicts with its element operator")
        representation["target"] = target
    source = row.get("VALUE_SOURCE") or "FIELD"
    if source not in {"FIELD", "CONFIG"} or source == "CONFIG" and (operator not in {"object", "record"} or not target):
        raise ValueError("CONFIG values require an explicit object member target")
    if source == "CONFIG":
        representation["value_source"] = source
    if row.get("VALUE_REQUIRED") not in (None, ""):
        representation["required"] = _registry_meta_bool(row, "VALUE_REQUIRED")
    if transform == "skip" and representation.get("required"):
        raise ValueError("Skip transform cannot supply a required value")
    allowed = {"VALUE_SOURCE", "VALUE_REQUIRED"}
    if transform == "security-objective":
        allowed.add("ALLOWED_VALUES")
        if row.get("ALLOWED_VALUES"):
            params["approved_legacy_values"] = _metadata_items(row, "ALLOWED_VALUES")
    if transform == "status-crosswalk":
        allowed.update(("VALUE_MAP", "OTHER_REMARKS_TEMPLATE"))
        crosswalk = {}
        for entry in _metadata_items(row, "VALUE_MAP"):
            if entry.count("=") != 1:
                raise ValueError("VALUE_MAP entries must be source=target")
            source, target = (part.strip() for part in entry.split("=", 1))
            source = re.sub(r"[^a-z0-9]+", "-", source.lower()).strip("-")
            if not source or not target or source in crosswalk:
                raise ValueError("VALUE_MAP contains empty or conflicting labels")
            crosswalk[source] = target
        if not crosswalk:
            raise ValueError("Crosswalk requires VALUE_MAP")
        params["crosswalk"] = crosswalk
        template = row.get("OTHER_REMARKS_TEMPLATE")
        if template:
            if template.count("{label}") != 1 or any(c in template.replace("{label}", "") for c in "{}"):
                raise ValueError("OTHER_REMARKS_TEMPLATE requires one {label} placeholder")
            params["other_remarks_prefix"], params["other_remarks_suffix"] = template.split("{label}")
        elif "other" in crosswalk.values():
            raise ValueError("Crosswalk other value requires an explanation")
    if operator == "assignments":
        allowed.update(("ROLE_ID", "ROLE_TITLE"))
        representation.update(role_id=_metadata_column_text(row, "ROLE_ID", True),
                              role_title=_metadata_column_text(row, "ROLE_TITLE", True))
    if operator == "references":
        allowed.update(("REFERENCE_TYPE", "LOOKUP_KEY", "DESCRIPTION_REQUIRED"))
        representation["reference_type"] = _metadata_column_text(row, "REFERENCE_TYPE", True)
        if row.get("LOOKUP_KEY"):
            representation["hydrate_lookup"] = _metadata_column_text(row, "LOOKUP_KEY")
        if row.get("DESCRIPTION_REQUIRED") not in (None, ""):
            if not row.get("LOOKUP_KEY"):
                raise ValueError("DESCRIPTION_REQUIRED needs LOOKUP_KEY")
            representation["description_required"] = _registry_meta_bool(row, "DESCRIPTION_REQUIRED")
    columns = {"ALLOWED_VALUES", "VALUE_MAP", "OTHER_REMARKS_TEMPLATE", "ROLE_ID", "ROLE_TITLE",
               "REFERENCE_TYPE", "LOOKUP_KEY", "DESCRIPTION_REQUIRED", "VALUE_SOURCE", "VALUE_REQUIRED"}
    if any(row.get(key) not in (None, "") for key in columns - allowed):
        raise ValueError("CSV parameter does not apply to the selected operation")
    return dict(row, TRANSFORM_PARAMS=params, REPRESENTATION=operator, REPRESENTATION_PARAMS=representation,
                APPROVAL_STATUS=row["EXECUTION_STATUS"], RULE_ID=rule)


def _mapping_route(row, profile, model, paths, inactive, aliases, roots, routing, source_keys, unreviewed):
    """Return exclusion reason, or the canonical registered owner and member path."""
    status = row.get("EXECUTION_STATUS")
    original = row.get("OSCAL_ELEMENT_PATH") or ""
    path = row.get("RUNTIME_TARGET_PATH") or "" if status in {"APPROVED", "BLOCKED_IF_POPULATED"} else original
    label = _model_token(row.get("OSCAL_MODEL"))
    owner_model, label_model = roots.get(path.split(".", 1)[0]), aliases.get(label)
    source = row.get("SOURCE_KEY")
    reason, severity = None, "BLOCKED"
    if status not in {None, "", "APPROVED", "BLOCKED_IF_POPULATED", "DEFERRED", "EXCLUDED"} or (
            not status and row.get("RUNTIME_TARGET_PATH")):
        reason = "INVALID_EXECUTION_STATUS"
    elif source and source not in source_keys:
        reason = "UNKNOWN_SOURCE_KEY"
    elif source and source != profile["SOURCE_KEY"]:
        reason, severity = "OTHER_SOURCE", "EXCLUDED"
    elif status and not source:
        reason = "MISSING_SOURCE_KEY"
    elif status in {"DEFERRED", "EXCLUDED"}:
        reason, severity = "EXPLICIT_" + status, status
    elif label_model and owner_model and label_model != owner_model or (
            status and roots.get(original.split(".", 1)[0]) not in {None, owner_model}):
        reason = "MODEL_PATH_CONFLICT"
    elif label in routing["labels"] or path in routing["paths"]:
        reason, severity = "PLACEHOLDER_MAPPING", "DEFERRED"
    elif owner_model and owner_model != model or not path and label_model and label_model != model:
        reason, severity = "OTHER_MODEL", "EXCLUDED"
    elif any(row.get(key) not in (None, "") for key in (
            "TRANSFORM_PARAMS", "REPRESENTATION_PARAMS", "REPRESENTATION", "VALUE_CONSTRAINTS", "APPROVAL_STATUS")):
        reason = "RETIRED_MAPPING_METADATA"
    elif not status:
        reason, severity = "MISSING_APPROVED_METADATA", "DEFERRED" if unreviewed == "DEFER" else "BLOCKED"
    elif not row.get("SOURCE_FIELD_NAME"):
        reason = "MISSING_SOURCE_FIELD"
    elif not path or owner_model is None:
        reason = "UNKNOWN_MODEL_OR_PATH"
    elif any(path == boundary or path.startswith(boundary + ".") for boundary in inactive):
        reason = "REGISTRY_PATH_NOT_EXECUTABLE"
    owner = _owner_for_path(path, paths)
    relative = path[len(owner):].lstrip(".") if owner else ""
    if not reason and (owner is None or any(token in relative for token in ("[", "]", ".."))):
        reason = "UNREGISTERED_COLLECTION"
    if reason:
        return None, {"reason": reason, "severity": severity, "field": row.get("SOURCE_FIELD_NAME")}
    return dict(row, ARTIFACT_MODEL=row.get("OSCAL_MODEL"), CANONICAL_ELEMENT_PATH=path,
                OWNER_ELEMENT_PATH=owner, FIELD_RELATIVE_PATH=relative, OSCAL_MODEL=model,
                OSCAL_FIELD_NAME=row.get("OSCAL_FIELD_NAME") or (relative.split(".")[-1] if relative else None)), None


def compile_mapping_contexts(mapping_rows, registry_rows, source_profiles, model_contracts, routing_metadata=None):
    """One input boundary: pure compilation, no source reads or executable metadata."""
    registry = [_meta_row(row) for row in registry_rows]
    active = [row for row in registry if _registry_meta_bool(row, "IS_ACTIVE")]
    mappings = {key: [_meta_row(row) for row in rows] for key, rows in mapping_rows.items()}
    source_keys = {profile["SOURCE_KEY"] for profile in source_profiles}
    if len(source_keys) != len(source_profiles) or source_keys != set(mappings):
        raise ValueError("Each source needs one explicit mapping input")
    for profile in source_profiles:
        models = profile["MODEL_KEYS"]
        if not models or len(set(models)) != len(models) or set(models) - set(model_contracts):
            raise ValueError("Source route requires distinct configured models")
    aliases, roots = {}, {}
    for model, contract in model_contracts.items():
        if contract.get("MODEL_KEY") != model or {"ELEMENTS", "ROOT_PATH", "DEFAULT_ELEMENT", "MAPPING_RULES",
                "PATH_RULES", "SELECTED_FIELDS", "EXCLUDED_FIELDS", "REFERENCE_GROUPS"} & contract.keys():
            raise ValueError("Model settings cannot override CSV mappings or registry structure")
        for label in [model, *contract.get("MODEL_ALIASES", ())]:
            token = _model_token(label)
            if not token or aliases.get(token, model) != model:
                raise ValueError("Ambiguous model alias")
            aliases[token] = model
    for row in active:
        model, root = _registry_model(row), _registry_path(row).split(".", 1)[0]
        if not model or not root or roots.get(root, model) != model:
            raise ValueError("Registry root requires one model owner")
        roots[root] = model
        for label in (model, root, row.get("OSCAL_MODEL"), row.get("MODEL_NAME")):
            token = _model_token(label)
            if token and aliases.get(token, model) != model:
                raise ValueError("Registry label conflicts with configured ownership")
            if token:
                aliases[token] = model
    routing_metadata = routing_metadata or {}
    if set(routing_metadata) - {"DEFERRED_MODEL_LABELS", "DEFERRED_TARGET_PATHS"}:
        raise ValueError("Unknown routing setting")
    if any(not isinstance(values, (tuple, list)) or any(not isinstance(v, str) or not v.strip() for v in values)
           for values in routing_metadata.values()):
        raise ValueError("Routing placeholders must be lists of nonblank text")
    routing = {"labels": {_model_token(v) for v in routing_metadata.get("DEFERRED_MODEL_LABELS", ())},
               "paths": set(routing_metadata.get("DEFERRED_TARGET_PATHS", ()))}
    if "" in routing["labels"] or routing["labels"] & set(aliases) or routing["paths"] & {_registry_path(row) for row in active}:
        raise ValueError("Placeholder conflicts with a registered model or path")
    contexts = []
    for profile in source_profiles:
        for model in profile["MODEL_KEYS"]:
            settings = copy.deepcopy(model_contracts[model])
            model_rows = [row for row in active if _registry_model(row) == model]
            paths = {_registry_path(row) for row in model_rows}
            inactive = {_registry_path(row) for row in registry if _registry_model(row) == model} - paths
            selected, issues = [], []
            for index, row in enumerate(mappings[profile["SOURCE_KEY"]]):
                canonical, issue = _mapping_route(row, profile, model, paths, inactive, aliases, roots,
                                                   routing, source_keys, settings.get("UNREVIEWED_ROWS"))
                if issue:
                    issues.append(dict(issue, row=index))
                else:
                    selected.append(canonical)
            selected.sort(key=lambda row: (row["OWNER_ELEMENT_PATH"], row["CANONICAL_ELEMENT_PATH"], row["SOURCE_FIELD_NAME"]))
            root, model_rows, elements, groups = _registry_elements(model_rows, selected, profile, model)
            namespaces = {(p["SOURCE_SYSTEM_NAME"], p["SOURCE_TABLE_NAME"])
                          for p in source_profiles if model in p["MODEL_KEYS"]}
            if groups and len(namespaces) != 1:
                raise ValueError("Existing party UUID identity requires one source namespace per model")
            report = dict(settings.get("REPORT") or {})
            if report:
                observations = [path for path, spec in elements.items() if spec["operator"] == "observations"]
                if len(observations) != 1 or "TARGET_PATH" in report:
                    raise ValueError("Report requires one registry observation path")
                report["TARGET_PATH"] = observations[0]
            settings.update(ROOT_PATH=root, ELEMENTS=elements, ELEMENT_PATHS=tuple(elements), REFERENCE_GROUPS=groups, REPORT=report)
            storage = copy.deepcopy(profile.get("MODEL_STORAGE_CONTRACTS", {}).get(model, settings.get("STORAGE_CONTRACT")))
            settings["STORAGE_CONTRACT"] = storage
            config = dict(copy.deepcopy(profile.get("BASE_CONFIG", {})), OSCAL_MODEL=model, ROOT_PATH=root,
                          ROOT_ELEMENT_TYPE=next(row for row in model_rows if _registry_path(row) == root).get("ELEMENT_TYPE") or root,
                          STORAGE_CONTRACT=storage, EXECUTE_WRITES=False)
            config.update({key: profile[key] for key in ("SOURCE_SYSTEM_NAME", "SOURCE_TABLE_NAME", "RAW_TABLE")})
            for key in ("TARGET_DIM", "TARGET_FACT", "DIM_PK_COLUMN", "FACT_PK_COLUMN"):
                config.pop(key, None)
                if storage:
                    config[key] = storage[key]
            plan, contract_error = None, None
            if not any(issue["severity"] == "BLOCKED" for issue in issues):
                try:
                    selected = [_compile_mapping(row, elements) for row in selected]
                    identities = [(row["OWNER_ELEMENT_PATH"], row["SOURCE_FIELD_NAME"], row["FIELD_RELATIVE_PATH"]) for row in selected]
                    if len({row["RULE_ID"] for row in selected}) != len(selected) or len(set(identities)) != len(selected):
                        raise ValueError("Duplicate mapping rule or field target")
                    options = {key: value for key, value in settings.get("RUNTIME_OPTIONS", {}).items()
                               if key in {"parse_decimal", "null_source_as_empty"}}
                    plan = dict(version=1, release=LEAN_MAPPER_RELEASE, elements=elements, mappings=selected,
                                reference_groups=groups, options=options, report=report)
                except ValueError as error:
                    contract_error = str(error)
                    issues.append(dict(row=None, field=None, reason="METADATA_CONTRACT_ERROR", severity="BLOCKED", affected_rows=len(selected)))
                    selected = []
            counts = Counter()
            reasons = Counter()
            for issue in issues:
                counts[issue["severity"]] += issue.get("affected_rows", 1)
                reasons[issue["reason"]] += issue.get("affected_rows", 1)
            route_report = dict(STATUS="BLOCKED" if counts["BLOCKED"] else "READY",
                                INPUT_ROWS=len(mappings[profile["SOURCE_KEY"]]), SELECTED_ROWS=len(selected),
                                EXCLUDED_ROWS=counts["EXCLUDED"], DEFERRED_ROWS=counts["DEFERRED"], BLOCKED_ROWS=counts["BLOCKED"],
                                REASON_COUNTS=dict(reasons), SEVERITY_COUNTS=dict(counts), ROUTING_POLICY="registry-first-v1",
                                ISSUE_EVENTS_TOTAL=len(issues), ISSUE_SAMPLE_LIMIT=25, ISSUE_SAMPLES_TRUNCATED=len(issues) > 25,
                                ISSUES=sorted(issues, key=lambda issue: issue["severity"] != "BLOCKED")[:25])
            if contract_error:
                route_report["CONTRACT_ERROR"] = contract_error
            by_path = {}
            for row in selected:
                by_path.setdefault(row["OWNER_ELEMENT_PATH"], []).append(row)
            contexts.append(dict(source_key=profile["SOURCE_KEY"], config=config, model_contract=settings,
                                 mapping_rows=selected, registry_rows=model_rows, mappings_by_path=by_path,
                                 compiled_plan=plan, routing_report=route_report))
    return contexts


MAPPING_CONTEXTS = compile_mapping_contexts(MAPPING_INPUTS, REGISTRY_INPUT_ROWS, SOURCE_PROFILES,
                                            MODEL_CONTRACTS, ROUTING_METADATA)
print("Mapping routes:", [(c["source_key"], c["config"]["OSCAL_MODEL"], c["routing_report"]) for c in MAPPING_CONTEXTS])


# %% Cell 4 - Reusable transforms and registry operators

import copy
import datetime
import hashlib
import json
import math
import re
import uuid
from decimal import Decimal

SKIP_VALUE = object()
ARCHER_SELECT_ID_CONTAINER_KEYS = {"valuelistid", "valuelistids", "valueslistid", "valueslistids"}


def _to_python(value):
    if hasattr(value, "as_dict"):
        return value.as_dict(recursive=True)
    return value.as_list() if hasattr(value, "as_list") else value


def _has_value(value):
    return value not in (None, "", [], {})


def resolve_json_path(source_obj, field_path):
    """Read a literal source key first, then a dotted/slash path or list index."""
    if not field_path:
        return None
    if isinstance(source_obj, dict) and field_path in source_obj:
        return _to_python(source_obj[field_path])
    current = source_obj
    for token in filter(None, re.split(r"[./]", str(field_path))):
        current = _to_python(current)
        if isinstance(current, dict):
            current = current.get(token, current.get(token.upper()))
        elif isinstance(current, list) and token.isdigit() and int(token) < len(current):
            current = current[int(token)]
        else:
            return None
    return _to_python(current)


def _stable_property_name(field):
    return re.sub(r"[^a-z0-9]+", "-", field.lower()).strip("-")


def _deterministic_uuid(*parts):
    return str(uuid.uuid5(uuid.NAMESPACE_URL, "|".join(map(str, parts))))


def _deterministic_hash(*parts):
    return hashlib.md5("|".join(map(str, parts)).encode("utf-8")).hexdigest()


def _scalar_text(value, shape_error, value_error, allow_bool=False):
    value = _to_python(value)
    if value is None or isinstance(value, (dict, list)) or isinstance(value, bool) and not allow_bool:
        raise ValueError(shape_error)
    text = ("true" if value else "false") if isinstance(value, bool) else str(value).strip()
    if not text or text.lower() in {"nan", "inf", "+inf", "-inf"}:
        raise ValueError(value_error)
    return text


def _oscal_property_values(value):
    return [_scalar_text(item, "Property value must be scalar", "Property value must be finite and nonblank", True)
            for item in (value if isinstance(value, list) else [value])]


def _extract_reference_ids(value):
    value = _to_python(value)
    if isinstance(value, dict):
        for key in ("UserList", "ValuesListIds", "ValueListIds", "ContentIds", "Ids", "Value"):
            if key in value and _has_value(value[key]):
                return _extract_reference_ids(value[key])
        for key, item in value.items():
            if re.sub(r"[^a-z0-9]", "", str(key).lower()) in ARCHER_SELECT_ID_CONTAINER_KEYS and _has_value(item):
                return _extract_reference_ids(item)
    if isinstance(value, list):
        result = []
        for item in value:
            extracted = _extract_reference_ids(item)
            result.extend(extracted if isinstance(extracted, list) else [extracted])
        return result
    return value


def _contains_archer_select_id_container(value):
    value = _to_python(value)
    if isinstance(value, dict):
        return any(re.sub(r"[^a-z0-9]", "", str(key).lower()) in ARCHER_SELECT_ID_CONTAINER_KEYS
                   or _contains_archer_select_id_container(item) for key, item in value.items())
    return isinstance(value, list) and any(_contains_archer_select_id_container(item) for item in value)


def resolve_archer_select_value(value, context):
    lookup = context["lookups"].get("archer_values", {})
    strict = _contains_archer_select_id_container(value)
    extracted = _extract_reference_ids(value)

    def resolve(item):
        item = _to_python(item)
        if item is None:
            return None
        if isinstance(item, (dict, list, bool)):
            if strict:
                raise ValueError("Archer select-value container is invalid")
            return item
        key = str(item).strip()
        if strict and (key not in lookup or not _has_value(lookup[key])):
            raise ValueError("Archer select-value ID is unresolved")
        return lookup.get(key, item)

    if isinstance(extracted, list):
        return [result for item in extracted if (result := resolve(item)) is not None]
    return resolve(extracted)


def _single_archer_label(value, context):
    extracted = _extract_reference_ids(value)
    values = [item for item in (extracted if isinstance(extracted, list) else [extracted]) if item is not None]
    if len(values) != 1 or isinstance(values[0], (dict, list)):
        return None
    item, key = values[0], str(values[0]).strip()
    label = context["lookups"].get("archer_values", {}).get(key)
    if label is not None:
        return str(label).strip() or None
    return key if isinstance(item, str) and key and not key.isdigit() else None


def transform_fips_199(value, context):
    extracted = _extract_reference_ids(value)
    normalized, lookups = [], context["lookups"]
    for item in (extracted if isinstance(extracted, list) else [extracted]):
        if item is None:
            continue
        key = str(item).strip()
        label = lookups.get("fips_values", {}).get(key)
        if label is None:
            candidate = str(lookups.get("archer_values", {}).get(key, item)).strip().lower()
            label = candidate if candidate in {"low", "moderate", "high"} else None
        if label is not None:
            normalized.append(label)
    return normalized[0] if len(normalized) == 1 else normalized or None


def transform_document_identifier(value):
    return _scalar_text(value, "Document identifier must be scalar", "Document identifier must be finite and nonblank")


def transform_authorization_date(value):
    """Keep the source calendar date; never reinterpret an offset as UTC."""
    value = _to_python(value)
    if not _has_value(value):
        return SKIP_VALUE
    try:
        if isinstance(value, (datetime.datetime, datetime.date)):
            return datetime.date(value.year, value.month, value.day).isoformat()
        if isinstance(value, str):
            text = value.strip()
            if re.fullmatch(r"[0-9]{4}-[0-9]{2}-[0-9]{2}", text):
                return datetime.date.fromisoformat(text).isoformat()
            if re.fullmatch(r"[0-9]{4}-[0-9]{2}-[0-9]{2}[Tt ][0-9]{2}:[0-9]{2}:[0-9]{2}"
                            r"(?:\.[0-9]{1,9})?(?:[Zz]|[+-](?:[01][0-9]|2[0-3]):[0-5][0-9])?", text):
                text = text[:10] + "T" + text[11:]
                if text[-1:] in {"Z", "z"}:
                    text = text[:-1] + "+00:00"
                return datetime.datetime.fromisoformat(text).date().isoformat()
    except (ValueError, TypeError, OverflowError):
        pass
    raise ValueError("Mapped date requires a valid ISO date or timestamp")


def _score_value(value, context):
    if not _has_value(value):
        return None
    if _contains_archer_select_id_container(value):
        value = resolve_archer_select_value(value, context)
    values = value if isinstance(value, list) else [value]
    if len(values) != 1 or not isinstance(values[0], (str, int, float, bool, Decimal)):
        raise ValueError("One scalar score is required per observation")
    item = values[0]
    if isinstance(item, float) and not math.isfinite(item) or isinstance(item, Decimal) and not item.is_finite():
        raise ValueError("Score must be finite")
    result = _oscal_property_values(item)[0]
    if result.lower() in {"infinity", "+infinity", "-infinity"}:
        raise ValueError("Score must be finite")
    return result


def _metadata_text(value, label):
    if not isinstance(value, str) or not value.strip():
        raise ValueError(label + " must be nonblank text")
    return value


def _metadata_transform(row, value, context):
    transform, params = row["TRANSFORM_ID"], row.get("TRANSFORM_PARAMS") or {}
    if transform == "skip" or not _has_value(value):
        return SKIP_VALUE
    if transform == "direct":
        return _to_python(value)
    if transform in {"text", "timestamp", "canonical-text"}:
        value = _metadata_text(_to_python(value), "Mapped value")
        if transform == "canonical-text" and value != value.strip():
            raise ValueError("Controlled value must be canonical text")
        return value
    if transform == "date":
        return transform_authorization_date(value)
    if transform == "identifier":
        return transform_document_identifier(value)
    if transform == "archer-select":
        result = resolve_archer_select_value(value, context)
        return result if _has_value(result) else SKIP_VALUE
    if transform == "scalar-score":
        return _score_value(value, context)
    if transform == "security-objective":
        result = transform_fips_199(value, context)
        if isinstance(result, list):
            raise ValueError("Security objective resolved to multiple values")
        if _has_value(result):
            return str(result)
        label = _single_archer_label(value, context)
        if label is None or label not in params.get("approved_legacy_values", ()):
            raise ValueError("Security objective contains an unreviewed label")
        return label
    if transform == "status-crosswalk":
        label = _single_archer_label(value, context)
        if label is None:
            raise ValueError("Crosswalk source label is unresolved or multivalued")
        target = params["crosswalk"].get(_stable_property_name(label))
        if target is None:
            raise ValueError("Label is absent from reviewed crosswalk")
        result = {"state": target}
        if target == "other":
            result["remarks"] = params["other_remarks_prefix"] + label + params.get("other_remarks_suffix", ".")
        return result
    raise ValueError("Populated source has no reviewed transformation")


def _metadata_mapped_value(row, source_obj, context):
    field, params = row["SOURCE_FIELD_NAME"], _metadata_params(row)
    raw = context["config"].get(field) if params.get("value_source") == "CONFIG" else resolve_json_path(source_obj, field)
    try:
        value = _metadata_transform(row, raw, context)
        if params.get("required") and (value is SKIP_VALUE or not _has_value(value)):
            raise ValueError("Required mapped value is absent after conversion")
    except (TypeError, ValueError, ArithmeticError):
        context["graph_report"]["STATUS"] = "BLOCKED"
        raise ValueError("Mapping failed for field " + field + " (" + str(row.get("RULE_ID", "")) + ")") from None
    context["graph_report"]["MISSING_VALUES" if value is SKIP_VALUE else "MAPPED_VALUES"] += 1
    return value


def _metadata_assign(payload, target, value, preserve_existing=False):
    current, tokens = payload, target.split(".")
    for token in tokens[:-1]:
        current = current.setdefault(token, {})
        if not isinstance(current, dict):
            raise ValueError("Nested payload member conflicts with scalar")
    member = tokens[-1]
    if member in current and current[member] != value:
        if preserve_existing:
            return
        raise ValueError("Singleton target has conflicting populated mappings")
    current[member] = value


def _metadata_get(payload, target):
    current = payload
    for token in target.split("."):
        current = current.get(token) if isinstance(current, dict) else None
    return current


def _metadata_parent_key(parameters, source_record_id):
    rule = parameters.get("parent_instance_rule")
    if rule == "source-record":
        return source_record_id
    return "singleton" if rule == "singleton" else None


def _append_unique_collection_instance(instances, instance):
    for existing in instances:
        if existing["instance_key"] == instance["instance_key"]:
            if existing["payload"] != instance["payload"]:
                raise ValueError("Collection identity resolves to conflicting payloads")
            return
    instances.append(instance)


def _party_reference_identifier(item):
    item = _to_python(item)
    if isinstance(item, dict):
        item = item.get("Id") or item.get("UserId") or item.get("ContentId")
        if not _has_value(item):
            raise ValueError("Responsible-party reference has no stable identifier")
        return str(item).strip()
    return _scalar_text(item, "Responsible-party reference identifier is invalid", "Responsible-party reference identifier is empty")


def _component_reference_content_ids(value):
    result = []
    for item in (value if isinstance(value, list) else [value]):
        item = _to_python(item)
        item = item.get("ContentId") if isinstance(item, dict) else item
        result.append(_scalar_text(item, "Component reference has invalid ContentId", "Component reference has invalid ContentId"))
    return result


def _component_text(value, label, required):
    if value is None or isinstance(value, str) and not value.strip():
        if required:
            raise ValueError("Component hydration " + label + " is missing")
        return None
    if not isinstance(value, str):
        raise ValueError("Component hydration " + label + " must be text")
    return value.strip()


def _build_component_hydration_lookups(source_df, mapping_rows, source_dfs, context):
    """Stream frozen references once; fetch only needed lookup IDs in bounded SQL batches."""
    from snowflake.snowpark import functions as F
    contracts, fields = {}, {}
    for row in mapping_rows:
        params = _metadata_params(row)
        kind, binding = params["reference_type"], params.get("hydrate_lookup")
        if not binding:
            continue
        contract = dict(context["lookups"]["component_contract"][binding], binding=binding,
                        description_required=bool(params.get("description_required")))
        if contracts.setdefault(kind, contract) != contract:
            raise ValueError("Reference type has contradictory hydration contracts")
        fields[row["SOURCE_FIELD_NAME"]] = kind
    if not fields:
        return {}
    ids, types = {kind: set() for kind in contracts}, {}
    for record in source_df.to_local_iterator():
        source = _metadata_parse(record, context)
        for field, kind in fields.items():
            value = resolve_json_path(source, field)
            if not _has_value(value):
                continue
            if not isinstance(value, list):
                raise ValueError("Approved component reference root must be an array")
            for identifier in _component_reference_content_ids(value):
                if types.setdefault(identifier, kind) != kind:
                    raise ValueError("Component hydration identity has a type collision")
                ids[kind].add(identifier)
    lookups = {}
    for kind, contract in contracts.items():
        frame = source_dfs[contract["binding"]]
        columns = {str(name).strip('"').upper(): name for name in frame.columns}
        identifier_col = F.trim(F.col(columns["CONTENT_ID"]).cast("string"))
        identifiers, found = sorted(ids[kind]), {}
        for start in range(0, len(identifiers), 1000):
            batch = frame.filter(identifier_col.isin(identifiers[start:start + 1000])).select(
                identifier_col.alias("CONTENT_ID"), F.col(columns["CURATED_JSON"]).alias("CURATED_JSON"))
            for record in batch.to_local_iterator():
                identifier = record["CONTENT_ID"]
                if identifier in found:
                    raise ValueError("Component lookup contains duplicate ContentId values")
                payload = _metadata_parse(record, context)
                found[identifier] = {
                    "title": _component_text(resolve_json_path(payload, contract["title_field"]), "title", True),
                    "description": _component_text(resolve_json_path(payload, contract["description_field"]),
                                                   "description", contract["description_required"]),
                }
        if found.keys() != ids[kind]:
            raise ValueError("Component hydration lookup record is missing")
        lookups[kind] = found
    return lookups


def _metadata_party_uuid(group, source_record_id, identifier, context):
    # Cell 3 permits one source namespace per linked model; preserve its accepted seed.
    return _deterministic_uuid(context["config"]["SOURCE_SYSTEM_NAME"], source_record_id, "party", identifier)


def _metadata_party_instances(path, source_obj, source_id, operator, parameters, context):
    group = next(group for group in context["compiled_plan"]["reference_groups"]
                 if path in (group["roles_path"], group["parties_path"], group["assignments_path"]))
    cache = context.setdefault("_metadata_reference_cache", {})
    if group["assignments_path"] not in cache:
        roles, parties, assignments = {}, {}, {}
        for row in context["mappings_by_path"].get(group["assignments_path"], ()):
            value = _metadata_mapped_value(row, source_obj, context)
            if value is SKIP_VALUE:
                continue
            params, extracted = _metadata_params(row), _extract_reference_ids(value)
            members = extracted if isinstance(extracted, list) else [extracted]
            party_ids = dict.fromkeys(_metadata_party_uuid(group, source_id, _party_reference_identifier(item), context)
                                      for item in members if item is not None)
            if not party_ids:
                continue
            role, title = params["role_id"], params["role_title"]
            if roles.setdefault(role, title) != title:
                raise ValueError("Role identity resolves to conflicting titles")
            parties.update(dict.fromkeys(party_ids, group["party_type"]))
            field, references = assignments.setdefault(role, (row["SOURCE_FIELD_NAME"], {}))
            references.update(party_ids)
        cache[group["assignments_path"]] = {
            "roles": [(key, {"id": key, "title": title}) for key, title in roles.items()],
            "parties": [(key, {"uuid": key, "type": kind}) for key, kind in parties.items()],
            "assignments": [(field, {"role-id": role, "party-uuids": list(references)})
                            for role, (field, references) in assignments.items()],
        }
    return [{"instance_key": key, "payload": payload,
             "parent_instance_key": _metadata_parent_key(parameters, source_id)}
            for key, payload in cache[group["assignments_path"]][operator]]


def _metadata_reference_instances(source_obj, source_id, rows, parameters, context):
    references = {}
    for row in rows:
        value, params = _metadata_mapped_value(row, source_obj, context), _metadata_params(row)
        if value is SKIP_VALUE:
            continue
        for identifier in _component_reference_content_ids(value):
            previous = references.get(identifier)
            if previous and previous["reference_type"] != params["reference_type"]:
                raise ValueError("Referenced identity has contradictory types")
            if previous is None or params.get("hydrate_lookup"):
                references[identifier] = params
    result = []
    for identifier, params in sorted(references.items()):
        payload = {"type": params["reference_type"]}
        if params.get("hydrate_lookup"):
            hydrated = context["component_hydration_lookups"][params["reference_type"]][identifier]
            payload["title"] = hydrated["title"]
            if hydrated["description"] is not None:
                payload["description"] = hydrated["description"]
        result.append({"instance_key": identifier, "payload": payload,
                       "parent_instance_key": _metadata_parent_key(parameters, source_id)})
    return result


def _metadata_instances(source_obj, source_id, registry_row, context):
    path = registry_row["element_path"]
    specification = context["compiled_plan"]["elements"].get(path)
    if specification is None:
        return []
    operator, parameters = specification["operator"], specification["parameters"]
    rows, parent = context["mappings_by_path"].get(path, ()), _metadata_parent_key(parameters, source_id)
    if operator in {"roles", "parties", "assignments"}:
        return _metadata_party_instances(path, source_obj, source_id, operator, parameters, context)
    if operator == "references":
        return _metadata_reference_instances(source_obj, source_id, rows, parameters, context)
    payload, instances, crosswalks = {}, [], []
    for row in rows:
        value = _metadata_mapped_value(row, source_obj, context)
        if value is SKIP_VALUE:
            continue
        field, target = row["SOURCE_FIELD_NAME"], _metadata_target(row)
        if operator in {"properties", "observations"}:
            values = _oscal_property_values(value)
            if operator == "observations" and len(values) != 1:
                raise ValueError("One scalar value is required per observation")
            for item in values:
                prop = {"name": _stable_property_name(field), "value": item}
                item_payload = {"props": [prop]} if operator == "observations" else prop
                key = field if operator == "observations" else field + ":" + _deterministic_hash("source-field-value-v1", field, item)
                _append_unique_collection_instance(instances, {"instance_key": key, "payload": item_payload,
                                                               "parent_instance_key": parent})
        elif operator == "values":
            for member in (value if isinstance(value, list) else [value]):
                item_payload = copy.deepcopy(member) if isinstance(member, dict) else {}
                raw = _metadata_get(item_payload, target) if isinstance(member, dict) else member
                values = _oscal_property_values(raw)
                if len(values) != 1:
                    raise ValueError("Value identity requires exactly one scalar")
                normalized = values[0]
                cursor, tokens = item_payload, target.split(".")
                for token in tokens[:-1]:
                    cursor = cursor.setdefault(token, {})
                cursor[tokens[-1]] = normalized
                _append_unique_collection_instance(instances, {"instance_key": _deterministic_hash("value-v1", normalized),
                                                               "payload": item_payload, "parent_instance_key": parent})
        elif row["TRANSFORM_ID"] == "status-crosswalk":
            crosswalks.append(value)
        else:
            _metadata_assign(payload, target, value)
    for members in crosswalks:
        for member, value in members.items():
            _metadata_assign(payload, member, value, preserve_existing=member == "remarks")
    if any(not _has_value(_metadata_get(payload, member)) for member in parameters.get("required_members", ())):
        if parameters.get("optional_assembly"):
            return []
        raise ValueError("Required payload member is missing")
    if operator in {"object", "record"} and (payload or parameters.get("materialize_empty") or operator == "record"):
        instances.append({"instance_key": source_id if operator == "record" else "singleton",
                          "payload": payload, "parent_instance_key": parent})
    return instances


def _metadata_uuid(path, instance, source_system, source_table, source_id, model_key, context):
    if context["compiled_plan"]["elements"][path]["parameters"].get("uuid_from_instance"):
        return instance["instance_key"]
    return _deterministic_uuid(context["config"]["IDENTITY_VERSION"], source_system,
                               source_table, source_id, model_key, path, instance["instance_key"])


def _metadata_payload(path, payload, node_uuid, context):
    if context["compiled_plan"]["elements"][path]["parameters"].get("include_uuid"):
        if payload.get("uuid") not in (None, "", node_uuid):
            raise ValueError("Payload UUID conflicts with node UUID")
        return dict(payload, uuid=node_uuid)
    return payload


def _metadata_record_complete(nodes_by_path, context):
    # Linked collections were built together from the same role/party sets.
    context.pop("_metadata_reference_cache", None)


def _element_type(path):
    return path.rsplit(".", 1)[-1].replace("[]", "")


def _canonical_registry_rows(element_registry_df, model_key, context):
    rows = []
    for row in context["registry_rows"]:
        path = _registry_path(row)
        rows.append({"element_path": path, "element_type": row.get("ELEMENT_TYPE") or _element_type(path),
                     "parent_path": row.get("PARENT_NODE_PATH") or None, "level": path.count(".") + 1,
                     "process_order": row.get("PROCESS_ORDER"), "is_collection": _registry_meta_bool(row, "IS_COLLECTION")})
    return sorted(rows, key=lambda row: (row["level"], row["process_order"] if row["process_order"] is not None else 0,
                                         row["element_path"]))


def _metadata_parse(record, context):
    value, options = _to_python(record["CURATED_JSON"]), context["compiled_plan"].get("options", {})
    if value is None and options.get("null_source_as_empty", False):
        return {}
    if isinstance(value, str):
        value = json.loads(value, parse_float=Decimal) if options.get("parse_decimal", True) else json.loads(value)
    if not isinstance(value, dict):
        raise ValueError("Source JSON must resolve to an object")
    return value


def _prepare_model_context(context, model_key, source_system, source_table):
    if context["compiled_plan"].get("release") != "lean-csv-registry-v1":
        raise ValueError("Run the matching lean Cell 3 before building the graph")
    config = context["config"]
    if (config["OSCAL_MODEL"], config["SOURCE_SYSTEM_NAME"], config["SOURCE_TABLE_NAME"]) != (model_key, source_system, source_table):
        raise ValueError("Graph arguments conflict with compiled metadata context")
    context.pop("_metadata_reference_cache", None)
    context["graph_report"] = {"SOURCE_RECORDS": 0, "INVALID_SOURCE_RECORDS": 0, "DUPLICATE_SOURCE_RECORDS": 0,
                               "MAPPED_VALUES": 0, "MISSING_VALUES": 0, "STATUS": "NOT_RUN", "OUTPUTS_PUBLISHED": False}
    return context


def _metadata_prepare(source_df, context):
    plan = context["compiled_plan"]
    references = [row for row in plan["mappings"] if row["TRANSFORM_ID"] != "skip"
                  and plan["elements"][row["OWNER_ELEMENT_PATH"]]["operator"] == "references"]
    context["component_hydration_lookups"] = _build_component_hydration_lookups(
        source_df, references, context["lookups"].get("component_sources", {}), context) if references else {}


def _metadata_finish(nodes, edges, context):
    report = context["graph_report"]
    if not report["SOURCE_RECORDS"] or report["INVALID_SOURCE_RECORDS"] or report["DUPLICATE_SOURCE_RECORDS"]:
        report["STATUS"] = "BLOCKED"
        raise ValueError("Source is empty or contains invalid or duplicate record identities")
    report.update(STATUS="MAPPED_SCOPE_BUILT", OUTPUTS_PUBLISHED=True, NODES=len(nodes), EDGES=len(edges),
                  DOCUMENTS=report["SOURCE_RECORDS"], FULL_MODEL_COMPLETE=False, SCHEMA_VALIDATED=False)


print("Cell 4 transforms and registry operators ready")


# %% Cell 5 - Build nodes and parent-child edges

def _create_canonical_graph_frame(rows, kind):
    columns = (
        "NODE_KEY", "ELEMENT_PATH", "PARENT_NODE_PATH", "INSTANCE_KEY", "PARENT_INSTANCE_KEY", "OSCAL_UUID",
        "ELEMENT_TYPE", "METADATA_JSON", "SOURCE_SYSTEM_NAME", "SOURCE_TABLE_NAME",
        "SOURCE_RECORD_ID", "DW_PIPELINE_RUN_ID", "DW_LOAD_TIMESTAMP", "DW_LOAD_TIMESTAMP_TZ",
    ) if kind == "nodes" else (
        "EDGE_KEY", "FK_SOURCE_ELEMENT_HASH", "FK_TARGET_ELEMENT_HASH", "DEPENDENCY_TYPE",
        "SOURCE_OSCAL_UUID", "TARGET_OSCAL_UUID",
    )
    schema = StructType([StructField(name, TimestampType(TimestampTimeZone.TZ)
                        if name in {"DW_LOAD_TIMESTAMP", "DW_LOAD_TIMESTAMP_TZ"} else StringType())
                         for name in columns])
    return session.create_dataframe([tuple(row.get(name) for name in columns) for row in rows], schema=schema)


def build_oscal_graph(source_df, canonical_mapping_df, element_registry_df,
                      model_key, source_system, source_table, context=None):
    context = _prepare_model_context(context, model_key, source_system, source_table)
    config, report = context["config"], context["graph_report"]
    registry = _canonical_registry_rows(element_registry_df, model_key, context)
    root = context["model_contract"]["ROOT_PATH"]
    context["root_element_type"] = next(row["element_type"] for row in registry if row["element_path"] == root)
    _metadata_prepare(source_df, context)
    nodes, edges, records = [], [], set()
    timestamp = datetime.datetime.now(datetime.timezone.utc)
    for record in source_df.to_local_iterator():
        record_id = record["SOURCE_RECORD_ID"]
        if not isinstance(record_id, str) or not record_id.strip() or record_id != record_id.strip():
            raise ValueError("Source record identity must be a nonblank canonical string")
        if record_id in records:
            raise ValueError("Duplicate source record identity")
        records.add(record_id)
        report["SOURCE_RECORDS"] += 1
        source = _metadata_parse(record, context)
        by_path = {}
        for row in registry:
            path, parent_path = row["element_path"], row["parent_path"]
            instances = {}
            by_path[path] = instances
            for item in _metadata_instances(source, record_id, row, context):
                key = item["instance_key"]
                if not isinstance(key, str) or not key.strip() or key in instances:
                    raise ValueError("Element instances require unique nonblank identities")
                node_key = _deterministic_hash(config["IDENTITY_VERSION"], source_system,
                                               source_table, record_id, model_key, path, key)
                node_uuid = _metadata_uuid(path, item, source_system, source_table, record_id, model_key, context)
                payload = _metadata_payload(path, item["payload"], node_uuid, context)
                if not isinstance(payload, dict):
                    raise ValueError("An element payload must be an object")
                node = {
                    "NODE_KEY": node_key, "ELEMENT_PATH": path, "PARENT_NODE_PATH": parent_path, "INSTANCE_KEY": key,
                    "PARENT_INSTANCE_KEY": item.get("parent_instance_key"), "OSCAL_UUID": node_uuid,
                    "ELEMENT_TYPE": row["element_type"],
                    "METADATA_JSON": json.dumps(payload, sort_keys=True, default=str, allow_nan=False),
                    "SOURCE_SYSTEM_NAME": source_system, "SOURCE_TABLE_NAME": source_table,
                    "SOURCE_RECORD_ID": record_id, "DW_PIPELINE_RUN_ID": config["RUN_ID"],
                    "DW_LOAD_TIMESTAMP": timestamp, "DW_LOAD_TIMESTAMP_TZ": timestamp,
                }
                instances[key] = node
                nodes.append(node)
                if not parent_path:
                    continue
                parents = by_path.get(parent_path, {})
                parent_key = item.get("parent_instance_key")
                parent = parents.get(parent_key) if parent_key is not None else (
                    next(iter(parents.values())) if len(parents) == 1 else None)
                if parent is None:
                    raise ValueError("Missing or ambiguous parent instance for " + path)
                edges.append({
                    "EDGE_KEY": _deterministic_hash("edge-v1", parent["NODE_KEY"], node_key, "CONTAINS"),
                    "FK_SOURCE_ELEMENT_HASH": parent["NODE_KEY"], "FK_TARGET_ELEMENT_HASH": node_key,
                    "DEPENDENCY_TYPE": "CONTAINS", "SOURCE_OSCAL_UUID": parent["OSCAL_UUID"],
                    "TARGET_OSCAL_UUID": node_uuid,
                })
        _metadata_record_complete({path: list(values.values()) for path, values in by_path.items()}, context)
    if not nodes:
        raise ValueError("Graph builder produced no nodes")
    _metadata_finish(nodes, edges, context)
    return _create_canonical_graph_frame(nodes, "nodes"), _create_canonical_graph_frame(edges, "edges")


# %% Cell 6 - Validate once, preview, then atomically upsert the reviewed tables
# Pause other target writers during COMMIT; the snapshots detect changes but do not lock tables.
import json
import re
import uuid

OSCAL_LOAD_RELEASE = "oscal-lean-daily-v3"
_AUDIT = {"DW_PIPELINE_RUN_ID", "DW_LOAD_TIMESTAMP", "DW_LOAD_TIMESTAMP_TZ"}
_DIM_FIELDS = {
    "ELEMENT_TYPE": "VARCHAR(64)", "OSCAL_UUID": "VARCHAR(32)", "METADATA_JSON": "VARIANT",
    "SOURCE_SYSTEM_NAME": "VARCHAR(100)", "SOURCE_TABLE_NAME": "VARCHAR(128)",
    "SOURCE_RECORD_ID": "VARCHAR(128)", "DW_PIPELINE_RUN_ID": "VARCHAR(64)",
    "DW_LOAD_TIMESTAMP": "TIMESTAMP_TZ(9)", "DW_LOAD_TIMESTAMP_TZ": "TIMESTAMP_TZ(9)",
}
_FACT_FIELDS = {
    "FK_SOURCE_ELEMENT_HASH": "BINARY(16)", "FK_TARGET_ELEMENT_HASH": "BINARY(16)",
    "DEPENDENCY_TYPE": "VARCHAR(32)", "SOURCE_OSCAL_UUID": "VARCHAR(32)",
    "TARGET_OSCAL_UUID": "VARCHAR(32)",
}


class LoadError(RuntimeError):
    def __init__(self, code, details=None):
        self.code, self.details = code, details or {}
        super().__init__(code)


def _load_query(statement):
    return session.sql(statement).collect()


def _load_count(statement):
    return int(_load_query(statement)[0]["N"])


def _load_zero(statement, code):
    count = _load_count(statement)
    if count:
        raise LoadError(code, {"COUNT": count})


def _load_identifier(value):
    if not isinstance(value, str) or not re.fullmatch(r"[A-Z][A-Z0-9_]*(?:\.[A-Z][A-Z0-9_]*){0,2}", value):
        raise LoadError("INVALID_STORAGE_IDENTIFIER")
    return value


def _load_literal(value):
    if not isinstance(value, str) or not value.strip():
        raise LoadError("MISSING_CONFIGURATION_VALUE")
    return "'" + value.replace("'", "''") + "'"


def _load_no_transaction():
    if _load_query("SELECT CURRENT_TRANSACTION() AS TX")[0]["TX"] is not None:
        raise LoadError("EXISTING_TRANSACTION")


def _load_storage(config):
    if type(config.get("EXECUTE_WRITES")) is not bool:
        raise LoadError("EXPLICIT_BOOLEAN_WRITE_MODE_REQUIRED")
    if config.get("OBSOLETE_ROW_POLICY", "BLOCK") != "BLOCK":
        raise LoadError("ONLY_BLOCK_OBSOLETE_POLICY_IS_APPROVED")
    storage = config.get("STORAGE_CONTRACT")
    if not storage or storage.get("VERIFIED") is not True:
        if config["EXECUTE_WRITES"]:
            raise LoadError("STORAGE_CONTRACT_NOT_VERIFIED")
        return None
    storage = dict(storage)
    if storage.get("PHYSICAL_PROFILE") != "BINARY16_UUID32":
        raise LoadError("UNSUPPORTED_STORAGE_PROFILE")
    for name in ("TARGET_DIM", "TARGET_FACT", "DIM_PK_COLUMN", "FACT_PK_COLUMN"):
        _load_identifier(storage[name])
        if storage[name].count(".") != (2 if name.startswith("TARGET_") else 0):
            raise LoadError("INVALID_STORAGE_IDENTIFIER")
        if config.get(name, storage[name]) != storage[name]:
            raise LoadError("CONFIG_STORAGE_MISMATCH")
    if storage["TARGET_DIM"] == storage["TARGET_FACT"]:
        raise LoadError("DIM_AND_FACT_TARGETS_MUST_DIFFER")
    if storage["DIM_PK_COLUMN"] in _DIM_FIELDS or storage["FACT_PK_COLUMN"] in _FACT_FIELDS:
        raise LoadError("PRIMARY_KEY_COLUMN_CONFLICT")
    for name in ("SOURCE_SYSTEM_NAME", "SOURCE_TABLE_NAME", "RAW_TABLE", "IDENTITY_VERSION",
                 "ROOT_PATH", "ROOT_ELEMENT_TYPE", "MODEL_KEY"):
        value = config.get("OSCAL_MODEL" if name == "MODEL_KEY" else name)
        if value != storage.get(name) or not isinstance(value, str) or not value:
            raise LoadError("CONFIG_STORAGE_MISMATCH")
    return storage


def _load_graph(nodes, edges, config):
    """One graph boundary for both stored and targetless models; reports contain counts only."""
    def rows(frame):
        values = frame.to_local_iterator() if hasattr(frame, "to_local_iterator") else iter(frame)
        return (value.as_dict() if hasattr(value, "as_dict") else dict(value) for value in values)
    def key(value):
        if not isinstance(value, str) or not re.fullmatch(r"[0-9a-fA-F]{32}", value):
            raise LoadError("INVALID_GRAPH_HASH")
        return value.lower()
    root = config["ROOT_PATH"]
    by_key, roots, parents, uuids = {}, {}, {}, set()
    for node in rows(nodes):
        k, sid, path = key(node.get("NODE_KEY")), node.get("SOURCE_RECORD_ID"), node.get("ELEMENT_PATH")
        if k in by_key:
            raise LoadError("DUPLICATE_NODE_KEY")
        if not isinstance(sid, str) or not sid.strip() or not isinstance(path, str):
            raise LoadError("MISSING_GRAPH_RECORD_OR_PATH")
        if not (path == root or path.startswith(root + ".")):
            raise LoadError("WRONG_MODEL_PATH")
        parent_path = node.get("PARENT_NODE_PATH")
        if "PARENT_NODE_PATH" not in node or (path == root and parent_path is not None) or (
                path != root and (not isinstance(parent_path, str) or not path.startswith(parent_path + "."))):
            raise LoadError("MISSING_OR_INVALID_PARENT_PATH")
        element_type = node.get("ELEMENT_TYPE")
        if (not isinstance(element_type, str) or not element_type.strip()
                or (path == root and element_type != config["ROOT_ELEMENT_TYPE"])):
            raise LoadError("WRONG_NODE_TYPE_OR_SOURCE")
        if node.get("MODEL_KEY", config["OSCAL_MODEL"]) != config["OSCAL_MODEL"] or any(
                node.get(name) != config[name] for name in ("SOURCE_SYSTEM_NAME", "SOURCE_TABLE_NAME")):
            raise LoadError("WRONG_NODE_TYPE_OR_SOURCE")
        identity, instance = node.get("OSCAL_UUID"), node.get("INSTANCE_KEY")
        if not isinstance(identity, str) or not re.fullmatch(r"[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}", identity):
            raise LoadError("INVALID_NODE_UUID")
        if identity in uuids:
            raise LoadError("DUPLICATE_NODE_UUID")
        uuids.add(identity)
        if not isinstance(instance, str) or not instance.strip():
            raise LoadError("MISSING_INSTANCE_KEY")
        try:
            payload = node.get("METADATA_JSON")
            payload = json.loads(payload) if isinstance(payload, str) else payload
            if not isinstance(payload, dict):
                raise ValueError()
            json.dumps(payload, allow_nan=False)
        except (ValueError, TypeError):
            raise LoadError("INVALID_NODE_PAYLOAD") from None
        by_key[k] = (sid, path, identity, instance, node.get("PARENT_INSTANCE_KEY"), parent_path)
        parents[k] = 0
        if path == root:
            if sid in roots:
                raise LoadError("DUPLICATE_RECORD_ROOT")
            roots[sid] = k
    if not roots or config.get("EXPECTED_SOURCE_RECORDS", len(roots)) != len(roots):
        raise LoadError("SOURCE_RECORD_GRAPH_COVERAGE_MISMATCH")
    edge_keys = set()
    for edge in rows(edges):
        ek = key(edge.get("EDGE_KEY"))
        if ek in edge_keys:
            raise LoadError("DUPLICATE_EDGE_KEY")
        edge_keys.add(ek)
        source, target = key(edge.get("FK_SOURCE_ELEMENT_HASH")), key(edge.get("FK_TARGET_ELEMENT_HASH"))
        if source not in by_key or target not in by_key:
            raise LoadError("ORPHAN_EDGE")
        parent, child = by_key[source], by_key[target]
        if parent[0] != child[0] or parent[0] not in roots:
            raise LoadError("CROSS_RECORD_EDGE")
        if (edge.get("DEPENDENCY_TYPE") != "CONTAINS" or edge.get("SOURCE_OSCAL_UUID") != parent[2]
                or edge.get("TARGET_OSCAL_UUID") != child[2]):
            raise LoadError("EDGE_RELATIONSHIP_OR_UUID_MISMATCH")
        if (not child[1].startswith(parent[1] + ".") or (child[4] is not None and child[4] != parent[3])
                or child[5] != parent[1]):
            raise LoadError("WRONG_PARENT_CONTEXT")
        parents[target] += 1
    root_keys = set(roots.values())
    if any(count != (0 if k in root_keys else 1) for k, count in parents.items()):
        raise LoadError("WRONG_PARENT_COUNT")
    # Paths strictly descend and each non-root has one parent: cycles and disconnected nodes are impossible.
    return {"nodes": len(by_key), "edges": len(edge_keys), "source_records": len(roots)}


def _load_schema(table, pk, fields, kind):
    expected = {pk: "BINARY(16)", **fields}
    actual = {}
    for row in _load_query("DESC TABLE " + table):
        row = row.as_dict() if hasattr(row, "as_dict") else dict(row)
        row = {str(k).lower(): value for k, value in row.items()}
        name = row["name"]
        nullable = "N" if kind == "FACT" or name == pk else "Y"
        if (name in actual or row.get("kind") != "COLUMN" or row.get("null?") != nullable
                or row.get("expression") not in (None, "")):
            raise LoadError("TARGET_SCHEMA_MISMATCH", {"TABLE_KIND": kind})
        actual[name] = row["type"].upper().replace(" ", "")
    if actual != expected:
        raise LoadError("TARGET_SCHEMA_MISMATCH", {"TABLE_KIND": kind})
    return tuple(expected)


def _load_changed(columns, left="t", right="s", audit=False):
    return " OR ".join(f"{left}.{name} IS DISTINCT FROM {right}.{name}"
                       for name in columns if audit or name not in _AUDIT)


def _load_changes(target, stage, pk, columns):
    changed = _load_changed(columns)
    row = _load_query(f"""SELECT
      COUNT_IF(t.{pk} IS NULL) AS INSERTS,
      COUNT_IF(t.{pk} IS NOT NULL AND ({changed})) AS UPDATES,
      COUNT_IF(t.{pk} IS NOT NULL AND NOT ({changed})) AS UNCHANGED
      FROM {stage} s LEFT JOIN {target} t ON t.{pk}=s.{pk}""")[0]
    return {name: int(row[name] or 0) for name in ("INSERTS", "UPDATES", "UNCHANGED")}


def _load_merge(target, stage, pk, columns):
    assignments = ", ".join(f"t.{name}=s.{name}" for name in columns if name != pk)
    return (f"MERGE INTO {target} t USING {stage} s ON t.{pk}=s.{pk} "
            f"WHEN MATCHED AND ({_load_changed(columns)}) THEN UPDATE SET {assignments} "
            f"WHEN NOT MATCHED THEN INSERT ({', '.join(columns)}) "
            f"VALUES ({', '.join('s.' + name for name in columns)})")


def _load_equal(left, right, code):
    for first, second in ((left, right), (right, left)):
        _load_zero(f"SELECT COUNT(*) AS N FROM (({first}) MINUS ({second}))", code)


def _load_scope(context):
    c, names = context["storage"], context["names"]
    dim, fact, dk, fk = (c[name] for name in ("TARGET_DIM", "TARGET_FACT", "DIM_PK_COLUMN", "FACT_PK_COLUMN"))
    source = " AND ".join(f"t.{name}={_load_literal(c[name])}" for name in ("SOURCE_SYSTEM_NAME", "SOURCE_TABLE_NAME"))
    dim_query = f"""SELECT t.* FROM {dim} t LEFT JOIN {names['D']} s ON s.{dk}=t.{dk}
      LEFT JOIN (SELECT DISTINCT SOURCE_RECORD_ID FROM {names['D']}) i
      ON i.SOURCE_RECORD_ID=t.SOURCE_RECORD_ID AND {source}
      WHERE s.{dk} IS NOT NULL OR i.SOURCE_RECORD_ID IS NOT NULL"""
    keys = f"SELECT {dk} FROM ({dim_query}) UNION SELECT {dk} FROM {names['D']}"
    fact_query = f"""SELECT t.* FROM {fact} t LEFT JOIN {names['F']} s ON s.{fk}=t.{fk}
      LEFT JOIN ({keys}) p ON p.{dk}=t.FK_SOURCE_ELEMENT_HASH
      LEFT JOIN ({keys}) c ON c.{dk}=t.FK_TARGET_ELEMENT_HASH
      WHERE s.{fk} IS NOT NULL OR p.{dk} IS NOT NULL OR c.{dk} IS NOT NULL"""
    return dim_query, fact_query


def _load_preflight(context):
    c, names = context["storage"], context["names"]
    queries = _load_scope(context)
    for kind, query, fields in zip(("D", "F"), queries, (_DIM_FIELDS, _FACT_FIELDS)):
        table, pk, columns = context[kind]
        _load_zero(f"SELECT COUNT(*) AS N FROM (SELECT {pk} FROM {table} GROUP BY {pk} "
                   f"HAVING {pk} IS NULL OR COUNT(*)>1)", "TARGET_NULL_OR_DUPLICATE_KEYS")
        _load_zero(f"SELECT COUNT(*) AS N FROM ({query}) t WHERE NOT EXISTS "
                   f"(SELECT 1 FROM {names[kind]} s WHERE s.{pk}=t.{pk})", "OBSOLETE_TARGET_ROWS_BLOCKED")
        identity = [name for name in fields if name not in _AUDIT | {"METADATA_JSON"}]
        _load_zero(f"SELECT COUNT(*) AS N FROM ({query}) t JOIN {names[kind]} s ON s.{pk}=t.{pk} "
                   f"WHERE {_load_changed(identity)}", "TARGET_IDENTITY_PROVENANCE_CONFLICT")
    dim, fact = queries
    dk, fk = c["DIM_PK_COLUMN"], c["FACT_PK_COLUMN"]
    _load_zero(f"SELECT COUNT(*) AS N FROM ({dim}) WHERE NOT COALESCE(IS_OBJECT(METADATA_JSON), FALSE)",
               "INVALID_STORED_PAYLOAD")
    _load_zero(f"""SELECT COUNT(*) AS N FROM ({fact}) f
      LEFT JOIN ({dim}) p ON p.{dk}=f.FK_SOURCE_ELEMENT_HASH
      LEFT JOIN ({dim}) c ON c.{dk}=f.FK_TARGET_ELEMENT_HASH
      WHERE p.{dk} IS NULL OR c.{dk} IS NULL""", "TARGET_ORPHAN_OR_CROSS_SCOPE_EDGE")
    _load_zero(f"""SELECT COUNT(*) AS N FROM (SELECT d.{dk}, d.ELEMENT_TYPE, COUNT(f.{fk}) AS PARENTS
      FROM ({dim}) d LEFT JOIN ({fact}) f ON f.FK_TARGET_ELEMENT_HASH=d.{dk}
      GROUP BY d.{dk}, d.ELEMENT_TYPE HAVING PARENTS <>
      CASE WHEN d.ELEMENT_TYPE={_load_literal(c['ROOT_ELEMENT_TYPE'])} THEN 0 ELSE 1 END)""", "TARGET_WRONG_PARENT_COUNT")
    return queries


def _load_prepare(nodes, edges, config):
    storage = _load_storage(config)
    if storage is None:
        return {"graph": _load_graph(nodes, edges, config), "storage": None}
    _load_no_transaction()  # All materialization DDL must finish before BEGIN.
    context = {"storage": storage}
    for kind, table_key, pk_key, fields in (("D", "TARGET_DIM", "DIM_PK_COLUMN", _DIM_FIELDS),
                                           ("F", "TARGET_FACT", "FACT_PK_COLUMN", _FACT_FIELDS)):
        table, pk = storage[table_key], storage[pk_key]
        context[kind] = (table, pk, _load_schema(table, pk, fields, "DIM" if kind == "D" else "FACT"))
    prefix = storage["TARGET_DIM"].rsplit(".", 1)[0] + ".TMP_OSCAL_" + uuid.uuid4().hex.upper()
    names = {name: prefix + "_" + name for name in ("N", "E", "D", "F", "BD", "BF")}
    context["names"] = names
    for frame, name in ((nodes, names["N"]), (edges, names["E"])):
        frame.write.save_as_table(name, mode="errorifexists", table_type="temporary")
    context["graph"] = _load_graph(session.table(names["N"]), session.table(names["E"]), config)
    for kind, raw, source_pk, fields in (("D", "N", "NODE_KEY", _DIM_FIELDS), ("F", "E", "EDGE_KEY", _FACT_FIELDS)):
        _, pk, columns = context[kind]
        expressions = [f"TO_BINARY({source_pk}, 'HEX') AS {pk}"]
        for name, dtype in fields.items():
            value = (f"TO_BINARY({name}, 'HEX')" if dtype == "BINARY(16)" else
                     f"REPLACE({name}, '-', '')" if name.endswith("OSCAL_UUID") else
                     f"PARSE_JSON({name})" if dtype == "VARIANT" else
                     f"CAST({name} AS {dtype})" if dtype.startswith("TIMESTAMP_") else name)
            expressions.append(f"{value} AS {name}")
        _load_query(f"CREATE TEMPORARY TABLE {names[kind]} AS SELECT {', '.join(expressions)} FROM {names[raw]}")
        for name, dtype in fields.items():
            if dtype.startswith("VARCHAR"):
                width = int(dtype[8:-1])
                _load_zero(f"SELECT COUNT(*) AS N FROM {names[kind]} WHERE LENGTH({name})>{width}", "TARGET_STRING_CAPACITY_EXCEEDED")
        _load_query(f"CREATE TEMPORARY TABLE {names['B' + kind]} AS SELECT * FROM {context[kind][0]}")
    context["scope"] = _load_preflight(context)
    context["changes"] = {kind: _load_changes(context[kind][0], names[kind], context[kind][1], context[kind][2]) for kind in ("D", "F")}
    return context


def _load_baseline(context):
    for kind in ("D", "F"):
        table, _, columns = context[kind]
        grouped = ", ".join(columns)
        query = f"SELECT {grouped}, COUNT(*) AS ROW_MULTIPLICITY FROM {{}} GROUP BY {grouped}"
        _load_equal(query.format(table), query.format(context["names"]["B" + kind]), "TARGET_BASELINE_CHANGED")


def _load_verify(context):
    _load_preflight(context)
    names, report = context["names"], {}
    for kind in ("D", "F"):
        table, pk, columns = context[kind]
        changes = _load_changes(table, names[kind], pk, columns)
        if changes["INSERTS"] or changes["UPDATES"]:
            raise LoadError("SAVED_VALUES_OR_KEYS_DIFFER")
        same = "NOT (" + _load_changed(columns, "b", "s") + ")"
        _load_zero(f"""SELECT COUNT(*) AS N FROM {names[kind]} s JOIN {table} t ON t.{pk}=s.{pk}
          LEFT JOIN {names['B' + kind]} b ON b.{pk}=s.{pk}
          WHERE (b.{pk} IS NOT NULL AND ({same}) AND ({_load_changed(columns, 't', 'b', True)}))
          OR ((b.{pk} IS NULL OR NOT ({same})) AND ({_load_changed(columns, audit=True)}))""", "SAVED_AUDIT_VALUES_DIFFER")
        untouched = f"WHERE NOT EXISTS (SELECT 1 FROM {names[kind]} s WHERE s.{pk}=t.{pk})"
        _load_equal(f"SELECT t.* FROM {table} t {untouched}",
                    f"SELECT t.* FROM {names['B' + kind]} t {untouched}", "UNTOUCHED_ROWS_CHANGED")
        report["DIM" if kind == "D" else "FACT"] = changes
    return report


def validate_and_load_oscal(canonical_nodes_df, canonical_edges_df, config):
    config = dict(config)
    result = {"release": OSCAL_LOAD_RELEASE, "model": config.get("OSCAL_MODEL"),
              "mode": "COMMIT" if config.get("EXECUTE_WRITES") is True else "PREVIEW",
              "writes_executed": False, "persisted": False, "committed": False,
              "target_dml_attempted": False, "pre_write_validation_passed": False}
    phase, context = "PREPARATION", None
    try:
        context = _load_prepare(canonical_nodes_df, canonical_edges_df, config)
        result.update(context["graph"], validation_passed=True, storage_verified=context["storage"] is not None)
        if context["storage"] is None:
            result["status"] = "MAPPED_GRAPH_VALIDATED_TARGET_CONTRACT_PENDING"
            return result
        result.update(pre_write_validation_passed=True, expected_changes=context["changes"])
        if not config["EXECUTE_WRITES"]:
            result["status"] = "PREVIEW_PASSED_NO_TARGET_DML"
            return result
        _load_no_transaction()
        phase = "BEGIN"
        _load_query("BEGIN TRANSACTION")
        phase = "TRANSACTION"
        try:
            _load_baseline(context)
            _load_preflight(context)
            for kind in ("D", "F"):
                target, pk, columns = context[kind]
                result["target_dml_attempted"] = True
                counts = _load_query(_load_merge(target, context["names"][kind], pk, columns))[0]
                expected = context["changes"][kind]
                if (int(counts["number of rows inserted"]), int(counts["number of rows updated"])) != (expected["INSERTS"], expected["UPDATES"]):
                    raise LoadError("UNEXPECTED_MERGE_CHANGE_COUNT")
            _load_verify(context)  # Zero remaining inserts/updates proves a rerun will be unchanged.
        except BaseException as error:
            result["cause"] = error.code if isinstance(error, LoadError) else type(error).__name__
            phase = "ROLLBACK"
            _load_query("ROLLBACK")
            phase = "ROLLBACK_READBACK"
            _load_baseline(context)
            result["rollback_readback_verified"] = True
            phase = "ROLLED_BACK"
            raise LoadError("TRANSACTION_ROLLED_BACK") from None
        phase = "COMMIT"
        _load_query("COMMIT")
        result.update(writes_executed=True, persisted=True, committed=True)
        phase = "POST_COMMIT_READBACK"
        result["verification"] = _load_verify(context)
        result["status"] = "COMMITTED_AND_VERIFIED"
        return result
    except BaseException as error:
        code = error.code if isinstance(error, LoadError) else "LOAD_OPERATION_FAILED"
        if phase in {"BEGIN", "COMMIT", "ROLLBACK", "ROLLBACK_READBACK"}:
            code, result["persisted"] = phase + "_OUTCOME_UNKNOWN_DO_NOT_RETRY", "UNKNOWN"
        elif phase == "POST_COMMIT_READBACK":
            code = "POST_COMMIT_READBACK_FAILED_DO_NOT_RETRY"
        result.update(status=code, phase=phase)
        raise LoadError(code, result) from None


def verify_oscal_load(canonical_nodes_df, canonical_edges_df, config):
    context = _load_prepare(canonical_nodes_df, canonical_edges_df, dict(config, EXECUTE_WRITES=False))
    if context["storage"] is None:
        return {"status": "TARGET_CONTRACT_PENDING", "storage_verified": False, **context["graph"]}
    return {"status": "LOAD_VERIFIED", "storage_verified": True, **_load_verify(context)}


validate_and_load_oscal._oscal_loader_release = OSCAL_LOAD_RELEASE


# %% Cell 7 - Run the mapping
OSCAL_LOAD_MODE = "PREVIEW"  # Change to COMMIT only for a verified destination.


class PipelineError(ValueError):
    def __init__(self, report):
        super().__init__("OSCAL pipeline stopped; inspect OSCAL_PIPELINE_REPORT")
        self.report = report


def run_oscal_mapping(source_df, canonical_mapping_df, element_registry_df, config, context=None):
    """Build the graph, validate it, and load only when this run enables writes."""
    nodes, edges = build_oscal_graph(
        source_df, canonical_mapping_df, element_registry_df, config["OSCAL_MODEL"],
        config["SOURCE_SYSTEM_NAME"], config["SOURCE_TABLE_NAME"], context=context,
    )
    config = dict(config)
    if "EXPECTED_SOURCE_RECORDS" not in config:
        config["EXPECTED_SOURCE_RECORDS"] = source_df.count()
    result = validate_and_load_oscal(nodes, edges, config)
    return nodes, edges, result


def run_oscal_pipeline(source_inputs, mapping_contexts, load_mode="PREVIEW"):
    """Preview every route before the first commit. Transactions are per route."""
    report = {"mode": load_mode, "status": "RUNNING", "groups": [],
              "writes_executed": False, "commit_attempted": False}
    graphs, active = {}, None
    try:
        if load_mode not in {"PREVIEW", "COMMIT"} or not mapping_contexts:
            raise ValueError("Choose PREVIEW or COMMIT and at least one mapping route")
        if getattr(validate_and_load_oscal, "_oscal_loader_release", None) != "oscal-lean-daily-v3":
            raise ValueError("Run the matching Cell 6 before Cell 7")
        routes = {}
        for context in mapping_contexts:
            config = context["config"]
            active = (context["source_key"], config["OSCAL_MODEL"])
            if active in routes or active[0] not in source_inputs:
                raise ValueError("Duplicate mapping route or missing source input")
            if context["routing_report"]["STATUS"] != "READY" or not context["mapping_rows"]:
                raise ValueError("Mapping route is blocked or has no approved rows")
            if config.get("EXECUTE_WRITES") is not False:
                raise ValueError("Keep shared EXECUTE_WRITES false; choose the Cell 7 load mode")
            if load_mode == "COMMIT" and (config.get("STORAGE_CONTRACT") or {}).get("VERIFIED") is not True:
                raise ValueError("Every selected route needs a verified destination before COMMIT")
            routes[active] = context
        for active, original in routes.items():
            context = copy.deepcopy(original)
            source = source_inputs[active[0]]
            context["lookups"] = source.get("lookups", {})
            expected = source.get("selection", {}).get("SELECTED_ROWS")
            if expected is not None:
                context["config"]["EXPECTED_SOURCE_RECORDS"] = expected
            nodes, edges, result = run_oscal_mapping(source["source_df"], None, None, context["config"], context)
            graphs[active] = {"nodes": nodes, "edges": edges, "context": context}
            report["groups"].append({"source": active[0], "model": active[1], "load": result})
        if load_mode == "COMMIT":
            for group in report["groups"]:
                active = (group["source"], group["model"])
                graph = graphs[active]
                report["commit_attempted"] = True
                result = validate_and_load_oscal(graph["nodes"], graph["edges"],
                                                dict(graph["context"]["config"], EXECUTE_WRITES=True))
                group["load"] = result
                report["writes_executed"] |= result["writes_executed"]
        report["status"] = "COMMITTED_AND_VERIFIED" if load_mode == "COMMIT" else "PREVIEW_COMPLETE"
        return graphs, report
    except BaseException as error:
        details = getattr(error, "details", {})
        report.update(status="COMMIT_FAILED_REVIEW_REQUIRED" if report["commit_attempted"] else "FAILED_BEFORE_COMMIT",
                      failed_route=active, error_type=type(error).__name__, load_error=details)
        report["writes_executed"] |= details.get("writes_executed") is True
        raise PipelineError(report) from None


MODEL_GRAPHS = PIPELINE_REPORT = None
try:
    MODEL_GRAPHS, PIPELINE_REPORT = run_oscal_pipeline(SOURCE_INPUTS, MAPPING_CONTEXTS, OSCAL_LOAD_MODE)
except PipelineError as error:
    PIPELINE_REPORT = error.report
    raise
finally:
    print("OSCAL_PIPELINE_REPORT")
    print(json.dumps(PIPELINE_REPORT, indent=2, default=str))
