-- POC published OSCAL Authorization Package view.
-- Uses SOURCE_RECORD_ID as the cross-model business key because the current
-- SSP, POAM, Assessment Results, and Assessment Plan model contracts are all
-- bound to the same Archer Authorization Package source.
-- Validate live persisted root SOURCE_RECORD_ID equality before promoting this
-- beyond POC status.

CREATE OR REPLACE VIEW
RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_PUBLISHED.C2S_OSCAL_AUTHORIZATION_PACKAGE_ALL
AS

WITH SSP_ROOT AS
(
    SELECT
        SOURCE_RECORD_ID,
        PK_OSCAL_SSP_ELEMENT_HASH AS SSP_ROOT_PK,
        OSCAL_UUID                AS SSP_UUID
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
    WHERE ELEMENT_TYPE = 'system-security-plan'
),

SSP_SYSTEM_CHARACTERISTICS AS
(
    SELECT
        R.SOURCE_RECORD_ID,
        C.METADATA_JSON:"system-name"::STRING
            AS AUTHORIZATION_PACKAGE_NAME,
        C.METADATA_JSON:"system-name-short"::STRING
            AS ACRONYM,
        C.METADATA_JSON:"description"::STRING
            AS MISSION_PURPOSE

    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT R

    JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY F
      ON F.FK_SOURCE_ELEMENT_HASH = R.PK_OSCAL_SSP_ELEMENT_HASH

    JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT C
      ON C.PK_OSCAL_SSP_ELEMENT_HASH = F.FK_TARGET_ELEMENT_HASH

    WHERE R.ELEMENT_TYPE = 'system-security-plan'
      AND C.ELEMENT_TYPE = 'system-characteristics'
),

POAM_ROOT AS
(
    SELECT
        SOURCE_RECORD_ID,
        PK_DIM_OSCAL_POAM_ELEMENT_HASH AS POAM_ROOT_PK,
        OSCAL_UUID                     AS POAM_UUID
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT
    WHERE ELEMENT_TYPE = 'plan-of-action-and-milestones'
),

ASSESSMENT_RESULTS_ROOT AS
(
    SELECT
        SOURCE_RECORD_ID,
        PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH
            AS ASSESSMENT_RESULTS_ROOT_PK,
        OSCAL_UUID
            AS ASSESSMENT_RESULTS_UUID
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT
    WHERE ELEMENT_TYPE = 'assessment-results'
),

ASSESSMENT_PLAN_ROOT AS
(
    SELECT
        SOURCE_RECORD_ID,
        PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH
            AS ASSESSMENT_PLAN_ROOT_PK,
        OSCAL_UUID
            AS ASSESSMENT_PLAN_UUID
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT
    WHERE ELEMENT_TYPE = 'assessment-plan'
)

SELECT
    S.SOURCE_RECORD_ID
        AS ARCHER_AUTHORIZATION_PACKAGE_DATA_CONTENT_ID,

    SC.AUTHORIZATION_PACKAGE_NAME,
    SC.ACRONYM,
    SC.MISSION_PURPOSE,

    S.SSP_ROOT_PK,
    S.SSP_UUID,

    P.POAM_ROOT_PK,
    P.POAM_UUID,

    AR.ASSESSMENT_RESULTS_ROOT_PK,
    AR.ASSESSMENT_RESULTS_UUID,

    AP.ASSESSMENT_PLAN_ROOT_PK,
    AP.ASSESSMENT_PLAN_UUID

FROM SSP_ROOT S

LEFT JOIN SSP_SYSTEM_CHARACTERISTICS SC
  ON SC.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID

LEFT JOIN POAM_ROOT P
  ON P.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID

LEFT JOIN ASSESSMENT_RESULTS_ROOT AR
  ON AR.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID

LEFT JOIN ASSESSMENT_PLAN_ROOT AP
  ON AP.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID;
