-- POC published OSCAL Authorization Package view.
-- Populate fields only where the current OSCAL mappings and generated payloads support them.
-- SOURCE_RECORD_ID is the cross-model business key for the current shared Authorization Package source.
-- Known unresolved/deferred mappings are intentionally not fabricated here.

CREATE OR REPLACE VIEW
RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_PUBLISHED.C2S_OSCAL_AUTHORIZATION_PACKAGE_ALL
AS

WITH SSP_ROOT AS
(
    SELECT
        SOURCE_RECORD_ID,
        PK_OSCAL_SSP_ELEMENT_HASH AS SSP_ROOT_PK,
        OSCAL_UUID                AS SSP_UUID
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
    WHERE ELEMENT_TYPE = 'system-security-plan'
),

SSP_SYSTEM_CHARACTERISTICS AS
(
    SELECT
        R.SOURCE_RECORD_ID,
        C.PK_OSCAL_SSP_ELEMENT_HASH AS SYSTEM_CHARACTERISTICS_PK,
        C.METADATA_JSON:"system-name"::STRING             AS AUTHORIZATION_PACKAGE_NAME,
        C.METADATA_JSON:"system-name-short"::STRING       AS ACRONYM,
        C.METADATA_JSON:"description"::STRING             AS MISSION_PURPOSE,
        C.METADATA_JSON:"status":"state"::STRING         AS OPERATIONAL_STATUS,
        C.METADATA_JSON:"status":"remarks"::STRING       AS AUTHORIZATION_COMMENTS,
        C.METADATA_JSON:"date-authorized"::STRING         AS ATOIATO_DATE,
        C.METADATA_JSON:"security-sensitivity-level"::STRING AS SECURITY_CATEGORY
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT R
    JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY F
      ON F.FK_SOURCE_ELEMENT_HASH = R.PK_OSCAL_SSP_ELEMENT_HASH
    JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT C
      ON C.PK_OSCAL_SSP_ELEMENT_HASH = F.FK_TARGET_ELEMENT_HASH
    WHERE R.ELEMENT_TYPE = 'system-security-plan'
      AND C.ELEMENT_TYPE = 'system-characteristics'
),

SSP_SC_CHILDREN AS
(
    SELECT
        SC.SOURCE_RECORD_ID,
        C.ELEMENT_TYPE,
        C.METADATA_JSON
    FROM SSP_SYSTEM_CHARACTERISTICS SC
    JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY F
      ON F.FK_SOURCE_ELEMENT_HASH = SC.SYSTEM_CHARACTERISTICS_PK
    JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT C
      ON C.PK_OSCAL_SSP_ELEMENT_HASH = F.FK_TARGET_ELEMENT_HASH
),

SSP_SYSTEM_IDS AS
(
    SELECT
        SOURCE_RECORD_ID,
        MAX(METADATA_JSON:"id"::STRING) AS SAP_ID
    FROM SSP_SC_CHILDREN
    WHERE ELEMENT_TYPE = 'system-ids'
    GROUP BY SOURCE_RECORD_ID
),

SSP_AUTHORIZATION_BOUNDARY AS
(
    SELECT
        SOURCE_RECORD_ID,
        MAX(METADATA_JSON:"description"::STRING) AS AUTHORIZATION_BOUNDARY_DESCRIPTION
    FROM SSP_SC_CHILDREN
    WHERE ELEMENT_TYPE = 'authorization-boundary'
    GROUP BY SOURCE_RECORD_ID
),

SSP_SECURITY_IMPACT AS
(
    SELECT
        SOURCE_RECORD_ID,
        MAX(METADATA_JSON:"security-objective-confidentiality"::STRING) AS SECURITY_OBJECTIVE_CONFIDENTIALITY,
        MAX(METADATA_JSON:"security-objective-integrity"::STRING)       AS SECURITY_OBJECTIVE_INTEGRITY,
        MAX(METADATA_JSON:"security-objective-availability"::STRING)    AS SECURITY_OBJECTIVE_AVAILABILITY
    FROM SSP_SC_CHILDREN
    WHERE ELEMENT_TYPE = 'security-impact-level'
    GROUP BY SOURCE_RECORD_ID
),

SSP_PROPERTIES AS
(
    SELECT
        SOURCE_RECORD_ID,
        LISTAGG(IFF(METADATA_JSON:"name"::STRING = 'information-system-type',
                    METADATA_JSON:"value"::STRING, NULL), ' | ')
          WITHIN GROUP (ORDER BY METADATA_JSON:"value"::STRING) AS INFORMATION_SYSTEM_TYPE,
        LISTAGG(IFF(METADATA_JSON:"name"::STRING = 'fisma-reportable',
                    METADATA_JSON:"value"::STRING, NULL), ' | ')
          WITHIN GROUP (ORDER BY METADATA_JSON:"value"::STRING) AS FISMA_REPORTABLE,
        LISTAGG(IFF(METADATA_JSON:"name"::STRING = 'financial-system',
                    METADATA_JSON:"value"::STRING, NULL), ' | ')
          WITHIN GROUP (ORDER BY METADATA_JSON:"value"::STRING) AS FINANCIAL_SYSTEM,
        LISTAGG(IFF(METADATA_JSON:"name"::STRING = 'mission-critical',
                    METADATA_JSON:"value"::STRING, NULL), ' | ')
          WITHIN GROUP (ORDER BY METADATA_JSON:"value"::STRING) AS MISSION_CRITICAL,
        LISTAGG(IFF(METADATA_JSON:"name"::STRING = 'critical-infrastructure',
                    METADATA_JSON:"value"::STRING, NULL), ' | ')
          WITHIN GROUP (ORDER BY METADATA_JSON:"value"::STRING) AS CRITICAL_INFRASTRUCTURE,
        LISTAGG(IFF(METADATA_JSON:"name"::STRING = 'package-type',
                    METADATA_JSON:"value"::STRING, NULL), ' | ')
          WITHIN GROUP (ORDER BY METADATA_JSON:"value"::STRING) AS PACKAGE_TYPE,
        LISTAGG(IFF(METADATA_JSON:"name"::STRING = 'pia-required',
                    METADATA_JSON:"value"::STRING, NULL), ' | ')
          WITHIN GROUP (ORDER BY METADATA_JSON:"value"::STRING) AS PIA_REQUIRED,
        LISTAGG(IFF(METADATA_JSON:"name"::STRING = 'information-classification',
                    METADATA_JSON:"value"::STRING, NULL), ' | ')
          WITHIN GROUP (ORDER BY METADATA_JSON:"value"::STRING) AS INFORMATION_CLASSIFICATION,
        LISTAGG(IFF(METADATA_JSON:"name"::STRING = 'daily-loss-amount-from-outage',
                    METADATA_JSON:"value"::STRING, NULL), ' | ')
          WITHIN GROUP (ORDER BY METADATA_JSON:"value"::STRING) AS DAILY_LOSS_AMOUNT_FROM_OUTAGE
    FROM SSP_SC_CHILDREN
    WHERE ELEMENT_TYPE = 'props'
    GROUP BY SOURCE_RECORD_ID
),

SSP_METADATA AS
(
    SELECT
        R.SOURCE_RECORD_ID,
        M.PK_OSCAL_SSP_ELEMENT_HASH AS METADATA_PK,
        M.METADATA_JSON:"title"::STRING         AS OSCAL_METADATA_TITLE,
        M.METADATA_JSON:"version"::STRING       AS OSCAL_DOCUMENT_VERSION,
        M.METADATA_JSON:"oscal-version"::STRING AS OSCAL_VERSION
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT R
    JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY F
      ON F.FK_SOURCE_ELEMENT_HASH = R.PK_OSCAL_SSP_ELEMENT_HASH
    JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT M
      ON M.PK_OSCAL_SSP_ELEMENT_HASH = F.FK_TARGET_ELEMENT_HASH
    WHERE R.ELEMENT_TYPE = 'system-security-plan'
      AND M.ELEMENT_TYPE = 'metadata'
),

SSP_METADATA_CHILDREN AS
(
    SELECT
        M.SOURCE_RECORD_ID,
        C.ELEMENT_TYPE,
        C.METADATA_JSON
    FROM SSP_METADATA M
    JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY F
      ON F.FK_SOURCE_ELEMENT_HASH = M.METADATA_PK
    JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT C
      ON C.PK_OSCAL_SSP_ELEMENT_HASH = F.FK_TARGET_ELEMENT_HASH
),

SSP_DOCUMENT_IDS AS
(
    SELECT
        SOURCE_RECORD_ID,
        MAX(METADATA_JSON:"identifier"::STRING) AS TRACKING_ID
    FROM SSP_METADATA_CHILDREN
    WHERE ELEMENT_TYPE = 'document-ids'
    GROUP BY SOURCE_RECORD_ID
),

SSP_RESPONSIBLE_PARTIES AS
(
    SELECT
        SOURCE_RECORD_ID,
        MAX(IFF(METADATA_JSON:"role-id"::STRING = 'information-owner',
                METADATA_JSON:"party-uuids"::STRING, NULL)) AS INFORMATION_OWNER_IO_PARTY_UUIDS,
        MAX(IFF(METADATA_JSON:"role-id"::STRING = 'system-owner',
                METADATA_JSON:"party-uuids"::STRING, NULL)) AS INFORMATION_SYSTEM_OWNER_ISO_PARTY_UUIDS,
        MAX(IFF(METADATA_JSON:"role-id"::STRING = 'authorizing-official',
                METADATA_JSON:"party-uuids"::STRING, NULL)) AS AUTHORIZING_OFFICIAL_AO_PARTY_UUIDS,
        MAX(IFF(METADATA_JSON:"role-id"::STRING = 'system-security-officer',
                METADATA_JSON:"party-uuids"::STRING, NULL)) AS INFORMATION_SYSTEM_SECURITY_OFFICER_ISSO_PARTY_UUIDS,
        MAX(IFF(METADATA_JSON:"role-id"::STRING = 'privacy-officer',
                METADATA_JSON:"party-uuids"::STRING, NULL)) AS PRIVACY_OFFICER_PO_PARTY_UUIDS
    FROM SSP_METADATA_CHILDREN
    WHERE ELEMENT_TYPE = 'responsible-parties'
    GROUP BY SOURCE_RECORD_ID
),

POAM_ROOT AS
(
    SELECT
        SOURCE_RECORD_ID,
        PK_DIM_OSCAL_POAM_ELEMENT_HASH AS POAM_ROOT_PK,
        OSCAL_UUID                     AS POAM_UUID
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT
    WHERE ELEMENT_TYPE = 'plan-of-action-and-milestones'
),

POAM_ITEMS AS
(
    SELECT
        R.SOURCE_RECORD_ID,
        COUNT(*) AS POAM_ITEM_COUNT,
        LISTAGG(I.OSCAL_UUID, ', ') WITHIN GROUP (ORDER BY I.OSCAL_UUID) AS POAM_ITEM_UUIDS
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT R
    JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_POAM_DEPENDENCY F
      ON F.FK_SOURCE_ELEMENT_HASH = R.PK_DIM_OSCAL_POAM_ELEMENT_HASH
    JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT I
      ON I.PK_DIM_OSCAL_POAM_ELEMENT_HASH = F.FK_TARGET_ELEMENT_HASH
    WHERE R.ELEMENT_TYPE = 'plan-of-action-and-milestones'
      AND I.ELEMENT_TYPE = 'poam-items'
    GROUP BY R.SOURCE_RECORD_ID
),

ASSESSMENT_RESULTS_ROOT AS
(
    SELECT
        SOURCE_RECORD_ID,
        PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH AS ASSESSMENT_RESULTS_ROOT_PK,
        OSCAL_UUID AS ASSESSMENT_RESULTS_UUID
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT
    WHERE ELEMENT_TYPE = 'assessment-results'
),

ASSESSMENT_PLAN_ROOT AS
(
    SELECT
        SOURCE_RECORD_ID,
        PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH AS ASSESSMENT_PLAN_ROOT_PK,
        OSCAL_UUID AS ASSESSMENT_PLAN_UUID
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT
    WHERE ELEMENT_TYPE = 'assessment-plan'
)

SELECT
    S.SOURCE_RECORD_ID AS ARCHER_AUTHORIZATION_PACKAGE_DATA_CONTENT_ID,

    SC.AUTHORIZATION_PACKAGE_NAME,
    SC.ACRONYM,
    IDS.SAP_ID,
    SC.MISSION_PURPOSE,
    SC.OPERATIONAL_STATUS,
    SC.AUTHORIZATION_COMMENTS,
    SC.ATOIATO_DATE,
    SC.SECURITY_CATEGORY,
    AB.AUTHORIZATION_BOUNDARY_DESCRIPTION,

    P.INFORMATION_SYSTEM_TYPE,
    P.FISMA_REPORTABLE,
    P.FINANCIAL_SYSTEM,
    P.MISSION_CRITICAL,
    P.CRITICAL_INFRASTRUCTURE,
    P.PACKAGE_TYPE,
    P.PIA_REQUIRED,
    P.INFORMATION_CLASSIFICATION,
    P.DAILY_LOSS_AMOUNT_FROM_OUTAGE,

    SI.SECURITY_OBJECTIVE_CONFIDENTIALITY,
    SI.SECURITY_OBJECTIVE_INTEGRITY,
    SI.SECURITY_OBJECTIVE_AVAILABILITY,

    MD.OSCAL_METADATA_TITLE,
    MD.OSCAL_DOCUMENT_VERSION,
    MD.OSCAL_VERSION,
    DI.TRACKING_ID,

    RP.INFORMATION_OWNER_IO_PARTY_UUIDS,
    RP.INFORMATION_SYSTEM_OWNER_ISO_PARTY_UUIDS,
    RP.AUTHORIZING_OFFICIAL_AO_PARTY_UUIDS,
    RP.INFORMATION_SYSTEM_SECURITY_OFFICER_ISSO_PARTY_UUIDS,
    RP.PRIVACY_OFFICER_PO_PARTY_UUIDS,

    S.SSP_ROOT_PK,
    S.SSP_UUID,

    PR.POAM_ROOT_PK,
    PR.POAM_UUID,
    PI.POAM_ITEM_COUNT,
    PI.POAM_ITEM_UUIDS,

    AR.ASSESSMENT_RESULTS_ROOT_PK,
    AR.ASSESSMENT_RESULTS_UUID,

    AP.ASSESSMENT_PLAN_ROOT_PK,
    AP.ASSESSMENT_PLAN_UUID

FROM SSP_ROOT S
LEFT JOIN SSP_SYSTEM_CHARACTERISTICS SC
  ON SC.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SSP_SYSTEM_IDS IDS
  ON IDS.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SSP_AUTHORIZATION_BOUNDARY AB
  ON AB.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SSP_SECURITY_IMPACT SI
  ON SI.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SSP_PROPERTIES P
  ON P.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SSP_METADATA MD
  ON MD.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SSP_DOCUMENT_IDS DI
  ON DI.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SSP_RESPONSIBLE_PARTIES RP
  ON RP.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN POAM_ROOT PR
  ON PR.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN POAM_ITEMS PI
  ON PI.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN ASSESSMENT_RESULTS_ROOT AR
  ON AR.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN ASSESSMENT_PLAN_ROOT AP
  ON AP.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID;
