-- ACTIVE published view over the expanded OSCAL Authorization Package ALL view.
-- Date: 2026-09-25
-- Keep this view intentionally thin.
--
-- Re-run this CREATE OR REPLACE VIEW after recreating
-- C2S_OSCAL_AUTHORIZATION_PACKAGE_ALL so SELECT * resolves the expanded
-- published column set.

CREATE OR REPLACE VIEW
RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_PUBLISHED.C2S_OSCAL_AUTHORIZATION_PACKAGE_ACTIVE
AS
SELECT *
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_PUBLISHED.C2S_OSCAL_AUTHORIZATION_PACKAGE_ALL
WHERE ACRONYM LIKE '%IPNCCS%'
   OR ACRONYM LIKE '%CCS%'
   OR ACRONYM LIKE '%C2S%';
