-- Expanded published OSCAL Authorization Package view.
-- Date: 2026-09-25
--
-- One row per Source One Authorization Package / SOURCE_RECORD_ID.
-- Uses only committed OSCAL DIM/FACT tables.
--
-- Design rules:
-- * SOURCE_RECORD_ID is the cross-model business key.
-- * FACT foreign keys validate hierarchy within each OSCAL model.
-- * Every one-to-many collection is aggregated before the final cross-model join.
-- * Assessment Results is explicitly scoped to Source One because its DIM/FACT
--   tables are shared with Source Two.
-- * This view exposes native scalar fields for easy consumers and also exposes
--   structured VARIANT arrays/objects for components, controls, observations,
--   POA&M items, tasks, parties, and extension properties.
-- * No RAW/historical table dependency.
--
-- Recreate C2S_OSCAL_AUTHORIZATION_PACKAGE_ACTIVE after this view so SELECT *
-- picks up the expanded column set.

CREATE OR REPLACE VIEW
RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_PUBLISHED.C2S_OSCAL_AUTHORIZATION_PACKAGE_ALL
AS

WITH
-- =====================================================================
-- SSP
-- =====================================================================
SSP_NODES AS
(
    SELECT
        PK_OSCAL_SSP_ELEMENT_HASH AS NODE_KEY,
        SOURCE_RECORD_ID,
        ELEMENT_TYPE,
        OSCAL_UUID,
        METADATA_JSON
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT
    WHERE SOURCE_SYSTEM_NAME = 'ARCHER'
      AND SOURCE_TABLE_NAME = 'ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
),

SSP_ROOT AS
(
    SELECT
        SOURCE_RECORD_ID,
        NODE_KEY AS SSP_ROOT_PK,
        OSCAL_UUID AS SSP_UUID
    FROM SSP_NODES
    WHERE ELEMENT_TYPE = 'system-security-plan'
),

SSP_EDGE_STATS AS
(
    SELECT
        S.SOURCE_RECORD_ID,
        COUNT(*) AS SSP_EDGE_COUNT,
        COUNT_IF(S.SOURCE_RECORD_ID <> T.SOURCE_RECORD_ID) AS SSP_CROSS_RECORD_EDGE_COUNT
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY F
    JOIN SSP_NODES S
      ON S.NODE_KEY = F.FK_SOURCE_ELEMENT_HASH
    JOIN SSP_NODES T
      ON T.NODE_KEY = F.FK_TARGET_ELEMENT_HASH
    GROUP BY S.SOURCE_RECORD_ID
),

SSP_NODE_STATS AS
(
    SELECT
        SOURCE_RECORD_ID,
        COUNT(*) AS SSP_NODE_COUNT,
        COUNT_IF(ELEMENT_TYPE = 'system-security-plan') AS SSP_ROOT_COUNT,
        COUNT_IF(ELEMENT_TYPE = 'metadata') AS SSP_METADATA_NODE_COUNT,
        COUNT_IF(ELEMENT_TYPE = 'system-characteristics') AS SSP_SYSTEM_CHARACTERISTICS_NODE_COUNT,
        COUNT_IF(ELEMENT_TYPE = 'components') AS SSP_COMPONENT_NODE_COUNT,
        COUNT_IF(ELEMENT_TYPE = 'implemented-requirements') AS SSP_IMPLEMENTED_REQUIREMENT_COUNT,
        COUNT_IF(ELEMENT_TYPE = 'props') AS SSP_PROP_NODE_COUNT
    FROM SSP_NODES
    GROUP BY SOURCE_RECORD_ID
),

SSP_ROOT_CHILDREN AS
(
    SELECT
        R.SOURCE_RECORD_ID,
        C.NODE_KEY,
        C.ELEMENT_TYPE,
        C.OSCAL_UUID,
        C.METADATA_JSON
    FROM SSP_ROOT R
    JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY F
      ON F.FK_SOURCE_ELEMENT_HASH = R.SSP_ROOT_PK
    JOIN SSP_NODES C
      ON C.NODE_KEY = F.FK_TARGET_ELEMENT_HASH
),

SSP_SYSTEM_CHARACTERISTICS AS
(
    SELECT
        SOURCE_RECORD_ID,
        NODE_KEY AS SYSTEM_CHARACTERISTICS_PK,
        METADATA_JSON:"system-name"::STRING AS AUTHORIZATION_PACKAGE_NAME,
        METADATA_JSON:"system-name-short"::STRING AS ACRONYM,
        METADATA_JSON:"description"::STRING AS MISSION_PURPOSE,
        METADATA_JSON:"status":"state"::STRING AS OPERATIONAL_STATUS,
        METADATA_JSON:"status":"remarks"::STRING AS AUTHORIZATION_COMMENTS,
        METADATA_JSON:"date-authorized"::STRING AS ATOIATO_DATE,
        METADATA_JSON:"security-sensitivity-level"::STRING AS SECURITY_CATEGORY
    FROM SSP_ROOT_CHILDREN
    WHERE ELEMENT_TYPE = 'system-characteristics'
),

SSP_SC_CHILDREN AS
(
    SELECT
        SC.SOURCE_RECORD_ID,
        C.NODE_KEY,
        C.ELEMENT_TYPE,
        C.OSCAL_UUID,
        C.METADATA_JSON
    FROM SSP_SYSTEM_CHARACTERISTICS SC
    JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY F
      ON F.FK_SOURCE_ELEMENT_HASH = SC.SYSTEM_CHARACTERISTICS_PK
    JOIN SSP_NODES C
      ON C.NODE_KEY = F.FK_TARGET_ELEMENT_HASH
),

SSP_SYSTEM_IDS AS
(
    SELECT
        SOURCE_RECORD_ID,
        ARRAY_AGG(
            OBJECT_CONSTRUCT_KEEP_NULL(
                'uuid', OSCAL_UUID,
                'id', METADATA_JSON:"id"
            )
        ) WITHIN GROUP (ORDER BY OSCAL_UUID) AS SYSTEM_IDS,
        MAX(METADATA_JSON:"id"::STRING) AS SAP_ID
    FROM SSP_SC_CHILDREN
    WHERE ELEMENT_TYPE = 'system-ids'
    GROUP BY SOURCE_RECORD_ID
),

SSP_AUTHORIZATION_BOUNDARY AS
(
    SELECT
        SOURCE_RECORD_ID,
        MAX(METADATA_JSON:"description"::STRING) AS AUTHORIZATION_BOUNDARY_DESCRIPTION
    FROM SSP_SC_CHILDREN
    WHERE ELEMENT_TYPE = 'authorization-boundary'
    GROUP BY SOURCE_RECORD_ID
),

SSP_SECURITY_IMPACT AS
(
    SELECT
        SOURCE_RECORD_ID,
        MAX(METADATA_JSON:"security-objective-confidentiality"::STRING) AS SECURITY_OBJECTIVE_CONFIDENTIALITY,
        MAX(METADATA_JSON:"security-objective-integrity"::STRING) AS SECURITY_OBJECTIVE_INTEGRITY,
        MAX(METADATA_JSON:"security-objective-availability"::STRING) AS SECURITY_OBJECTIVE_AVAILABILITY,
        MAX(METADATA_JSON) AS SECURITY_IMPACT_PAYLOAD
    FROM SSP_SC_CHILDREN
    WHERE ELEMENT_TYPE = 'security-impact-level'
    GROUP BY SOURCE_RECORD_ID
),

SSP_SC_PROP_VALUES AS
(
    SELECT
        SOURCE_RECORD_ID,
        METADATA_JSON:"name"::STRING AS PROP_NAME,
        ARRAY_AGG(METADATA_JSON:"value")
          WITHIN GROUP (ORDER BY OSCAL_UUID) AS PROP_VALUES
    FROM SSP_SC_CHILDREN
    WHERE ELEMENT_TYPE = 'props'
      AND METADATA_JSON:"name" IS NOT NULL
    GROUP BY SOURCE_RECORD_ID, METADATA_JSON:"name"::STRING
),

SSP_SC_PROPERTIES AS
(
    SELECT
        SOURCE_RECORD_ID,
        OBJECT_AGG(PROP_NAME, TO_VARIANT(PROP_VALUES)) AS SSP_SYSTEM_CHARACTERISTICS_PROPERTIES
    FROM SSP_SC_PROP_VALUES
    GROUP BY SOURCE_RECORD_ID
),

SSP_METADATA AS
(
    SELECT
        SOURCE_RECORD_ID,
        NODE_KEY AS METADATA_PK,
        METADATA_JSON:"title"::STRING AS OSCAL_METADATA_TITLE,
        METADATA_JSON:"version"::STRING AS OSCAL_DOCUMENT_VERSION,
        METADATA_JSON:"oscal-version"::STRING AS OSCAL_VERSION,
        METADATA_JSON:"published"::STRING AS PUBLISHED,
        METADATA_JSON:"last-modified"::STRING AS LAST_MODIFIED
    FROM SSP_ROOT_CHILDREN
    WHERE ELEMENT_TYPE = 'metadata'
),

SSP_METADATA_CHILDREN AS
(
    SELECT
        M.SOURCE_RECORD_ID,
        C.NODE_KEY,
        C.ELEMENT_TYPE,
        C.OSCAL_UUID,
        C.METADATA_JSON
    FROM SSP_METADATA M
    JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY F
      ON F.FK_SOURCE_ELEMENT_HASH = M.METADATA_PK
    JOIN SSP_NODES C
      ON C.NODE_KEY = F.FK_TARGET_ELEMENT_HASH
),

SSP_DOCUMENT_IDS AS
(
    SELECT
        SOURCE_RECORD_ID,
        MAX(METADATA_JSON:"identifier"::STRING) AS TRACKING_ID,
        ARRAY_AGG(METADATA_JSON)
          WITHIN GROUP (ORDER BY OSCAL_UUID) AS DOCUMENT_IDS
    FROM SSP_METADATA_CHILDREN
    WHERE ELEMENT_TYPE = 'document-ids'
    GROUP BY SOURCE_RECORD_ID
),

SSP_METADATA_PROP_VALUES AS
(
    SELECT
        SOURCE_RECORD_ID,
        METADATA_JSON:"name"::STRING AS PROP_NAME,
        ARRAY_AGG(METADATA_JSON:"value")
          WITHIN GROUP (ORDER BY OSCAL_UUID) AS PROP_VALUES
    FROM SSP_METADATA_CHILDREN
    WHERE ELEMENT_TYPE = 'props'
      AND METADATA_JSON:"name" IS NOT NULL
    GROUP BY SOURCE_RECORD_ID, METADATA_JSON:"name"::STRING
),

SSP_METADATA_PROPERTIES AS
(
    SELECT
        SOURCE_RECORD_ID,
        OBJECT_AGG(PROP_NAME, TO_VARIANT(PROP_VALUES)) AS SSP_METADATA_PROPERTIES
    FROM SSP_METADATA_PROP_VALUES
    GROUP BY SOURCE_RECORD_ID
),

SSP_RESPONSIBLE_PARTIES AS
(
    SELECT
        SOURCE_RECORD_ID,
        ARRAY_AGG(
            OBJECT_CONSTRUCT_KEEP_NULL(
                'role-id', METADATA_JSON:"role-id",
                'party-uuids', METADATA_JSON:"party-uuids"
            )
        ) WITHIN GROUP (ORDER BY METADATA_JSON:"role-id"::STRING, OSCAL_UUID) AS RESPONSIBLE_PARTIES,
        MAX(IFF(METADATA_JSON:"role-id"::STRING = 'information-owner',
                METADATA_JSON:"party-uuids"::STRING, NULL)) AS INFORMATION_OWNER_IO_PARTY_UUIDS,
        MAX(IFF(METADATA_JSON:"role-id"::STRING = 'system-owner',
                METADATA_JSON:"party-uuids"::STRING, NULL)) AS INFORMATION_SYSTEM_OWNER_ISO_PARTY_UUIDS,
        MAX(IFF(METADATA_JSON:"role-id"::STRING = 'senior-information-systems-security-officer',
                METADATA_JSON:"party-uuids"::STRING, NULL)) AS SISSO_PARTY_UUIDS,
        MAX(IFF(METADATA_JSON:"role-id"::STRING = 'authorizing-official',
                METADATA_JSON:"party-uuids"::STRING, NULL)) AS AUTHORIZING_OFFICIAL_AO_PARTY_UUIDS,
        MAX(IFF(METADATA_JSON:"role-id"::STRING = 'system-security-officer',
                METADATA_JSON:"party-uuids"::STRING, NULL)) AS INFORMATION_SYSTEM_SECURITY_OFFICER_ISSO_PARTY_UUIDS,
        MAX(IFF(METADATA_JSON:"role-id"::STRING = 'information-system-security-engineer',
                METADATA_JSON:"party-uuids"::STRING, NULL)) AS ISSE_PARTY_UUIDS,
        MAX(IFF(METADATA_JSON:"role-id"::STRING = 'information-system-administrator',
                METADATA_JSON:"party-uuids"::STRING, NULL)) AS ISA_PARTY_UUIDS,
        MAX(IFF(METADATA_JSON:"role-id"::STRING = 'authorizing-official-designated-representative',
                METADATA_JSON:"party-uuids"::STRING, NULL)) AS AODR_PARTY_UUIDS,
        MAX(IFF(METADATA_JSON:"role-id"::STRING = 'privacy-officer',
                METADATA_JSON:"party-uuids"::STRING, NULL)) AS PRIVACY_OFFICER_PO_PARTY_UUIDS
    FROM SSP_METADATA_CHILDREN
    WHERE ELEMENT_TYPE = 'responsible-parties'
    GROUP BY SOURCE_RECORD_ID
),

SSP_ROLES AS
(
    SELECT
        SOURCE_RECORD_ID,
        ARRAY_AGG(METADATA_JSON)
          WITHIN GROUP (ORDER BY OSCAL_UUID) AS ROLES
    FROM SSP_METADATA_CHILDREN
    WHERE ELEMENT_TYPE = 'roles'
    GROUP BY SOURCE_RECORD_ID
),

SSP_PARTIES AS
(
    SELECT
        SOURCE_RECORD_ID,
        ARRAY_AGG(
            OBJECT_CONSTRUCT_KEEP_NULL(
                'uuid', OSCAL_UUID,
                'payload', METADATA_JSON
            )
        ) WITHIN GROUP (ORDER BY OSCAL_UUID) AS PARTIES
    FROM SSP_METADATA_CHILDREN
    WHERE ELEMENT_TYPE = 'parties'
    GROUP BY SOURCE_RECORD_ID
),

SSP_SYSTEM_IMPLEMENTATION AS
(
    SELECT
        SOURCE_RECORD_ID,
        NODE_KEY AS SYSTEM_IMPLEMENTATION_PK
    FROM SSP_ROOT_CHILDREN
    WHERE ELEMENT_TYPE = 'system-implementation'
),

SSP_COMPONENTS AS
(
    SELECT
        SI.SOURCE_RECORD_ID,
        COUNT(*) AS COMPONENT_COUNT,
        ARRAY_AGG(
            OBJECT_CONSTRUCT_KEEP_NULL(
                'uuid', C.OSCAL_UUID,
                'type', C.METADATA_JSON:"type",
                'title', C.METADATA_JSON:"title",
                'description', C.METADATA_JSON:"description",
                'payload', C.METADATA_JSON
            )
        ) WITHIN GROUP (ORDER BY C.OSCAL_UUID) AS COMPONENTS
    FROM SSP_SYSTEM_IMPLEMENTATION SI
    JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY F
      ON F.FK_SOURCE_ELEMENT_HASH = SI.SYSTEM_IMPLEMENTATION_PK
    JOIN SSP_NODES C
      ON C.NODE_KEY = F.FK_TARGET_ELEMENT_HASH
    WHERE C.ELEMENT_TYPE = 'components'
    GROUP BY SI.SOURCE_RECORD_ID
),

SSP_CONTROL_IMPLEMENTATION AS
(
    SELECT
        SOURCE_RECORD_ID,
        NODE_KEY AS CONTROL_IMPLEMENTATION_PK
    FROM SSP_ROOT_CHILDREN
    WHERE ELEMENT_TYPE = 'control-implementation'
),

SSP_IMPLEMENTED_REQUIREMENTS AS
(
    SELECT
        CI.SOURCE_RECORD_ID,
        COUNT(*) AS IMPLEMENTED_REQUIREMENT_COUNT,
        ARRAY_AGG(
            OBJECT_CONSTRUCT_KEEP_NULL(
                'uuid', C.OSCAL_UUID,
                'control-id', C.METADATA_JSON:"control-id",
                'remarks', C.METADATA_JSON:"remarks",
                'payload', C.METADATA_JSON
            )
        ) WITHIN GROUP (ORDER BY C.METADATA_JSON:"control-id"::STRING, C.OSCAL_UUID) AS IMPLEMENTED_REQUIREMENTS
    FROM SSP_CONTROL_IMPLEMENTATION CI
    JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY F
      ON F.FK_SOURCE_ELEMENT_HASH = CI.CONTROL_IMPLEMENTATION_PK
    JOIN SSP_NODES C
      ON C.NODE_KEY = F.FK_TARGET_ELEMENT_HASH
    WHERE C.ELEMENT_TYPE = 'implemented-requirements'
    GROUP BY CI.SOURCE_RECORD_ID
),

-- =====================================================================
-- Assessment Results
-- =====================================================================
AR_NODES AS
(
    SELECT
        PK_DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT_HASH AS NODE_KEY,
        SOURCE_RECORD_ID,
        ELEMENT_TYPE,
        OSCAL_UUID,
        METADATA_JSON
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_RESULTS_ELEMENT
    WHERE SOURCE_SYSTEM_NAME = 'ARCHER'
      AND SOURCE_TABLE_NAME = 'ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
),

AR_ROOT AS
(
    SELECT
        SOURCE_RECORD_ID,
        NODE_KEY AS ASSESSMENT_RESULTS_ROOT_PK,
        OSCAL_UUID AS ASSESSMENT_RESULTS_UUID
    FROM AR_NODES
    WHERE ELEMENT_TYPE = 'assessment-results'
),

AR_EDGE_STATS AS
(
    SELECT
        S.SOURCE_RECORD_ID,
        COUNT(*) AS AR_EDGE_COUNT,
        COUNT_IF(S.SOURCE_RECORD_ID <> T.SOURCE_RECORD_ID) AS AR_CROSS_RECORD_EDGE_COUNT
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_RESULTS_DEPENDENCY F
    JOIN AR_NODES S
      ON S.NODE_KEY = F.FK_SOURCE_ELEMENT_HASH
    JOIN AR_NODES T
      ON T.NODE_KEY = F.FK_TARGET_ELEMENT_HASH
    GROUP BY S.SOURCE_RECORD_ID
),

AR_NODE_STATS AS
(
    SELECT
        SOURCE_RECORD_ID,
        COUNT(*) AS AR_NODE_COUNT,
        COUNT_IF(ELEMENT_TYPE = 'assessment-results') AS AR_ROOT_COUNT,
        COUNT_IF(ELEMENT_TYPE = 'observations') AS AR_OBSERVATION_COUNT,
        COUNT_IF(ELEMENT_TYPE = 'findings') AS AR_NATIVE_FINDING_COUNT,
        COUNT_IF(ELEMENT_TYPE = 'props') AS AR_PROP_NODE_COUNT
    FROM AR_NODES
    GROUP BY SOURCE_RECORD_ID
),

AR_OBSERVATIONS AS
(
    SELECT
        SOURCE_RECORD_ID,
        ARRAY_AGG(
            OBJECT_CONSTRUCT_KEEP_NULL(
                'uuid', OSCAL_UUID,
                'payload', METADATA_JSON
            )
        ) WITHIN GROUP (ORDER BY OSCAL_UUID) AS ASSESSMENT_OBSERVATIONS
    FROM AR_NODES
    WHERE ELEMENT_TYPE = 'observations'
    GROUP BY SOURCE_RECORD_ID
),

AR_PROP_VALUES AS
(
    SELECT
        SOURCE_RECORD_ID,
        METADATA_JSON:"name"::STRING AS PROP_NAME,
        ARRAY_AGG(METADATA_JSON:"value")
          WITHIN GROUP (ORDER BY OSCAL_UUID) AS PROP_VALUES
    FROM AR_NODES
    WHERE ELEMENT_TYPE = 'props'
      AND METADATA_JSON:"name" IS NOT NULL
    GROUP BY SOURCE_RECORD_ID, METADATA_JSON:"name"::STRING
),

AR_PROPERTIES AS
(
    SELECT
        SOURCE_RECORD_ID,
        OBJECT_AGG(PROP_NAME, TO_VARIANT(PROP_VALUES)) AS ASSESSMENT_RESULT_PROPERTIES
    FROM AR_PROP_VALUES
    GROUP BY SOURCE_RECORD_ID
),

-- =====================================================================
-- POA&M
-- =====================================================================
POAM_NODES AS
(
    SELECT
        PK_DIM_OSCAL_POAM_ELEMENT_HASH AS NODE_KEY,
        SOURCE_RECORD_ID,
        ELEMENT_TYPE,
        OSCAL_UUID,
        METADATA_JSON
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT
    WHERE SOURCE_SYSTEM_NAME = 'ARCHER'
      AND SOURCE_TABLE_NAME = 'ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
),

POAM_ROOT AS
(
    SELECT
        SOURCE_RECORD_ID,
        NODE_KEY AS POAM_ROOT_PK,
        OSCAL_UUID AS POAM_UUID
    FROM POAM_NODES
    WHERE ELEMENT_TYPE = 'plan-of-action-and-milestones'
),

POAM_EDGE_STATS AS
(
    SELECT
        S.SOURCE_RECORD_ID,
        COUNT(*) AS POAM_EDGE_COUNT,
        COUNT_IF(S.SOURCE_RECORD_ID <> T.SOURCE_RECORD_ID) AS POAM_CROSS_RECORD_EDGE_COUNT
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_POAM_DEPENDENCY F
    JOIN POAM_NODES S
      ON S.NODE_KEY = F.FK_SOURCE_ELEMENT_HASH
    JOIN POAM_NODES T
      ON T.NODE_KEY = F.FK_TARGET_ELEMENT_HASH
    GROUP BY S.SOURCE_RECORD_ID
),

POAM_ITEMS AS
(
    SELECT
        SOURCE_RECORD_ID,
        COUNT(*) AS POAM_ITEM_COUNT,
        ARRAY_AGG(
            OBJECT_CONSTRUCT_KEEP_NULL(
                'uuid', OSCAL_UUID,
                'payload', METADATA_JSON
            )
        ) WITHIN GROUP (ORDER BY OSCAL_UUID) AS POAM_ITEMS
    FROM POAM_NODES
    WHERE ELEMENT_TYPE = 'poam-items'
    GROUP BY SOURCE_RECORD_ID
),

POAM_NODE_STATS AS
(
    SELECT
        SOURCE_RECORD_ID,
        COUNT(*) AS POAM_NODE_COUNT,
        COUNT_IF(ELEMENT_TYPE = 'plan-of-action-and-milestones') AS POAM_ROOT_COUNT
    FROM POAM_NODES
    GROUP BY SOURCE_RECORD_ID
),

-- =====================================================================
-- Security Assessment Plan
-- =====================================================================
SAP_NODES AS
(
    SELECT
        PK_DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT_HASH AS NODE_KEY,
        SOURCE_RECORD_ID,
        ELEMENT_TYPE,
        OSCAL_UUID,
        METADATA_JSON
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_ASSESSMENT_PLAN_ELEMENT
    WHERE SOURCE_SYSTEM_NAME = 'ARCHER'
      AND SOURCE_TABLE_NAME = 'ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW'
),

SAP_ROOT AS
(
    SELECT
        SOURCE_RECORD_ID,
        NODE_KEY AS ASSESSMENT_PLAN_ROOT_PK,
        OSCAL_UUID AS ASSESSMENT_PLAN_UUID
    FROM SAP_NODES
    WHERE ELEMENT_TYPE = 'assessment-plan'
),

SAP_EDGE_STATS AS
(
    SELECT
        S.SOURCE_RECORD_ID,
        COUNT(*) AS SAP_EDGE_COUNT,
        COUNT_IF(S.SOURCE_RECORD_ID <> T.SOURCE_RECORD_ID) AS SAP_CROSS_RECORD_EDGE_COUNT
    FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_ASSESSMENT_PLAN_DEPENDENCY F
    JOIN SAP_NODES S
      ON S.NODE_KEY = F.FK_SOURCE_ELEMENT_HASH
    JOIN SAP_NODES T
      ON T.NODE_KEY = F.FK_TARGET_ELEMENT_HASH
    GROUP BY S.SOURCE_RECORD_ID
),

SAP_NODE_STATS AS
(
    SELECT
        SOURCE_RECORD_ID,
        COUNT(*) AS SAP_NODE_COUNT,
        COUNT_IF(ELEMENT_TYPE = 'assessment-plan') AS SAP_ROOT_COUNT,
        COUNT_IF(ELEMENT_TYPE = 'tasks') AS SAP_TASK_COUNT,
        COUNT_IF(ELEMENT_TYPE = 'props') AS SAP_PROP_NODE_COUNT
    FROM SAP_NODES
    GROUP BY SOURCE_RECORD_ID
),

SAP_TASKS AS
(
    SELECT
        SOURCE_RECORD_ID,
        ARRAY_AGG(
            OBJECT_CONSTRUCT_KEEP_NULL(
                'uuid', OSCAL_UUID,
                'title', METADATA_JSON:"title",
                'type', METADATA_JSON:"type",
                'remarks', METADATA_JSON:"remarks",
                'payload', METADATA_JSON
            )
        ) WITHIN GROUP (ORDER BY OSCAL_UUID) AS ASSESSMENT_TASKS
    FROM SAP_NODES
    WHERE ELEMENT_TYPE = 'tasks'
    GROUP BY SOURCE_RECORD_ID
),

SAP_PROP_VALUES AS
(
    SELECT
        SOURCE_RECORD_ID,
        METADATA_JSON:"name"::STRING AS PROP_NAME,
        ARRAY_AGG(METADATA_JSON:"value")
          WITHIN GROUP (ORDER BY OSCAL_UUID) AS PROP_VALUES
    FROM SAP_NODES
    WHERE ELEMENT_TYPE = 'props'
      AND METADATA_JSON:"name" IS NOT NULL
    GROUP BY SOURCE_RECORD_ID, METADATA_JSON:"name"::STRING
),

SAP_PROPERTIES AS
(
    SELECT
        SOURCE_RECORD_ID,
        OBJECT_AGG(PROP_NAME, TO_VARIANT(PROP_VALUES)) AS ASSESSMENT_PLAN_PROPERTIES
    FROM SAP_PROP_VALUES
    GROUP BY SOURCE_RECORD_ID
)

SELECT
    S.SOURCE_RECORD_ID AS ARCHER_AUTHORIZATION_PACKAGE_DATA_CONTENT_ID,

    -- SSP native values
    SC.AUTHORIZATION_PACKAGE_NAME,
    SC.ACRONYM,
    IDS.SAP_ID,
    SC.MISSION_PURPOSE,
    SC.OPERATIONAL_STATUS,
    SC.AUTHORIZATION_COMMENTS,
    SC.ATOIATO_DATE,
    SC.SECURITY_CATEGORY,
    AB.AUTHORIZATION_BOUNDARY_DESCRIPTION,
    SI.SECURITY_OBJECTIVE_CONFIDENTIALITY,
    SI.SECURITY_OBJECTIVE_INTEGRITY,
    SI.SECURITY_OBJECTIVE_AVAILABILITY,

    -- Metadata
    MD.OSCAL_METADATA_TITLE,
    MD.OSCAL_DOCUMENT_VERSION,
    MD.OSCAL_VERSION,
    MD.PUBLISHED,
    MD.LAST_MODIFIED,
    DI.TRACKING_ID,
    DI.DOCUMENT_IDS,
    MP.SSP_METADATA_PROPERTIES,

    -- Existing easy-to-consume SSP property columns
    P.SSP_SYSTEM_CHARACTERISTICS_PROPERTIES:"information-system-type"[0]::STRING AS INFORMATION_SYSTEM_TYPE,
    P.SSP_SYSTEM_CHARACTERISTICS_PROPERTIES:"fisma-reportable"[0]::STRING AS FISMA_REPORTABLE,
    P.SSP_SYSTEM_CHARACTERISTICS_PROPERTIES:"financial-system"[0]::STRING AS FINANCIAL_SYSTEM,
    P.SSP_SYSTEM_CHARACTERISTICS_PROPERTIES:"mission-critical"[0]::STRING AS MISSION_CRITICAL,
    P.SSP_SYSTEM_CHARACTERISTICS_PROPERTIES:"critical-infrastructure"[0]::STRING AS CRITICAL_INFRASTRUCTURE,
    P.SSP_SYSTEM_CHARACTERISTICS_PROPERTIES:"package-type"[0]::STRING AS PACKAGE_TYPE,
    P.SSP_SYSTEM_CHARACTERISTICS_PROPERTIES:"pia-required"[0]::STRING AS PIA_REQUIRED,
    P.SSP_SYSTEM_CHARACTERISTICS_PROPERTIES:"information-classification"[0]::STRING AS INFORMATION_CLASSIFICATION,
    P.SSP_SYSTEM_CHARACTERISTICS_PROPERTIES:"daily-loss-amount-from-outage"[0]::STRING AS DAILY_LOSS_AMOUNT_FROM_OUTAGE,
    P.SSP_SYSTEM_CHARACTERISTICS_PROPERTIES:"authorization-decision"[0]::STRING AS AUTHORIZATION_DECISION,

    -- All system-characteristics properties, including Control Implementation
    -- summary/source-preservation properties, in one future-friendly object.
    P.SSP_SYSTEM_CHARACTERISTICS_PROPERTIES,

    -- SSP people and structural collections
    RP.INFORMATION_OWNER_IO_PARTY_UUIDS,
    RP.INFORMATION_SYSTEM_OWNER_ISO_PARTY_UUIDS,
    RP.SISSO_PARTY_UUIDS,
    RP.AUTHORIZING_OFFICIAL_AO_PARTY_UUIDS,
    RP.INFORMATION_SYSTEM_SECURITY_OFFICER_ISSO_PARTY_UUIDS,
    RP.ISSE_PARTY_UUIDS,
    RP.ISA_PARTY_UUIDS,
    RP.AODR_PARTY_UUIDS,
    RP.PRIVACY_OFFICER_PO_PARTY_UUIDS,
    RP.RESPONSIBLE_PARTIES,
    RL.ROLES,
    PT.PARTIES,
    IDS.SYSTEM_IDS,

    -- SSP System Implementation + Control Implementation
    COALESCE(CP.COMPONENT_COUNT,0) AS COMPONENT_COUNT,
    CP.COMPONENTS,
    COALESCE(IR.IMPLEMENTED_REQUIREMENT_COUNT,0) AS IMPLEMENTED_REQUIREMENT_COUNT,
    IR.IMPLEMENTED_REQUIREMENTS,

    -- SSP identity / QA
    S.SSP_ROOT_PK,
    S.SSP_UUID,
    NS.SSP_NODE_COUNT,
    ES.SSP_EDGE_COUNT,
    NS.SSP_PROP_NODE_COUNT,
    IFF(NS.SSP_ROOT_COUNT=1
        AND COALESCE(ES.SSP_EDGE_COUNT,0)=NS.SSP_NODE_COUNT-1
        AND COALESCE(ES.SSP_CROSS_RECORD_EDGE_COUNT,0)=0,
        'PASS','FAIL') AS SSP_RELATIONSHIP_INTEGRITY,

    -- Assessment Results
    AR.ASSESSMENT_RESULTS_ROOT_PK,
    AR.ASSESSMENT_RESULTS_UUID,
    ANS.AR_NODE_COUNT,
    AES.AR_EDGE_COUNT,
    ANS.AR_OBSERVATION_COUNT,
    ANS.AR_NATIVE_FINDING_COUNT,
    ANS.AR_PROP_NODE_COUNT,
    AO.ASSESSMENT_OBSERVATIONS,
    APROP.ASSESSMENT_RESULT_PROPERTIES,
    IFF(ANS.AR_ROOT_COUNT=1
        AND COALESCE(AES.AR_EDGE_COUNT,0)=ANS.AR_NODE_COUNT-1
        AND COALESCE(AES.AR_CROSS_RECORD_EDGE_COUNT,0)=0,
        'PASS','FAIL') AS ASSESSMENT_RESULTS_RELATIONSHIP_INTEGRITY,

    -- POA&M
    PR.POAM_ROOT_PK,
    PR.POAM_UUID,
    PNS.POAM_NODE_COUNT,
    PES.POAM_EDGE_COUNT,
    COALESCE(PI.POAM_ITEM_COUNT,0) AS POAM_ITEM_COUNT,
    PI.POAM_ITEMS,
    IFF(PNS.POAM_ROOT_COUNT=1
        AND COALESCE(PES.POAM_EDGE_COUNT,0)=PNS.POAM_NODE_COUNT-1
        AND COALESCE(PES.POAM_CROSS_RECORD_EDGE_COUNT,0)=0,
        'PASS','FAIL') AS POAM_RELATIONSHIP_INTEGRITY,

    -- Security Assessment Plan
    SAP.ASSESSMENT_PLAN_ROOT_PK,
    SAP.ASSESSMENT_PLAN_UUID,
    SNS.SAP_NODE_COUNT,
    SES.SAP_EDGE_COUNT,
    SNS.SAP_TASK_COUNT,
    SNS.SAP_PROP_NODE_COUNT,
    ST.ASSESSMENT_TASKS,
    SPROP.ASSESSMENT_PLAN_PROPERTIES,
    IFF(SNS.SAP_ROOT_COUNT=1
        AND COALESCE(SES.SAP_EDGE_COUNT,0)=SNS.SAP_NODE_COUNT-1
        AND COALESCE(SES.SAP_CROSS_RECORD_EDGE_COUNT,0)=0,
        'PASS','FAIL') AS ASSESSMENT_PLAN_RELATIONSHIP_INTEGRITY,

    -- Cross-model QA
    IFF(AR.SOURCE_RECORD_ID IS NOT NULL,1,0) AS HAS_ASSESSMENT_RESULTS,
    IFF(PR.SOURCE_RECORD_ID IS NOT NULL,1,0) AS HAS_POAM,
    IFF(SAP.SOURCE_RECORD_ID IS NOT NULL,1,0) AS HAS_ASSESSMENT_PLAN,
    IFF(
        AR.SOURCE_RECORD_ID IS NOT NULL
        AND PR.SOURCE_RECORD_ID IS NOT NULL
        AND SAP.SOURCE_RECORD_ID IS NOT NULL,
        'PASS','FAIL'
    ) AS CROSS_MODEL_COVERAGE,

    IFF(
        NS.SSP_ROOT_COUNT=1
        AND COALESCE(ES.SSP_EDGE_COUNT,0)=NS.SSP_NODE_COUNT-1
        AND COALESCE(ES.SSP_CROSS_RECORD_EDGE_COUNT,0)=0
        AND ANS.AR_ROOT_COUNT=1
        AND COALESCE(AES.AR_EDGE_COUNT,0)=ANS.AR_NODE_COUNT-1
        AND COALESCE(AES.AR_CROSS_RECORD_EDGE_COUNT,0)=0
        AND PNS.POAM_ROOT_COUNT=1
        AND COALESCE(PES.POAM_EDGE_COUNT,0)=PNS.POAM_NODE_COUNT-1
        AND COALESCE(PES.POAM_CROSS_RECORD_EDGE_COUNT,0)=0
        AND SNS.SAP_ROOT_COUNT=1
        AND COALESCE(SES.SAP_EDGE_COUNT,0)=SNS.SAP_NODE_COUNT-1
        AND COALESCE(SES.SAP_CROSS_RECORD_EDGE_COUNT,0)=0,
        'PASS','FAIL'
    ) AS OVERALL_RELATIONSHIP_INTEGRITY

FROM SSP_ROOT S
LEFT JOIN SSP_SYSTEM_CHARACTERISTICS SC
  ON SC.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SSP_SYSTEM_IDS IDS
  ON IDS.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SSP_AUTHORIZATION_BOUNDARY AB
  ON AB.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SSP_SECURITY_IMPACT SI
  ON SI.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SSP_SC_PROPERTIES P
  ON P.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SSP_METADATA MD
  ON MD.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SSP_DOCUMENT_IDS DI
  ON DI.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SSP_METADATA_PROPERTIES MP
  ON MP.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SSP_RESPONSIBLE_PARTIES RP
  ON RP.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SSP_ROLES RL
  ON RL.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SSP_PARTIES PT
  ON PT.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SSP_COMPONENTS CP
  ON CP.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SSP_IMPLEMENTED_REQUIREMENTS IR
  ON IR.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SSP_NODE_STATS NS
  ON NS.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SSP_EDGE_STATS ES
  ON ES.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID

LEFT JOIN AR_ROOT AR
  ON AR.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN AR_NODE_STATS ANS
  ON ANS.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN AR_EDGE_STATS AES
  ON AES.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN AR_OBSERVATIONS AO
  ON AO.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN AR_PROPERTIES APROP
  ON APROP.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID

LEFT JOIN POAM_ROOT PR
  ON PR.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN POAM_NODE_STATS PNS
  ON PNS.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN POAM_EDGE_STATS PES
  ON PES.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN POAM_ITEMS PI
  ON PI.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID

LEFT JOIN SAP_ROOT SAP
  ON SAP.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SAP_NODE_STATS SNS
  ON SNS.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SAP_EDGE_STATS SES
  ON SES.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SAP_TASKS ST
  ON ST.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID
LEFT JOIN SAP_PROPERTIES SPROP
  ON SPROP.SOURCE_RECORD_ID = S.SOURCE_RECORD_ID;
