-- Source One raw-load identity / CURATED_JSON diagnostic
-- Date: 2026-10-01
-- READ ONLY. No DML / DDL.
--
-- Purpose:
-- Diagnose Cell 2 error:
--   ValueError: Source contains missing record identities
--
-- Cell 2 reads CONTENT_ID as SOURCE_RECORD_ID and rejects any NULL/blank value.
-- This query proves whether the gap is upstream in the Matillion raw->curated step.
--
-- Result set 1: whole-table counts.
-- Result set 2: RAW_DATA physical type counts.
-- Result set 3: only problem rows, with RequestedObject.Id exposed for repair diagnosis.
--
-- No source payload values other than the requested-object identity are returned.

WITH src AS (
    SELECT
        CONTENT_ID::VARCHAR AS CONTENT_ID,
        CURATED_JSON,
        RAW_DATA,
        IFF(
            TYPEOF(RAW_DATA) = 'ARRAY',
            RAW_DATA[0],
            RAW_DATA
        ) AS RAW_OBJECT
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
),
norm AS (
    SELECT
        CONTENT_ID,
        CURATED_JSON,
        RAW_DATA,
        RAW_OBJECT,
        RAW_OBJECT:"RequestedObject":"Id"::VARCHAR AS REQUESTED_OBJECT_ID
    FROM src
)
SELECT
    COUNT(*) AS SOURCE_ROWS,
    COUNT_IF(CONTENT_ID IS NULL OR LENGTH(TRIM(CONTENT_ID)) = 0) AS MISSING_CONTENT_ID_ROWS,
    COUNT_IF(CURATED_JSON IS NULL) AS CURATED_JSON_NULL_ROWS,
    COUNT_IF(
        (CONTENT_ID IS NULL OR LENGTH(TRIM(CONTENT_ID)) = 0)
        AND CURATED_JSON IS NULL
    ) AS BOTH_ID_AND_CURATED_NULL_ROWS,
    COUNT_IF(REQUESTED_OBJECT_ID IS NULL OR LENGTH(TRIM(REQUESTED_OBJECT_ID)) = 0)
        AS MISSING_REQUESTED_OBJECT_ID_ROWS,
    COUNT_IF(
        CONTENT_ID IS NOT NULL
        AND REQUESTED_OBJECT_ID IS NOT NULL
        AND TRIM(CONTENT_ID) <> TRIM(REQUESTED_OBJECT_ID)
    ) AS CONTENT_ID_MISMATCH_ROWS
FROM norm;


SELECT
    TYPEOF(RAW_DATA) AS RAW_DATA_TYPE,
    COUNT(*) AS ROWS
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
GROUP BY TYPEOF(RAW_DATA)
ORDER BY ROWS DESC, RAW_DATA_TYPE;


WITH src AS (
    SELECT
        CONTENT_ID::VARCHAR AS CONTENT_ID,
        CURATED_JSON,
        RAW_DATA,
        IFF(
            TYPEOF(RAW_DATA) = 'ARRAY',
            RAW_DATA[0],
            RAW_DATA
        ) AS RAW_OBJECT
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
),
norm AS (
    SELECT
        CONTENT_ID,
        CURATED_JSON,
        RAW_DATA,
        RAW_OBJECT:"RequestedObject":"Id"::VARCHAR AS REQUESTED_OBJECT_ID
    FROM src
)
SELECT
    REQUESTED_OBJECT_ID,
    CONTENT_ID,
    TYPEOF(RAW_DATA) AS RAW_DATA_TYPE,
    TYPEOF(CURATED_JSON) AS CURATED_JSON_TYPE,
    IFF(CURATED_JSON IS NULL, 'Y', 'N') AS CURATED_JSON_IS_SQL_NULL,
    CASE
        WHEN REQUESTED_OBJECT_ID IS NULL OR LENGTH(TRIM(REQUESTED_OBJECT_ID)) = 0
            THEN 'RAW_REQUESTED_OBJECT_ID_MISSING'
        WHEN CONTENT_ID IS NULL OR LENGTH(TRIM(CONTENT_ID)) = 0
            THEN 'CONTENT_ID_NOT_POPULATED'
        WHEN CURATED_JSON IS NULL
            THEN 'CURATED_JSON_NOT_POPULATED'
        WHEN TRIM(CONTENT_ID) <> TRIM(REQUESTED_OBJECT_ID)
            THEN 'CONTENT_ID_MISMATCH'
        ELSE 'OK'
    END AS DIAGNOSIS
FROM norm
WHERE CONTENT_ID IS NULL
   OR LENGTH(TRIM(CONTENT_ID)) = 0
   OR CURATED_JSON IS NULL
   OR REQUESTED_OBJECT_ID IS NULL
   OR LENGTH(TRIM(REQUESTED_OBJECT_ID)) = 0
   OR (
       CONTENT_ID IS NOT NULL
       AND REQUESTED_OBJECT_ID IS NOT NULL
       AND TRIM(CONTENT_ID) <> TRIM(REQUESTED_OBJECT_ID)
   )
ORDER BY DIAGNOSIS, REQUESTED_OBJECT_ID
LIMIT 100;
