-- Synthetic read-only Snowflake test. No production table or Matillion variable.
-- Expected: OLD_KEYS=7, NEW_KEYS=12, and every check TRUE.
WITH sample AS (
    SELECT 'SQL_NULL' AS SQL_KEY, CAST(NULL AS VARIANT) AS TYPED_VALUE
    UNION ALL SELECT 'JSON_NULL', PARSE_JSON('null')
    UNION ALL SELECT 'EMPTY_TEXT', TO_VARIANT(NULLIF('', ''))
    UNION ALL SELECT 'BAD_NUMBER', TO_VARIANT(TRY_TO_NUMBER('not-a-number'))
    UNION ALL SELECT 'BAD_DATE', TO_VARIANT(TRY_TO_DATE('not-a-date'))
    UNION ALL SELECT 'ZERO', TO_VARIANT(0)
    UNION ALL SELECT 'FALSE_VALUE', TO_VARIANT(FALSE)
    UNION ALL SELECT 'TEXT_VALUE', TO_VARIANT('unchanged')
    UNION ALL SELECT 'OBJECT_VALUE', PARSE_JSON('{"ValuesList":[{"Id":7,"Name":"Example"}],"Other":"kept"}')
    UNION ALL SELECT 'ARRAY_VALUE', PARSE_JSON('[1,2]')
    UNION ALL SELECT 'ssp_uuid', CAST(NULL AS VARIANT)
    UNION ALL SELECT 'TRACKING_ID', TO_VARIANT('EXAMPLE-ID')
), aggregated AS (
    SELECT OBJECT_AGG(SQL_KEY, TYPED_VALUE) AS OLD_JSON,
           OBJECT_AGG(SQL_KEY, COALESCE(TYPED_VALUE, PARSE_JSON('null'))) AS NEW_JSON,
           OBJECT_AGG(SQL_KEY, TYPED_VALUE) AS ID_SOURCE_JSON
    FROM sample
)
SELECT ARRAY_SIZE(OBJECT_KEYS(OLD_JSON)) AS OLD_KEYS,
       ARRAY_SIZE(OBJECT_KEYS(NEW_JSON)) AS NEW_KEYS,
       IS_NULL_VALUE(NEW_JSON:"SQL_NULL") AS SQL_NULL_KEY_RETAINED,
       IS_NULL_VALUE(NEW_JSON:"JSON_NULL") AS JSON_NULL_KEY_RETAINED,
       IS_NULL_VALUE(NEW_JSON:"EMPTY_TEXT") AS EMPTY_TEXT_POLICY_UNCHANGED,
       IS_NULL_VALUE(NEW_JSON:"BAD_NUMBER") AS BAD_NUMBER_KEY_RETAINED_NOT_REPAIRED,
       IS_NULL_VALUE(NEW_JSON:"BAD_DATE") AS BAD_DATE_KEY_RETAINED_NOT_REPAIRED,
       EQUAL_NULL(NEW_JSON:"ZERO", OLD_JSON:"ZERO") AS ZERO_UNCHANGED,
       EQUAL_NULL(NEW_JSON:"FALSE_VALUE", OLD_JSON:"FALSE_VALUE") AS FALSE_UNCHANGED,
       EQUAL_NULL(NEW_JSON:"TEXT_VALUE", OLD_JSON:"TEXT_VALUE") AS TEXT_UNCHANGED,
       EQUAL_NULL(NEW_JSON:"OBJECT_VALUE", OLD_JSON:"OBJECT_VALUE") AS COMPLETE_OBJECT_UNCHANGED,
       EQUAL_NULL(NEW_JSON:"ARRAY_VALUE", OLD_JSON:"ARRAY_VALUE") AS ARRAY_UNCHANGED,
       EQUAL_NULL(
           COALESCE(OLD_JSON:"ssp_uuid"::STRING, OLD_JSON:"TRACKING_ID"::STRING, 'FALLBACK'),
           COALESCE(ID_SOURCE_JSON:"ssp_uuid"::STRING, ID_SOURCE_JSON:"TRACKING_ID"::STRING, 'FALLBACK')
       ) AS CONTENT_ID_SELECTION_UNCHANGED
FROM aggregated;
