-- SSP QA sample: validate one Archer field against its OSCAL element path
-- Archer field: FISMA_REPORTABLE
-- Expected OSCAL path: system-security-plan.system-characteristics.props[]
-- Replace 565189 with the SOURCE_RECORD_ID / Archer record being tested.

SELECT
    root.SOURCE_RECORD_ID,
    prop.METADATA_JSON:name::STRING AS PROPERTY_NAME,
    prop.METADATA_JSON:value        AS PROPERTY_VALUE,
    prop.METADATA_JSON              AS FULL_PROP_JSON

FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT root

JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY f1
    ON f1.FK_SOURCE_ELEMENT_HASH = root.PK_OSCAL_SSP_ELEMENT_HASH

JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT sc
    ON sc.PK_OSCAL_SSP_ELEMENT_HASH = f1.FK_TARGET_ELEMENT_HASH

JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_SSP_DEPENDENCY f2
    ON f2.FK_SOURCE_ELEMENT_HASH = sc.PK_OSCAL_SSP_ELEMENT_HASH

JOIN RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_SSP_ELEMENT prop
    ON prop.PK_OSCAL_SSP_ELEMENT_HASH = f2.FK_TARGET_ELEMENT_HASH

WHERE root.ELEMENT_TYPE = 'system-security-plan'
  AND sc.ELEMENT_TYPE = 'system-characteristics'
  AND prop.ELEMENT_TYPE = 'props'
  AND root.SOURCE_RECORD_ID = '565189'
  AND prop.METADATA_JSON:name::STRING = 'fisma-reportable';
