"""Generate copy-ready notebook pages from one maintained seven-cell source.

Developer packaging tool only; never upload or run this as a Snowflake cell.
Use --check in CI. No database, network, transformation or mapping execution.
"""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NAMES = (
    "01_initialization_and_configuration.py",
    "02_source_mapping_registry_inputs.py",
    "03_canonical_mapping_contract.py",
    "04_parsing_transform_payload_helpers.py",
    "05_registry_graph_builder.py",
    "06_validation_and_guarded_loader.py",
    "07_mapper_orchestrator.py",
)
HEADER = '''"""NB_ARCHER_OSCAL_MAPPER_V1

Metadata-driven seven-cell mapper: one selector, reviewed mapping metadata,
registry hierarchy, reusable transformations, and guarded persistence.
Upload mapper_contract.v1.json and the approved mapping CSV to notebook Files.
Default PREVIEW: no target DML. AR destination contract remains pending.
Generated by tools/sync_notebook_cells.py from notebooks/cells/; edit that source.
See docs/SHARED_SEVEN_CELL_MAPPER.md for scope and run instructions.
"""
'''


def generated_files():
    sections = []
    for index, name in enumerate(NAMES, 1):
        text = (ROOT / "notebooks" / "cells" / name).read_text(encoding="utf-8-sig")
        text = text.replace("\r\n", "\n").rstrip() + "\n"
        if not text.startswith("# %% Cell " + str(index) + " - "):
            raise ValueError("Cell heading does not match packaging order: " + name)
        compile(text, name, "exec")
        sections.append(text)
        yield ROOT / "notebooks" / "cells_v2" / name, text
    combined = HEADER + "\n\n" + "\n\n".join(sections)
    compile(combined, "NB_ARCHER_OSCAL_MAPPER_V1.py", "exec")
    yield ROOT / "notebooks" / "NB_ARCHER_OSCAL_MAPPER_V1.py", combined


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report drift without writing files")
    args = parser.parse_args()
    changed = []
    for path, text in generated_files():
        current = path.read_text(encoding="utf-8-sig") if path.exists() else None
        if current != text:
            changed.append(path.relative_to(ROOT).as_posix())
            if not args.check:
                path.write_text(text, encoding="utf-8", newline="\n")
    if args.check and changed:
        raise SystemExit("Generated notebook pages are stale: " + ", ".join(changed))
    print("Notebook pages synchronized" + (" (check only)" if args.check else ""))


if __name__ == "__main__":
    main()
