-- POA&M targets: the owner-approved SSP/AR layout with POAM table/PK names.
-- Run as SQL outside an active transaction. Creates missing tables only.
-- Existing tables and data are preserved; the loader checks their exact schema.
CREATE TABLE IF NOT EXISTS RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT (
    PK_DIM_OSCAL_POAM_ELEMENT_HASH BINARY(16) NOT NULL,
    ELEMENT_TYPE VARCHAR(64),
    OSCAL_UUID VARCHAR(32),
    METADATA_JSON VARIANT,
    SOURCE_SYSTEM_NAME VARCHAR(100),
    SOURCE_TABLE_NAME VARCHAR(128),
    SOURCE_RECORD_ID VARCHAR(128),
    DW_PIPELINE_RUN_ID VARCHAR(64),
    DW_LOAD_TIMESTAMP TIMESTAMP_TZ(9),
    DW_LOAD_TIMESTAMP_TZ TIMESTAMP_TZ(9),
    PRIMARY KEY (PK_DIM_OSCAL_POAM_ELEMENT_HASH)
);

CREATE TABLE IF NOT EXISTS RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_POAM_DEPENDENCY (
    PK_FACT_OSCAL_POAM_DEPENDENCY_HASH BINARY(16) NOT NULL,
    FK_SOURCE_ELEMENT_HASH BINARY(16) NOT NULL,
    FK_TARGET_ELEMENT_HASH BINARY(16) NOT NULL,
    DEPENDENCY_TYPE VARCHAR(32) NOT NULL,
    SOURCE_OSCAL_UUID VARCHAR(32) NOT NULL,
    TARGET_OSCAL_UUID VARCHAR(32) NOT NULL,
    PRIMARY KEY (PK_FACT_OSCAL_POAM_DEPENDENCY_HASH)
);

DESC TABLE RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_POAM_ELEMENT;
DESC TABLE RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_POAM_DEPENDENCY;
