-- Catalog targets: shared SSP / Assessment Results / POA&M physical layout with Catalog-specific names.
-- Run as SQL outside an active transaction. Creates missing tables only.
-- Existing tables and data are preserved; IF NOT EXISTS does not repair an existing mismatched schema.
-- The mapper loader must still validate the live table definitions before any COMMIT.

CREATE TABLE IF NOT EXISTS RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_CATALOG_ELEMENT (
    PK_DIM_OSCAL_CATALOG_ELEMENT_HASH BINARY(16) NOT NULL,
    ELEMENT_TYPE VARCHAR(64),
    OSCAL_UUID VARCHAR(32),
    METADATA_JSON VARIANT,
    SOURCE_SYSTEM_NAME VARCHAR(100),
    SOURCE_TABLE_NAME VARCHAR(128),
    SOURCE_RECORD_ID VARCHAR(128),
    DW_PIPELINE_RUN_ID VARCHAR(64),
    DW_LOAD_TIMESTAMP TIMESTAMP_TZ(9),
    DW_LOAD_TIMESTAMP_TZ TIMESTAMP_TZ(9),
    PRIMARY KEY (PK_DIM_OSCAL_CATALOG_ELEMENT_HASH)
);

CREATE TABLE IF NOT EXISTS RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_CATALOG_DEPENDENCY (
    PK_FACT_OSCAL_CATALOG_DEPENDENCY_HASH BINARY(16) NOT NULL,
    FK_SOURCE_ELEMENT_HASH BINARY(16) NOT NULL,
    FK_TARGET_ELEMENT_HASH BINARY(16) NOT NULL,
    DEPENDENCY_TYPE VARCHAR(32) NOT NULL,
    SOURCE_OSCAL_UUID VARCHAR(32) NOT NULL,
    TARGET_OSCAL_UUID VARCHAR(32) NOT NULL,
    PRIMARY KEY (PK_FACT_OSCAL_CATALOG_DEPENDENCY_HASH)
);

DESC TABLE RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_CATALOG_ELEMENT;
DESC TABLE RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_CATALOG_DEPENDENCY;
