-- Component Definition target rebuild
-- Date: 2026-09-17
-- Basis: owner-provided live Snowflake evidence shows DIM_OSCAL_COMPONENT_ELEMENT exists with 0 rows,
--        uses an older 9-column contract, and no FACT_OSCAL_COMPONENT_DEPENDENCY target was discovered.
-- Scope: rebuild ONLY the Component Definition DIM target and create/rebuild its FACT target.
-- Assessment Plan, Assessment Results, Catalog, POA&M, and SSP targets are NOT touched.
--
-- IMPORTANT: CREATE OR REPLACE is intentionally used for the Component targets because the current
-- DIM is owner-confirmed empty. Do not rerun this file after Component data has been loaded without
-- first proving both Component targets are empty.

-- Pre-write confirmation. Expected now: 0.
SELECT COUNT(*) AS CURRENT_COMPONENT_DIM_ROWS
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_COMPONENT_ELEMENT;

-- Rebuild the empty legacy Component DIM to the exact shared loader physical contract.
CREATE OR REPLACE TABLE RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_COMPONENT_ELEMENT (
    PK_DIM_OSCAL_COMPONENT_ELEMENT_HASH BINARY(16) NOT NULL,
    ELEMENT_TYPE VARCHAR(64),
    OSCAL_UUID VARCHAR(32),
    METADATA_JSON VARIANT,
    SOURCE_SYSTEM_NAME VARCHAR(100),
    SOURCE_TABLE_NAME VARCHAR(128),
    SOURCE_RECORD_ID VARCHAR(128),
    DW_PIPELINE_RUN_ID VARCHAR(64),
    DW_LOAD_TIMESTAMP TIMESTAMP_TZ(9),
    DW_LOAD_TIMESTAMP_TZ TIMESTAMP_TZ(9),
    PRIMARY KEY (PK_DIM_OSCAL_COMPONENT_ELEMENT_HASH)
);

-- Create the matching Component dependency fact using the same contract as SSP/AR/SAP/Catalog.
CREATE OR REPLACE TABLE RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_COMPONENT_DEPENDENCY (
    PK_FACT_OSCAL_COMPONENT_DEPENDENCY_HASH BINARY(16) NOT NULL,
    FK_SOURCE_ELEMENT_HASH BINARY(16) NOT NULL,
    FK_TARGET_ELEMENT_HASH BINARY(16) NOT NULL,
    DEPENDENCY_TYPE VARCHAR(32) NOT NULL,
    SOURCE_OSCAL_UUID VARCHAR(32) NOT NULL,
    TARGET_OSCAL_UUID VARCHAR(32) NOT NULL,
    PRIMARY KEY (PK_FACT_OSCAL_COMPONENT_DEPENDENCY_HASH)
);

-- Read-back verification: these definitions must match Cell 6 exactly before any Component COMMIT.
DESC TABLE RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_COMPONENT_ELEMENT;
DESC TABLE RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_COMPONENT_DEPENDENCY;

SELECT 'DIM_OSCAL_COMPONENT_ELEMENT' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_COMPONENT_ELEMENT
UNION ALL
SELECT 'FACT_OSCAL_COMPONENT_DEPENDENCY', COUNT(*)
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_COMPONENT_DEPENDENCY;
