-- Source 2 Topic read-only discovery
-- Date: 2026-09-17
-- Purpose: verify the physical Topic RAW binding, CURATED_JSON field shapes,
-- parent Source relationship coverage, and candidate Catalog-group fields before runtime promotion.
-- READ ONLY: no DDL, DML, temp objects, or target-table writes.

-- 1) Verify the physical Topic table name first.
SELECT
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    ROW_COUNT,
    CREATED,
    LAST_ALTERED
FROM RTX_RAW_DEV.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'ES_ESC_GRC'
  AND UPPER(TABLE_NAME) LIKE '%AUTHORITATIVE%SOURCES%TOPIC%'
ORDER BY TABLE_NAME;

-- Expected candidate from the owner-supplied logical Archer name + established RAW naming pattern:
-- RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_TOPIC_RAW
-- If query 1 does NOT show that exact table, stop here and send the result before running the remainder.

-- 2) Exact column contract for the candidate Topic RAW table.
SELECT
    ORDINAL_POSITION,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE
FROM RTX_RAW_DEV.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ES_ESC_GRC'
  AND TABLE_NAME = 'ARCHER_CONTENT_AUTHORITATIVE_SOURCES_TOPIC_RAW'
ORDER BY ORDINAL_POSITION;

-- 3) Identity and CURATED_JSON completeness.
SELECT
    COUNT(*) AS RAW_ROWS,
    COUNT_IF(CONTENT_ID IS NULL OR TRIM(CONTENT_ID::STRING) = '') AS MISSING_CONTENT_ID_ROWS,
    COUNT(DISTINCT CONTENT_ID::STRING) AS DISTINCT_CONTENT_IDS,
    COUNT_IF(CURATED_JSON IS NULL) AS NULL_CURATED_JSON_ROWS,
    COUNT_IF(TYPEOF(CURATED_JSON) <> 'OBJECT') AS NON_OBJECT_CURATED_JSON_ROWS
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_TOPIC_RAW;

-- 4) Full top-level CURATED_JSON key inventory: names, population and observed JSON types.
WITH key_rows AS (
    SELECT
        f.VALUE::STRING AS FIELD_NAME,
        GET(t.CURATED_JSON, f.VALUE::STRING) AS FIELD_VALUE
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_TOPIC_RAW t,
         LATERAL FLATTEN(INPUT => OBJECT_KEYS(t.CURATED_JSON)) f
)
SELECT
    FIELD_NAME,
    COUNT(*) AS ROWS_WITH_KEY,
    COUNT_IF(FIELD_VALUE IS NOT NULL AND NOT IS_NULL_VALUE(FIELD_VALUE)) AS POPULATED_ROWS,
    COUNT_IF(IS_NULL_VALUE(FIELD_VALUE)) AS JSON_NULL_ROWS,
    LISTAGG(DISTINCT TYPEOF(FIELD_VALUE), ', ') WITHIN GROUP (ORDER BY TYPEOF(FIELD_VALUE)) AS OBSERVED_TYPES
FROM key_rows
GROUP BY FIELD_NAME
ORDER BY FIELD_NAME;

-- 5) Workbook-field coverage for all 52 Topic-tab rows.
WITH fields(FIELD_NAME) AS (
    SELECT COLUMN1 FROM VALUES
        ('TOPIC_NAME'),
        ('TOPIC_ID'),
        ('TOPIC_TRACKING_ID'),
        ('ARCHER_CONTENT_AUTHORITATIVE_SOURCES_TOPIC_CONTENT_ID'),
        ('DOCUMENT_NUMBER'),
        ('SOURCE_NAME_CALC_FIELD'),
        ('CONTENT_SOURCE'),
        ('TOPIC_DESCRIPTION'),
        ('INFORMATION'),
        ('CRITICALITY'),
        ('TOPIC_CRITICALITY_VALUE'),
        ('SOURCE_REFERENCES'),
        ('SECTION_REFERENCES'),
        ('TOTAL_NUMBER_OF_SECTIONS'),
        ('CONTROL_STANDARDS'),
        ('CONTROL_STANDARDS_FROM_SECTION_AND_SUBSECTION_LEVELS'),
        ('MASTER_CONTROLS_AUTHORITATIVE_SOURCES'),
        ('NUMBER_OF_CONTROL_STANDARDS_TOPIC_LEVEL'),
        ('CONTROL_PROCEDURES'),
        ('RELATED_CONTROL_PROCEDURES'),
        ('COMPLIANCE_RATING'),
        ('PCT_OF_NONCOMPLIANT_CONTROLS'),
        ('COUNT_OF_CONTROLS'),
        ('COUNT_OF_NONCOMPLIANT_CONTROLS'),
        ('RELATED_TO_KEY_CONTROLS'),
        ('FINDINGS'),
        ('CONTROL_TESTING_RESULTS_FAILED_EXTERNAL_CONTROL_REQUIREMENT'),
        ('DEVIATIONS_AUTHORITATIVE_SOURCES'),
        ('DEVIATIONS_TOPICS_LINKED_HELPER'),
        ('POLICY_LEVEL_3'),
        ('POLICY_LEVEL_3_FROM_SECTION_AND_SUBSECTION_LEVELS'),
        ('NUMBER_OF_POLICIES_TOPIC_LEVEL'),
        ('LINKED_TO_POLICY_TOPIC_LEVEL'),
        ('TOTAL_NUMBER_OF_SECTIONS_LINKED_TO_POLICY'),
        ('PERCENT_OF_SECTIONS_LINKED_TO_POLICY'),
        ('ENGAGEMENT_SCOPE_IN_CONTROL_TOPIC'),
        ('QUESTION_LIBRARY'),
        ('EVIDENCE_REPOSITORY'),
        ('ATTACHMENTS'),
        ('DEFAULT_RECORD_PERMISSIONS'),
        ('TOPIC_DATE_CREATED'),
        ('TOPIC_LAST_UPDATED'),
        ('ARCHER_CONTENT_AUTHORITATIVE_SOURCES_TOPIC_FIRST_PUBLISHED'),
        ('ARCHER_CONTENT_AUTHORITATIVE_SOURCES_TOPIC_LAST_UPDATED'),
        ('INSERT_DATE'),
        ('UPDATE_DATE'),
        ('CHECKSUM_VALUE'),
        ('_OF_NONCOMPLIANT_CONTROLS'),
        ('CONTROL_STANDARDS__FROM_SECTION_AND_SUBSECTION_LEVELS'),
        ('POLICY_LEVEL_3__FROM_SECTION_AND_SUBSECTION_LEVELS')
), profiled AS (
    SELECT
        f.FIELD_NAME,
        GET(t.CURATED_JSON, f.FIELD_NAME) AS FIELD_VALUE
    FROM fields f
    CROSS JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_TOPIC_RAW t
)
SELECT
    FIELD_NAME,
    COUNT_IF(FIELD_VALUE IS NOT NULL AND NOT IS_NULL_VALUE(FIELD_VALUE)) AS POPULATED_ROWS,
    COUNT_IF(IS_NULL_VALUE(FIELD_VALUE)) AS JSON_NULL_ROWS,
    LISTAGG(DISTINCT TYPEOF(FIELD_VALUE), ', ') WITHIN GROUP (ORDER BY TYPEOF(FIELD_VALUE)) AS OBSERVED_TYPES
FROM profiled
GROUP BY FIELD_NAME
ORDER BY FIELD_NAME;

-- 6) Required Topic-group identity/title profile without exposing business values.
SELECT
    COUNT(*) AS TOPIC_ROWS,
    COUNT_IF(GET(CURATED_JSON, 'TOPIC_NAME') IS NULL
             OR TRIM(GET(CURATED_JSON, 'TOPIC_NAME')::STRING) = '') AS MISSING_TOPIC_NAME_ROWS,
    COUNT_IF(GET(CURATED_JSON, 'TOPIC_ID') IS NULL
             OR TRIM(GET(CURATED_JSON, 'TOPIC_ID')::STRING) = '') AS MISSING_TOPIC_ID_ROWS,
    COUNT(DISTINCT GET(CURATED_JSON, 'TOPIC_ID')::STRING) AS DISTINCT_TOPIC_IDS,
    COUNT_IF(GET(CURATED_JSON, 'TOPIC_ID') IS NOT NULL
             AND REGEXP_LIKE(TRIM(GET(CURATED_JSON, 'TOPIC_ID')::STRING), '^[A-Za-z0-9._:-]+$')) AS SIMPLE_ID_SHAPE_ROWS
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_TOPIC_RAW;

-- 7) Parent Source reference cardinality and exact join coverage.
WITH topic_parent_refs AS (
    SELECT
        t.CONTENT_ID::STRING AS TOPIC_CONTENT_ID,
        r.VALUE AS REF_ITEM,
        TRY_TO_VARCHAR(r.VALUE:ContentId) AS SOURCE_CONTENT_ID
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_TOPIC_RAW t,
         LATERAL FLATTEN(INPUT => GET(t.CURATED_JSON, 'SOURCE_REFERENCES'), OUTER => TRUE) r
), per_topic AS (
    SELECT
        TOPIC_CONTENT_ID,
        COUNT_IF(REF_ITEM IS NOT NULL) AS REF_COUNT
    FROM topic_parent_refs
    GROUP BY TOPIC_CONTENT_ID
), joined AS (
    SELECT
        r.TOPIC_CONTENT_ID,
        r.SOURCE_CONTENT_ID,
        s.CONTENT_ID::STRING AS MATCHED_SOURCE_CONTENT_ID
    FROM topic_parent_refs r
    LEFT JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW s
      ON s.CONTENT_ID::STRING = r.SOURCE_CONTENT_ID
    WHERE r.REF_ITEM IS NOT NULL
)
SELECT
    (SELECT COUNT(*) FROM per_topic) AS TOPIC_ROWS,
    (SELECT COUNT_IF(REF_COUNT = 0) FROM per_topic) AS TOPICS_WITH_NO_SOURCE_REFERENCE,
    (SELECT COUNT_IF(REF_COUNT = 1) FROM per_topic) AS TOPICS_WITH_ONE_SOURCE_REFERENCE,
    (SELECT COUNT_IF(REF_COUNT > 1) FROM per_topic) AS TOPICS_WITH_MULTIPLE_SOURCE_REFERENCES,
    COUNT(*) AS SOURCE_REFERENCE_ITEMS,
    COUNT_IF(SOURCE_CONTENT_ID IS NULL OR TRIM(SOURCE_CONTENT_ID) = '') AS SOURCE_REFERENCE_ITEMS_WITHOUT_CONTENT_ID,
    COUNT_IF(MATCHED_SOURCE_CONTENT_ID IS NULL) AS UNMATCHED_SOURCE_REFERENCE_ITEMS,
    COUNT(DISTINCT MATCHED_SOURCE_CONTENT_ID) AS DISTINCT_MATCHED_SOURCE_RECORDS
FROM joined;

-- 8) Reference item shapes only; no actual IDs/values returned.
WITH refs AS (
    SELECT 'SOURCE_REFERENCES' AS FIELD_NAME, r.VALUE AS ITEM
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_TOPIC_RAW t,
         LATERAL FLATTEN(INPUT => GET(t.CURATED_JSON, 'SOURCE_REFERENCES')) r
    UNION ALL
    SELECT 'SECTION_REFERENCES', r.VALUE
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_TOPIC_RAW t,
         LATERAL FLATTEN(INPUT => GET(t.CURATED_JSON, 'SECTION_REFERENCES')) r
    UNION ALL
    SELECT 'CONTROL_STANDARDS', r.VALUE
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_TOPIC_RAW t,
         LATERAL FLATTEN(INPUT => GET(t.CURATED_JSON, 'CONTROL_STANDARDS')) r
), item_keys AS (
    SELECT
        FIELD_NAME,
        TYPEOF(ITEM) AS ITEM_TYPE,
        k.VALUE::STRING AS ITEM_KEY
    FROM refs,
         LATERAL FLATTEN(INPUT => IFF(TYPEOF(ITEM) = 'OBJECT', OBJECT_KEYS(ITEM), ARRAY_CONSTRUCT())) k
)
SELECT
    FIELD_NAME,
    ITEM_TYPE,
    COUNT(*) AS KEY_OCCURRENCES,
    LISTAGG(DISTINCT ITEM_KEY, ', ') WITHIN GROUP (ORDER BY ITEM_KEY) AS OBSERVED_ITEM_KEYS
FROM item_keys
GROUP BY FIELD_NAME, ITEM_TYPE
ORDER BY FIELD_NAME, ITEM_TYPE;

-- 9) Value-list/security-object shape summary for fields likely to require transforms.
WITH fields(FIELD_NAME) AS (
    SELECT COLUMN1 FROM VALUES
        ('CONTENT_SOURCE'),
        ('CRITICALITY'),
        ('COMPLIANCE_RATING'),
        ('ENGAGEMENT_SCOPE_IN_CONTROL_TOPIC'),
        ('DEFAULT_RECORD_PERMISSIONS')
), values_by_field AS (
    SELECT
        f.FIELD_NAME,
        GET(t.CURATED_JSON, f.FIELD_NAME) AS FIELD_VALUE
    FROM fields f
    CROSS JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_TOPIC_RAW t
    WHERE GET(t.CURATED_JSON, f.FIELD_NAME) IS NOT NULL
      AND NOT IS_NULL_VALUE(GET(t.CURATED_JSON, f.FIELD_NAME))
), object_keys AS (
    SELECT
        FIELD_NAME,
        TYPEOF(FIELD_VALUE) AS VALUE_TYPE,
        k.VALUE::STRING AS OBJECT_KEY
    FROM values_by_field,
         LATERAL FLATTEN(INPUT => IFF(TYPEOF(FIELD_VALUE) = 'OBJECT', OBJECT_KEYS(FIELD_VALUE), ARRAY_CONSTRUCT())) k
)
SELECT
    FIELD_NAME,
    VALUE_TYPE,
    COUNT(*) AS KEY_OCCURRENCES,
    LISTAGG(DISTINCT OBJECT_KEY, ', ') WITHIN GROUP (ORDER BY OBJECT_KEY) AS OBSERVED_OBJECT_KEYS
FROM object_keys
GROUP BY FIELD_NAME, VALUE_TYPE
ORDER BY FIELD_NAME, VALUE_TYPE;

-- 10) Candidate scalar/date field population and type summary.
WITH fields(FIELD_NAME) AS (
    SELECT COLUMN1 FROM VALUES
        ('TOPIC_NAME'),
        ('TOPIC_ID'),
        ('TOPIC_TRACKING_ID'),
        ('TOPIC_CRITICALITY_VALUE'),
        ('TOTAL_NUMBER_OF_SECTIONS'),
        ('NUMBER_OF_CONTROL_STANDARDS_TOPIC_LEVEL'),
        ('COUNT_OF_CONTROLS'),
        ('TOPIC_DATE_CREATED'),
        ('TOPIC_LAST_UPDATED')
), p AS (
    SELECT f.FIELD_NAME, GET(t.CURATED_JSON, f.FIELD_NAME) AS FIELD_VALUE
    FROM fields f
    CROSS JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_TOPIC_RAW t
)
SELECT
    FIELD_NAME,
    COUNT_IF(FIELD_VALUE IS NOT NULL AND NOT IS_NULL_VALUE(FIELD_VALUE)) AS POPULATED_ROWS,
    LISTAGG(DISTINCT TYPEOF(FIELD_VALUE), ', ') WITHIN GROUP (ORDER BY TYPEOF(FIELD_VALUE)) AS OBSERVED_TYPES
FROM p
GROUP BY FIELD_NAME
ORDER BY FIELD_NAME;

-- Final note:
-- Do not update the registry, runtime CSV, or Catalog targets from this discovery alone.
-- The Topic group must attach to the already committed Source Catalog across a separate RAW table.
-- Current Cell 5 builds parents within a source record, so cross-table parent resolution must be proven
-- and implemented generically before Topic nodes are promoted to runtime.
