-- Source 2 sources_source -> Component Definition readiness
-- Date: 2026-09-17
-- Purpose: resolve Component Definition grain / relationship inputs before registry or runtime writes.
-- READ ONLY: no DDL, DML, temporary objects, registry writes, or target writes.

-- 1) Re-read the rebuilt Component Definition targets.
SELECT
    TABLE_NAME,
    ROW_COUNT,
    CREATED,
    LAST_ALTERED
FROM RTX_ENTERPRISESERVICES_DEV.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'ES_ESC_GRC_CURATED'
  AND TABLE_NAME IN ('DIM_OSCAL_COMPONENT_ELEMENT', 'FACT_OSCAL_COMPONENT_DEPENDENCY')
ORDER BY TABLE_NAME;

SELECT
    TABLE_NAME,
    ORDINAL_POSITION,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE
FROM RTX_ENTERPRISESERVICES_DEV.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ES_ESC_GRC_CURATED'
  AND TABLE_NAME IN ('DIM_OSCAL_COMPONENT_ELEMENT', 'FACT_OSCAL_COMPONENT_DEPENDENCY')
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- 2) Current Component Definition registry state.
SELECT
    OSCAL_MODEL_KEY,
    NODE_PATH,
    PARENT_NODE_PATH,
    ELEMENT_TYPE,
    IS_COLLECTION,
    INSTANCE_KEY_RULE,
    ITEM_PATH,
    OPERATOR,
    UUID_POLICY,
    PROCESS_ORDER,
    IS_ACTIVE
FROM RTX_RAW_DEV.ES_ESC_GRC.OSCAL_ELEMENT_REGISTRY
WHERE UPPER(OSCAL_MODEL_KEY) = 'COMPONENT_DEFINITION'
   OR LOWER(NODE_PATH) LIKE 'component-definition%'
ORDER BY PROCESS_ORDER, NODE_PATH;

-- 3) Population and top-level shapes for every populated/ambiguous Source-tab Component row.
WITH fields(FIELD_NAME) AS (
    SELECT COLUMN1 FROM VALUES
      ('POLICIES_AUTHORITATIVE_SOURCE_REFERENCES'),
      ('POLICY_LEVEL_3_FROM_TOPIC_SECTION_AND_SUBSECTION_LEVELS'),
      ('LINKED_TO_POLICY_SOURCE_LEVEL'),
      ('NUMBER_OF_POLICIES_SOURCE_LEVEL'),
      ('CONTROL_PROCEDURES')
), profiled AS (
    SELECT
        f.FIELD_NAME,
        GET(t.CURATED_JSON, f.FIELD_NAME) AS FIELD_VALUE
    FROM fields f
    CROSS JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW t
)
SELECT
    FIELD_NAME,
    COUNT(*) AS SOURCE_ROWS,
    COUNT_IF(FIELD_VALUE IS NOT NULL AND NOT IS_NULL_VALUE(FIELD_VALUE)) AS POPULATED_ROWS,
    COUNT_IF(FIELD_VALUE IS NULL OR IS_NULL_VALUE(FIELD_VALUE)) AS JSON_NULL_ROWS,
    LISTAGG(DISTINCT TYPEOF(FIELD_VALUE), ', ') WITHIN GROUP (ORDER BY TYPEOF(FIELD_VALUE)) AS OBSERVED_TYPES
FROM profiled
GROUP BY FIELD_NAME
ORDER BY FIELD_NAME;

-- 4A) Array item types only; no IDs/values returned.
WITH fields(FIELD_NAME) AS (
    SELECT COLUMN1 FROM VALUES
      ('POLICIES_AUTHORITATIVE_SOURCE_REFERENCES'),
      ('POLICY_LEVEL_3_FROM_TOPIC_SECTION_AND_SUBSECTION_LEVELS'),
      ('CONTROL_PROCEDURES')
), items AS (
    SELECT
        f.FIELD_NAME,
        r.VALUE AS ITEM
    FROM fields f
    CROSS JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW t,
    LATERAL FLATTEN(INPUT => IFF(TYPEOF(GET(t.CURATED_JSON, f.FIELD_NAME)) = 'ARRAY', GET(t.CURATED_JSON, f.FIELD_NAME), ARRAY_CONSTRUCT())) r
)
SELECT
    FIELD_NAME,
    TYPEOF(ITEM) AS ITEM_TYPE,
    COUNT(*) AS ITEM_COUNT
FROM items
GROUP BY FIELD_NAME, TYPEOF(ITEM)
ORDER BY FIELD_NAME, ITEM_TYPE;

-- 4B) Object-key contracts inside array items only; no IDs/values returned.
WITH fields(FIELD_NAME) AS (
    SELECT COLUMN1 FROM VALUES
      ('POLICIES_AUTHORITATIVE_SOURCE_REFERENCES'),
      ('POLICY_LEVEL_3_FROM_TOPIC_SECTION_AND_SUBSECTION_LEVELS'),
      ('CONTROL_PROCEDURES')
), items AS (
    SELECT
        f.FIELD_NAME,
        r.VALUE AS ITEM
    FROM fields f
    CROSS JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW t,
    LATERAL FLATTEN(INPUT => IFF(TYPEOF(GET(t.CURATED_JSON, f.FIELD_NAME)) = 'ARRAY', GET(t.CURATED_JSON, f.FIELD_NAME), ARRAY_CONSTRUCT())) r
), keys AS (
    SELECT
        FIELD_NAME,
        k.VALUE::STRING AS OBJECT_KEY
    FROM items,
    LATERAL FLATTEN(INPUT => IFF(TYPEOF(ITEM) = 'OBJECT', OBJECT_KEYS(ITEM), ARRAY_CONSTRUCT())) k
)
SELECT
    FIELD_NAME,
    COUNT(*) AS KEY_OCCURRENCES,
    LISTAGG(DISTINCT OBJECT_KEY, ', ') WITHIN GROUP (ORDER BY OBJECT_KEY) AS OBSERVED_OBJECT_KEYS
FROM keys
GROUP BY FIELD_NAME
ORDER BY FIELD_NAME;

-- 5) LINKED_TO_POLICY_SOURCE_LEVEL Archer-select lookup coverage.
-- Counts only; no select IDs or labels returned.
WITH ids AS (
    SELECT
        v.VALUE::STRING AS SELECT_VALUE_ID
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW t,
    LATERAL FLATTEN(
      INPUT => COALESCE(
        GET(GET(t.CURATED_JSON, 'LINKED_TO_POLICY_SOURCE_LEVEL'), 'ValuesListIds'),
        GET(GET(t.CURATED_JSON, 'LINKED_TO_POLICY_SOURCE_LEVEL'), 'ValueListIds'),
        ARRAY_CONSTRUCT()
      )
    ) v
), coverage AS (
    SELECT
        i.SELECT_VALUE_ID,
        m.SELECT_VALUE_ID AS MATCHED_ID
    FROM ids i
    LEFT JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_META_VALUE m
      ON TRIM(m.SELECT_VALUE_ID::STRING) = TRIM(i.SELECT_VALUE_ID)
)
SELECT
    COUNT(*) AS SELECT_ID_OCCURRENCES,
    COUNT(DISTINCT SELECT_VALUE_ID) AS DISTINCT_SELECT_IDS,
    COUNT_IF(MATCHED_ID IS NULL) AS UNMATCHED_SELECT_ID_OCCURRENCES,
    COUNT(DISTINCT IFF(MATCHED_ID IS NULL, SELECT_VALUE_ID, NULL)) AS DISTINCT_UNMATCHED_SELECT_IDS
FROM coverage;

-- 6) Discover likely Archer RAW candidates for policy/procedure relationship hydration.
-- Table names only; this does not assume any candidate is correct.
SELECT
    TABLE_NAME,
    ROW_COUNT
FROM RTX_RAW_DEV.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'ES_ESC_GRC'
  AND TABLE_NAME LIKE '%_RAW'
  AND (
       UPPER(TABLE_NAME) LIKE '%POLIC%'
    OR UPPER(TABLE_NAME) LIKE '%PROCEDUR%'
    OR UPPER(TABLE_NAME) LIKE '%CONTROL_STANDARD%'
  )
ORDER BY TABLE_NAME;

-- Stop here. Return these read-only outputs before any Component registry/runtime change.
