-- Source 2 sources_source remaining-model readiness
-- Date: 2026-09-17
-- Purpose: finish populated Source-tab rows that belong to Assessment Results,
-- Assessment Plan, and Component Definition without inventing target grain.
-- READ ONLY: no DDL, DML, temp objects, registry writes, or target writes.

-- 1) Current live registry support for the three remaining models.
SELECT
    OSCAL_MODEL_KEY,
    NODE_PATH,
    PARENT_NODE_PATH,
    ELEMENT_TYPE,
    IS_COLLECTION,
    INSTANCE_KEY_RULE,
    ITEM_PATH,
    OPERATOR,
    UUID_POLICY,
    PROCESS_ORDER
FROM RTX_RAW_DEV.ES_ESC_GRC.OSCAL_ELEMENT_REGISTRY
WHERE UPPER(OSCAL_MODEL_KEY) IN ('ASSESSMENT_RESULTS', 'SECURITY_ASSESSMENT_PLAN', 'COMPONENT_DEFINITION')
ORDER BY OSCAL_MODEL_KEY, PROCESS_ORDER, NODE_PATH;

-- 2) Discover existing curated DIM/FACT targets for those models.
SELECT
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    ROW_COUNT,
    CREATED,
    LAST_ALTERED
FROM RTX_ENTERPRISESERVICES_DEV.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'ES_ESC_GRC_CURATED'
  AND (
       UPPER(TABLE_NAME) LIKE '%OSCAL%ASSESSMENT_RESULTS%'
    OR UPPER(TABLE_NAME) LIKE '%OSCAL%ASSESSMENT_PLAN%'
    OR UPPER(TABLE_NAME) LIKE '%OSCAL%COMPONENT%'
  )
ORDER BY TABLE_NAME;

-- 3) Column contracts for every discovered candidate target table.
SELECT
    TABLE_NAME,
    ORDINAL_POSITION,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE
FROM RTX_ENTERPRISESERVICES_DEV.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ES_ESC_GRC_CURATED'
  AND (
       UPPER(TABLE_NAME) LIKE '%OSCAL%ASSESSMENT_RESULTS%'
    OR UPPER(TABLE_NAME) LIKE '%OSCAL%ASSESSMENT_PLAN%'
    OR UPPER(TABLE_NAME) LIKE '%OSCAL%COMPONENT%'
  )
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- 4) Confirm only the populated Source-tab fields that still need another model.
-- No business values are returned.
WITH fields(MODEL_KEY, FIELD_NAME) AS (
    SELECT * FROM VALUES
        ('ASSESSMENT_RESULTS', 'COMPLIANCE_RATING'),
        ('ASSESSMENT_RESULTS', 'COUNT_OF_NONCOMPLIANT_CONTROLS'),
        ('ASSESSMENT_RESULTS', 'DEVIATIONS_AUTHORITATIVE_SOURCES_LINKED_TO_CONTROL_STANDARDS'),
        ('COMPONENT_DEFINITION', 'POLICIES_AUTHORITATIVE_SOURCE_REFERENCES'),
        ('COMPONENT_DEFINITION', 'POLICY_LEVEL_3_FROM_TOPIC_SECTION_AND_SUBSECTION_LEVELS'),
        ('COMPONENT_DEFINITION', 'LINKED_TO_POLICY_SOURCE_LEVEL'),
        ('COMPONENT_DEFINITION', 'NUMBER_OF_POLICIES_SOURCE_LEVEL'),
        ('SECURITY_ASSESSMENT_PLAN', 'ENGAGEMENT_SCOPE_IN_CONTROL_SOURCE')
), p AS (
    SELECT
        f.MODEL_KEY,
        f.FIELD_NAME,
        GET(t.CURATED_JSON, f.FIELD_NAME) AS FIELD_VALUE
    FROM fields f
    CROSS JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW t
)
SELECT
    MODEL_KEY,
    FIELD_NAME,
    COUNT_IF(FIELD_VALUE IS NOT NULL AND NOT IS_NULL_VALUE(FIELD_VALUE)) AS POPULATED_ROWS,
    LISTAGG(DISTINCT TYPEOF(FIELD_VALUE), ', ') WITHIN GROUP (ORDER BY TYPEOF(FIELD_VALUE)) AS OBSERVED_TYPES
FROM p
GROUP BY MODEL_KEY, FIELD_NAME
ORDER BY MODEL_KEY, FIELD_NAME;

-- 5) Existing Catalog target state after the first committed Source batch.
-- This is only a count checkpoint before the new tracking-id mapping is previewed.
SELECT 'DIM_OSCAL_CATALOG_ELEMENT' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.DIM_OSCAL_CATALOG_ELEMENT
UNION ALL
SELECT 'FACT_OSCAL_CATALOG_DEPENDENCY', COUNT(*)
FROM RTX_ENTERPRISESERVICES_DEV.ES_ESC_GRC_CURATED.FACT_OSCAL_CATALOG_DEPENDENCY;

-- Stop here. Return these aggregate/readiness outputs before any registry or model-contract writes.
