-- Source 2 / sources_source full-tab mapping readiness
-- Date: 2026-09-17
-- Purpose: finish the Source worksheet before moving to Topic.
-- Scope: profile all 56 Source-tab fields, with extra detail for the 42 rows not yet in runtime.
-- READ ONLY: no DDL, DML, temp objects, target writes, or business-value output.

-- Verified physical source from the completed Source-level Catalog work:
-- RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW

-- 1) Reconfirm the current Source snapshot identity/JSON contract.
SELECT
    COUNT(*) AS RAW_ROWS,
    COUNT_IF(CONTENT_ID IS NULL OR TRIM(CONTENT_ID::STRING) = '') AS MISSING_CONTENT_ID_ROWS,
    COUNT(DISTINCT CONTENT_ID::STRING) AS DISTINCT_CONTENT_IDS,
    COUNT_IF(CURATED_JSON IS NULL) AS NULL_CURATED_JSON_ROWS,
    COUNT_IF(CURATED_JSON IS NOT NULL AND TYPEOF(CURATED_JSON) <> 'OBJECT') AS NON_OBJECT_CURATED_JSON_ROWS
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW;

-- 2) Full top-level CURATED_JSON key inventory. No values are returned.
WITH key_rows AS (
    SELECT
        f.VALUE::STRING AS FIELD_NAME,
        GET(t.CURATED_JSON, f.VALUE::STRING) AS FIELD_VALUE
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW t,
         LATERAL FLATTEN(INPUT => OBJECT_KEYS(t.CURATED_JSON)) f
)
SELECT
    FIELD_NAME,
    COUNT(*) AS ROWS_WITH_KEY,
    COUNT_IF(FIELD_VALUE IS NOT NULL AND NOT IS_NULL_VALUE(FIELD_VALUE)) AS POPULATED_ROWS,
    COUNT_IF(IS_NULL_VALUE(FIELD_VALUE)) AS JSON_NULL_ROWS,
    LISTAGG(DISTINCT TYPEOF(FIELD_VALUE), ', ') WITHIN GROUP (ORDER BY TYPEOF(FIELD_VALUE)) AS OBSERVED_TYPES
FROM key_rows
GROUP BY FIELD_NAME
ORDER BY FIELD_NAME;

-- 3) Coverage for every one of the 56 Source-tab workbook rows.
-- This is the authoritative completeness profile for deciding final row disposition.
WITH fields(WORKSHEET_ROW, FIELD_NAME, WORKBOOK_MODEL) AS (
    SELECT * FROM VALUES
        (2,  'SOURCE_NAME', 'CATALOG_METADATA'),
        (3,  'SOURCE_VERSION', 'CATALOG_METADATA'),
        (4,  'SOURCE_DESCRIPTION', 'CATALOG_METADATA'),
        (5,  'SOURCE_TRACKING_ID', 'CATALOG_METADATA'),
        (6,  'SOURCE_LINKS', 'CATALOG_BACK_MATTER'),
        (7,  'INFORMATION', 'CATALOG_METADATA'),
        (8,  'DISCLAIMER', 'CATALOG_METADATA'),
        (9,  'TOPIC_REFERENCES', 'CATALOG_BACK_MATTER'),
        (10, 'ATTACHMENTS', 'CATALOG_BACK_MATTER'),
        (11, 'CONTROL_STANDARDS', 'CATALOG'),
        (12, 'CONTROL_STANDARDS_FROM_TOPIC_SECTION_AND_SUBSECTION_LEVELS', 'CATALOG'),
        (13, 'CONTROL_STANDARDS__FROM_TOPIC_SECTION_AND_SUBSECTION_LEVELS', 'CATALOG'),
        (14, 'MASTER_CONTROLS_AUTHORITATIVE_SOURCES', 'CATALOG'),
        (15, 'CONTROL_PROCEDURES', 'CATALOG_OR_COMPONENT_DEFINITION'),
        (16, 'RELATED_CONTROL_PROCEDURES', 'CATALOG'),
        (17, 'NUMBER_OF_CONTROL_STANDARDS_SOURCE_LEVEL', 'CATALOG_METADATA'),
        (18, 'COMPLIANCE_RATING', 'ASSESSMENT_RESULTS'),
        (19, 'COUNT_OF_CONTROLS', 'CATALOG_METADATA'),
        (20, 'COUNT_OF_NONCOMPLIANT_CONTROLS', 'ASSESSMENT_RESULTS'),
        (21, 'PCT_OF_NONCOMPLIANT_CONTROLS', 'ASSESSMENT_RESULTS'),
        (22, '_OF_NONCOMPLIANT_CONTROLS', 'ASSESSMENT_RESULTS'),
        (23, 'RELATED_TO_KEY_CONTROLS', 'CATALOG'),
        (24, 'FINDINGS', 'ASSESSMENT_RESULTS'),
        (25, 'FINDINGS_AUTHORITATIVE_SOURCES', 'ASSESSMENT_RESULTS'),
        (26, 'CONTROL_TESTING_RESULTS_FAILED_EXTERNAL_CONTROL_REQUIREMENT', 'ASSESSMENT_RESULTS'),
        (27, 'DEVIATIONS_AUTHORITATIVE_SOURCES', 'ASSESSMENT_RESULTS'),
        (28, 'DEVIATIONS_AUTHORITATIVE_SOURCES_LINKED_TO_CONTROL_STANDARDS', 'ASSESSMENT_RESULTS'),
        (29, 'SOURCE_TYPE', 'CATALOG_METADATA'),
        (30, 'CRITICALITY', 'CATALOG_METADATA'),
        (31, 'SOURCE_CRITICALITY_VALUE', 'CATALOG_METADATA'),
        (32, 'AUTH_SOURCES_FILTER', 'CATALOG_METADATA'),
        (33, 'POLICIES_AUTHORITATIVE_SOURCE_REFERENCES', 'COMPONENT_DEFINITION'),
        (34, 'POLICY_LEVEL_3', 'COMPONENT_DEFINITION'),
        (35, 'POLICY_LEVEL_3_FROM_TOPIC_SECTION_AND_SUBSECTION_LEVELS', 'COMPONENT_DEFINITION'),
        (36, 'POLICY_LEVEL_3__FROM_TOPIC_SECTION_AND_SUBSECTION_LEVELS', 'COMPONENT_DEFINITION'),
        (37, 'LINKED_TO_POLICY_SOURCE_LEVEL', 'COMPONENT_DEFINITION'),
        (38, 'NUMBER_OF_POLICIES_SOURCE_LEVEL', 'COMPONENT_DEFINITION'),
        (39, 'ENGAGEMENT_SCOPE_IN_CONTROL_SOURCE', 'ASSESSMENT_PLAN'),
        (40, 'COMPLIANCE_ENGAGEMENTS_SCOPE_PROCEDURES_FROM_SELECTED_AUTHORITATIVE_SOURCES', 'ASSESSMENT_PLAN'),
        (41, 'QUESTION_LIBRARY', 'ASSESSMENT_PLAN'),
        (42, 'EVIDENCE_REPOSITORY', 'ASSESSMENT_RESULTS'),
        (43, 'EFFECTIVE_DATE', 'CATALOG_METADATA'),
        (44, 'OFFICIAL_RETIREMENT_DATE', 'CATALOG_METADATA'),
        (45, 'RTX_RETIREMENT_DATE', 'CATALOG_METADATA'),
        (46, 'DATE_CREATED', 'CATALOG_METADATA'),
        (47, 'LAST_UPDATED', 'CATALOG_METADATA'),
        (48, 'ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_FIRST_PUBLISHED', 'CATALOG_METADATA'),
        (49, 'ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_LAST_UPDATED', 'CATALOG_METADATA'),
        (50, 'ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_CONFIRMED_IN_ARCHER', 'CATALOG_METADATA'),
        (51, 'RECORD_STATUS', 'CATALOG_METADATA'),
        (52, 'DEFAULT_RECORD_PERMISSIONS', 'CATALOG_METADATA'),
        (53, 'CONTENT_SOURCE', 'CATALOG_METADATA'),
        (54, 'INSERT_DATE', 'SYSTEM_METADATA'),
        (55, 'UPDATE_DATE', 'SYSTEM_METADATA'),
        (56, 'CHECKSUM_VALUE', 'SYSTEM_METADATA'),
        (57, 'ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_CONTENT_ID', 'CATALOG_METADATA')
), profiled AS (
    SELECT
        f.WORKSHEET_ROW,
        f.FIELD_NAME,
        f.WORKBOOK_MODEL,
        GET(t.CURATED_JSON, f.FIELD_NAME) AS FIELD_VALUE
    FROM fields f
    CROSS JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW t
)
SELECT
    WORKSHEET_ROW,
    FIELD_NAME,
    WORKBOOK_MODEL,
    COUNT_IF(FIELD_VALUE IS NOT NULL AND NOT IS_NULL_VALUE(FIELD_VALUE)) AS POPULATED_ROWS,
    COUNT_IF(IS_NULL_VALUE(FIELD_VALUE)) AS JSON_NULL_ROWS,
    LISTAGG(DISTINCT TYPEOF(FIELD_VALUE), ', ') WITHIN GROUP (ORDER BY TYPEOF(FIELD_VALUE)) AS OBSERVED_TYPES
FROM profiled
GROUP BY WORKSHEET_ROW, FIELD_NAME, WORKBOOK_MODEL
ORDER BY WORKSHEET_ROW;

-- 4) Remaining Catalog-metadata narrative/identity fields.
WITH fields(FIELD_NAME) AS (
    SELECT COLUMN1 FROM VALUES
        ('SOURCE_DESCRIPTION'),
        ('SOURCE_TRACKING_ID'),
        ('INFORMATION'),
        ('DATE_CREATED'),
        ('LAST_UPDATED'),
        ('ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_FIRST_PUBLISHED'),
        ('ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_LAST_UPDATED'),
        ('ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_CONFIRMED_IN_ARCHER'),
        ('DEFAULT_RECORD_PERMISSIONS'),
        ('ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_CONTENT_ID')
), p AS (
    SELECT f.FIELD_NAME, GET(t.CURATED_JSON, f.FIELD_NAME) AS FIELD_VALUE
    FROM fields f
    CROSS JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW t
)
SELECT
    FIELD_NAME,
    COUNT_IF(FIELD_VALUE IS NOT NULL AND NOT IS_NULL_VALUE(FIELD_VALUE)) AS POPULATED_ROWS,
    LISTAGG(DISTINCT TYPEOF(FIELD_VALUE), ', ') WITHIN GROUP (ORDER BY TYPEOF(FIELD_VALUE)) AS OBSERVED_TYPES
FROM p
GROUP BY FIELD_NAME
ORDER BY FIELD_NAME;

-- 5) SOURCE_DESCRIPTION versus INFORMATION conflict profile.
-- We need a deterministic disposition before either/both can own Catalog remarks.
SELECT
    COUNT(*) AS SOURCE_ROWS,
    COUNT_IF(GET(CURATED_JSON, 'SOURCE_DESCRIPTION') IS NOT NULL
             AND NOT IS_NULL_VALUE(GET(CURATED_JSON, 'SOURCE_DESCRIPTION'))) AS SOURCE_DESCRIPTION_POPULATED,
    COUNT_IF(GET(CURATED_JSON, 'INFORMATION') IS NOT NULL
             AND NOT IS_NULL_VALUE(GET(CURATED_JSON, 'INFORMATION'))) AS INFORMATION_POPULATED,
    COUNT_IF(GET(CURATED_JSON, 'SOURCE_DESCRIPTION') IS NOT NULL
             AND NOT IS_NULL_VALUE(GET(CURATED_JSON, 'SOURCE_DESCRIPTION'))
             AND GET(CURATED_JSON, 'INFORMATION') IS NOT NULL
             AND NOT IS_NULL_VALUE(GET(CURATED_JSON, 'INFORMATION'))) AS BOTH_POPULATED,
    COUNT_IF(GET(CURATED_JSON, 'SOURCE_DESCRIPTION') IS NOT NULL
             AND NOT IS_NULL_VALUE(GET(CURATED_JSON, 'SOURCE_DESCRIPTION'))
             AND GET(CURATED_JSON, 'INFORMATION') IS NOT NULL
             AND NOT IS_NULL_VALUE(GET(CURATED_JSON, 'INFORMATION'))
             AND GET(CURATED_JSON, 'SOURCE_DESCRIPTION')::STRING = GET(CURATED_JSON, 'INFORMATION')::STRING) AS BOTH_EQUAL,
    COUNT_IF(GET(CURATED_JSON, 'SOURCE_DESCRIPTION') IS NOT NULL
             AND NOT IS_NULL_VALUE(GET(CURATED_JSON, 'SOURCE_DESCRIPTION'))
             AND GET(CURATED_JSON, 'INFORMATION') IS NOT NULL
             AND NOT IS_NULL_VALUE(GET(CURATED_JSON, 'INFORMATION'))
             AND GET(CURATED_JSON, 'SOURCE_DESCRIPTION')::STRING <> GET(CURATED_JSON, 'INFORMATION')::STRING) AS BOTH_DIFFERENT
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW;

-- 6) Competing publication/update fields: population, co-population and equality.
SELECT
    COUNT(*) AS SOURCE_ROWS,
    COUNT_IF(GET(CURATED_JSON, 'DATE_CREATED') IS NOT NULL
             AND NOT IS_NULL_VALUE(GET(CURATED_JSON, 'DATE_CREATED'))) AS DATE_CREATED_POPULATED,
    COUNT_IF(GET(CURATED_JSON, 'ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_FIRST_PUBLISHED') IS NOT NULL
             AND NOT IS_NULL_VALUE(GET(CURATED_JSON, 'ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_FIRST_PUBLISHED'))) AS PREFIXED_FIRST_PUBLISHED_POPULATED,
    COUNT_IF(GET(CURATED_JSON, 'DATE_CREATED') IS NOT NULL
             AND NOT IS_NULL_VALUE(GET(CURATED_JSON, 'DATE_CREATED'))
             AND GET(CURATED_JSON, 'ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_FIRST_PUBLISHED') IS NOT NULL
             AND NOT IS_NULL_VALUE(GET(CURATED_JSON, 'ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_FIRST_PUBLISHED'))) AS CREATED_AND_FIRST_PUBLISHED_BOTH,
    COUNT_IF(GET(CURATED_JSON, 'DATE_CREATED')::STRING =
             GET(CURATED_JSON, 'ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_FIRST_PUBLISHED')::STRING) AS CREATED_EQUALS_FIRST_PUBLISHED,
    COUNT_IF(GET(CURATED_JSON, 'LAST_UPDATED') IS NOT NULL
             AND NOT IS_NULL_VALUE(GET(CURATED_JSON, 'LAST_UPDATED'))) AS LAST_UPDATED_POPULATED,
    COUNT_IF(GET(CURATED_JSON, 'ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_LAST_UPDATED') IS NOT NULL
             AND NOT IS_NULL_VALUE(GET(CURATED_JSON, 'ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_LAST_UPDATED'))) AS PREFIXED_LAST_UPDATED_POPULATED,
    COUNT_IF(GET(CURATED_JSON, 'LAST_UPDATED') IS NOT NULL
             AND NOT IS_NULL_VALUE(GET(CURATED_JSON, 'LAST_UPDATED'))
             AND GET(CURATED_JSON, 'ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_LAST_UPDATED') IS NOT NULL
             AND NOT IS_NULL_VALUE(GET(CURATED_JSON, 'ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_LAST_UPDATED'))) AS UPDATED_BOTH,
    COUNT_IF(GET(CURATED_JSON, 'LAST_UPDATED')::STRING =
             GET(CURATED_JSON, 'ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_LAST_UPDATED')::STRING) AS UPDATED_VALUES_EQUAL,
    COUNT_IF(GET(CURATED_JSON, 'ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_CONFIRMED_IN_ARCHER') IS NOT NULL
             AND NOT IS_NULL_VALUE(GET(CURATED_JSON, 'ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_CONFIRMED_IN_ARCHER'))) AS CONFIRMED_IN_ARCHER_POPULATED
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW;

-- 7) Relationship/back-matter/other-model field top-level shapes.
-- This tells us which rows are scalar, array, object, or absent before choosing operators.
WITH fields(FIELD_NAME) AS (
    SELECT COLUMN1 FROM VALUES
        ('SOURCE_LINKS'),
        ('TOPIC_REFERENCES'),
        ('ATTACHMENTS'),
        ('CONTROL_STANDARDS'),
        ('CONTROL_STANDARDS_FROM_TOPIC_SECTION_AND_SUBSECTION_LEVELS'),
        ('CONTROL_STANDARDS__FROM_TOPIC_SECTION_AND_SUBSECTION_LEVELS'),
        ('MASTER_CONTROLS_AUTHORITATIVE_SOURCES'),
        ('CONTROL_PROCEDURES'),
        ('RELATED_CONTROL_PROCEDURES'),
        ('COMPLIANCE_RATING'),
        ('COUNT_OF_NONCOMPLIANT_CONTROLS'),
        ('PCT_OF_NONCOMPLIANT_CONTROLS'),
        ('_OF_NONCOMPLIANT_CONTROLS'),
        ('RELATED_TO_KEY_CONTROLS'),
        ('FINDINGS'),
        ('FINDINGS_AUTHORITATIVE_SOURCES'),
        ('CONTROL_TESTING_RESULTS_FAILED_EXTERNAL_CONTROL_REQUIREMENT'),
        ('DEVIATIONS_AUTHORITATIVE_SOURCES'),
        ('DEVIATIONS_AUTHORITATIVE_SOURCES_LINKED_TO_CONTROL_STANDARDS'),
        ('POLICIES_AUTHORITATIVE_SOURCE_REFERENCES'),
        ('POLICY_LEVEL_3'),
        ('POLICY_LEVEL_3_FROM_TOPIC_SECTION_AND_SUBSECTION_LEVELS'),
        ('POLICY_LEVEL_3__FROM_TOPIC_SECTION_AND_SUBSECTION_LEVELS'),
        ('LINKED_TO_POLICY_SOURCE_LEVEL'),
        ('NUMBER_OF_POLICIES_SOURCE_LEVEL'),
        ('ENGAGEMENT_SCOPE_IN_CONTROL_SOURCE'),
        ('COMPLIANCE_ENGAGEMENTS_SCOPE_PROCEDURES_FROM_SELECTED_AUTHORITATIVE_SOURCES'),
        ('QUESTION_LIBRARY'),
        ('EVIDENCE_REPOSITORY')
), p AS (
    SELECT f.FIELD_NAME, GET(t.CURATED_JSON, f.FIELD_NAME) AS FIELD_VALUE
    FROM fields f
    CROSS JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW t
)
SELECT
    FIELD_NAME,
    COUNT_IF(FIELD_VALUE IS NOT NULL AND NOT IS_NULL_VALUE(FIELD_VALUE)) AS POPULATED_ROWS,
    LISTAGG(DISTINCT TYPEOF(FIELD_VALUE), ', ') WITHIN GROUP (ORDER BY TYPEOF(FIELD_VALUE)) AS OBSERVED_TYPES
FROM p
GROUP BY FIELD_NAME
ORDER BY FIELD_NAME;

-- 8A) For populated ARRAY relationship fields, count item types.
WITH fields(FIELD_NAME) AS (
    SELECT COLUMN1 FROM VALUES
        ('TOPIC_REFERENCES'),
        ('CONTROL_STANDARDS'),
        ('CONTROL_STANDARDS_FROM_TOPIC_SECTION_AND_SUBSECTION_LEVELS'),
        ('CONTROL_STANDARDS__FROM_TOPIC_SECTION_AND_SUBSECTION_LEVELS'),
        ('MASTER_CONTROLS_AUTHORITATIVE_SOURCES'),
        ('RELATED_CONTROL_PROCEDURES'),
        ('FINDINGS'),
        ('FINDINGS_AUTHORITATIVE_SOURCES'),
        ('CONTROL_TESTING_RESULTS_FAILED_EXTERNAL_CONTROL_REQUIREMENT'),
        ('DEVIATIONS_AUTHORITATIVE_SOURCES'),
        ('DEVIATIONS_AUTHORITATIVE_SOURCES_LINKED_TO_CONTROL_STANDARDS'),
        ('POLICIES_AUTHORITATIVE_SOURCE_REFERENCES'),
        ('LINKED_TO_POLICY_SOURCE_LEVEL'),
        ('QUESTION_LIBRARY')
), items AS (
    SELECT
        f.FIELD_NAME,
        r.VALUE AS ITEM
    FROM fields f
    CROSS JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW t,
         LATERAL FLATTEN(INPUT => GET(t.CURATED_JSON, f.FIELD_NAME)) r
    WHERE TYPEOF(GET(t.CURATED_JSON, f.FIELD_NAME)) = 'ARRAY'
)
SELECT
    FIELD_NAME,
    TYPEOF(ITEM) AS ITEM_TYPE,
    COUNT(*) AS ITEM_COUNT
FROM items
GROUP BY FIELD_NAME, TYPEOF(ITEM)
ORDER BY FIELD_NAME, ITEM_TYPE;

-- 8B) Object keys inside ARRAY relationship items. No IDs or values returned.
WITH fields(FIELD_NAME) AS (
    SELECT COLUMN1 FROM VALUES
        ('TOPIC_REFERENCES'),
        ('CONTROL_STANDARDS'),
        ('CONTROL_STANDARDS_FROM_TOPIC_SECTION_AND_SUBSECTION_LEVELS'),
        ('CONTROL_STANDARDS__FROM_TOPIC_SECTION_AND_SUBSECTION_LEVELS'),
        ('MASTER_CONTROLS_AUTHORITATIVE_SOURCES'),
        ('RELATED_CONTROL_PROCEDURES'),
        ('FINDINGS'),
        ('FINDINGS_AUTHORITATIVE_SOURCES'),
        ('CONTROL_TESTING_RESULTS_FAILED_EXTERNAL_CONTROL_REQUIREMENT'),
        ('DEVIATIONS_AUTHORITATIVE_SOURCES'),
        ('DEVIATIONS_AUTHORITATIVE_SOURCES_LINKED_TO_CONTROL_STANDARDS'),
        ('POLICIES_AUTHORITATIVE_SOURCE_REFERENCES'),
        ('LINKED_TO_POLICY_SOURCE_LEVEL'),
        ('QUESTION_LIBRARY')
), items AS (
    SELECT f.FIELD_NAME, r.VALUE AS ITEM
    FROM fields f
    CROSS JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW t,
         LATERAL FLATTEN(INPUT => GET(t.CURATED_JSON, f.FIELD_NAME)) r
    WHERE TYPEOF(GET(t.CURATED_JSON, f.FIELD_NAME)) = 'ARRAY'
      AND TYPEOF(r.VALUE) = 'OBJECT'
), keys AS (
    SELECT i.FIELD_NAME, k.VALUE::STRING AS ITEM_KEY
    FROM items i,
         LATERAL FLATTEN(INPUT => OBJECT_KEYS(i.ITEM)) k
)
SELECT
    FIELD_NAME,
    COUNT(*) AS KEY_OCCURRENCES,
    LISTAGG(DISTINCT ITEM_KEY, ', ') WITHIN GROUP (ORDER BY ITEM_KEY) AS OBSERVED_ITEM_KEYS
FROM keys
GROUP BY FIELD_NAME
ORDER BY FIELD_NAME;

-- 9A) Archer select/security object shapes for current + other-model candidate fields.
WITH fields(FIELD_NAME) AS (
    SELECT COLUMN1 FROM VALUES
        ('SOURCE_TYPE'),
        ('CRITICALITY'),
        ('AUTH_SOURCES_FILTER'),
        ('CONTENT_SOURCE'),
        ('COMPLIANCE_RATING'),
        ('LINKED_TO_POLICY_SOURCE_LEVEL'),
        ('ENGAGEMENT_SCOPE_IN_CONTROL_SOURCE'),
        ('DEFAULT_RECORD_PERMISSIONS')
), objects AS (
    SELECT f.FIELD_NAME, GET(t.CURATED_JSON, f.FIELD_NAME) AS FIELD_VALUE
    FROM fields f
    CROSS JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW t
    WHERE GET(t.CURATED_JSON, f.FIELD_NAME) IS NOT NULL
      AND NOT IS_NULL_VALUE(GET(t.CURATED_JSON, f.FIELD_NAME))
), keys AS (
    SELECT
        o.FIELD_NAME,
        TYPEOF(o.FIELD_VALUE) AS VALUE_TYPE,
        k.VALUE::STRING AS OBJECT_KEY
    FROM objects o,
         LATERAL FLATTEN(INPUT => IFF(TYPEOF(o.FIELD_VALUE) = 'OBJECT', OBJECT_KEYS(o.FIELD_VALUE), ARRAY_CONSTRUCT())) k
)
SELECT
    FIELD_NAME,
    VALUE_TYPE,
    COUNT(*) AS KEY_OCCURRENCES,
    LISTAGG(DISTINCT OBJECT_KEY, ', ') WITHIN GROUP (ORDER BY OBJECT_KEY) AS OBSERVED_OBJECT_KEYS
FROM keys
GROUP BY FIELD_NAME, VALUE_TYPE
ORDER BY FIELD_NAME, VALUE_TYPE;

-- 9B) Lookup coverage for ValuesListIds-style fields using the existing ARCHER_META_VALUE contract.
WITH fields(FIELD_NAME) AS (
    SELECT COLUMN1 FROM VALUES
        ('SOURCE_TYPE'),
        ('CRITICALITY'),
        ('AUTH_SOURCES_FILTER'),
        ('CONTENT_SOURCE'),
        ('COMPLIANCE_RATING'),
        ('LINKED_TO_POLICY_SOURCE_LEVEL'),
        ('ENGAGEMENT_SCOPE_IN_CONTROL_SOURCE')
), ids AS (
    SELECT
        f.FIELD_NAME,
        v.VALUE::STRING AS SELECT_VALUE_ID
    FROM fields f
    CROSS JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW t,
         LATERAL FLATTEN(
             INPUT => COALESCE(
                 GET(GET(t.CURATED_JSON, f.FIELD_NAME), 'ValuesListIds'),
                 GET(GET(t.CURATED_JSON, f.FIELD_NAME), 'ValueListIds')
             )
         ) v
)
SELECT
    i.FIELD_NAME,
    COUNT(*) AS SELECT_ID_OCCURRENCES,
    COUNT(DISTINCT i.SELECT_VALUE_ID) AS DISTINCT_SELECT_IDS,
    COUNT_IF(m.SELECT_VALUE_ID IS NULL) AS UNMATCHED_SELECT_ID_OCCURRENCES,
    COUNT(DISTINCT IFF(m.SELECT_VALUE_ID IS NULL, i.SELECT_VALUE_ID, NULL)) AS DISTINCT_UNMATCHED_SELECT_IDS
FROM ids i
LEFT JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_META_VALUE m
  ON TRIM(m.SELECT_VALUE_ID::STRING) = TRIM(i.SELECT_VALUE_ID)
GROUP BY i.FIELD_NAME
ORDER BY i.FIELD_NAME;

-- 10) DEFAULT_RECORD_PERMISSIONS structure only; do not treat it as OSCAL role text automatically.
WITH permissions AS (
    SELECT GET(CURATED_JSON, 'DEFAULT_RECORD_PERMISSIONS') AS P
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW
    WHERE GET(CURATED_JSON, 'DEFAULT_RECORD_PERMISSIONS') IS NOT NULL
      AND NOT IS_NULL_VALUE(GET(CURATED_JSON, 'DEFAULT_RECORD_PERMISSIONS'))
), keys AS (
    SELECT TYPEOF(P) AS PERMISSION_TYPE, k.VALUE::STRING AS OBJECT_KEY
    FROM permissions,
         LATERAL FLATTEN(INPUT => IFF(TYPEOF(P) = 'OBJECT', OBJECT_KEYS(P), ARRAY_CONSTRUCT())) k
)
SELECT
    PERMISSION_TYPE,
    COUNT(*) AS KEY_OCCURRENCES,
    LISTAGG(DISTINCT OBJECT_KEY, ', ') WITHIN GROUP (ORDER BY OBJECT_KEY) AS OBSERVED_OBJECT_KEYS
FROM keys
GROUP BY PERMISSION_TYPE
ORDER BY PERMISSION_TYPE;

-- 11) System-metadata keys: confirm whether they are in CURATED_JSON or only technical/wide metadata.
WITH fields(FIELD_NAME) AS (
    SELECT COLUMN1 FROM VALUES
        ('INSERT_DATE'),
        ('UPDATE_DATE'),
        ('CHECKSUM_VALUE')
), p AS (
    SELECT f.FIELD_NAME, GET(t.CURATED_JSON, f.FIELD_NAME) AS FIELD_VALUE
    FROM fields f
    CROSS JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORITATIVE_SOURCES_SOURCE_RAW t
)
SELECT
    FIELD_NAME,
    COUNT_IF(FIELD_VALUE IS NOT NULL AND NOT IS_NULL_VALUE(FIELD_VALUE)) AS POPULATED_ROWS,
    LISTAGG(DISTINCT TYPEOF(FIELD_VALUE), ', ') WITHIN GROUP (ORDER BY TYPEOF(FIELD_VALUE)) AS OBSERVED_TYPES
FROM p
GROUP BY FIELD_NAME
ORDER BY FIELD_NAME;

-- Stop after these read-only results.
-- Do not update runtime mappings, registry rows, model bindings, or targets until the outputs are reviewed.
