-- Profile discovery only: inspect the only current RAW key containing PROFILE/IMPORT.
-- Read-only. No target writes and no record IDs returned.
WITH source AS (
    SELECT TRY_PARSE_JSON(TO_VARCHAR(CURATED_JSON)) AS payload
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
)
SELECT
    TYPEOF(payload:COLLINS_IMPORT) AS COLLINS_IMPORT_TYPE,
    payload:COLLINS_IMPORT AS COLLINS_IMPORT,
    COUNT(*) AS CURRENT_RECORD_COUNT
FROM source
GROUP BY ALL
ORDER BY CURRENT_RECORD_COUNT DESC
LIMIT 30;
