-- Profile discovery only: inspect candidate control-selection fields across RAW stored versions.
-- Read-only. No target writes. Counts are RAW stored-version counts, not mapper-deduplicated counts.
WITH source AS (
    SELECT TRY_PARSE_JSON(TO_VARCHAR(CURATED_JSON)) AS payload
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
)
SELECT
    TYPEOF(payload:ALLOCATE_BASELINE_CONTROLS) AS ALLOCATE_BASELINE_CONTROLS_TYPE,
    payload:ALLOCATE_BASELINE_CONTROLS AS ALLOCATE_BASELINE_CONTROLS,
    TYPEOF(payload:CONTROL_SET_TO_ASSESS) AS CONTROL_SET_TO_ASSESS_TYPE,
    payload:CONTROL_SET_TO_ASSESS AS CONTROL_SET_TO_ASSESS,
    COUNT(*) AS STORED_VERSION_COUNT
FROM source
GROUP BY ALL
ORDER BY STORED_VERSION_COUNT DESC
LIMIT 30;
