-- Profile discovery only: current RAW table is one row per CONTENT_ID (owner read-back: 2,813 rows / 2,813 distinct IDs / 0 null IDs).
-- Resolve baseline recommendation and control-set/version select IDs to labels in one aggregate result.
-- Read-only. No record IDs and no target writes. Keep source-value results private.
WITH source AS (
    SELECT TRY_PARSE_JSON(TO_VARCHAR(CURATED_JSON)) AS payload
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
), ids AS (
    SELECT
        TRY_TO_NUMBER(payload:BASELINE_RECOMMENDATION:ValuesListIds[0]::STRING) AS BASELINE_ID,
        TRY_TO_NUMBER(payload:CONTROL_SET_VERSION_NUMBER:ValuesListIds[0]::STRING) AS CONTROL_SET_ID,
        TRY_TO_NUMBER(payload:CONTROL_SET_VERSION_NUMBER_HRC:ValuesListIds[0]::STRING) AS CONTROL_SET_HRC_ID
    FROM source
)
SELECT
    i.BASELINE_ID,
    b.SELECT_VALUE_NAME AS BASELINE_RECOMMENDATION,
    i.CONTROL_SET_ID,
    c.SELECT_VALUE_NAME AS CONTROL_SET_VERSION_NUMBER,
    i.CONTROL_SET_HRC_ID,
    h.SELECT_VALUE_NAME AS CONTROL_SET_VERSION_NUMBER_HRC,
    COUNT(*) AS CURRENT_RECORD_COUNT
FROM ids i
LEFT JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_META_VALUE b
    ON b.SELECT_VALUE_ID = i.BASELINE_ID
LEFT JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_META_VALUE c
    ON c.SELECT_VALUE_ID = i.CONTROL_SET_ID
LEFT JOIN RTX_RAW_DEV.ES_ESC_GRC.ARCHER_META_VALUE h
    ON h.SELECT_VALUE_ID = i.CONTROL_SET_HRC_ID
GROUP BY ALL
ORDER BY CURRENT_RECORD_COUNT DESC;
