-- Profile discovery only: inspect candidate control-set/version fields from stored RAW versions.
-- Read-only. No target writes.
WITH source AS (
    SELECT TRY_PARSE_JSON(TO_VARCHAR(CURATED_JSON)) AS payload
    FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
)
SELECT
    TYPEOF(payload:CONTROL_SET_VERSION_NUMBER) AS CONTROL_SET_VERSION_NUMBER_TYPE,
    payload:CONTROL_SET_VERSION_NUMBER AS CONTROL_SET_VERSION_NUMBER,

    TYPEOF(payload:CONTROL_SET_VERSION_NUMBER_HRC) AS CONTROL_SET_VERSION_NUMBER_HRC_TYPE,
    payload:CONTROL_SET_VERSION_NUMBER_HRC AS CONTROL_SET_VERSION_NUMBER_HRC,

    TYPEOF(payload:INSERT_TECHNICAL_SECURITY_BASELINE_TSB_OR_CONFIGURATIONS)
        AS TSB_CONFIG_TYPE,
    payload:INSERT_TECHNICAL_SECURITY_BASELINE_TSB_OR_CONFIGURATIONS
        AS TSB_CONFIG,

    COUNT(*) AS STORED_VERSION_COUNT
FROM source
GROUP BY ALL
ORDER BY STORED_VERSION_COUNT DESC
LIMIT 30;
