-- Read-only discovery: inspect candidate Archer Authorization Package fields related to SSP Control Implementation.
-- Purpose: determine whether any candidate field contains a ContentId/cross-reference that can be followed to Control Implementation records.
-- No target writes.

SELECT
    CONTENT_ID,
    CURATED_JSON:ALLOCATED_CONTROLS AS ALLOCATED_CONTROLS,
    CURATED_JSON:MASTER_CONTROLS AS MASTER_CONTROLS,
    CURATED_JSON:GS_LAB_CONTROL_ENTITY AS GS_LAB_CONTROL_ENTITY,
    CURATED_JSON:CONTROL_SET_TO_ASSESS AS CONTROL_SET_TO_ASSESS
FROM RTX_RAW_DEV.ES_ESC_GRC.ARCHER_CONTENT_AUTHORIZATION_PACKAGE_RAW
WHERE
       CURATED_JSON:ALLOCATED_CONTROLS IS NOT NULL
    OR CURATED_JSON:MASTER_CONTROLS IS NOT NULL
    OR CURATED_JSON:GS_LAB_CONTROL_ENTITY IS NOT NULL
    OR CURATED_JSON:CONTROL_SET_TO_ASSESS IS NOT NULL
LIMIT 50;
